### ISSUE TITLE
Refreshing of comments in panel

### ISSUE THREAD

**Issue by ldelossa** [microsoft/vscode-pull-request-github#4387] opened 2023-01-10 14:10 UTC
- Extension version: v0.57.2022122310
- VSCode Version: 1.74.2
- OS: Fedora Linux

Steps to Reproduce:

1. Open a repo to a branch which a PR exists
2. Create a comment
3. View the 'ago' portion of the comment, it will remain inaccurate over along period of time. 

Hello, 

When I check out a branch in which a PR is open for the 'comments' panel is now available. This is really handy and I love this feature. 

However, there does not seem to be anyway to refresh the comments and get the latest ones. Right now, I have comments I made over 24 hrs ago, yet the panel still says it was created '8 hours ago'. 

Is there anyway to manually refresh the comments? To be clear, I'm not in 'Review Mode' at all, I'm just looking at a branch which a PR is open too, and the plugin is painting comments in my editors and shows a list of them in the panel.

**Comment by alexr00** [comment] 2023-01-11 11:52
When you have a PR checked out ("review mode") then we refresh every couple minutes. However, we may never refresh if you don't have a PR checked out. We should probably refresh periodically (maybe once per hour) if you have comments that are not part of a checked out PR.

**Comment by ldelossa** [comment] 2023-01-11 13:44
Yup, even if its just exposing a manual "refresh comments" command.

**Comment by tannerbaum** [comment] 2023-02-09 14:32
@alexr00 This is maybe a separate issue and I can't exactly verify when it happens, but I have noticed often that when I switch from one PR to another, the comments panel (and the comment icons next to the line number) are not updated to reflect the current PR/branch I am in. I am currently on the preview version of the extension but I thought it happened on release version as well. 

Is this the result of a weird workflow of mine or maybe something else?

**Comment by alexr00** [comment] 2023-02-13 16:58
@tannerbaum Are you opening PR files with comments from the "Pull Requests" view? Comments from non-checked out PRs will stick around regardless of the branch you're on as we don't know when you're "done" with a non-checked out PR.

**Comment by ldelossa** [comment] 2023-02-16 23:02
@alexr00 can you fill me in with some info. When will the plugin actually find comments when a pr is **not** checked out? 

I use `gh pr checkout` to get a branch, and it seems very hit or miss as to whether it can determine if a PR is open for the checked out branch, and populate the comments section in the panel. I rather like this "light weight" code review feature, which shows comments when not specifically checking out a PR via the plugin.

**Comment by alexr00** [comment] 2023-02-17 09:15
@ldelossa you can browse a PR by expanding the PR node in the "Pull Requests" view.

`gh pr checkout` PRs not being recognized is a duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/4464.

**Comment by alexr00** [comment] 2023-08-23 16:23
I've added a refresh button. We still don't automatically refresh the comments of non-checked out PRs as this could end up being expensive.

![image](https://github.com/microsoft/vscode-pull-request-github/assets/38270282/ce18af0b-64a1-4fe4-8196-05448317f99e)

**Closed** 2023-08-23 17:32 UTC
Labels: feature-request

**Comment by ldelossa** [comment] 2023-08-24 15:23
Thank you!!! A refresh button is perfect. Automatic refresh could be nice (mixed with the notification system) but I understand the concern. This is already a huge improvement :)
