### ISSUE TITLE
After many files in a large PR the last files redirect to Github instead of opening the diff

### ISSUE THREAD

**Issue by YLivay** [microsoft/vscode-pull-request-github#1160] opened 2019-05-16 14:33 UTC
Issue Type: <b>Bug</b>

1. Checkout the branch the PR is on locally 
2. Open a large PR with many files in the extension
3. Click the last files on the list in vscode

Expected: Should open the diff in vscode
Actual: Redirects to view the file on Github.com

Sounds like it may be related to https://github.com/microsoft/vscode-pull-request-github/issues/552
Even if I have the branch checked out, past ~170 files clicking the files redirect to view the blob in Github instead of showing the diff.

Extension version: 0.6.0
VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:20:22.771Z)
OS version: Linux x64 5.0.13-300.fc30.x86_64

**Comment by RMacfarlane** [comment] 2019-05-23 23:32
Hey @YLivay, this is a duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/442. There are some situations where we cannot fetch the file content so we redirect to GitHub (if the change was just a file rename, or the file is an unsupported type, for example). I just merged in a PR from the community to show a notification in such a case.

**Comment by YLivay** [comment] 2019-05-25 11:25
Hey @RMacfarlane, I don't think this is a duplicate. This issue is about well supported files not being handled. The files that are not handled are only the last ones on the list, and they are the same type as the files that were returned. I'm assuming GitHub is just not returning the last entries because of the sheer size of the request. I'm hoping there's a way to break it apart to multiple requests instead of having the extension give up past a few hundred files.

**Comment by alexr00** [comment] 2022-06-23 11:26
Should be fixed by https://github.com/microsoft/vscode-pull-request-github/issues/3623

**Closed by alexr00** 2022-06-23 11:26 UTC
Labels: feature-request, github
