### ISSUE TITLE
Do we have to show the repository dropdown for only one repo

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-pull-request-github#4380] opened 2023-01-04 13:45 UTC
1. Create a new PR. Notice there are 4 drop-downs. 
2. I believe this makes the view much more complicated than having just 2 drop-downs as GitHub does

Do we show the repository drop-down because there can be multiple repositories in the Workspace?
Does it make sense that we do not show the repository dropdown for Workspaces that have only one repository? I believe this is the majority and would quite simplify the flow. What do you think?

![Screenshot 2023-01-04 at 14 33 29](https://user-images.githubusercontent.com/1926584/210567921-f471a62b-9d4e-4fcb-aab2-7a272e7c50f6.png)

**Comment by isidorn** [comment] 2023-01-04 15:49
Thanks for the explanation.

**Comment by alexr00** [comment] 2023-03-17 15:11
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/4403

**Closed by alexr00** 2023-03-17 15:11 UTC
