### ISSUE TITLE
"Stop working on #{}" shown when clicking issue

### ISSUE THREAD

**Issue by filliph** [microsoft/vscode-pull-request-github#4876] opened 2023-06-01 10:52 UTC
Type: <b>Bug</b>

When clicking the issue in the Status Bar, the drop-down says "Stop working on #{}" instead of showing the actual issue number.

Extension version: 0.64.0
VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:39:26.248Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12700K (20 x 3610)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.80GB (14.77GB free)|
|Process Argv|--crash-reporter-id 5145b872-b690-4540-952d-398f42fa50c8|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
2e4cg342:30602488
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
pythonfmttext:30731395
fixhidewlkth:30730051
showsbindicator:30730056
pythongtdpath:30739704

```

</details>

**Comment by filliph** [comment] 2023-06-01 10:52
![image](https://github.com/microsoft/vscode-pull-request-github/assets/9424286/e2f9dc95-ab9a-4b22-8cc6-32b5603edfd6)

**Comment by Danp2** [comment] 2023-06-01 16:53
I believe that this has already been addressed in https://github.com/microsoft/vscode-pull-request-github/issues/4821

**Comment by alexr00** [comment] 2023-06-05 14:49
Yes, duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/4821

**Closed by alexr00** 2023-06-05 14:49 UTC
