### ISSUE TITLE
Notify user of a New PR for review

### ISSUE THREAD

**Issue by anatoly-yakubov-betpawa** [microsoft/vscode-pull-request-github#1913] opened 2020-06-16 12:37 UTC
Notify user of new (assigned) PR for a review. 
Push or periodical refresh with extension's icon status is a minimum. 
Status bar + pop-up that opens PR when clicked is a preferred way.

Without it users have to use other channels to disturb / notify / ask each other for a review. GitHub's email notification opens web UI, while reviewing using this extension is a much better experience.

**Comment by alexr00** [comment] 2020-11-11 16:46
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/1128

**Closed by alexr00** 2020-11-11 16:46 UTC
Labels: feature-request
