### ISSUE TITLE
Should not be possible to approve the same PR multiple times

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode-pull-request-github#523] opened 2018-10-01 13:11 UTC
![image](https://user-images.githubusercontent.com/900690/46290513-5495d900-c58c-11e8-9ba5-24aadaa2ec3d.png)

**Comment by RMacfarlane** [comment] 2018-10-01 16:53
Duplicate of https://github.com/Microsoft/vscode-pull-request-github/issues/473

**Closed by RMacfarlane** 2018-10-01 16:53 UTC
Labels: bug
