### ISSUE TITLE
Allow picking target branch from list when creating PR

### ISSUE THREAD

**Issue by mhuggins7278** [microsoft/vscode-pull-request-github#2126] opened 2020-09-11 17:48 UTC
It would be nice if the target branch was a picklist instead of just a text input defaulted to the base branch.

**Comment by RMacfarlane** [comment] 2020-10-06 17:59
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/814

**Closed by RMacfarlane** 2020-10-06 17:59 UTC
