### ISSUE TITLE
After pull request is merged only comment option should be available

### ISSUE THREAD

**Issue by meaghanlewis** [microsoft/vscode-pull-request-github#1026] opened 2019-03-05 16:25 UTC
- Extension version:
- VSCode Version:
- OS:

Steps to Reproduce:

1. Merge an open pull request.
2. Confirm that PR was merged
3. Note that the options to Close Pull Request, Request Changes, and Approve should no longer be visible

Merged PR in VS Code:
<img width="874" alt="screen shot 2019-03-04 at 9 34 07 pm" src="https://user-images.githubusercontent.com/10103121/53819907-b5e91c00-3f1f-11e9-9ad6-77da2a0c0151.png">

Merged PR in GitHub:
<img width="853" alt="screen shot 2019-03-05 at 8 22 44 am" src="https://user-images.githubusercontent.com/10103121/53820043-edf05f00-3f1f-11e9-8027-84a1b015ad67.png">

**Comment by RMacfarlane** [comment] 2019-10-09 23:28
Closing as a duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/473

**Closed by RMacfarlane** 2019-10-09 23:28 UTC
Labels: bug
