### ISSUE TITLE
Cannot comment in GitHub PRs - GraphQL error

### ISSUE THREAD

**Issue by MatejMarecek** [microsoft/vscode-pull-request-github#6478] opened 2024-11-15 12:22 UTC
Type: <b>Bug</b>

> Creating comment failed: Error: GraphQL error: Fragment ReviewComment was used, but not defined

When trying to comments to PRs.

Extension version: 0.100.1
VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT arm64 10.0.26100
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Snapdragon(R) X 12-core X1E80100 @ 3.40 GHz (12 x 2976)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|31.57GB (12.11GB free)|
|Process Argv|--folder-uri file:///c%3A/Noimos/GitHub/apps/services-dotnet --crash-reporter-id 1139cc4b-3387-4487-8ac0-4018b6739144|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
0ee40948:31013168
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl2:31139839
pythonrstrctxt:31112756
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31181875

```

</details>

**Comment by jrieken** [comment] 2024-11-15 17:12
dupe of https://github.com/microsoft/vscode-pull-request-github/issues/6467

**Closed by jrieken** 2024-11-15 17:12 UTC
Labels: important
