### ISSUE TITLE
Add support for multi-line comments in PRs

### ISSUE THREAD

**Issue by awmottaz** [microsoft/vscode-pull-request-github#1894] opened 2020-06-11 18:04 UTC
It would be great to see support for multi-line comments in this extension.

> To add a comment on multiple lines, click and drag to select the range of lines, then click the blue comment icon.
— https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/commenting-on-a-pull-request#adding-line-comments-to-a-pull-request

**Comment by AdamVig** [comment] 2020-06-12 15:08
Duplicate of #1376.

**Closed** 2020-06-12 17:03 UTC
