### ISSUE TITLE
Comments shown twice

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode-pull-request-github#2937] opened 2021-08-24 12:45 UTC
Testing #2931

Not sure how I got into that but a comment is shown twice

<img width="513" alt="capture" src="https://user-images.githubusercontent.com/1931590/130618522-86e3e44f-bec2-4ca1-9747-37d64cf879b4.png">

**Comment by alexr00** [comment] 2021-08-31 13:48
@dbaeumer I thought this would have something to do with opening the same file from multiple places, but I can't reproduce the issue. Do you have any ideas about what you were doing when this happened?

**Comment by dbaeumer** [comment] 2021-09-03 08:57
Sorry, not really. I just noticed it. Feel free to close if you can't reproduce.

**Comment by chivalry** [comment] 2021-11-17 22:32
I'm seeing this in my project right now, and they grow. The first time I saw it there were three, then four, now five.

![image](https://user-images.githubusercontent.com/600992/142293052-0fc77005-3ce0-4bb3-a671-9defb85499ec.png)

Reloading the window did fix it.

16" M1 Pro MBP running macOS 12.0.1, VS Code 1.62.2, extension version 0.32.0

**Comment by chivalry** [comment] 2021-11-17 23:21
The problem did come back after refreshing. Interestingly, I'm _not_ seeing all of the PR comments. Thinking it might be a refresh issue, I clicked the extension's Refresh Pull Requests List button, and whereas there were two of the above screenshot's comments, there then became three. Clicking refresh again gave me four. But again, I'm still not seeing the rest of the comments for that file. There is one before it and seven after it that I only see when logged into GitHub via a browser.

**Comment by alexr00** [comment] 2022-03-02 14:50
@chivalry there was an issue where you could end up quite a lot of double state, Should be fixed by https://github.com/microsoft/vscode-pull-request-github/commit/b27aafefddc997034d82e9bc52d0679ec2e4183e. Please do ping this issue if you're still seeing the bug!

**Closed by alexr00** 2022-03-02 14:50 UTC
Labels: bug
