### ISSUE TITLE
Avatar image in tree view initially missing when first created PR

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode-pull-request-github#2312] opened 2020-12-03 00:41 UTC
Running through https://github.com/microsoft/vssaas-planning/issues/1527 on codespaces

After I make a PR using GHPR, the tree view for the PR has an empty space for my avatar. 

![image](https://user-images.githubusercontent.com/8586769/100948600-132b4c00-34bd-11eb-9e35-4540dcc0147c.png)
ref https://github.com/microsoft/vscode-internalbacklog/issues/1661

**Comment by RMacfarlane** [comment] 2020-12-03 00:58
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/2310

**Closed by RMacfarlane** 2020-12-03 00:58 UTC
