### ISSUE TITLE
Collapse the extra email information for "email replies"

### ISSUE THREAD

**Issue by connorshea** [microsoft/vscode-pull-request-github#394] opened 2018-09-10 19:22 UTC
The formatting of email replies in VS Code is currently rather ugly. Essentially, it still includes the extra email information (the comment being replied-to) that GitHub collapses on the web. There's also no marker in VS Code that suggests the comment was sent via email.

Comment in GitHub:

<img width="835" alt="screen shot 2018-09-10 at 1 18 08 pm" src="https://user-images.githubusercontent.com/2977353/45319071-009f5380-b4fc-11e8-8319-30d66389f4db.png">

Comment in VS Code:

<img width="1017" alt="screen shot 2018-09-10 at 1 17 21 pm" src="https://user-images.githubusercontent.com/2977353/45319024-e2d1ee80-b4fb-11e8-9223-d8472016134c.png">

Ideally, I'd like VS Code to collapse the extra info at the bottom, just like GitHub does.

**Comment by alexr00** [comment] 2022-12-13 10:44
Duplicate of https://github.com/microsoft/vscode/issues/168963

**Closed by alexr00** 2022-12-13 10:44 UTC
Labels: feature-request
