### ISSUE TITLE
Issues are created in the wrong repository when you've more than 1 folder in your project

### ISSUE THREAD

**Issue by photonstorm** [microsoft/vscode-pull-request-github#1840] opened 2020-05-29 10:03 UTC
- Extension version: 0.16.1
- VSCode Version: 1.45.1
- OS: Windows 10

Steps to Reproduce:

1. Create a project and add 2 (or more) folders to it. Each folder should point to a different repository. It doesn't matter if you own the repository or not.
2. Edit a source file in any of the folders and add a TODO.
3. Using the Create Issue wizard, enter details for the issue and save it.

The issue is not created in the repo to which the source file belongs, but one of the others from the folder list. It appears to be random as to which one is selected. In testing I had it try to create issues in a variety of different repos (my project has 6 different folders added to it, each of which is a unique repository).

It even tried to create an issue in a repo I didn't even own (thankfully I spotted that quickly). Using the Edit icon to view the `NewIssue.md` shows the repo it's going to, so it's possible to abort before it saves it, but it does render the feature sadly useless.

**Comment by RMacfarlane** [comment] 2020-05-29 14:30
Hey @photonstorm, this looks like a duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/1768. We've just checked in a fix for this, so it should be available in our next release in a couple of weeks.

**Closed by RMacfarlane** 2020-05-29 14:30 UTC
