### ISSUE TITLE
Enterprise 3.9: GraphQL error Fragment on Bot can't be spread inside RequestedReviewer

### ISSUE THREAD

**Issue by janakjjp** [microsoft/vscode-pull-request-github#6441] opened 2024-10-30 19:35 UTC
- Extension version: 0.100.0 (just updated)
- VSCode Version: 1.95.0
- OS: macOS Sequoia 15.0.1
- Repository Clone Configuration (single repository/fork of an upstream repository): enterprise monorepo
- Github Product (Github.com/Github Enterprise version x.x.x): GitHub Enterprise 3.9.16

Steps to Reproduce:

1. Update to the latest extension (released today)
2. Go to the Pull Requests extension.
3. Expand a Pull Request on the LHS nav and click Description. The error is generated and the PR description pane does not load in a tab.
4. Revert to 0.98.0, and then the above 3 steps work as expected.

**Comment by notatallshaw-gts** [comment] 2024-10-31 19:15
Also getting this on:

```
Version: 1.95.0 (user setup)
Commit: 912bb683695358a54ae0c670461738984cbb5b95
Date: 2024-10-28T20:16:24.561Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.19045
```

Using SSH Remote if that makes a difference.

**Comment by alexr00** [comment] 2024-11-07 09:12
Thanks for the ping!

**Comment by alexr00** [comment] 2024-11-07 12:58
@janakjjp and @notatallshaw-gts there's a new pre-release version out with the fix. Would you be able to try it out and let me know if it fixes the issue for you?

**Comment by notatallshaw-gts** [comment] 2024-11-07 18:26
@alexr00 Yes, I switched to

```
Name: GitHub Pull Requests
Id: GitHub.vscode-pull-request-github
Description: Pull Request and Issue Provider for GitHub
Version: 0.101.2024110711
Publisher: GitHub
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github
```

Restarted my VS Code for good measure, and opened a PR and it worked, thanks for the fix.

**Comment by alexr00** [comment] 2024-11-08 08:27
Thanks for verifying! I'll put out a new stable version with the fix.

**Comment by alexr00** [comment] 2024-11-18 09:16
Fix revealed a bigger issue. I'll need to revert it and make a larger change for the next regular release.

**Comment by notatallshaw-gts** [comment] 2024-11-18 15:44
Thanks for the update, I've pinned my GitHub Pull Requests to 0.98 until this is resolved, for those who don't know how to do this and get this error":

1. Go to the "GitHub Pull Requests" extension in the extensions side bar
2. Click the down arrow next to "Uninstall"
3. Select "Install Specific Version..."
4. Click on "0.98.0"

**Comment by DougAGault** [comment] 2024-11-20 14:32
Thanks @notatallshaw-gts for the instructions. falling back to 0.98 helped me too. 

Keeping an eye on this to find out when this will be fixed in a major release.

**Comment by alexr00** [comment] 2024-11-20 16:01
Full transparency: GitHub Enterprise 3.9 was [deprecated over the summer](https://docs.github.com/en/enterprise-server@3.14/admin/all-releases). While I prefer to keep support for deprecated version since I know that users don't have control of when their admins update, fixing this isn't high priority for us. I'll try to look in December, but there's a good chance it will slip.

**Comment by DougAGault** [comment] 2024-11-20 16:05
We're on Github Enterprise 3.10.16, and I was still getting the GraphQL error. ¯\_(ツ)_/¯

**Closed** 2024-12-03 17:15 UTC
Labels: bug, GitHubEnterprise

**Comment by alexr00** [comment] 2024-12-04 08:31
Found a way to make a very simple fix! Change is available in pre-release and will go out in the stable release next week.

**Comment by alexr00** [comment] 2024-12-10 15:58
Enterprise users, would you be able to try out the latest pre-release version of the extension and confirm whether the issue is resolved?

**Comment by notatallshaw-gts** [comment] 2024-12-10 16:20
> Enterprise users, would you be able to try out the latest pre-release version of the extension and confirm whether the issue is resolved?

What version exactly? I don't see a pre-release available posted in the last two weeks:

![Image](https://github.com/user-attachments/assets/adeabeba-f7a1-4008-abe9-f6897edaab1f)

**Comment by DougAGault** [comment] 2024-12-10 17:51
> What version exactly? I don't see a pre-release available posted in the last two weeks:
> 
Same.. not seeing anything "new"

**Comment by notatallshaw-gts** [comment] 2024-12-10 18:06
So, it's interesting because new versions are available under "Version History" here: https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github


But they are not showing up when I click "Switch to Pre-Release Version" and then try and install a specific version or refresh VS Code/

I tried manually downloading the [latest VSIX](https://marketplace.visualstudio.com/_apis/public/gallery/publishers/GitHub/vsextensions/vscode-pull-request-github/0.101.2024120916/vspackage) and install it manually into my VS Code but I got the following error:

![Image](https://github.com/user-attachments/assets/95a46824-0a15-437b-9087-18f0116e949b)

Am I doing something wrong here? My VS Code version info is:

```
Version: 1.95.3 (user setup)
Commit: f1a4fb101478ce6ec82fe9627c43efbf9e98c813
Date: 2024-11-13T14:50:04.152Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.19045
```

**Comment by alexr00** [comment] 2024-12-11 16:49
Ah, you'll need to use VS Code Insiders to try the latest pre-release. I should have mentioned this 😳

Thank you all for jumping in to try to verify!

**Comment by DougAGault** [comment] 2024-12-11 17:22
> Ah, you'll need to use VS Code Insiders to try the latest pre-release. I should have mentioned this 😳
> 
> Thank you all for jumping in to try to verify!

Yeah... can't do that.. Our version of VSCODE is controlled by Central IT. 

Let us know when it's GA and I'll be happy to validate.

**Comment by rzhao271** [comment] 2024-12-11 18:17
Moving milestone to next month.

**Comment by DougAGault** [comment] 2024-12-11 21:57
I also tested on the 1.96.0 (just got rolled out internally) and 0.103.2024121117 

Everything seemed to work fine. No issues, no error message.

**Comment by alexr00** [comment] 2024-12-12 09:07
Thank you folks! The fix is available in the latest stable release now.
