### ISSUE TITLE
Can configure my pull request and issues 

### ISSUE THREAD

**Issue by drbetique** [microsoft/vscode-pull-request-github#2140] opened 2020-09-20 18:45 UTC
Issue Type: <b>Bug</b>

i get the following message each time i tried to configure my github extention Command 'GitHub Pull Requests: Configure...' resulted in an error (command 'pr.configurePRViewlet' not found)

Extension version: 0.20.0
VS Code version: Code 1.49.1 (58bb7b2331731bf72587010e943852e13e6fd3cf, 2020-09-16T23:27:51.792Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2670QM CPU @ 2.20GHz (8 x 2195)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|5.91GB (1.00GB free)|
|Process Argv|--crash-reporter-id 16ecc1a2-8650-4fd4-a92c-d0683ca4c1ef|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by scottwallacesh** [comment] 2020-11-13 11:45
What got this working for me was adding an entry to `~/.vscode/argv.json`:
```javascript
{
    // Allow Github Pull Request to work
    "enable-proposed-api": [
        "GitHub.vscode-pull-request-github"
    ]
}
```

**Comment by alexr00** [comment] 2020-12-30 10:53
Closing because I'm unable to reproduce the issue.

**Closed by alexr00** 2020-12-30 10:53 UTC
