### ISSUE TITLE
Unable to authenticate with github enterprise

### ISSUE THREAD

**Issue by dave-hart** [microsoft/vscode-pull-request-github#1755] opened 2020-05-05 06:16 UTC
My current vscode workspace has an enterprise github project open, but the github pull requests plugin authenticates me with GitHub.com rather than my enterprise server.

I have been using the extension for a number of months with no problems, but when opening vscode yesterday I was prompted to authenticate, and have thus far been unable to get it to authenticate with my enterprise server.

I have followed the instructions in this wiki https://github.com/Microsoft/vscode-pull-request-github/wiki but the command mentioned to manually add an access token no longer seems to exist.

- Extension version: 0.16.0
- VSCode Version: 1.45.0-Insider
- OS: MacOs
- GitHub Enterprise Version: 2.19.8

Steps to Reproduce:

1. Open vscode
2. Select `GitHub Pull Requests` App
3. Click to authenticate
4. Complete the Github authentication flow in the resulting browser window, giving permission

**Comment by v-vazquez** [comment] 2020-05-07 23:46
They removed the support because they don't have servers... What ... 

https://github.com/Microsoft/vscode-pull-request-github/wiki

**Comment by sasikumardr** [comment] 2020-05-08 04:53
Workaround for now is to downgrade to extension version 0.15

**Comment by KnisterPeter** [comment] 2020-05-08 08:43
I'm really sad about this :cry:

**Comment by erihanse** [comment] 2020-05-08 10:06
Shouldn't this have been mentioned in the changelog atleast?

**Comment by codeartlabs** [comment] 2020-05-08 12:53
Is there any chance to config the enterprise host and its token as follows?
![image](https://user-images.githubusercontent.com/7697703/81407358-d76e1500-916d-11ea-8095-5182e5147a85.png)
I tried but it doesn't work...

**Comment by tk3369** [comment] 2020-05-09 19:27
Seems counter-intuitive that a paying customer is getting fewer features...

**Comment by sasikumardr** [comment] 2020-05-10 04:37
This is not github's offering. As far as vscode team's concern, they are just helping vscode community with some useful extensions.  As they mentioned in wiki, they have some technical and resource challenges for providing support for GitHub enterprise.
May be we should help creating PRs for adding this support rather than expecting everything from dev team.

**Comment by tk3369** [comment] 2020-05-10 06:18
That's fair... but Microsoft owns GitHub.  I guess I'm expecting a little more :-) 

The wiki says:
> This iteration we moved to a new method of authentication built into VSCode in an effort to unify authentication and account management, and this API currently doesn't support Enterprise accounts.

It's unclear how to contribute PR.  Maybe there's a better write-up somewhere about the challenge...

**Comment by ggcatu** [comment] 2020-05-11 09:24
Wow, this is really a shame, I use this extension daily for github enterprise, I wouldn't mind contributing to this..

**Comment by RMacfarlane** [comment] 2020-11-11 00:03
Closing as a duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/1793

**Closed by RMacfarlane** 2020-11-11 00:03 UTC
