### ISSUE TITLE
Team reviewers - auth warning but not being prompted for auth

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode-pull-request-github#4773] opened 2023-04-26 11:35 UTC
Testing #4764

When I click on the "Teams" icon, I see the following warning. Is that expected?

<img width="471" alt="image" src="https://user-images.githubusercontent.com/3372902/234562915-1c4a616a-d9c2-4f42-8468-75f79e6700c1.png">

The notification should contain an action to re-auth.

**Comment by alexr00** [comment] 2023-04-26 13:09
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/4770

**Closed by alexr00** 2023-04-26 13:09 UTC
