### ISSUE TITLE
Search string in modified pull request files

### ISSUE THREAD

**Issue by Splines** [microsoft/vscode-pull-request-github#6240] opened 2024-09-23 08:31 UTC
Thanks for this amazing extension, works like a charm 🎉

A feature I'd be looking forward to is to **limit the VSCode in-built search to *files* that were modified in the currently checked out pull request**. Additionally, an option to only search in the modified *lines* of these files would also be great.

This feature could help get a better understanding of what a PR changed as you would be able to easily search in it for strings you've seen somewhere in the modified lines and find out about its usage and how files are related to each other. Without this *limited* search, many more occurrences of a given string in the entire codebase might show up making it harder to discern what was changed in the PR and what not.

**Comment by alexr00** [comment] 2024-09-26 10:28
Cool idea! @andreamah is this something that the search API you've been working on might enable?

**Comment by andreamah** [comment] 2024-09-26 16:03
Hmm. Since the files will still be of `file` scheme, the `fileSearchProvider` and `textSearchProvider` won't apply to this case. It's mostly if you have a custom filesystem / scheme.

**Comment by alexr00** [comment] 2024-12-16 11:39
Duplicate of @5752

**Closed by alexr00** 2024-12-16 11:39 UTC
Labels: feature-request

**Comment by Tushar1729-k** [comment] 2025-04-14 19:35
Hi @Splines , @alexr00 , @andreamah is this merged in? If so how do I use it?
