### ISSUE TITLE
Double click on file does not keep it open

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode-pull-request-github#1249] opened 2019-06-26 18:48 UTC
Issue Type: <b>Bug</b>

Normally when you double click on a file, it keeps it open in a tab even when you open a different file afterwards. This doesn't happen with the Changes In Pull Request  > Files tree.

Extension version: 0.8.0
VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:29:22.216Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|16.00GB (1.11GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by JacksonKearl** [comment] 2019-06-26 18:50
Hey @rebornix and @RMacfarlane ! Sorry for bombarding you with issues / requests. I do enjoy using the extension though!

**Comment by RMacfarlane** [comment] 2019-10-09 17:42
Closing as a duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/1035

**Closed by RMacfarlane** 2019-10-09 17:42 UTC
Labels: enhancement
