### ISSUE TITLE
Fetching Pull Requests Failed..."undefined" cannot be set for field q (code: invalid)

### ISSUE THREAD

**Issue by rbuckton** [microsoft/vscode-pull-request-github#1982] opened 2020-07-09 20:51 UTC
- Extension version: 0.17.0
- VSCode Version: 1.47.0-insider
- OS: Windows 10

Steps to Reproduce:

1. Sign in to GitHub via the extension
2. Open a local repo for https://github.com/microsoft/TypeScript
3. Wait for Pull Requests to populate in the extension.
4. Expand the `Created By Me` node
5. No items are returned and the following error is shown in VS Code:
   ![image](https://user-images.githubusercontent.com/3902892/87088946-7d7be100-c1ea-11ea-8db5-1d27b31a3c13.png)

A few notes:
- `Pull Requests` under the `All` category seem to be working fine.
- `Issues` seems to be working fine.
- All repos in the microsoft org now require additional, periodic "single-sign-on" authentication with Microsoft.
- Due to some errors related to compression from git when using SSH, I have my remotes set up as follows:
  ```
  > git remote -v
  origin  https://github.com/microsoft/TypeScript.git (fetch)
  origin  git@github.com:microsoft/TypeScript.git (push)
  ```

**Comment by rbuckton** [comment] 2020-07-09 20:59
I've worked around the issue following the same instructions in the wiki here: https://github.com/microsoft/vscode-pull-request-github/wiki#personal-access-token-authentication and enabling the token for SSO. 

If the above cannot be fixed directly, it would be helpful to update the wiki and possibly improve the error message to indicate where to find more information.

**Comment by alexr00** [comment] 2021-11-18 15:54
There have been many changes in auth in the last year. Closing, but please comment if the issue is still occurring.

**Closed by alexr00** 2021-11-18 15:54 UTC
Labels: bug
