### ISSUE TITLE
Unable to parse remote X... repeated every time the plugin does anything

### ISSUE THREAD

**Issue by kierenj** [microsoft/vscode-pull-request-github#489] opened 2018-09-17 08:51 UTC
Issue Type: <b>Bug</b>

I do have a dodgy remote, yes.  But I don't need reminding every 5 seconds until I fix it.  Is it possible to have this restricted to only appear when I'm actually using the repo in question, or better still, be dismissable / snoozable?

Extension version: 0.1.5
VS Code version: Code 1.27.1 (5944e81f3c46a3938a82c701f96d7a59b074cfdc, 2018-09-06T09:21:18.328Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2494)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (8.13GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe .|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by achton** [comment] 2018-09-17 09:28
I think this is a duplicate of #440.

**Comment by kierenj** [comment] 2018-09-17 09:47
Ah they are related.  Well, the error is the same one, but my query in particular is about the fact the error appears very frequently and can't be dismissed without reappearing, not relating to ssh://**** specifically?

**Comment by auchenberg** [comment] 2018-09-19 05:47
Getting the same here. 

My remotes:
```
dokku   dokku@dokku.kenneth.io:2018.coldfront.co (fetch)
dokku   dokku@dokku.kenneth.io:2018.coldfront.co (push)
next    dokku@dokku.kenneth.io:next.coldfront.co (fetch)
next    dokku@dokku.kenneth.io:next.coldfront.co (push)
origin  git@github.com:auchenberg/2018.coldfront.co.git (fetch)
origin  git@github.com:auchenberg/2018.coldfront.co.git (push)
```

**Comment by rebornix** [comment] 2018-10-09 23:47
@auchenberg I can no longer reproduce this issue with 0.1.7, can you help verify?

**Comment by RMacfarlane** [comment] 2019-10-09 23:30
I'm not able to reproduce this issue in 0.12.0, closing since there have been no new reports of this.

**Closed by RMacfarlane** 2019-10-09 23:30 UTC
Labels: bug, needs more info
