### ISSUE TITLE
Duplicate buttons in PR comments

### ISSUE THREAD

**Issue by burkeholland** [microsoft/vscode-pull-request-github#2463] opened 2021-02-05 15:23 UTC
- Extension version: v2021.2.4862
- VSCode Version: Codespaces Prod Commit e035230
- OS: Windows 10

Steps to Reproduce:

1. Open [this PR with existing comments](https://github.com/chrisdias/gh-static-e2e/pull/4) in a Codespace
2. Reply to a comment

## What Happens
There are duplicate buttons for "Start Review" and "Add Comment"

![image](https://user-images.githubusercontent.com/686963/107052898-d406c900-6793-11eb-80da-d218b8b063cf.png)

**Comment by RMacfarlane** [comment] 2021-02-05 16:28
I think you have both the nightly and stable versions of the extension active

https://github.com/microsoft/vscode-pull-request-github/issues/1782

**Comment by bamurtaugh** [comment] 2021-02-05 21:34
I was seeing duplicate PR buttons:

![image](https://user-images.githubusercontent.com/25310137/107091198-34a6fd80-67b6-11eb-96f2-a3d2c6981702.png)

I was confused because I only saw the Nightly in my Extensions viewlet:

![image](https://user-images.githubusercontent.com/25310137/107091353-7e8fe380-67b6-11eb-94f4-1cea4cbc27f9.png)

I still looked up the Stable version, and it _is_ enabled:

![image](https://user-images.githubusercontent.com/25310137/107091465-b26b0900-67b6-11eb-9b32-9bd17288abb0.png)

I disabled it and reloaded, which fixed my problem:

![image](https://user-images.githubusercontent.com/25310137/107091555-d75f7c00-67b6-11eb-85f3-6a498bd69b71.png)

Any idea why it didn't show up in the Extensions viewlet in that first look?

**Comment by RMacfarlane** [comment] 2021-02-05 21:44
That's very weird!

@sandy081 Any ideas here?

**Comment by sandy081** [comment] 2021-02-09 15:11
Stable version of the extension is installed as Built in and hence it is not shown in installed list but will be shown in built in list (just like js-debug). Since you have both extensions installed and enabled you are seeing two icons.

**Comment by RMacfarlane** [comment] 2021-02-09 19:10
Going to go ahead and close this since I think this is a duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/1782

**Closed by RMacfarlane** 2021-02-09 19:10 UTC
