### ISSUE TITLE
How to create a PR using the extension?

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode-pull-request-github#321] opened 2018-08-29 09:19 UTC
Testing https://github.com/Microsoft/vscode/issues/57301

Maybe I missed it, but if I am a user getting started with github and with a certain project, what steps can I do to create a PR using the extension? It seems imbalanced in showing only existing PRs.

**Comment by lhutz** [comment] 2018-09-11 06:12
I think it is not yet available in this extension, like it's mentioned in #283

**Comment by RMacfarlane** [comment] 2018-09-12 16:34
Closing as a duplicate of https://github.com/Microsoft/vscode-pull-request-github/issues/283

**Closed by RMacfarlane** 2018-09-12 16:34 UTC
