### ISSUE TITLE
Creating comment failed: Error Cannot find document

### ISSUE THREAD

**Issue by scrossan-crown** [microsoft/vscode-pull-request-github#1290] opened 2019-08-05 15:47 UTC
- Extension version: 0.9.2
- Version: 1.36.1 (user setup)
- Commit: 2213894ea0415ee8c85c5eea0d0ff81ecc191529
- Date: 2019-07-08T22:59:35.033Z
- Electron: 4.2.5
- Chrome: 69.0.3497.128
- Node.js: 10.11.0
- V8: 6.9.427.31-electron.0
- OS: Windows_NT x64 10.0.18950

Steps to Reproduce:

1. Start a review
2. Type a new comment and then click `Add Comment` button

The comment does seem to get created, as I can close the file and come back and the comment is still there.

![image](https://user-images.githubusercontent.com/30405149/62477143-40b89600-b7a0-11e9-9c96-a0b1f69ffc8f.png)

**Comment by ProLoser** [comment] 2019-08-05 23:01
This has been happening for me for a few weeks now:

![image](https://user-images.githubusercontent.com/67395/62500225-562ac180-b79a-11e9-999b-860939de7d21.png)

**Comment by vivan-niche** [comment] 2020-06-18 21:19
Also experiencing this. The comment is saved somewhere locally, as closing and re-opening the file still shows it, but it is not synced to github.

**Comment by S-p-Ace** [comment] 2021-04-07 09:34
Getting this too every now and then... even now nearly 2 years later smh
Usually reloading the window fixes it but sometimes it gets stuck. Even exiting and reentering review mode didn't help this time.
Though in the end refreshing the pull requests list and expanding the files tree under the PR description entry seems to have fixed it.

Looks like the file index of the PR or something like that is getting out of synch sometimes and that's why the error occurs.

**Comment by alexr00** [comment] 2022-12-13 07:23
Next time some one sees this can you set `"githubRepositories.logLevel": "debug"`, reproduce the issue, then share the output from GitHub Pull Request?

**Closed** 2023-06-20 09:22 UTC
Labels: info-needed
