### ISSUE TITLE
Clicking "Description" immedatiely steals focus

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode-pull-request-github#5819] opened 2024-03-08 15:33 UTC
Clicking "Description" immedatiely steals focus:

![Image](https://github.com/microsoft/vscode-pull-request-github/assets/2931520/55f50704-ad15-409a-af1d-82c0e5d81577)

Subsequently clicking it does not.

**Comment by alexr00** [comment] 2024-03-15 11:24
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/5332#issuecomment-1757299591.

**Closed** 2024-03-15 11:24 UTC
Labels: *duplicate
