### ISSUE TITLE
Comment textbox loses scroll position on typing

### ISSUE THREAD

**Issue by johnknoop** [microsoft/vscode-pull-request-github#5841] opened 2024-03-18 14:44 UTC
- Extension version: v0.82.0
- VSCode Version: 1.87.2 (system setup)
Commit: 863d2581ecda6849923a2118d93a088b0745d9d6
Date: 2024-03-08T15:20:17.278Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.22631

Steps to Reproduce:

1. Type enough text into a comment textbox so that it will overflow vertically.
2. Type a key

As you can see on my screen recording, when I enter a new character into the textbox, it "scrolls up". I can scroll down to bottom again using the scrollbar (or the scroll wheel on the mouse), but if I hit another character, it scrolls up again. Also: I can't even scroll to bottom using the down error (see screen recording), only using the scrollbar / scrollwheel.

![96e05236-6f89-445a-b087-2a6fbe4391d3](https://github.com/microsoft/vscode-pull-request-github/assets/3394270/c7984bc6-3670-4cb6-8a2d-567a75d64fdf)

**Comment by johnknoop** [comment] 2024-03-18 14:45
Also: would be nice to be able to resize the textbox for when you want to write a longer comment.

**Comment by alexr00** [comment] 2024-03-26 11:00
Duplicate of https://github.com/microsoft/vscode/issues/207333, which is available in VS Code Insiders.

**Closed by alexr00** 2024-03-26 11:00 UTC
