### ISSUE TITLE
Checks not listed in "Description" view, only Statuses are

### ISSUE THREAD

**Issue by foolip** [microsoft/vscode-pull-request-github#1413] opened 2019-10-25 07:20 UTC
- Extension version: 0.12.0
- VSCode Version: 1.39.2
- OS: Debian 4.19.37

Steps to Reproduce:

1. Clone the wpt repo and find https://github.com/web-platform-tests/wpt/pull/19754 in the list of pull requests in VS Code. For me it's under "Created By Me" but for others it may be hard to find.
2.At the bottom of the "Description" view, "2 successful checks" will be shown. On github.com, a total of 19 checks are shown. The ones missing in VS Code are the ones using the new [GitHub Checks API](https://developer.github.com/v3/checks/).

Screenshot: 
![image](https://user-images.githubusercontent.com/498917/67551047-3c997600-f708-11e9-8979-299343575395.png)

This is the same screenshot as in https://github.com/microsoft/vscode-pull-request-github/issues/1412, but this is *not* a dupe issue.

**Comment by foolip** [comment] 2019-10-25 07:22
For comparison, this is what https://github.com/web-platform-tests/wpt/pull/19754 looks like to me right now:
![image](https://user-images.githubusercontent.com/498917/67551304-dfea8b00-f708-11e9-863b-a3332db08cd7.png)

Note the "19 successful checks".

**Comment by IllusionMH** [comment] 2020-01-13 18:51
Looks like duplicate of #457

**Comment by RMacfarlane** [comment] 2020-01-13 21:38
Thanks @IllusionMH! Closing as a duplicate.

**Closed by RMacfarlane** 2020-01-13 21:38 UTC
Labels: enhancement
