### ISSUE TITLE
Random file opens when window loads

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-pull-request-github#2595] opened 2021-03-19 21:18 UTC
- Open a PR
- Close all editors
- Reload the window
- A random file diff from my PR is opened

**Comment by RMacfarlane** [comment] 2021-04-09 20:31
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/2295, this should already be fixed

**Closed by RMacfarlane** 2021-04-09 20:31 UTC
