### ISSUE TITLE
Request header field Accept is not allowed by Access-Control-Allow-Headers. https://api.github.com/graphql

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode-pull-request-github#3434] opened 2022-03-24 21:28 UTC
Version: 1.66.0-insider
Commit: c5dece632b4b1ea98db872e1edcfc92994503274
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Safari/605.1.15
Embedder: vscode.dev

1. On insiders.vscode.dev using Safari
2. Log in to GitHub 
3. Open a remote repository
4. Try expanding a PR in that repo

**Bug**
Nothing happens

In the dev  tools, I see:

```
[Error] Failed to load resource: the server responded with a status of 404 () (WorkspaceSnapshot, line 0)
[Error] Request header field Accept is not allowed by Access-Control-Allow-Headers.
[Error] Failed to load resource: Request header field Accept is not allowed by Access-Control-Allow-Headers. (graphql, line 0)
[Error] Request header field Accept is not allowed by Access-Control-Allow-Headers.
[Error] Failed to load resource: Request header field Accept is not allowed by Access-Control-Allow-Headers. (graphql, line 0)
[Error] Request header field Accept is not allowed by Access-Control-Allow-Headers.
[Error] Failed to load resource: Request header field Accept is not allowed by Access-Control-Allow-Headers. (graphql, line 0)
```

![Screen Shot 2022-03-24 at 2 26 54 PM](https://user-images.githubusercontent.com/12821956/160013319-784cd030-b752-4401-9318-2e95befa6502.png)

**Comment by alexr00** [comment] 2022-03-28 09:38
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/3430

**Closed** 2022-03-28 09:39 UTC
