### ISSUE TITLE
Missing Rich Code Navigation

### ISSUE THREAD

**Issue by deerawan** [microsoft/vscode-pull-request-github#1473] opened 2020-01-04 11:17 UTC
- Extension version: 0.13.0
- VSCode Version: 1.41.1, 1.42.0-insider
- OS: Darwin x64 19.2.0

Steps to Reproduce:

1. Open vscode / vscode insider
2. Install Extension 
3. Open PR
4. Try to click right to open menu but couldn't see code navigation options there e.g peek definition, go to definition. `cmd + click` is also not working. 

![rich-code-navigation](https://user-images.githubusercontent.com/1243921/71764687-22b5b400-2f3f-11ea-8b90-596303abd6bc.gif)

I read this page and just know about rich code navigation https://code.visualstudio.com/blogs/2018/12/04/rich-navigation

**Comment by RMacfarlane** [comment] 2020-01-06 18:25
@deerwan Unfortunately, code navigation only works if you have already checked out the pull request, and if you're exploring the files from the "Changes in Pull Request" tree that appears in that case. I would like to change it so that it also works from the tree in your screenshot as well when the PR is checked out. This issue covers that: https://github.com/microsoft/vscode-pull-request-github/issues/486

When the PR is not checked out, the file contents are being displayed directly from GitHub since the current commit may not be on disk, and is not the current state of the file system.

I'm going to close this as a duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/486

**Closed by RMacfarlane** 2020-01-06 18:25 UTC

**Comment by deerawan** [comment] 2020-01-07 08:26
@RMacfarlane ah noted, thank you for your response. I tried from "Changes in Pull Request" and it works, I could navigate it well. 

Your explanation about need to checkout first makes sense. 👍
