### ISSUE TITLE
Github Enterprise Support

### ISSUE THREAD

**Issue by noambloom** [microsoft/vscode-pull-request-github#2251] opened 2020-11-04 08:51 UTC
Support for Github Enterprise has been dropped since 0.16 but now that GH Cli is out and seems to support it (https://cli.github.com/manual/#github-enterprise-server) would it be possible to leverage their support and use the github cli as the backend for this extension?

**Comment by lupalby** [comment] 2020-11-06 18:08
I would be happy with beta support and actively help to test it. I would love for GHE support to be back!

**Comment by RMacfarlane** [comment] 2020-11-10 17:30
Closing as a duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/1793

**Closed by RMacfarlane** 2020-11-10 17:30 UTC
Labels: feature-request
