### ISSUE TITLE
allow to open file in editor from diff

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode-pull-request-github#504] opened 2018-09-19 09:26 UTC
- I checked out the PR
- In the 'github pull requests' viewlet, I go through the diffs and want to make a modification
- I didn't find an easy way to open the change in a real editor

The git diff editors have a 'open file' action.
![screenshot from 2018-09-19 11-26-08](https://user-images.githubusercontent.com/6461412/45744455-e4d43580-bbfe-11e8-8608-793412fd2895.png)

**Comment by RMacfarlane** [comment] 2018-09-19 16:54
Duplicate of https://github.com/Microsoft/vscode-pull-request-github/issues/268

**Closed by RMacfarlane** 2018-09-19 16:54 UTC
