### ISSUE TITLE
SCM: change icon hides when extension is installed

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-pull-request-github#379] opened 2018-09-10 15:03 UTC
I have no clue why but with this extension installed, icons for change type are removed from my SCM view shortly after window load:

![before](https://user-images.githubusercontent.com/900690/45305784-5df6cd00-b51b-11e8-8527-b3d5e6907a21.gif)

/cc @joaomoreno

**Comment by joaomoreno** [comment] 2018-09-10 15:05
cc @jrieken

**Comment by jrieken** [comment] 2018-09-10 15:34
hm, interesting...

**Comment by jrieken** [comment] 2018-09-11 08:49
Not able to reproduce this with 0.1.2

**Comment by RMacfarlane** [comment] 2018-09-20 23:17
I'm also not able to reproduce this with the latest version, 0.1.6, so will close this

**Comment by bpasero** [comment] 2018-09-23 07:10
Still happens:

![image](https://user-images.githubusercontent.com/900690/45925159-8796f780-bf10-11e8-8a7c-a042c4876718.png)

**Comment by jrieken** [comment] 2018-09-24 07:12
Steps? Logs? Console logs?

**Comment by bpasero** [comment] 2018-09-24 08:54
@jrieken 

* yo code
* git commit -m "init"
* rm README.md
* Git > Changes View
* wait 2 seconds

=> :bug: icon is gone

**Comment by bpasero** [comment] 2018-09-24 08:56
![peek 2018-09-24 10-55](https://user-images.githubusercontent.com/900690/45943870-699cc600-bfe8-11e8-8304-e992a0a853b3.gif)

**Comment by bpasero** [comment] 2018-09-24 08:56
[logs.zip](https://github.com/Microsoft/vscode-pull-request-github/files/2410195/logs.zip)

**Comment by bpasero** [comment] 2018-10-12 09:31
I am still seeing this all the time, was this pushed?

**Comment by RMacfarlane** [comment] 2018-10-12 23:48
Hmm, yeah it was pushed. The change should be in version 0.2.0 of the extension

**Comment by bpasero** [comment] 2018-10-19 05:58
Still happening:

![image](https://user-images.githubusercontent.com/900690/47200051-b3bd6100-d374-11e8-8d4e-8ddc43e7eda2.png)

![image](https://user-images.githubusercontent.com/900690/47200056-b91aab80-d374-11e8-9acb-c5b8c66e91f3.png)

**Comment by RMacfarlane** [comment] 2019-10-08 18:44
Closing as a duplicate of https://github.com/microsoft/vscode/issues/81467

**Closed by RMacfarlane** 2019-10-08 18:44 UTC
Labels: bug
