### ISSUE TITLE
Link hovers work inconsistently

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#1507] opened 2020-02-25 14:27 UTC
The hover shows up sometimes and not others. Link to xtermjs/xterm.js inside a microsoft/vscode clone.

![image](https://user-images.githubusercontent.com/2193314/75256001-a8175100-5797-11ea-9ee0-b074544e5ff0.png)

There is this in the console which may or may not be related

<details><pre><code>ERR file:///c%3A/Users/daimms.REDMOND/Documents/dev/Microsoft/vscode has no GitHub remotes: Error: file:///c%3A/Users/daimms.REDMOND/Documents/dev/Microsoft/vscode has no GitHub remotes
	at S.<anonymous> (c:\Users\daimms.REDMOND\.vscode-insiders\extensions\github.vscode-pull-request-github-insiders-2020.2.29762\media\extension.js:1:118506)
	at Generator.next (<anonymous>)
	at c:\Users\daimms.REDMOND\.vscode-insiders\extensions\github.vscode-pull-request-github-insiders-2020.2.29762\media\extension.js:1:96797
	at new Promise (<anonymous>)
	at r (c:\Users\daimms.REDMOND\.vscode-insiders\extensions\github.vscode-pull-request-github-insiders-2020.2.29762\media\extension.js:1:96574)
	at S.getOrigin (c:\Users\daimms.REDMOND\.vscode-insiders\extensions\github.vscode-pull-request-github-insiders-2020.2.29762\media\extension.js:1:118431)
	at Object.<anonymous> (c:\Users\daimms.REDMOND\.vscode-insiders\extensions\github.vscode-pull-request-github-insiders-2020.2.29762\media\extension.js:1:90470)
	at Generator.next (<anonymous>)
	at c:\Users\daimms.REDMOND\.vscode-insiders\extensions\github.vscode-pull-request-github-insiders-2020.2.29762\media\extension.js:1:89759
	at new Promise (<anonymous>)
	at r (c:\Users\daimms.REDMOND\.vscode-insiders\extensions\github.vscode-pull-request-github-insiders-2020.2.29762\media\extension.js:1:89536)
	at Object.t.getIssue (c:\Users\daimms.REDMOND\.vscode-insiders\extensions\github.vscode-pull-request-github-insiders-2020.2.29762\media\extension.js:1:90361)
	at t.IssueHoverProvider.<anonymous> (c:\Users\daimms.REDMOND\.vscode-insiders\extensions\github.vscode-pull-request-github-insiders-2020.2.29762\media\extension.js:1:1229782)
	at Generator.next (<anonymous>)
	at c:\Users\daimms.REDMOND\.vscode-insiders\extensions\github.vscode-pull-request-github-insiders-2020.2.29762\media\extension.js:1:1229241
	at new Promise (<anonymous>)
	at r (c:\Users\daimms.REDMOND\.vscode-insiders\extensions\github.vscode-pull-request-github-insiders-2020.2.29762\media\extension.js:1:1229018)
	at t.IssueHoverProvider.createHover (c:\Users\daimms.REDMOND\.vscode-insiders\extensions\github.vscode-pull-request-github-insiders-2020.2.29762\media\extension.js:1:1229733)
	at t.IssueHoverProvider.provideHover (c:\Users\daimms.REDMOND\.vscode-insiders\extensions\github.vscode-pull-request-github-insiders-2020.2.29762\media\extension.js:1:1229688)
	at c:\Users\daimms.REDMOND\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:585:255
	at c:\Users\daimms.REDMOND\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:54:345
	at new Promise (<anonymous>)
	at Object.t.asPromise (c:\Users\daimms.REDMOND\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:54:317)
	at S.provideHover (c:\Users\daimms.REDMOND\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:585:226)
	at c:\Users\daimms.REDMOND\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:607:893
	at V._withAdapter (c:\Users\daimms.REDMOND\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:604:832)
	at V.$provideHover (c:\Users\daimms.REDMOND\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:607:871)
	at p._doInvokeHandler (c:\Users\daimms.REDMOND\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:688:464)
	at p._invokeHandler (c:\Users\daimms.REDMOND\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:688:156)
	at p._receiveRequest (c:\Users\daimms.REDMOND\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:686:766)
	at p._receiveOneMessage (c:\Users\daimms.REDMOND\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:685:623)
	at c:\Users\daimms.REDMOND\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:683:791
	at l.fire (c:\Users\daimms.REDMOND\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:48:845)
	at v.fire (c:\Users\daimms.REDMOND\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:191:325)
	at c:\Users\daimms.REDMOND\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:851:104
	at l.fire (c:\Users\daimms.REDMOND\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:48:845)
	at v.fire (c:\Users\daimms.REDMOND\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:191:325)
	at t.PersistentProtocol._receiveMessage (c:\Users\daimms.REDMOND\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:195:717)
	at c:\Users\daimms.REDMOND\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:192:897
	at l.fire (c:\Users\daimms.REDMOND\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:48:845)
	at p.acceptChunk (c:\Users\daimms.REDMOND\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:188:897)
	at c:\Users\daimms.REDMOND\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:188:249
	at Socket.t (c:\Users\daimms.REDMOND\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:197:232)
	at Socket.emit (events.js:203:13)
	at addChunk (_stream_readable.js:295:12)
	at readableAddChunk (_stream_readable.js:276:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
</code></pre></details>

Version: 1.43.0-insider (user setup)
Commit: 89cafb24e5d75a0c8d561a6cdd95e93b5679e152
Date: 2020-02-25T05:29:49.719Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

Ext: 2020.2.29762

**Comment by alexr00** [comment] 2020-03-03 14:38
@Tyriar I think this has been fixed by one of the other changes I've made since I can't reproduce it. Let Please re-open if you're still seeing it!

**Closed by alexr00** 2020-03-03 14:38 UTC
Labels: bug
