### ISSUE TITLE
Creating a draft PR does not dismiss the Create Pull Request view

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-pull-request-github#3769] opened 2022-07-26 15:32 UTC
After creating a PR as draft, I get an error dialog and the Create Pull Request view does not dismiss in favor of the PR tree view. However if I go on GitHub I see that the PR was successfully created.
 <img width="425" alt="image" src="https://user-images.githubusercontent.com/30305945/181047923-8b4de22c-9cd5-4bff-9845-fa7a7a065674.png">

**Comment by alexr00** [comment] 2022-07-26 16:01
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/3755.

**Closed by alexr00** 2022-07-26 16:01 UTC
