### ISSUE TITLE
Edit base branch

### ISSUE THREAD

**Issue by fenilldomadiya** [microsoft/vscode-pull-request-github#5748] opened 2024-02-13 11:52 UTC
feature look like github pull request change base branch.

go to any open branch -> edit -> has dropdown of base branch.

could you please add same ui so that PR raiser could change desitnation.

**Comment by alexr00** [comment] 2024-02-19 17:22
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/1968

**Closed by alexr00** 2024-02-19 17:22 UTC
