### ISSUE TITLE
Resource not accessible by integration weirdness in codespaces

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode-pull-request-github#2210] opened 2020-10-13 00:30 UTC
Attempting to add a comment, get "resource not accessible by integration" error. Then get put into state where comment looks like it was posted but is in edit mode, try to save and I get "cannot reply to temporary comment error", but the comment gets duplicated. 

![image](https://user-images.githubusercontent.com/8586769/95801821-70bacd80-0cb0-11eb-9a3a-e9349982acf4.png)

**Comment by JacksonKearl** [comment] 2020-10-13 00:36
On trying to delete the comments, I can delete up to the topmost one, but at that point clicking the 'x' gives me an "are you sure" popup then it's a noop. Nothing logged to console.

**Comment by RMacfarlane** [comment] 2020-10-15 19:11
Closing as a duplicate of https://github.com/microsoft/vscode-internalbacklog/issues/1069

The type of token we get from Codespaces is different than in desktop, and is meant to work with only a particular repo. This causes issues for trying to perform actions against forks and there also seem to be some problems with private repos

**Closed by RMacfarlane** 2020-10-15 19:11 UTC
