### ISSUE TITLE
Cannot quit review mode from Changes in PR tree view

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-pull-request-github#259] opened 2018-08-22 18:43 UTC
Right now we have to either open the description page or find the pr in the PRs tree view and use the context menu to quit the review mode.

**Comment by alexr00** [comment] 2020-11-10 12:28
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/199

**Closed** 2020-11-10 12:28 UTC
Labels: feature-request
