### ISSUE TITLE
Description PReditor reused although directy 

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode-pull-request-github#325] opened 2018-08-29 13:26 UTC
Testing https://github.com/Microsoft/vscode/issues/57301

- Have two PRs
- open the description of the first one
- type into the comments field but don't submit the comment
- open the description of another PR

Observe: the editor is reused and your comment is lost.

**Comment by alexr00** [comment] 2020-11-10 12:54
Closing as designed since only allowing one description at a time is intentional.

**Closed by alexr00** 2020-11-10 12:54 UTC
Labels: ux
