### ISSUE TITLE
Can't fetch Pull Requests

### ISSUE THREAD

**Issue by jacksbox** [microsoft/vscode-pull-request-github#1142] opened 2019-05-02 09:38 UTC
I finished setting up the extension and connecting it to github, but sadly it can't fetch any PRs:

It fails with:
```
[Info] GitHubRepository> Fetching all pull requests failed: Only absolute URLs are supported
```

Can anybody give me a hint what I can do here? The error message is not that descriptive...

**Comment by RMacfarlane** [comment] 2019-05-02 23:11
@jacksbox Hmm, this looks like a node fetch error. This is with the latest version of the extension (0.6.0)? Are you using GitHub enterprise? Can you try changing the `githubPullRequests.logLevel` setting to debug/check the dev console by running the `Developer: Toggle Developer Tools` command?

**Comment by jacksbox** [comment] 2019-05-03 08:39
@RMacfarlane  I'm using the version 0.6.0, after setting the logLevel to debug, the output is 
```
[Debug 12350s 274ms] Looking for git repository
[Debug 12350s 274ms] Git repository found, initializing review manager and pr tree view.
[Debug 12350s 277ms] PullRequestManager> update repositories
[Debug 12350s 278ms] PullRequestManager> Displaying origin remote
[Debug 12350s 433ms] Found GitHub remote
```
there isn't any new output when I click on refresh in the GitHubPullRequest Section (neither in the integrated output console, nor in the Developer Tools).

**Comment by RMacfarlane** [comment] 2019-05-06 17:11
Is there anything special about your network configuration? What OS is this on?

**Comment by jacksbox** [comment] 2019-05-08 10:02
macOS 10.14.3, no special network configuration.

I tried `unintall` and `reinstall` the extension, and the output changed slightly.

```
[Debug 154897s 843ms] Looking for git repository
[Debug 154897s 843ms] Git repository found, initializing review manager and pr tree view.
[Debug 154897s 846ms] PullRequestManager> update repositories
[Debug 154897s 849ms] PullRequestManager> Displaying all github remotes
[Debug 154897s 849ms] PullRequestGitHelper> Get user created remotes - start
[Debug 154898s 299ms] PullRequestGitHelper> Get user created remotes - end
[Debug 154898s 313ms] No GitHub remotes found
[Debug 154898s 330ms] Review> no matching pull request metadata found for current branch SAEFRNT-275_interactive-rating-form
[Debug 154898s 330ms] PullRequestManager> update repositories
[Debug 154898s 331ms] PullRequestManager> Displaying origin remote
[Debug 154898s 376ms] Found GitHub remote
```

If I click the `+` button in the PullRequest panel, following error shows up in the dev tools.
```
[[object Object]]<file> has no GitHub remotes
```

Maybe as further information, the normal git commit, pull, push integration works perfectly.

**Comment by RMacfarlane** [comment] 2019-05-23 23:39
@jacksbox Does this reproduce with the newest version of the extension, 0.7.0? (Note that it requires the latest VS Code, 1.34.0)

**Comment by jacksbox** [comment] 2019-06-04 11:09
jep, still the same behaviour

**Comment by jacksbox** [comment] 2019-06-04 11:20
oh, I figured it out 😄 
using `GitHub Pull Requests: Sign out of GitHub` and `GitHub Pull Requests: Sign in to GitHub` with some window reloads worked.
Guess I could have done that earlier, but the debug messages did not hint in this direction... also the Source Control tab worked normally.

**Comment by jaywryan** [comment] 2019-08-13 15:03
I still have this issue with Mac OS 10.13.6 and GHE 2.15 ```Fetching all pull requests failed: HttpError: Only absolute URLs are supported```

**Comment by danielbmeireles** [comment] 2019-09-19 13:54
I am having the same issue. Mac OS 10.14.6 + GHE 2.18.1. Github Pull Request Extension is in the 0.11.2 version.

`Fetching pull requests failed: Only absolute URLs are supported`

**Comment by alexr00** [comment] 2020-11-11 15:08
Auth has changed, so closing as fixed. If you're still seeing this please feel free to ping this issue.

**Closed by alexr00** 2020-11-11 15:08 UTC
