### ISSUE TITLE
Exiting review mode

### ISSUE THREAD

**Issue by svipas** [microsoft/vscode-pull-request-github#1236] opened 2019-06-13 06:25 UTC
- Extension version: 0.8.0
- VSCode Version: 1.35.1
- OS: macOS

As far as I understand review mode is simply checking into the branch. The problem is if I had a `master` branch, created an `update-something` branch and created a PR I'm now into review mode. **BUT** if I exit the review mode it will simply checkout to the `master` branch. What I really expecting from this extension is to have the ability to exit review mode and still be in the same branch. I really want features like the comment, etc., but only when I decide to do that instead of always when I'm into a specific branch where PR was created. I hope I explained it clearly :D

**Comment by phyllisstein** [comment] 2020-06-24 03:40
:wave: Hey gang. Just wanted to apply a gentle nudge in favor of this change. The work you've done to support the GitHub PR review flow in VSCode is, frankly, amazing. When I need to approve code, I love having it to hand.

But when I'm _contributing_ code, I usually open a draft pull request as soon as I have something substantive to push. The comment bar feels a little obtrusive while I'm actively making changes. Since, on balance, I do more contributing than reviewing, I wind up disabling this extension just to focus; then re-enabling it to spare myself GitHub's `textarea`s during reviews; then disabling it to focus; etc. _ad naus_.

Here's an example:

![2020-06-23 23 29 18](https://user-images.githubusercontent.com/2207980/85496776-dcb2e200-b5aa-11ea-8b2a-7defd89ffd51.gif)

It'd be great, is the upshot, if there were a way to exit review mode _without_ checking out the default branch. Thanks for considering it. ❤️

**Comment by kimmoahokas** [comment] 2020-09-15 13:40
I think #1704 might be about the same thing? Maybe MS employees are starting to work on this :)

**Comment by alexr00** [comment] 2020-11-11 15:19
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/408

**Closed by alexr00** 2020-11-11 15:19 UTC
Labels: feature-request
