### ISSUE TITLE
Linked pull requests

### ISSUE THREAD

**Issue by KristofMerey** [microsoft/vscode-pull-request-github#2676] opened 2021-04-25 13:11 UTC
If I create a pull request working on an issue branch, I expect that the new pull request is automatically linked to the issue in its section "Linked pull requests".

**Comment by alexr00** [comment] 2022-12-12 11:51
The GitHub API doesn't have a way to do this directly. The only way is to have a "Fixes #XYZ" type string in the PR description.

**Comment by alexr00** [comment] 2024-12-17 10:35
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/5824

**Closed by alexr00** 2024-12-17 10:35 UTC
Labels: feature-request, upstream
