### ISSUE TITLE
After checkout own PR, always returns to review mode when check out PR's working branch

### ISSUE THREAD

**Issue by johlju** [microsoft/vscode-pull-request-github#408] opened 2018-09-11 09:41 UTC
- Extension version: 0.1.2
- VSCode Version: 1.27.1 (5944e81f3c46a3938a82c701f96d7a59b074cfdc, 2018-09-06T09:21:18.328Z)
- OS: Windows_NT x64 10.0.18234

Steps to Reproduce:

Assume we have a working branch named 'feature-branch'
1. Send in a (own) PR to a repo (based on branch feature-branch).
2. Checkout (own) PR with extension.
3. Exit Review Mode ( `git checkout master`)
4. Run `git checkout feature-branch`.

Now we are in review mode again.

**Comment by RMacfarlane** [comment] 2018-09-11 16:38
If I'm understanding this correctly, this is by design. Since the branch `feature-branch` is associated with a PR, the extension will switch into review mode whenever you check it out, either from the Description page or the command line.

**Comment by johlju** [comment] 2018-09-11 16:53
But it wasn’t in review mode to start with. Although, it could be because I already had the working branch checked out when starting VS Code.

**Comment by a2sheppy** [comment] 2019-01-07 17:10
So, I have run into a similar issue. When I installed the extension, I was in the middle of making changes to resolve review feedback on an existing PR, so I had that PR's branch checked out. I made the mistake of clicking the "Check out" button on my PR within VS Code. When I realized I couldn't actually make my fixes while in review mode, I clicked "Exit Review Mode".

This asks me what branch I want to switch to. I don't want to switch branches. I need to continue working on the one I'm in already. Choosing the current branch from the list disables the "Exit Review Mode" button but doesn't do anything else that I can see. Upon giving up and restarting VS Code, I find that I'm still in review mode. If I instead choose another branch, like master, I wind up out of review mode and on that branch.

But then if I checkout my branch again, I'm back in review mode.

As far as I can see, there is no way to escape review mode now. I'm stumped, and am not sure how to fix this so I can resume work on my code...

**Comment by johlju** [comment] 2019-01-07 17:23
Disable the extension as a temporary workaround? :thinking:

**Comment by a2sheppy** [comment] 2019-01-07 17:24
@johlju Sure, get all clever and sci-fi. 😁

**Comment by segevfiner** [comment] 2019-12-25 09:48
There are multiple duplicate issues like this, probably one that I opened too. And this is one of the reasons I'm not using this extension after trying it.

The way "Exit Review Mode" works is confusing, it doesn't exit review mode, it just switches branches. Meaning that once you switch back to the branch you will be in review mode again as that state in the extension is left behind.

In my opinion, it should really exit review mode, returning to the state the extension is in on startup. Switching branches being an optional convenience for the use case of checking out a branch solely for looking at its PR and not a requirement to exit review mode.

You might enter review mode from creating a PR on your own branch, or to look at comments on it to fix them, you don't necessarily want to switch branches when done, just turn off review mode (The review gutter, etc.).

**Comment by bpasero** [comment] 2021-01-13 16:07
I would like to have a way to eiew mode. Now I am forced into it for a branch I switch to if it happens to be a PR too. But this PR I just created for myself, not for someone to review.

E.g. I see the review decorations now in the editor without having a way to turn that off:

![image](https://user-images.githubusercontent.com/900690/104477836-dd9c7700-55c1-11eb-8a08-0e9ee3c40bb9.png)

**Comment by guigagb** [comment] 2021-01-22 19:44
i want disable the start discussion too

**Comment by segevfiner** [comment] 2021-12-30 01:05
Might entail a separate issue but there also doesn't seem to be a way to associate an existing local branch with a PR, it might only do so when you create a PR from the extension? Or does it now create a separate branch for it `pr/*` branch for it?

**Comment by alexr00** [comment] 2022-06-29 12:15
With the setting `githubPullRequests.ignoredPullRequestBranches`, you can ignore PRs for specific branches.

With the command "Comments: Toggle Editor Commenting" you can quickly disable and re-enable the in-editor commenting features. 

Please do open a new issue you have any issues with those or if they won't solve your issue. If it really comes down to it I can look into adding a setting that lets you disable all autodetection of PRs.

**Closed by alexr00** 2022-06-29 12:15 UTC
Labels: feature-request
