### ISSUE TITLE
Not all language service features are available in diff until checked out

### ISSUE THREAD

**Issue by burkeholland** [microsoft/vscode-pull-request-github#2232] opened 2020-10-26 21:51 UTC
Found in scenario https://github.com/github/codespaces/issues/1608

- Extension version: 2020.10.34021
- VSCode Version: 1.50.1
- OS: Windows 10

Steps to Reproduce:

1. Click on a file in a PR that is not checked out
1. Notice that not all language services are available - i.e. unused parameters are not grayed out...

    ![image](https://user-images.githubusercontent.com/686963/97232538-4e927680-17ab-11eb-81b5-0f2a8e6cfd21.png)

1. Check out PR and notice that the diff now shows the unused variables

    ![image](https://user-images.githubusercontent.com/686963/97232585-64a03700-17ab-11eb-945f-a38826f6cce6.png)

**Comment by RMacfarlane** [comment] 2020-11-03 22:51
Closing as a duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/486. Thanks!

**Closed by RMacfarlane** 2020-11-03 22:51 UTC
Labels: duplicate, feature-request
