### ISSUE TITLE
Allow changing between two PRs on the same branch

### ISSUE THREAD

**Issue by blueo** [microsoft/vscode-pull-request-github#3412] opened 2022-03-17 01:04 UTC
As part of our workflow we'll open two PRs from the same branch into different target branches eg:

1. feature/branch -> main
2. feature/branch -> QA

This will create two entries in the 'Github' tab
![image](https://user-images.githubusercontent.com/948122/158715580-5ba957bd-60e2-438f-a76b-77f45e48bc71.png)

currently it is impossible to switch 'focus' between these requests without checking out a different branch first. Pressing 'checkout' on the 'unfocussed' PR does not do anything - presumably as you're already on that branch.

Ideally we could switch between multiple PRs on the same branch a bit more easily (eg the 'checkout' button would switch which PR you are currently focussed on).

**Comment by alexr00** [comment] 2023-12-15 15:18
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/2853

**Closed by alexr00** 2023-12-15 15:18 UTC
Labels: feature-request
