### ISSUE TITLE
Comments misplaced for unified diff view

### ISSUE THREAD

**Issue by arjun27** [microsoft/vscode-pull-request-github#1150] opened 2019-05-10 15:55 UTC
Steps to Reproduce:

On this PR - https://github.com/arjun27/Miniblog.Core/pull/2 - a comment is not positioned correctly on the unified diff view. Changing to side-by-side view fixes the issue.

<img width="1482" alt="Screen Shot 2019-05-09 at 6 46 55 AM" src="https://user-images.githubusercontent.com/284612/57540122-cf805880-7300-11e9-99de-6c5d964d0218.png">

<img width="1482" alt="Screen Shot 2019-05-09 at 6 46 22 AM" src="https://user-images.githubusercontent.com/284612/57540120-cd1dfe80-7300-11e9-8326-5f5bd80060f8.png">

Extension version: 0.6.0
VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:22:55.268Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 4|
|Memory (System)|8.00GB (0.32GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by RMacfarlane** [comment] 2019-05-21 17:14
@arjun27 This looks like a duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/160, let's track it there.

**Closed by RMacfarlane** 2019-05-21 17:14 UTC
