### ISSUE TITLE
Creating comment failed: TypeError: Cannot read properties of null (reading 'id')

### ISSUE THREAD

**Issue by ssardina** [microsoft/vscode-pull-request-github#3504] opened 2022-04-30 21:58 UTC
- **Extension version:** 0.40.0
- **VSCode Version:** 1.66.2
- **OS:** Linux on remote server mode (editing a repo on another machine)

**Steps to Reproduce:**

On a multi-repo workspace:

1. Open PR for repo A and issue a comment; works and is saved.
2. Open a second repo B
4. Issue a comment for repo B; will fail and not be saved 

Works once you restart Vscode and edit the PR of B directly, but once you open another repo C, same problem. 

However, when it works (for the first repo), Vscode does not bring up that pop-up selection box `GitHub Pull Request http://gitbub.com` when clicking `+`; I suspect extension gets confused and tries to do a comment somewhere else and has no permission

Expected: The comment is saved

Actual result:

![ghpr-problem](https://user-images.githubusercontent.com/2368384/166123842-3f084837-8417-4340-bd82-d738e2f3d26c.gif)

![image](https://user-images.githubusercontent.com/2368384/166123369-b340836f-1713-4073-a233-144966312ab7.png)

**Comment by alexr00** [comment] 2022-06-01 15:06
@ssardina do you have PRs checked out for one or both of these repos or are you just leaving comments by oping the diffs from the "Pull Requests" view?

**Comment by alexr00** [comment] 2022-06-02 12:51
Thanks @ssardina it does help. I can't reproduce it, but I'm wondering if you might have the same remote with different names setup in one or more of your repository clones.

 A few more questions to help determine this:
- Do you have one folder open in VS Code that has multiple repositories clones in the folder?
- Can you share the output of `git remote -v` for each of your repository clones?

**Comment by ssardina** [comment] 2022-06-02 22:33
mm difficult one indeed. I have many repos, each on its folder. All repos are in an GitHub organization (for a course). Here are the `remote -v` for two of them:

![image](https://user-images.githubusercontent.com/2368384/171749073-6d563223-f5a8-49f9-b803-0f3f6d455bee.png)


Yes one folder open in VS Code, the root of all submissions. There is then 1 folder per submission, each having its own repo, yes!

**Comment by alexr00** [comment] 2022-06-03 13:42
I can reproduce it, but only if I have two clones of the same repo. Example folder structure:

Folder "alexr00" - this is the folder I have open in VS Code.
  Folder "playground" - Contains a clone of my repository alexr00/playground
  Folder "playground-2" - Contains a clone of my repository alexr00/playground

@ssardina is it possible you have a similar duplication in your open folder?

**Comment by ssardina** [comment] 2022-06-06 07:27
Hi @alexr00 , thanks for following this up. 

Actually, no, they are different repos as you can see from the screenshot above:

![image](https://user-images.githubusercontent.com/2368384/172115270-3d29e6ac-04e5-4b2b-b51c-d7243cb930a9.png)

They do come from the same git template repo, but they are technically different repos. mm strange..

**Comment by alexr00** [comment] 2022-06-07 09:19
I will see if I can fix the issue with two clones of the same repo and maybe it will fix the issue you're seeing too.

**Comment by ssardina** [comment] 2022-06-07 11:17
It's a good idea/strategy, that is an issue as well anyways that you found! :-) Thanks!

**Comment by alexr00** [comment] 2022-07-11 11:54
@ssardina the [pre-release build](https://github.com/microsoft/vscode-pull-request-github/wiki/Pre-release-Build) has my fix for the double repo issue, which I think will also fix your issue. If you are able to try out the pre-release build and comment about whether the issue is fixed that would be very helpful!

There are still other bugs with multi repo support, tracked here: https://github.com/microsoft/vscode-pull-request-github/issues/3490

**Comment by alexr00** [comment] 2022-07-12 11:57
I'm going to close the issue so that it gets tracked for verification before the next release. @ssardina if you still see the issue I will reopen it!

**Closed by alexr00** 2022-07-12 11:57 UTC
Labels: bug

**Comment by ssardina** [comment] 2022-07-12 22:39
Will do @alexr00, thanks!
