### ISSUE TITLE
Custom queries not working properly for pull requests

### ISSUE THREAD

**Issue by muradddd** [microsoft/vscode-pull-request-github#5970] opened 2024-04-26 09:06 UTC
When I add new custom query it does not showing correct pull requests.

Steps to Reproduce:

1.This is custom query config for pull request
![image](https://github.com/microsoft/vscode-pull-request-github/assets/30631316/ccef17c1-00fc-49d9-8a17-faccb9542a0c)

2.This is pull request tab result for custom query
![image](https://github.com/microsoft/vscode-pull-request-github/assets/30631316/e0177cb6-e6c6-413e-a336-b58451f07386)

3. This is github query and result
![image](https://github.com/microsoft/vscode-pull-request-github/assets/30631316/6982afd7-0ebc-408b-8299-f2efe4a0240e)

- Extension version: 0.86.1
- VSCode Version: 1.88.1
- OS: Ubuntu 22.04.4 LTS
- Repository Clone Configuration (single repository/fork of an upstream repository): single pirvate repository
- Github Product (Github.com/Github Enterprise version x.x.x): github.com
```[tasklist]
### Tasks
```

**Comment by alexr00** [comment] 2024-05-02 13:41
@muradddd is this a public repo, and if so can you share a link to it?

**Comment by muradddd** [comment] 2024-05-06 09:38
@alexr00 no, it is private repo.

**Comment by alexr00** [comment] 2024-05-06 09:53
Ok, in that case my guess is that you have a rule set up to delete the PR branch when the PR is closed. We don't show any PRs where the PR branch has been deleted, regardless of open/closed state. Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/4613

**Closed by alexr00** 2024-05-06 09:53 UTC
Labels: info-needed

**Comment by muradddd** [comment] 2024-05-06 10:15
Yes. Is there any workaround that I can list deleted branch PR?
