### ISSUE TITLE
Add a comment on code not being changed in the pull request.

### ISSUE THREAD

**Issue by anthonyvercolano** [microsoft/vscode-pull-request-github#560] opened 2018-10-08 18:35 UTC
Sorry if this has been mentioned.  I did search.

I examine a pull request.  I notice a bug in code that is not a change in the current pull request.

I don't see how to add a comment to note the bug.

**Comment by RMacfarlane** [comment] 2018-10-09 19:03
Hey @anthonyvercolano, thanks for reporting this. Currently, the GitHub API for review comments only supports adding comments around changes in pull requests. However, there is a different API for adding comments to a specific commit that we may be able to use for this. This is something we would like to support.

**Comment by octogonz** [comment] 2019-02-12 22:00
> Hey @anthonyvercolano, thanks for reporting this. Currently, the GitHub API for review comments only supports adding comments around changes in pull requests.

Since Microsoft bought GitHub, maybe we could put some pressure on them to finally fix their API? 😊 This is a really terrible limitation.  Other PR systems like AzureDev Ops do not have this limitation.

(As an example use case, I was just looking at a PR where `SomeClass.downloadFiles()` was converted to be a cancelable `Promise`, which has implications for many other functions in that file that participate in the asynchronous operation.  It's really arbitrary to say that my entire PR commentary has to be attached to the 5 lines of diff context around `SomeClass.downloadFiles()`...)

**Comment by alexr00** [comment] 2024-12-17 11:51
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/3305

**Closed by alexr00** 2024-12-17 11:51 UTC
Labels: feature-request, upstream
