### ISSUE TITLE
No "outdated" indication for review comments in overview page

### ISSUE THREAD

**Issue by RMacfarlane** [Microsoft/vscode-pull-request-github#174] opened 2018-08-10 19:01 UTC
Would be nice to have some indication that a comment is on an "outdated" hunk, likely indicating that the author has already addressed it

**Comment by Tyriar** [comment] 2018-08-28 18:13
Was about to report this one, it really clutters the PR as an outdated comment typically means it's no longer relevant.

**Comment by Tyriar** [comment] 2018-08-30 16:56
Duplicate of https://github.com/Microsoft/vscode-pull-request-github/issues/89?

**Closed** 2019-01-07 19:50 UTC
Labels: overview, ux
