### ISSUE TITLE
"Error" when check out PR

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-pull-request-github#1756] opened 2020-05-05 14:11 UTC
When I check out this PR: https://github.com/microsoft/vscode/pull/96128

I get this notification 
![image](https://user-images.githubusercontent.com/323878/81075695-4c142b80-8eb0-11ea-9054-9b85e2e5cc88.png)

and git seems to be in a weird state where it says there is only one commit:

![image](https://user-images.githubusercontent.com/323878/81075742-5d5d3800-8eb0-11ea-8001-0cb2a03f60a8.png)

(This was also happening before I merged master into the PR on github)

**Comment by RMacfarlane** [comment] 2020-05-05 17:08
I believe this is a duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/1612

**Closed by RMacfarlane** 2020-05-05 17:08 UTC
