### ISSUE TITLE
Pre-select reviewers/assignees/labels in quick open

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode-pull-request-github#4211] opened 2022-11-17 20:37 UTC
When editing the set of Reviewers, Assignees or Labels using the quick pick, I expected the current values to appear in the quick open already selected.

There's even some inconsistency right now:

- For both Reviewers and Labels, the current values don't appear at all.

![image](https://user-images.githubusercontent.com/22350/202554255-c1fb0ad0-432c-4791-847a-4bd58a2eb5f5.png)

- For Assignees, the current values appear, but unchecked.

![image](https://user-images.githubusercontent.com/22350/202554507-b29ca073-6646-401c-ac67-d9c8e63eab90.png)

**Comment by alexr00** [comment] 2022-11-18 13:43
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/4084

**Closed** 2022-11-18 13:43 UTC
