### ISSUE TITLE
File can't be opened, redirects me to browser

### ISSUE THREAD

**Issue by levani-k** [microsoft/vscode-pull-request-github#5827] opened 2024-03-12 06:31 UTC
I have latest version and when trying to open a file this pupop is displayed and it can't open file localy and redirects me to browser, no more error is shown.

<img width="478" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/72494243/1f3583a0-b19d-4e3c-8697-660159fbc8d3">

**Comment by AkashKumarSingh11032001** [comment] 2024-03-14 07:00
Hi @levani-k, is it possible to share the sample .tsx file, it would be helpful to reproduce this issue locally, Thanks

**Comment by zbjornson** [comment] 2024-03-20 19:02
This happens for me also on a somewhat regular basis. I can't share an example file because it's closed-source, but it seems to happen for larger diffs (one right now is +3k/-3k).

Are there limits or criteria when this happens?

https://github.com/microsoft/vscode-pull-request-github/blob/9520aa5e8d52ebda5ec09989cb734059d3bb37fc/src/commands.ts#L270

**Comment by alexr00** [comment] 2024-03-26 10:54
I just made a fix for this in March. Can you install the pre-release version of the extension and see if you still see the issue there?

**Comment by yfengBTI** [comment] 2024-07-02 17:42
I am still seeing this issue with the pre-release version `v0.91.2024062808`.

**Comment by alexr00** [comment] 2024-07-03 09:36
@yfengBTI do you also get the "Large diffs are not rendered by default" message when you try to open the same file on the website?

**Comment by yfengBTI** [comment] 2024-07-03 14:19
> @yfengBTI do you also get the "Large diffs are not rendered by default" message when you try to open the same file on the website?

OK, I've narrowed it down, there seem to be two thresholds on the number of diffs.

One threshold will prompt the GitHub PR site to show `Large diffs are not rendered by default`, but you can click on `Load diff` to try to force it to open. This threshold doesn't show up with VS Code.

But if the number of diffs is over a higher threshold, then clicking on `Load diff` on the site will show a message like this:
![image](https://github.com/microsoft/vscode-pull-request-github/assets/854702/9b26bca8-d392-4f5d-aa17-574f4ab0a17d)
And these are the file diffs that cannot be opened in VS Code as well with the message `... can't be opened locally. Do you want to open it on GitHub?`

Hope it helps

**Comment by alexr00** [comment] 2024-07-03 15:16
It does help, thank you. I'll see if I can repro.

**Comment by yfengBTI** [comment] 2024-07-03 17:59
> > @yfengBTI do you also get the "Large diffs are not rendered by default" message when you try to open the same file on the website?
> 
> OK, I've narrowed it down, there seem to be two thresholds on the number of diffs.
> 
> One threshold will prompt the GitHub PR site to show `Large diffs are not rendered by default`, but you can click on `Load diff` to try to force it to open. This threshold doesn't show up with VS Code.
> 
> But if the number of diffs is over a higher threshold, then clicking on `Load diff` on the site will show a message like this: ![image](https://private-user-images.githubusercontent.com/854702/345458456-9b26bca8-d392-4f5d-aa17-574f4ab0a17d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMjkxMzcsIm5iZiI6MTcyMDAyODgzNywicGF0aCI6Ii84NTQ3MDIvMzQ1NDU4NDU2LTliMjZiY2E4LWQzOTItNGY1ZC1hYTE3LTU3NGY0YWIwYTE3ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwM1QxNzQ3MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mOTRkNTU2ZGQ1MThkM2IzYmVmNzFmY2MzNzRlYTBiNGU2OGIzMDk5ZjdjNjJhM2UzNjY4OWI0YjJkNDU4OWRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zLWY_dHrW8Zi7HFVw2O9gUFfQpnMWlq1pNDXmoBREFg) And these are the file diffs that cannot be opened in VS Code as well with the message `... can't be opened locally. Do you want to open it on GitHub?`

FYI, I've encountered one file that can be opened on the GitHub site after clicking `Load diff` but still cannot be opened in VS Code.
So maybe this threshold is between the prompt for `Load diff` and the full stop, or it's something else entirely.
For reference, the file was changed from 31 KB with windows CRLF EOL to 35 KB with a mix of CRLF and LF EOL.
There are a total of 23 differences.

**Comment by alexr00** [comment] 2024-07-10 10:55
Got a repro 👍

**Closed** 2024-07-10 16:01 UTC
Labels: bug

**Comment by meganrogge** [comment] 2024-07-23 23:16
@alexr00 what was the repro

**Comment by alexr00** [comment] 2024-07-24 09:14
To verify:
1. Push a file to a repo that has only one empty line
2. Make a PR where you change the contents of the file to [checker.ts](https://github.com/microsoft/TypeScript/blob/main/src/compiler/checker.ts)
3. Checkout the default branch.
4. In the Pull Requests view, expand the PR you created in 2 and open the diff of the file that you changed. Verify that the diff shows.
