### ISSUE TITLE
Getting: Please submit the comment at .... although the comment is submitted

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode-pull-request-github#256] opened 2018-08-22 10:39 UTC
<img width="649" alt="capture" src="https://user-images.githubusercontent.com/1931590/44459019-5f159800-a608-11e8-835c-96f13acfab08.png">

**Comment by RMacfarlane** [comment] 2018-08-22 14:50
Duplicate of https://github.com/Microsoft/vscode-pull-request-github/issues/235, will track this there

**Closed by RMacfarlane** 2018-08-22 14:50 UTC
