### ISSUE TITLE
Bad colours for create button dropdown

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode-pull-request-github#5051] opened 2023-07-12 19:11 UTC
With the Quiet Light theme
![Create button dropdown showing purple background and grey text. The text is almost indistinguishable](https://github.com/microsoft/vscode-pull-request-github/assets/7199958/fa00fec4-5ea5-4328-bf35-5188bf5bb201)

**Comment by hbons** [comment] 2023-07-12 20:37
duplicate of #5052.

**Closed by hbons** 2023-07-12 20:37 UTC
