### ISSUE TITLE
Edit on comment disappears when switching to another tab and back

### ISSUE THREAD

**Issue by everhardt** [microsoft/vscode-pull-request-github#2707] opened 2021-05-04 09:45 UTC
- Extension version: 0.25.1
- VSCode Version: 1.55.2 (Universal)
- OS: macOS 11.3 (20E232) on a MacBook Air (M1, 2020)

Steps to Reproduce:

1. Create a PR comment and press "Add comment"
2. Edit that comment, but do not yet press "Save"
3. Switch to another tab (doesn't matter whether you do so by mouse or keyboard)
4. Switch back to the tab with the comment: the edit of the comment from step 2 is gone and the text from step 1 is shown.

A similar issue (but then for new comments instead of editing them) was fixed in 2018, see #337

**Comment by burkeholland** [comment] 2021-08-22 16:08
@alexr00 I _think_ (in my naive understanding of the Comment API) that this is an issue with the `CommentController` and should be resolved in the core API. What do you think?

**Comment by alexr00** [comment] 2021-08-23 08:55
@burkeholland I think you're correct, I don't see a clear way to do this with the comments API. 
@rebornix is there a way we're missing to persist in-progress comment edits and replies when the editor is switched?

**Comment by alexr00** [comment] 2022-01-31 14:22
Duplicate of this fixed issue: https://github.com/microsoft/vscode-pull-request-github/issues/3200

**Closed by alexr00** 2022-01-31 14:22 UTC
Labels: bug
