### ISSUE TITLE
'Stop Working on Issue' Not Working

### ISSUE THREAD

**Issue by onyekaa** [microsoft/vscode-pull-request-github#1785] opened 2020-05-10 23:11 UTC
Extension version: 0.16.0
VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T15:57:33.467Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.13GB free)|
|Process Argv|-psn_0_1668273818|
|Screen Reader|no|
|VM|0%|
</details>

I updated VSCode a few days ago (I was using this extension while it was still just for PRs). While testing out the Issues section, I noticed it had randomly decided to set me as working on an issue and I can't stop it. 

At first, I was able to experiment with starting and stopping another issue but since then it's just been stuck on this issue 12. The problem with this is VSCode keeps switching me to the branch it made for the issue (as shown in the gif). I tried deleting the branch but reloading VSCode brings it back. That issue is just permanently active. I tried also starting another issue but nothing works. As a last resort I tried disabling the extension and restarting the app, but re-installing brings it back to that issue. I don't know what caused this. The only way to get it to stop with the branch switching is to disable the extension completely. 

![May-10-2020 23-59-17](https://user-images.githubusercontent.com/3392638/81512707-64ee6800-931a-11ea-8502-e2a8f52bf9a7.gif)

**Comment by b3u** [comment] 2020-05-22 16:17
@onyekaa Can you check if you still have the issue? I can't reproduce it anymore.

**Comment by onyekaa** [comment] 2020-05-26 06:36
@b3u Still happening for me for that repo. Same version. I'm not having the issue on other workspaces, though to be fair since this started I've refrained from using it elsewhere.

**Comment by ermshiperete** [comment] 2020-05-27 13:41
For me this might have started after having changed `githubIssues.workingIssueBranch` (after I started an issue). Afterwards I wasn't able to stop or start work on a different issue.

In a different project/repo (which has my new global workingIssueBranch setting) start and stop works as expected.

**Comment by alexr00** [comment] 2020-06-10 08:33
@onyekaa are you still seeing this behavior? Can you try disabling the extension and installing the nightly version of the extension?

**Comment by alexr00** [comment] 2020-06-11 09:05
@onyekaa  thanks for trying it out. Do you have uncommitted changes in the branch?

**Comment by ParkourKarthik** [comment] 2020-06-12 06:07
@alexr00 I'm also facing the same issue, I was actually testing on how to work with start and stop feature. I'm using v1.45.1. I tried several ways to get out of it like disabling and enabling the extension, removing all the issue queries but none worked out.
I don't know how it happened but it still kind of haunts me, whenever I re-open vsCode, it switches to a new branch with the issue ID. So, I had to disable the extension for now.
The possible clues that I could give out are:
- working in a private repo
- adjusted the issue queries so that I could see all issues (nothing is assigned to me)
- deleted the new branch created by the extension and worked in my own branch 
- I avoided the commit with "fixes #issue" (but used issue reference in commit)

For your other query, I don't have any uncommitted changes in local. I even stash them and tried stopping.

**Comment by alexr00** [comment] 2020-06-12 09:51
Can you try the [Nightly build](https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github-insiders) of the extension? I removed the logic to try to restore your state on reload there since the feedback was that it was confusing to have your branch changed like that. We should be releasing a new stable version of the regular build soon.

Thank you for using the extension and filing bugs!

**Comment by ParkourKarthik** [comment] 2020-06-15 06:19
@alexr00 I tried the nightly build, it is reset now properly. Thanks :smile:

**Closed** 2020-06-15 08:02 UTC
