### ISSUE TITLE
Assigning a reviewer to a PR no longer works as expected

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-pull-request-github#6457] opened 2024-11-05 21:31 UTC
> 
> Hello, I'd like to mention that assigning a reviewer to a PR within VS Code no longer functions as expected. It was working fine earlier, but after the October Update, it stopped working. 
> 
> Now, after creating a PR in VS Code, I have to log in to GitHub manually to add a reviewer.
>  

 _Originally posted by @aguluman in [#232769](https://github.com/microsoft/vscode/issues/232769#issuecomment-2458185786)_

**Comment by alexr00** [comment] 2024-11-06 09:14
I'm not able to reproduce this. How are you trying to add a reviewer?

**Comment by aguluman** [comment] 2024-11-06 17:27
Hello, thanks for reaching back.

I tried it out today, and I was able to assignee a reviewer on a new PR within VS-Code. I am presently on VS-Code 1.95.1.

The experience I mentioned was on Friday, when I tried to create a PR, and I got this similar response, ```Fetching pull requests failed: request to https://api.github.com/repos/Joli-Health/joli_health_backend/pulls?per_page=20&page=1 failed, reason: getaddrinfo ENOTFOUND api.github.com```

I assume, it's peculiar to my local machine and my internet connectivity.

**Comment by aguluman** [comment] 2024-11-07 17:40
No, I am using GitHub Pro.

**Comment by alexr00** [comment] 2024-11-08 13:01
Hmm. Closing as transient. We can reopen if you see it again.

**Closed by alexr00** 2024-11-08 13:01 UTC
Labels: info-needed
