### ISSUE TITLE
Support username suggestions in create PR panel view

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode-pull-request-github#5631] opened 2024-01-18 15:27 UTC
Not sure if this is possible without a full monaco editor being used for the PR description, but I often find myself having to go to GitHub to add `@` mentions to PRs since I cannot remember everyone's exact GH handle. It would be nice if like GH typing `@` gave me a list of suggested usernames to place in the description.

<img width="482" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/4544166/fc88f5b9-7467-4637-b1bb-e0c3f0a850f0">

**Comment by alexr00** [comment] 2024-01-19 09:43
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/2401. It does require a monaco editor.

**Closed by alexr00** 2024-01-19 09:43 UTC
Labels: feature-request
