### ISSUE TITLE
GraphQL error when trying to resolve a comment on private repo pull request

### ISSUE THREAD

**Issue by somewhatabstract** [microsoft/vscode-pull-request-github#2969] opened 2021-08-27 18:36 UTC
> NOTE: I searched for this in the issues and online and can't find a ticket that matches this.

I can respond to comments, I can add comments, and I can add emoji reactions to comments. But the `Resolve Conversation` button fails with an error toast.

`Resolving conversation failed: Error: GraphQL error: Could not resolve to a node with the global id of 'github-browse-https://github.com.216'`

# Version Info
## VSCode
Version: 1.59.1 (Universal)
Commit: 3866c3553be8b268c8a7f8c0482c0c0177aa8bfa
Date: 2021-08-19T11:53:52.479Z (1 wk ago)
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Darwin x64 20.5.0

## Extension
v0.29.2 [PREVIEW]

# Steps to Reproduce:

1. Select a PR that has review comments in a private repo
2. Try to resolve a comment
3. See the error toast

**Comment by alexr00** [comment] 2021-08-30 14:05
@somewhatabstract this sounds like a duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/2857 (which applies to all comments, not just old ones).

**Closed by alexr00** 2021-08-30 14:05 UTC

**Comment by somewhatabstract** [comment] 2021-08-30 14:10
> @somewhatabstract this sounds like a duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/2857 (which applies to all comments, not just old ones). 

Thank you, @alexr00. I'm sorry my searching failed to find that issue and thread. Lesson learned.
