### ISSUE TITLE
Tab Labels are/really/quite/long

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode-pull-request-github#2204] opened 2020-10-08 23:22 UTC
I'd expect the tab to just have the basename but it seems to include the entire path.

![image](https://user-images.githubusercontent.com/8586769/95522999-69c74e80-0982-11eb-8891-0f339464b21e.png)

**Comment by RMacfarlane** [comment] 2020-10-13 22:02
Closing as a duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/952

**Closed by RMacfarlane** 2020-10-13 22:02 UTC
