### ISSUE TITLE
when adding comment of content "..." in the end of the code, the WebView displays plain text error

### ISSUE THREAD

**Issue by hongfanmeng** [microsoft/vscode-pull-request-github#1991] opened 2020-07-12 11:26 UTC
- Extension version: 0.17.0
- VSCode Version: 1.47.0
- OS: Windows10

Steps to Reproduce:

1. add a comment of content "..." in the end of code
2. goto the description page and press the refresh button

**Comment by RMacfarlane** [comment] 2020-11-09 18:21
Closing this since I have not been able to reproduce it in the latest version of the extension, so think it has been fixed. Please let me know if you see it again. Thanks!

**Closed by RMacfarlane** 2020-11-09 18:21 UTC
