### ISSUE TITLE
PR View doesn't update when reviewer assigned

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode-pull-request-github#4428] opened 2023-01-23 14:12 UTC
1. Create a PR
2. Click the gear to assign a reviewer
3. 🐛 They're not listed in the PR summary view

<img width="992" alt="image" src="https://user-images.githubusercontent.com/4544166/214060815-d6830c4b-2511-4e00-8faa-a77b4d8c5264.png">

**Comment by alexr00** [comment] 2023-01-23 16:50
I'm not able to reproduce this. Is it just slow (https://github.com/microsoft/vscode-pull-request-github/issues/4271)?

**Comment by lramos15** [comment] 2023-01-23 19:04
It seems only to be broken for `vscode` for me. All other repos update accordingly. I waited 30 seconds without an update in the vscode repo.

**Comment by alexr00** [comment] 2023-01-24 11:31
Interesting. I'm not able to repro even in `vscode`. Is there anything in the developer console?

**Comment by lramos15** [comment] 2023-01-25 16:21
Nothing shows in the console, but I noticed it only seems to happen if you assign a reviewer right as the PR is created. Assigning a secondary reviewer a few seconds after even seems to "unstick" the list. Not sure if that helps.

**Comment by lramos15** [comment] 2023-02-01 15:19
Looks like this is just being slow for me again and not being completely frozen, so unsure if it's the same root cause and you'd like to consolidate the issues feel free to close.

**Comment by alexr00** [comment] 2023-02-02 10:01
Since it's just slow let's call it a duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/4271. If you see it not work at all again please let me know!

**Closed by alexr00** 2023-02-02 10:01 UTC
Labels: info-needed
