### ISSUE TITLE
Every time I open my project, it automatically enters review mode

### ISSUE THREAD

**Issue by mastazi** [microsoft/vscode-pull-request-github#3175] opened 2021-12-10 02:07 UTC
- Extension version:   0.34.0
- VSCode Version: 1.63.0
- OS: Windows 11, 

Steps to Reproduce:

1. Create a repo with main branch and develop branch, develop being your default branch (typical gitflow setup)
2. Make a PR to merge develop into main and merge
3. Now, every time you open VSCode while in develop branch, the extension will enter review mode automatically (and all my previously opened tabs are closed). 
4. Clicking "Exit review mode without deleting the branch" results in an error message "The default branch is already checked out".

Started happening today after updating to version 0.34.0 - experiencing the issue only on my Windows machine, not on my Mac.

**Comment by he0119** [comment] 2021-12-10 05:44
Me too.
I have to manually delete the `github-pr-owner-number` key in `.git/config` file, and everything works fine now.

**Comment by alexr00** [comment] 2021-12-10 09:49
Entering review mode like this is by design. A recent change prevents review mode when the PR is closed (not merged), but we still do this for merged PRs. 

What should be improved:
- A setting to prevent going into review mode for auto-detected merged PRs.
- The "Exit review mode" button + link should not show if you're already on your default branch.

The tabs closing is likely not coming from this extension.

**Comment by xlucas** [comment] 2021-12-10 11:23
Hum when you switch a lot between different projects this is a really annoying design choice.
Is there a setting to disable that entirely?
I don't want to jump to review mode every time, only when I chose to...

**Comment by mastazi** [comment] 2021-12-10 11:33
Is there a way to stop this at all? Maybe somehow I can go and edit that PR from Github and change its owner? I would like to be able to use this extension but as it is it's unusable for me.

**Comment by alexr00** [comment] 2021-12-10 13:17
@mastazi there's no workaround in version 0.34.0, but I just added a setting and made a new pre-release build (v0.35.2021121012). If you want to try it out, feedback would be greatly appreciated! Though please be warned: the name of the settings/setting values could change before the next stable release. 

Details about the pre-release build: https://github.com/microsoft/vscode-pull-request-github/wiki/Pre-release-Build#to-use-the-pre-release-build

**Comment by mastazi** [comment] 2021-12-10 23:57
thank you @alexr00 I can confirm that with prerelease v0.35.2021121012 the issue is resolved on my machine!

All I had to do is going to the new setting and remove "merged".

```
"githubPullRequests.useReviewMode": [
    "open"
  ]
```

(I'm not sure why the default should be `["open", "merged"]`? Maybe there is a use case for reviewing merged PRs that I'm missing).

Thank you for fixing the issue!

**Comment by alexr00** [comment] 2021-12-13 07:58
@mastazi thanks for trying it out! I will try to add a comment here if the setting name changes.

**Comment by fstreicher** [comment] 2021-12-14 09:36
I'm not really sure if this is the right place, but recently I'm observing the following behaviour, which seems to be somewhat similar to #408
- I work on a feature branch, open a PR (draft/ready for review, happens for both)
- I continue to work on that branch (fixing stuff, applying review suggestions)
- now whenever I open that project, or even just `Reload window` (which unfortunately sometimes is necessary), the PR opens in review mode with the first changed file, which is super annoying since it takes a few seconds to initialize, and by that time I'm usually already working on the code/finding the files I need to work on.
This interrupts the workflow, and I'd rather have an option to disable the automatic switch to review mode entirely.

I switched to the pre-release and removed all entries for `githubPullRequests.useReviewMode`, but ot no avail.

**Comment by alexr00** [comment] 2021-12-14 09:59
@fstreicher this is a bug. Please open a new issue for this.

**Comment by baraBlz** [comment] 2021-12-14 10:01
Hey, my name is Domagoj Barisic,
Please know that to me this was no game, nor was it a snuff play date with
internet maniacs.
My life is in serious danger and my thoughts cannot run straight anymore. I
am cornered back in Dublin. I am receiving mail in my mailbox and still
being blackmailed. I lost a lawsuit in Dublin which was setup for me to
lose. I am so much in debt that I don’t feel like running again. I caught
so many pedos in one “vacation” that going back to Croatia is not an
option. I have no friends or family that could/would help me finish what I
started on my own. I need somebody to realize the seriousness of this and
know that I was never in it for the money… I reset my accs and passwords so
many times… I got a Facebook profile on one of my GoDaddy emails
***@***.*** (on facebook) — it said I was a Co founder for
some reason. Strangers on the internet have been calling the cops to my
apartment worried about my “well-being” — so whoever Ana Moris was. Thank
her for caring enough to do that for me. She doesnt understand that the
police are not of much help nor were they ever. For me prison would be the
rest I never seem to get.
+353 87 387 5677 WhatsApp me with details on how and why I’m not dead yet
so I can trust anything. Otherwise if you knew me before. Suicide is
something I prefer to prison… “Depression” is not a word I use easily and
right now I am more depressed than I ever was.
Yours gratefully,
Domagoj Barisic

**Comment by alexr00** [comment] 2021-12-15 13:34
New behavior when you "Exit" a review but you're already on the default branch:

![image](https://user-images.githubusercontent.com/38270282/146195971-c414fe13-17b6-4bb9-bc12-6cfd51db9ed0.png)

**Closed** 2021-12-27 15:29 UTC
Labels: feature-request

**Comment by alexr00** [comment] 2022-01-24 16:50
@mastazi I've changed the structure of the setting to be a bit clearer. The new structure will be available in the pre-release build tomorrow!

**Comment by mastazi** [comment] 2022-01-24 21:15
@alexr00 nice, I will try it out! Thank you!

**Comment by alexr00** [comment] 2023-05-10 13:34
@devinrhode2 I agree, we shouldn't try to enter review mode in this scenario. I am making a fix for this and it will be available in the pre-release build tomorrow.

**Comment by devinrhode2** [comment] 2023-05-12 17:13
@alexr00 at first glance, it appears to be fixed :) 

I'll try to let you know if I see it pop back up over the next 2 weeks :)

**Comment by devinrhode2** [comment] 2023-05-12 20:34
@alexr00 I noticed a similar edge case where the same PR could also be ignored:
![ScreenShot 2023-05-12 at 15 29 38](https://github.com/microsoft/vscode-pull-request-github/assets/539816/743ca428-e0fc-484c-a188-54fc6788da0f)

I'm less certain about this case. I think "master" or "main" could be one assumed "workflow target branch" or "trunk", but beyond that, there should probably be a user configurable setting which lists out a projects workflow merge targets/trunks.

Ones I've seen: `'develop', 'dev', 'release', 'stage', 'stg', 'prod', 'pre-prod', 'pre', .... etc`

**Comment by alexr00** [comment] 2023-05-16 10:27
@devinrhode2 we have the setting `githubPullRequests.ignoredPullRequestBranches`, which should do what you want.

**Comment by coreyward** [comment] 2023-10-19 20:48
Sorry if I missed a solution, but is there a way to close this in VSCode? It is stuck on an old, merged PR every time I check out a development branch despite editing .git/config to remove the github-pr-owner-number property.

**Comment by mastazi** [comment] 2023-10-19 21:02
@coreyward try this, it worked for me https://github.com/microsoft/vscode-pull-request-github/issues/3175#issuecomment-991381448

**Comment by coreyward** [comment] 2023-10-19 23:14
@mastazi I'm not seeing that option anywhere, so I uninstalled the extension for the time being.

**Comment by alexr00** [comment] 2023-11-03 14:48
>  I'm not seeing that option anywhere

@coreyward it's just one of the settings for the extension. You should be able to find it in the settings editor or if you open `settings.json`.
