### ISSUE TITLE
Can't resolve conversations from description page

### ISSUE THREAD

**Issue by melink14** [microsoft/vscode-pull-request-github#2754] opened 2021-05-28 10:48 UTC
- Extension version: v.0.26.0
- VSCode Version: 1.56.2
- OS: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Receive review comments on an open PR.
2. Create commit to resolve comments and push.
3. Go Pull Request description to close comment and see that it's marked `Outdated` with no option to resolve.

Resolving conversations in general was added in https://github.com/microsoft/vscode-pull-request-github/pull/2641 but I assume the interaction with `Outdated` commits is surfacing some thorns.

Of course, the work around is to resolve from GitHub website but my long term goal is to do everything from inside VS Code of course!

**Comment by alexr00** [comment] 2021-06-10 14:07
Resolving a comment is not supported from the Description page. Instead, you need to go to the comment in the file that it's in and resolve it from there.

**Comment by BenjaVR** [comment] 2021-06-15 11:54
@alexr00 is there any reason why this is not supported from the Description page? Would you consider supporting this?

**Comment by alexr00** [comment] 2021-06-15 12:13
Yes, I'd consider it (I added it to the backlog because of this). It's just work that needs to be prioritized and done. A good way to let me know that there's interest in a feature request (and that I should consider prioritizing it) is to upvote it :).

**Comment by BenjaVR** [comment] 2021-06-15 13:33
Great to know! I did not notice you adding it to the backlog 😄 

Would you accept a PR for this? If you can point me in the right direction I can take a look at this.

**Comment by alexr00** [comment] 2021-06-15 14:09
@BenjaVR I would like to take a PR for it, but I have just taken over managing this extension so my knowledge of what direction to point you in is low right now, but here's what I can tell you:

The comment section on the overview page is done here. I think you'd probably need to add to the `action-bar`.
https://github.com/microsoft/vscode-pull-request-github/blob/09386e95d87909f1717f3c330b7e6c7c427bb8ee/webviews/components/comment.tsx#L61-L86

Here is how you delete a comment, which you can use as reference for resolving a comment.
https://github.com/microsoft/vscode-pull-request-github/blob/9346269d520d0ecc6fdcf4fd7369ca7eb5f354e1/webviews/common/context.tsx#L72-L97

Once you have the appropriate args, you can use this to resolve:
https://github.com/microsoft/vscode-pull-request-github/blob/4c6d79cb0e503f3af996d3e848a43b440f998ed4/src/commentHandlerResolver.ts#L22-L23

which I expect you would call from a new entry in this switch statement:
https://github.com/microsoft/vscode-pull-request-github/blob/cda4dd3fd7dd730ea45f589c69e8c71766f5c6ca/src/github/issueOverview.ts#L187-L188

**Comment by samgermain** [comment] 2021-10-11 07:13
Would also like this feature

**Comment by alexr00** [comment] 2021-11-22 14:10
duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/2685

**Closed by alexr00** 2021-11-22 14:10 UTC
Labels: feature-request
