### ISSUE TITLE
Method not implemented when creating pull request in insiders.vscode.dev

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-pull-request-github#5391] opened 2023-10-24 18:06 UTC
1. Created https://github.com/microsoft/vscode-vsce/pull/907
2. :bug: saw this 

![Image](https://github.com/microsoft/vscode-pull-request-github/assets/30305945/5229dc06-a42b-4cd6-a835-316b4b5d5e23)

Dev tools console error
```
Error: Method not implemented.
	at Pn.diffBetween (github.vscode-unpkg.net/GitHub/remotehub/0.62.0/extension/dist/browser/extension.js#vscode-extension:123:5276)
	at cy.gitFiles (github.vscode-unpkg.net/GitHub/vscode-pull-request-github/0.75.2023102409/extension/dist/browser/extension.js#vscode-extension:1948:2230)
	at sy.getGitChildren (github.vscode-unpkg.net/GitHub/vscode-pull-request-github/0.75.2023102409/extension/dist/browser/extension.js#vscode-extension:1931:7746)
	at sy.getChildren (github.vscode-unpkg.net/GitHub/vscode-pull-request-github/0.75.2023102409/extension/dist/browser/extension.js#vscode-extension:1931:6663)
	at p.Y (/github/microsoft/vscode-vsce/vs/workbench/api/worker/extensionHostWorker.js:80:66420)
	at p.getChildren (/github/microsoft/vscode-vsce/vs/workbench/api/worker/extensionHostWorker.js:80:62788)
	at l.$getChildren (/github/microsoft/vscode-vsce/vs/workbench/api/worker/extensionHostWorker.js:80:59351)
	at o.S (/github/microsoft/vscode-vsce/vs/workbench/api/worker/extensionHostWorker.js:84:48583)
	at o.Q (/github/microsoft/vscode-vsce/vs/workbench/api/worker/extensionHostWorker.js:84:48349)
	at o.M (/github/microsoft/vscode-vsce/vs/workbench/api/worker/extensionHostWorker.js:84:47426)
	at o.L (/github/microsoft/vscode-vsce/vs/workbench/api/worker/extensionHostWorker.js:84:46637)
	at A.eval [as value] (/github/microsoft/vscode-vsce/vs/workbench/api/worker/extensionHostWorker.js:84:45294)
	at o.y (v--16kri78ljaigi0574h12m7q7v88n8qlbl2boiu36e2tq9q2d37p8.vscode-cdn.net/insider/7dff07893ac160244db210e574eccc05f1cba2cb/out/vs/base/worker/workerMain.js?vscode-coi=2:32:1902)
	at o.fire (v--16kri78ljaigi0574h12m7q7v88n8qlbl2boiu36e2tq9q2d37p8.vscode-cdn.net/insider/7dff07893ac160244db210e574eccc05f1cba2cb/out/vs/base/worker/workerMain.js?vscode-coi=2:32:2119)
	at r.port1.onmessage (/github/microsoft/vscode-vsce/vs/workbench/api/worker/extensionHostWorker.js:91:3801)
```

**Comment by alexr00** [comment] 2023-10-25 08:41
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/5380

**Closed by alexr00** 2023-10-25 08:41 UTC
