### ISSUE TITLE
GitHub Checks and Merge Conflicts not updating in Extension UI

### ISSUE THREAD

**Issue by bnb** [microsoft/vscode-pull-request-github#1314] opened 2019-08-21 16:04 UTC
- Extension version: 0.10.0
- VSCode Version: 1.38.0-insider
- OS: macOS 10.14.5

**Steps to Reproduce:**

0. make a Node.js application and git push
1. set up Azure Pipelines as a CI check
2. enable [greenkeeper](https://greenkeeper.io/) on that repo
3. set add an outdated dependency to package.json and wait for Greenkeeper to PR an update

**Problem:**
GitHub Pull requests is not actually updating checks for Azure Pipelines, nor is it updating that merge conflicts have been resolved. This PR has never been loaded in the extension before, so it seems that only the initial state was polled and then never updated. Here's [the PR](https://github.com/cutenode/good-first-issue/pull/150), for reference.

![image](https://user-images.githubusercontent.com/502396/63448082-38e92a80-c40b-11e9-83e2-2db4eed44248.png)

**Comment by JustinGrote** [comment] 2020-05-12 22:16
This is probably a dupe of #1105 in the sense that the additional API to get this info has not been implemented into the extension yet.

**Comment by alexr00** [comment] 2021-11-17 16:08
duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/1105

**Closed by alexr00** 2021-11-17 16:08 UTC
