### ISSUE TITLE
SCM info box leaks into GHPR view

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#5951] opened 2024-04-23 18:47 UTC
Testing #5939

![image](https://github.com/microsoft/vscode-pull-request-github/assets/2193314/29514cdb-dedd-45e2-991b-ad78b3fb0216)
![image](https://github.com/microsoft/vscode-pull-request-github/assets/2193314/f9045223-ae94-45d8-abda-aa51453024aa)

Console:

![image](https://github.com/microsoft/vscode-pull-request-github/assets/2193314/6574ac69-cc88-41d9-a62f-41b45ffb54d8)

I was expecting this not to be possible but it turns out it's implemented via the context view:

![image](https://github.com/microsoft/vscode-pull-request-github/assets/2193314/50168254-a715-449d-8e14-756f6823ba3c)

**Comment by alexr00** [comment] 2024-04-24 08:29
Duplicate of https://github.com/microsoft/vscode/issues/211096

**Closed by alexr00** 2024-04-24 08:29 UTC
