### ISSUE TITLE
Unable to Add Comments in PR using GitHub Pull Requests Extension in VSCode

### ISSUE THREAD

**Issue by yasaswi-p** [microsoft/vscode-pull-request-github#5317] opened 2023-10-06 02:54 UTC
I'm using the GitHub Pull Requests extension in Visual Studio Code to review pull requests. I've been assigned a PR, and I partially reviewed it about a week ago. However, today, when I tried to continue my review, I ran into an issue. Specifically, I can't add comments near the lines in the PR - The `+` button at the start of each line is just greyed out.

Also, whenever I try to click the "Add File Comment" button, I receive the following message:
**The cursor must be within a commenting range to add a comment.** 

I was able to comment just fine a week ago, so I'm puzzled about what might have changed or what I might be doing wrong. I tried the following:
- restarted the vs code and restarted my system
- uninstalled and reinstalled the extension
- Signed out of my GitHub account and signed in again

Has anyone else experienced this issue or have any suggestions on how to resolve it?

This is the output of `Help: About`:

```
Version: 1.83.0 (user setup)
Commit: e7e037083ff4455cf320e344325dacb480062c3c
Date: 2023-10-03T16:12:16.321Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621
```

I'm currently using version 0.74.0 of the extension GitHub Pull Requests and Issues in VS Code.

Any help is appreciated.

**Comment by realqpat** [comment] 2023-10-06 12:38
Same here. It was working fine prior to updating the extension and vscode
I tried to roll back to the previous version of the extension but same issue.
What is odd is that I have multiple repos and while I can comment on files from one repo, I can't do it on files from the other repo.

**Comment by agus-condro-speedoc** [comment] 2023-10-11 05:49
Same here.. happens since the recent update

**Comment by AudTheCodeWitch** [comment] 2023-10-12 18:10
I'm also having this issue.

**Comment by janakjjp** [comment] 2023-10-13 21:45
I think this is a regression with VSCode itself; as per realqpat, going back one or two versions does not make the "+" control reappear.

I managed to get it to work *once*, but since then have been unable to comment again... so there is some flakiness or race condition going on here with the extension and the VSCode UI.

This is a pretty significant regression; any assistance would be immensely valuable, as I find the GitHub UI to be terrible for doing reviews.

**Comment by janakjjp** [comment] 2023-10-13 21:53
Can confirm — if you downgrade to https://update.code.visualstudio.com/1.82.0/darwin-universal/stable (that's the Mac link, you can find others via https://code.visualstudio.com/docs/supporting/faq#_previous-release-versions) *and* downgrade the extension to v0.72 (you have to, since 0.74 is pinned to the latest VSCode release) things work again.

Tagging @alexr00 on this one, hopefully it's easy to figure out — let us know if we can capture any debugging info for you!

**Comment by jpspringall** [comment] 2023-10-14 02:32
Sorry I've had a busy week, but I've done some investigation that may help @alexr00 
Though like others have said, I believe that this is an upstream issue rather an extension issue.
It's also very hit and miss as what the actual issue, as it appears to work correctly in some circumstances but not others
So fixing it for one scenario may not fix for everyone

@alexr00, I think this is the same issue that raised and closed a couple of weeks ago #5291

Log of what is happening:

```
2023-10-06 18:22:08.861 [debug] PullRequestModel> Fetch file changes and merge base of PR #565 - done, total files 5 
2023-10-06 18:22:08.891 [debug] RateLimit> Extension rate limit remaining: 140, PullRequestComments
2023-10-06 18:22:08.892 [debug] RateLimit> Extension rate limit remaining: 139, PullRequestComments
2023-10-06 18:22:08.892 [debug] RateLimit> Extension rate limit remaining: 138, PullRequestFiles
2023-10-06 18:22:09.039 [debug] RateLimit> GraphQL Rate limit remaining: 5166, PullRequestFiles
2023-10-06 18:22:09.175 [debug] RateLimit> GraphQL Rate limit remaining: 5165, PullRequestComments
2023-10-06 18:22:09.175 [debug] RateLimit> GraphQL Rate limit remaining: 5165, PullRequestComments
2023-10-06 18:22:09.177 [debug] RateLimit> Extension rate limit remaining: 140, GetPendingReviewId
2023-10-06 18:22:09.304 [debug] RateLimit> GraphQL Rate limit remaining: 5164, GetPendingReviewId
2023-10-06 18:23:40.554 [debug] ReviewCommentController> No commenting ranges: File scheme differs from repository scheme.
2023-10-06 18:23:40.557 [debug] ReviewCommentController> No commenting ranges: File scheme differs from repository scheme.
2023-10-06 18:23:45.598 [debug] ReviewCommentController> No commenting ranges: File scheme differs from repository scheme.
2023-10-06 18:23:45.601 [debug] ReviewCommentController> No commenting ranges: File scheme differs from repository scheme.
```

Debugging the code, in my case at least document is coming back with the scheme 'pr' and the repository is coming back with scheme 'file'

Side note, but do you think it's worth adding the schemes into the error message?

I've also found the following in my case at least:

1. If I check out the pr branch then both schemes are 'file' and so works
2. If you clone the repo into a new folder it appears to also work as expected
	So this makes it almost impossible to reproduce consistently and makes it look like might relate to how VSCode in interpreting the local git repository

**Comment by alexr00** [comment] 2023-10-16 16:37
@jpspringall thank you for the additional debugging and @janakjjp for tagging me. I am investigating now.

**Comment by jpspringall** [comment] 2023-10-16 21:26
No worries @alexr00 give me a shout if you need anymore information.

**Comment by alexr00** [comment] 2023-10-18 15:23
@jpspringall would you be able to grab more logs if you see this again? I'm specifically looking for lines like this:
```
2023-10-18 16:45:05.389 [info] Review> Validate state in progress
2023-10-18 16:45:05.389 [info] Review> Validating state...
...
2023-10-18 16:45:14.766 [info] Review> Queuing additional validate state
... 
2023-10-18 16:45:22.170 [info] Review> Queuing additional validate state
```

This one seems like a red herring:
```
 ReviewCommentController> No commenting ranges: File scheme differs from repository scheme.
```
The `pr` vs `file` scheme is expected: we use the `pr` scheme when showing diffs for PRs that are not currently checked out. 

There's currently a bug where we're getting stuck and the extensions internal state isn't updating: https://github.com/microsoft/vscode-pull-request-github/issues/5277
I suspect that this is another symptom of that same bug. The logs I'm looking indicate that the bug has occurred.

**Comment by jpspringall** [comment] 2023-10-19 04:25
Hey @alexr00 

You are quite right, it does look like `ReviewCommentController> No commenting ranges: File scheme differs from repository scheme.` is a red herring, as i managed to recreate the issue without that message being logged 


but there are no instances of:

```
2023-10-18 16:45:14.766 [info] Review> Queuing additional validate state
... 
2023-10-18 16:45:22.170 [info] Review> Queuing additional validate state
```
below is an extract of my log file

```
2023-10-19 16:29:11.842 [info] Looking for git repository
2023-10-19 16:29:11.842 [info] Found 0 repositories during activation
2023-10-19 16:29:11.842 [info] Git repository found, initializing review manager and pr tree view.
2023-10-19 16:29:11.844 [info] Registering git provider
2023-10-19 16:29:12.148 [info] Review> Validate state in progress
2023-10-19 16:29:12.148 [info] Review> Validating state...
2023-10-19 16:29:12.148 [info] Cannot updates repositories as git is uninitialized
2023-10-19 16:29:12.148 [info] Repo state for file:///[Path to local repo] changed.
2023-10-19 16:29:12.148 [info] Repo file:///[Path to local repo] has already been setup.
2023-10-19 16:29:12.824 [info] Review> No matching pull request metadata found locally for current branch [Branch name]
2023-10-19 16:29:12.824 [info] Review> no matching pull request metadata found for current branch [Branch name]
2023-10-19 16:29:12.824 [info] Review> No matching pull request metadata found on GitHub for current branch [Branch name]
2023-10-19 16:29:14.038 [info] Git initialization state changed: state=initialized
2023-10-19 16:29:14.038 [info] Review> Validate state in progress
2023-10-19 16:29:14.038 [info] Review> Validating state...
2023-10-19 16:29:14.039 [info] Found GitHub remote for folder [Path to local repo]
2023-10-19 16:29:14.350 [info] Trying to use globalState for assignableUsers.
2023-10-19 16:29:14.411 [info] Using globalState assignableUsers for 2.
....
2023-10-19 16:29:18.984 [warning] RateLimit> GraphQL Rate limit remaining: 192, GetAssignableUsers
2023-10-19 16:29:18.985 [debug] RateLimit> Extension rate limit remaining: 140, GetAssignableUsers
2023-10-19 16:29:19.330 [debug] PRNode> Fetch children of PRNode #171
2023-10-19 16:29:19.330 [debug] PullRequestModel> Fetch file changes, base, head and merge base of PR #171 - enter
2023-10-19 16:29:19.330 [debug] RateLimit> Extension rate limit remaining: 139, PullRequestFiles
2023-10-19 16:29:19.330 [debug] IssueModel> Fetch viewers latest review commit
2023-10-19 16:29:19.331 [debug] RateLimit> Extension rate limit remaining: 138, LatestReviewCommit
2023-10-19 16:29:19.331 [debug] RateLimit> Extension rate limit remaining: 137, GetPendingReviewId
2023-10-19 16:29:19.455 [info] RateLimit> Unexpectedly low rate limit: 1000
2023-10-19 16:29:19.455 [warning] RateLimit> GraphQL Rate limit remaining: 191, GetAssignableUsers
2023-10-19 16:29:19.456 [debug] RateLimit> Extension rate limit remaining: 137, GetAssignableUsers
2023-10-19 16:29:19.497 [info] RateLimit> Unexpectedly low rate limit: 1000
2023-10-19 16:29:19.497 [warning] RateLimit> GraphQL Rate limit remaining: 188, GetPendingReviewId
2023-10-19 16:29:19.501 [info] RateLimit> Unexpectedly low rate limit: 1000
2023-10-19 16:29:19.501 [warning] RateLimit> GraphQL Rate limit remaining: 190, LatestReviewCommit
2023-10-19 16:29:19.507 [info] RateLimit> Unexpectedly low rate limit: 1000
2023-10-19 16:29:19.507 [warning] RateLimit> GraphQL Rate limit remaining: 189, PullRequestFiles
2023-10-19 16:29:19.684 [debug] PullRequestModel> Fetch file changes and merge base of PR #171 - done, total files 16 
2023-10-19 16:29:19.687 [debug] RateLimit> Extension rate limit remaining: 139, PullRequestComments
2023-10-19 16:29:19.897 [info] RateLimit> Unexpectedly low rate limit: 1000
2023-10-19 16:29:19.897 [warning] RateLimit> GraphQL Rate limit remaining: 187, GetAssignableUsers
2023-10-19 16:29:19.897 [debug] RateLimit> Extension rate limit remaining: 139, GetAssignableUsers
2023-10-19 16:29:20.377 [info] RateLimit> Unexpectedly low rate limit: 1000
2023-10-19 16:29:20.377 [warning] RateLimit> GraphQL Rate limit remaining: 185, GetAssignableUsers
2023-10-19 16:29:20.377 [debug] RateLimit> Extension rate limit remaining: 139, GetAssignableUsers
2023-10-19 16:29:20.427 [info] RateLimit> Unexpectedly low rate limit: 1000
2023-10-19 16:29:20.428 [warning] RateLimit> GraphQL Rate limit remaining: 186, PullRequestComments
2023-10-19 16:29:20.816 [info] RateLimit> Unexpectedly low rate limit: 1000
2023-10-19 16:29:20.816 [warning] RateLimit> GraphQL Rate limit remaining: 184, GetAssignableUsers
2023-10-19 16:29:20.817 [debug] RateLimit> Extension rate limit remaining: 140, GetAssignableUsers
2023-10-19 16:29:21.326 [info] RateLimit> Unexpectedly low rate limit: 1000
2023-10-19 16:29:21.326 [warning] RateLimit> GraphQL Rate limit remaining: 183, GetAssignableUsers
2023-10-19 16:29:21.328 [debug] RateLimit> Extension rate limit remaining: 140, GetAssignableUsers
2023-10-19 16:29:21.485 [info] RateLimit> Unexpectedly low rate limit: 1000
2023-10-19 16:29:21.485 [warning] RateLimit> GraphQL Rate limit remaining: 182, GetAssignableUsers
```

The above was on:

Version: 1.83.1 (system setup)
Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc
Date: 2023-10-10T23:48:05.904Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045

GitHub Pull Requests and Issues v0.74.0
 

Though I have found out a bit more, though again this isn't reproducible on a clean checkout

Configuration is an upstream stream repo with my own fork

If my local repo is on a untracked branch comments work as expected
If my local repo is tracked forked branch, then comments do not work
If my local repo is on the upstream/main then comments work as expected

If you believe that the issues is caused by #5277, do you want to see if resolving that fixes this issue?
Once available, I can test on with vs code insiders build with a pre release extension?

I'm just conscious of the fact that it's incredibly hard to fix something that isn't easily reproducible, and there are a few work arounds available in the mean time

**Comment by alexr00** [comment] 2023-10-19 10:29
> Configuration is an upstream stream repo with my own fork
>
> If my local repo is on a untracked branch comments work as expected
> If my local repo is tracked forked branch, then comments do not work
> If my local repo is on the upstream/main then comments work as expected

Thank you! I can repro. We don't usually work on forks so I missed this.

**Closed** 2023-10-19 13:06 UTC
Labels: bug, candidate

**Comment by alexr00** [comment] 2023-10-19 14:29
@jpspringall I've released a new pre-release build with the fix. The bug is actually twofold:
- VS Code wasn't using the correct `id` for comments
- The extension actually re-used an id value.

It's possible to work around the VS Code issue in the extension, which I've also done. If you (or anyone else in this thread!) could try out the latest pre-release version of the extension with VS Code's latest **stable** release and confirm that the bug is fixed, then I'll release a new stable version of the extension with the workaround.

**Comment by jpspringall** [comment] 2023-10-19 20:31
Hey @alexr00 I have tested the pre release extension with both the stable & Insiders version of VS Code, and comments now work as expected for me :-) 

Let me know if there anything else, you would like me to test.

Cheers

J

**Comment by janakjjp** [comment] 2023-10-19 21:05
Can also confirm that the pre-release version resolves the issue for me (e.g., I pulled up a PR, didn't have the + button, reloaded with the prerelease, it's there now).

Thank you so much for the quick turnaround!

**Comment by jpspringall** [comment] 2023-10-20 00:05
Random thought @alexr00 Do you think it's worth updating the issue template to include the Repo Configuration, and to stop me forgetting, the Github Product, so it would go from:

```
- Extension version:
- VSCode Version:
- OS:
```
To
```
- Extension version:
- VSCode Version:
- OS:
- PR Repository Configuration: Single Repository/Upstream & Forked Repositories
- Github Product: Github.com/Github Enterprise 
```

**Comment by alexr00** [comment] 2023-10-20 12:42
Thank you both for verifying! I'll release a new stable build of the extension on Monday. 

@jpspringall, updating the template is a good suggestion: https://github.com/microsoft/vscode-pull-request-github/pull/5376

**Comment by yasaswi-p** [comment] 2023-11-13 08:15
@alexr00 The same issue resurfaced when I updated my VSCode today.

**Comment by alexr00** [comment] 2023-11-13 08:58
@yasaswi-p can you share the version of the extension and the version of VS Code?

**Comment by yasaswi-p** [comment] 2023-11-13 11:55
Thanks for your quick response @alexr00 
I've tried the pre-release version of the extension: `v0.77.2023110909` and also the release version: `v0.76.1`
Here's the VSCode version I'm using:

```Version: 1.84.2 (user setup)
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
Date: 2023-11-09T10:51:52.184Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22631
```

**Comment by alexr00** [comment] 2023-11-16 13:40
@yasaswi-p I'm not able to reproduce this issue. Can you share a bit more about your setup:
- Do you have a PR branch checked out?
- If so, Is the PR from a fork to the upstream repo?
- Is your `main` remote the fork or the upstream repo?

**Comment by jpspringall** [comment] 2023-11-16 20:53
For what it's worth @alexr00 this may a be different issue. The extension works as expected for me using the following:

Version: 1.84.2 (system setup)
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
Date: 2023-11-09T10:51:52.184Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045

Ext Version: v0.76.1

**Comment by yasaswi-p** [comment] 2023-11-17 07:51
@alexr00 I'm unable to reproduce this now. I'm able to add comments to the same PR on the same repo which I couldn't do perviously. Thanks again for the quick turnaround.

**Comment by JasonLamv-t** [comment] 2024-05-29 16:46
Same here, already tried to switch the pre-release version, reinstall the extension, reinstall the VSCode, and even remove all other extensions, but still does not work for the mdn/translated-content repo. Most PR's changes only contain markdown files, so I guess maybe the problem is about the file type. But I can't ensure that... I will try to reproduce it and will supplement more details later.

**Comment by fcFn** [comment] 2024-07-08 23:00
I had to go to the PR's "Files changed" tab, leave a comment (and before that I started a review, but not sure that is relevant), after which the comments started appearing in my VS Code. Before that it would not show commands or the plus icons in the gutter.

**Comment by jordanebelanger** [comment] 2024-08-07 15:01
This is still happening as of vscode 1.92.0 on mac arm64

**Comment by bilalLimi** [comment] 2025-03-23 17:04
Still happening @alexr00 🙏

**Comment by alexr00** [comment] 2025-03-24 09:11
Are you seeing the issue in a public PR? Can you share a link to the PR and point out which line you're trying to add a comment on?

**Comment by bilalLimi** [comment] 2025-03-28 07:19
Hi @alexr00, thanks for the answer 🙏

It's happening in a private repository; I can reproduce 100% of the time.

Steps to reproduce:
- Open a PR on VS Code (I'm using Cursor, but I think that there are no differences) that contains a deleted file.
- Open the deleted file. On the left, you should have the deleted content of the file in red, while on the right, just a single empty green line.
- (Error) With your cursor on any part of the deleted code on the left, click on the "comment" icon in the top right corner.
- I'm getting this error: "The cursor must be within a commenting range to add a comment."




Happy to provide you any other info you might need 🙏

**Comment by alexr00** [comment] 2025-04-11 14:25
Curosr is a closed source fork of VS Code, so I don't know what they might have changed. Let me know if you can repro with VS Code and I'll take a look!
