### ISSUE TITLE
Use different tool invocation messages for Notifications

### ISSUE THREAD

**Issue by benibenj** [microsoft/vscode-pull-request-github#6350] opened 2024-10-22 10:51 UTC
Testing #6329

Suggestions:
- `Summarizing Notification` instead of  `Using "Summarize a GitHub Notification"` (Notification could possibly be a link to the notification on GitHub)
- `Fetching Notification` instead of `Fetching notification from GitHub…` (Does not need to mention GitHub as this is the GitHub PR extension)

![Image](https://github.com/user-attachments/assets/f108b4e9-d9c0-4a1e-94db-c0a685a03868)

**Comment by alexr00** [comment] 2024-10-22 14:00
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/6340

**Closed by alexr00** 2024-10-22 14:00 UTC
