### ISSUE TITLE
Ability to copy link to pull request from pull request tab

### ISSUE THREAD

**Issue by coffeedoughnuts** [microsoft/vscode-pull-request-github#2044] opened 2020-08-05 08:38 UTC
Hi,

A common workflow for me is to create my PR from inside vsc using this extension, and then click the PR ID link to open it in a browser, copy the link, and send it to team members on slack asking them to take a look. It would be much easier if I could skip the browser step and have the ability to copy a link to the PR directly on the PR tab page in vsc.

Thanks for the great extension!

**Comment by RMacfarlane** [comment] 2020-08-10 14:53
This looks like a duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/1906, let's track it there.

**Closed by RMacfarlane** 2020-08-10 14:53 UTC
