### ISSUE TITLE
Failed to get pull request review comments

### ISSUE THREAD

**Issue by neils95** [microsoft/vscode-pull-request-github#1447] opened 2019-11-15 17:28 UTC
- Extension version: 0.13.0
- VSCode Version: 1.40.0
- OS: Windows 10

Steps to Reproduce:
I am using github enterprise, and am able to succesfully view open PRs and ADD comments. So if I add a comment on the PR, it shows up on github website. However, for some reason, VS code does not load any comments made on the github website. 

The extension log output is: `Failed to get pull request review comments: GraphQL error: Field 'state' doesn't exist on type 'PullRequestReviewComment'`

**Comment by RMacfarlane** [comment] 2019-11-15 17:36
@neils95 What version of github enterprise are you using?

**Comment by neils95** [comment] 2019-11-15 17:39
Going back to version 0.12 of the extension fixes this for me. Version of github enterprise is 2.15.6

**Comment by jasonwilliams** [comment] 2019-11-20 11:47
@RMacfarlane its failing for me on Github Enterprise too 
our version is `GitHub Enterprise 2.15.6`

I've since rolled back to v0.12 for now

**Comment by jasonwilliams** [comment] 2019-12-10 11:10
@RMacfarlane do you know what the bug is?

**Comment by RMacfarlane** [comment] 2019-12-10 18:52
@jasonwilliams The problem is that the "state" property on comments doesn't exist on the GraphQL schema for enterprise 2.15, it's available in 2.16 and up. GraphQL throws when you request data that's not available on the schema

**Comment by jasonwilliams** [comment] 2020-02-03 15:13
@RMacfarlane it might be worth closing this and saying you only support Github Enterprise 2.16 and up in the wiki

**Comment by RMacfarlane** [comment] 2020-11-11 17:00
We have discontinued support for GitHub Enterprise. https://github.com/microsoft/vscode-pull-request-github/wiki#2-is-github-enterprise-supported

**Closed by RMacfarlane** 2020-11-11 17:00 UTC
Labels: GitHubEnterprise, bug
