### ISSUE TITLE
Syntax highlighting for patches/suggested edits

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode-pull-request-github#723] opened 2018-12-04 22:30 UTC
Issue Type: <b>Feature Request</b>

https://github.com/Microsoft/vscode/issues/64262

Patches on the overview page don't get any syntax highlighting treatment. By comparision GH.com looks much nicer. We should add synatx highlighting.

Extension version: 0.337.0
VS Code version: Code - Insiders 1.30.0-insider (fa87e67ebfd6b8014ba697ddbc6c2d6c0e2cb970, 2018-12-04T09:26:33.257Z)
OS version: Darwin x64 18.0.0

**Comment by rebornix** [comment] 2019-01-02 19:17
Duplicate of #490. Let's track it there.

**Closed** 2019-01-02 19:17 UTC
Labels: duplicate, enhancement
