### ISSUE TITLE
Cannot create a discussion on an Added file when opening through Commits

### ISSUE THREAD

**Issue by wcerfgba** [microsoft/vscode-pull-request-github#2300] opened 2020-11-30 10:18 UTC
Issue Type: <b>Bug</b>

1. Open a Pull Request.
2. In 'Changes in Pull Request', expand Files and open a Modified file. Each modification in a Modified file accessed through Files tree has the white interaction bar on the left hand side, to 'Start discussion'.
3. In 'Changes in Pull Request', expand Files and open an Added file. The whole Added file accessed through Files tree has the Start discussion bar.
4. Expand 'Commits' and open a Modified file. Each modification has Start discussion bar.
5. Expand 'Commits' and open an Added file. The Start discussion bar is missing in this view!

Extension version: 0.21.2
VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:31:29.624Z)
OS version: Linux x64 5.9.10-arch1-1

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2451)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.56GB (5.07GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 0e53faab-c6a1-4e2b-a6a4-18c06abdc23b|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|i3|
|XDG_CURRENT_DESKTOP|i3|
|XDG_SESSION_DESKTOP|i3|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by alexr00** [comment] 2021-11-19 13:59
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/141

**Closed by alexr00** 2021-11-19 13:59 UTC
