### ISSUE TITLE
Using interactive rebase to amend commits resets the branch to the default branch after a few seconds

### ISSUE THREAD

**Issue by taisph** [microsoft/vscode-pull-request-github#3544] opened 2022-05-11 09:58 UTC
- Extension version: v0.42.0
- VSCode Version: 1.67.1
- OS: Ubuntu 20.04 LTS

Steps to Reproduce:

1. Use "start working on issue and checkout topic branch" to change to a feature/topic branch.
2. Make two (or more) commits.
3. Use `git rebase -i HEAD~2` in terminal and choose "edit" for the first commit. Wait a few seconds and the branch is suddenly changed back to the default branch (main in my case).

The key seems to be using the issue topic branch feature first. Using rebase in other branches does not seem to trigger the reset. I had to disable the GitHub extension to get the changes done.

**Comment by alexr00** [comment] 2022-07-11 11:41
Sorry it's taken me so long to take a look at this!

> Wait a few seconds and the branch is suddenly changed back to the default branch (main in my case).

I tried to reproduce the issue with your steps, but I haven't seen this happen, even after waiting for several minutes. How did you check to see/what were you looking at that showed that the branch had been changed?

**Comment by alexr00** [comment] 2022-12-09 14:43
Closing due to missing info.

**Closed** 2022-12-09 14:42 UTC
Labels: info-needed
