### ISSUE TITLE
Empty github dropdowns were seen...

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-pull-request-github#3772] opened 2022-07-26 20:58 UTC
Testing #3761

0) Installed the pre-release version of this extension into insiders.
1) I opened a workspace connected to an existing repo.
2) created a branch
3) made some changes and committed them
4) published the branch to github.

When trying to create a new pull request using this extension, none of the dropdowns populated. They were blank:

<img width="316" alt="image" src="https://user-images.githubusercontent.com/11685408/181110096-4ae0c16c-70b1-44cd-9556-84ae0e1fba53.png">

Waiting and clicking later didn't help. Nor did creating yet another branch. 

After reloading VS Code it all seemed to start working as documented. I did not have the extension installed prior to starting this repro scenario, perhaps this is a key point?

**Comment by alexr00** [comment] 2022-07-28 11:17
@greazer I'm not able to reproduce this issue. I tried uninstalling and reinstalling the extension. If you see it again can you share the output from GitHub Pull Request?

**Comment by airtonix** [comment] 2022-09-26 00:42
getting this issue too

**Comment by unional** [comment] 2022-09-28 19:40
![image](https://user-images.githubusercontent.com/3254987/192873424-8e84c4aa-bf06-46f3-8d8d-04bcc6689365.png)

Same thing here.
Here is the output:

```
[Info] Registering git provider
[Info] Looking for git repository
[Info] Found 1 repositories during activation
[Info] Git repository found, initializing review manager and pr tree view.
[Info] Review> Validate state in progress
[Info] Review> Validating state...
[Info] Found GitHub remote
[Info] Review> no matching pull request metadata found for current branch internal-commands
[Info] Review> no matching pull request metadata found on GitHub for current branch internal-commands
[Info] PullRequestTree> Removing PR #undefined from tree
```

Note that this happens on a GitHub organization, not GitHub user.

Here is the repository: https://github.com/justland/just-web/tree/internal-commands

**Comment by alexr00** [comment] 2022-10-05 12:13
Folks seeing this issue, what browser are you using?

**Comment by unional** [comment] 2022-10-05 17:33
Why does it have anything to do with browser? It is within VS Code.

Btw, I'm using Brave at the moment.
And this happens on `justland` GitHub organization repos, but not in `unional` GitHub personal account repos.

**Comment by alexr00** [comment] 2022-10-05 18:08
There are a couple places you can use VS Code from within your browser (vscode.dev and Codespaces for example). I incorrectly assumed you were using one of those because I've seen similar issues with Firefox. However, since it's desktop then browser doesn't matter.

Are there any error reported in the developer console when you seen this?

**Comment by unional** [comment] 2022-10-06 18:43
No error, it actually populate eventually, takes about a minute I think

**Comment by unional** [comment] 2022-10-07 00:43
Some more log messages, don't know if they are related:


```
rejected promise not handled within 1 second: Error: Command failed: C:\Program Files\Git\cmd\git.exe -c core.longpaths=true -c core.quotepath=false -c color.ui=false -c log.showSignature=false log --format=%x3cr%x3e%x20%H -n3 -m -L 2,2:.changeset/large-panthers-count.md
fatal: There is no path .changeset/large-panthers-count.md in the commit

stack trace: Error: Command failed: C:\Program Files\Git\cmd\git.exe -c core.longpaths=true -c core.quotepath=false -c color.ui=false -c log.showSignature=false log --format=%x3cr%x3e%x20%H -n3 -m -L 2,2:.changeset/large-panthers-count.md
fatal: There is no path .changeset/large-panthers-count.md in the commit

	at c:\Users\homa\.vscode\extensions\eamodio.gitlens-12.0.7\dist\gitlens.js:36:7507
	at ChildProcess.exithandler (node:child_process:415:5)
	at ChildProcess.emit (node:events:526:28)
	at maybeClose (node:internal/child_process:1092:16)
	at ChildProcess._handle.onexit (node:internal/child_process:302:5)


  ERR command 'issues.issueCompletion' not found: Error: command 'issues.issueCompletion' not found
    at v._tryExecuteCommand (vscode-file://vscode-app/c:/Users/homa/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1696:3532)
    at v.executeCommand (vscode-file://vscode-app/c:/Users/homa/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1696:3414)
    at async Promise.all (index 0)
    ```

**Comment by alexr00** [comment] 2022-10-10 18:00
> No error, it actually populate eventually, takes about a minute I think

We should have exactly 1 item in the branch drop down to start with. We then fetch all the branches to show in the drop down. This is to keep the start up performance of the view quick. Do you even see 1 branch in the drop down?

**Comment by unional** [comment] 2022-10-11 07:21
Right now, I do see one (old). Have seen Zero. 

It takes about 5 minutes before it repopulate with the updated branches.

**Comment by alexr00** [comment] 2022-10-11 14:58
5 minutes should never happen, we give up after 5 seconds (and we do it twice, so shouldn't be too much more than 10 seconds). Are you on a very slow internet connection?

**Comment by alexr00** [comment] 2022-10-11 16:17
Can you set the setting `githubPullRequests.logLevel`, reproduce the issue again, then share the output from GitHub Pull Request?

**Comment by unional** [comment] 2022-10-11 17:29
![image](https://user-images.githubusercontent.com/3254987/195159312-bc1a6a18-6b2f-492a-920b-f25ae1ce8d69.png)

Another example that it only refresh after 2 minutes.
I feel like it is on a fixed schedule and the interval is very long.

Will enable the logLevel and see.

**Comment by alexr00** [comment] 2022-12-09 12:37
Closing since we don't have debug level logs. Please do ping the issue if you see again!

**Closed by alexr00** 2022-12-09 12:37 UTC
Labels: info-needed

**Comment by unional** [comment] 2022-12-10 04:09
```
  ERR Illegal argument: character must be non-negative: Error: Illegal argument: character must be non-negative
    at I (c:\Users\homa\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:7:1279)
    at new b (c:\Users\homa\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:90:14999)
    at b.translate (c:\Users\homa\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:90:15790)
    at J0.provideCompletionItems (c:\Users\homa\.vscode\extensions\github.vscode-pull-request-github-0.54.1\dist\extension.js:1426:58327)
    at K.provideCompletionItems (c:\Users\homa\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:94:51930)
    at c:\Users\homa\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:94:77224
    at ne._withAdapter (c:\Users\homa\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:94:67325)
    at ne.$provideCompletionItems (c:\Users\homa\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:94:77200)
    at l._doInvokeHandler (c:\Users\homa\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:102:13680)
    at l._invokeHandler (c:\Users\homa\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:102:13362)
    at l._receiveRequest (c:\Users\homa\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:102:12081)
    at l._receiveOneMessage (c:\Users\homa\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:102:10834)
    at c:\Users\homa\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:102:8941
    at h.invoke (c:\Users\homa\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:145)
    at v.deliver (c:\Users\homa\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:2266)
    at g.fire (c:\Users\homa\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:1844)
    at r.fire (c:\Users\homa\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:70:16515)
    at c:\Users\homa\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:118:17104
    at h.invoke (c:\Users\homa\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:145)
    at v.deliver (c:\Users\homa\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:2266)
    at g.fire (c:\Users\homa\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:1844)
    at r.fire (c:\Users\homa\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:70:16515)
    at o._receiveMessage (c:\Users\homa\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:70:21327)
    at c:\Users\homa\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:70:18770
    at h.invoke (c:\Users\homa\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:145)
    at v.deliver (c:\Users\homa\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:2266)
    at g.fire (c:\Users\homa\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:1844)
    at g.acceptChunk (c:\Users\homa\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:70:13346)
    at c:\Users\homa\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:70:12476
    at Socket.i (c:\Users\homa\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:70:24594)
    at Socket.emit (node:events:526:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
log.ts:324   ERR [Extension Host] [ERROR] [streamChoices] [2022-12-10T03:38:46.511Z] Error parsing JSON stream data {"error":{"message":"request cancelled"}}
console.ts:137 [Extension Host] [ERROR] [streamChoices] [2022-12-10T03:38:46.511Z] Error parsing JSON stream data {"error":{"message":"request cancelled"}}
``` saw these, don't know if it is related.

**Comment by alexr00** [comment] 2022-12-12 09:47
> the pull request panel got stuck for a while before showing, so could be related

What did you see in the "create" view when it was stuck?

**Comment by unional** [comment] 2022-12-12 10:01
Something like `loading`, can't really remember

**Comment by alexr00** [comment] 2022-12-14 13:56
Thanks @unional. The "Loading..." while we fetch the content to show in the view is expected.

**Comment by airtonix** [comment] 2022-12-16 09:17
> @greazer I'm not able to reproduce this issue. I tried uninstalling and reinstalling the extension. If you see it again can you share the output from GitHub Pull Request?

Start using git worktrees... you'll see it immediately.
