### ISSUE TITLE
Search for a specific PR by name or number

### ISSUE THREAD

**Issue by NicolasHug** [Microsoft/vscode-pull-request-github#938] opened 2019-02-08 19:09 UTC
Sorry if I've missed something, but it doesn't seem to be possible to find a PR by name or by number. That makes the extension really hard to use for me since I have to manually browse the "All" list. In projects with hundreds of PRs this is impossible.

**Comment by rebornix** [comment] 2019-02-13 18:38
Duplicate of https://github.com/Microsoft/vscode-pull-request-github/issues/266

**Closed by rebornix** 2019-02-13 18:38 UTC
Labels: enhancement, help wanted
