### ISSUE TITLE
Extension experience doesn't integrate well with GitHub CLI

### ISSUE THREAD

**Issue by noelbundick** [microsoft/vscode-pull-request-github#2564] opened 2021-03-10 22:32 UTC
I often use a combination of VS Code and the terminal to interact with my repos. My expected experience was that I could use the [GitHub CLI](https://cli.github.com/) to checkout a PR, and then pick up where I left off in VS Code. Currently, that experience isn't integrated, and I can't use the tools seamlessly together

What I intuitively wanted to do:

```shell
# check out the PR using the gh cli
gh pr checkout 49

# poke at the incoming code in the terminal
npm install
npm test

# open up VS Code + this extension for some more review
code .
```

What actually happens:

* `gh` checks out a branch with the original name, ex: `scan-command-base`
* The extension doesn't realize that I have this PR checked out; it tells me I have 0 items under Local Pull Request Branches

![image](https://user-images.githubusercontent.com/1970162/110706558-e8801c00-81ac-11eb-859f-602b57775d33.png)

* I can right-click and open up the PR in VS Code. It gives me a different branch name, ex: `pr/Joshua-Phelps/49`

![image](https://user-images.githubusercontent.com/1970162/110706675-18c7ba80-81ad-11eb-86fd-ff3a7e04850d.png)

* After doing so, the `gh` cli doesn't know where it is anymore, and my PR commands no longer work

![image](https://user-images.githubusercontent.com/1970162/110706909-6a704500-81ad-11eb-9f46-e75496358f88.png)

**Comment by RMacfarlane** [comment] 2021-03-11 16:22
Hmm, this isn't expected behavior, the extension should be able to detect that the current branch is associated with a pull request. This is using the latest version of the extension?

**Comment by noelbundick** [comment] 2021-03-11 17:42
Thanks for the info! So far it's looking like the extension correctly detects the association when the PR branch is in the same repo, and then the failure case occurs when the PR originates from a fork

Versions:
* `github.vscode-pull-request-github`: `v0.24.0`
* `gh`: `gh version 1.7.0 (2021-03-04)`

https://github.com/noelbundick/config-analyzer/pulls

PR from branch in same repo:


```shell
gh pr checkout 50
```

![image](https://user-images.githubusercontent.com/1970162/110829784-5c720100-824d-11eb-81be-6d5e603201cc.png)

PR from a fork:

```shell
gh pr checkout 51
```

![image](https://user-images.githubusercontent.com/1970162/110829900-790e3900-824d-11eb-9ede-65433e9197a9.png)

**Comment by maelvls** [comment] 2021-06-23 18:10
```
git clone https://github.com/jetstack/cert-manager
cd cert-manager
gh pr checkout 4121
```

At this point, my .git/config looks like this:

```conf
[branch "certificate-shim"]
    remote = https://github.com/jakexks/cert-manager.git
    merge = refs/heads/certificate-shim
```

The tab "Github Pull Request" does not appear on the right, and the "GitHub" tab on the right shows 0 local pull requests.

<img alt="" src="https://user-images.githubusercontent.com/2195781/123146402-1b99a300-d45e-11eb-9b9b-320666809348.png" width="200">


Now, since the extension seems to want to have the `github-pr-owner-number` value set in .git/config (as per #1070), I manually set it:

```sh
git config branch.$(git branch --show-current).github-pr-owner-number \
  "$(gh pr view --json url | jq -r .url | sed 's@https://github.com/@@; s@/pull/@#@; s@/@#@g')"
```

Now, .git/config looks like this:

```conf
[branch "certificate-shim"]
    remote = https://github.com/jakexks/cert-manager.git
    merge = refs/heads/certificate-shim
    github-pr-owner-number = "jetstack#cert-manager#4121"
```

This time, the "Github" tab sees 1 pull request, but still no sign of the "Github Pull Request" tab:

![image](https://user-images.githubusercontent.com/2195781/123146584-58659a00-d45e-11eb-824f-3f6e72e6fb40.png)

Then, I tried right-clicking on the "Local branch" above and click "Checkout pull request".

(before that, I removed the `github-pr-owner-number` setting that I had set for my `certificate-shim` branch, otherwise it trips the extension due to duplicate `github-pr-owner-number` entries)

The .git/config now contains:

```conf
[remote "jakexks"]
    url = https://github.com/jakexks/cert-manager
    fetch = +refs/heads/*:refs/remotes/jakexks/*
    github-pr-remote = true
[branch "pr/jakexks/4121"]
    remote = jakexks
    merge = refs/heads/certificate-shim
    rebase = true
    github-pr-owner-number = "jetstack#cert-manager#4121"
```

This time, the "GitHub Pull Request" tab shows and I can see the PR comments in-line when opening the files.

![image](https://user-images.githubusercontent.com/2195781/123147234-16892380-d45f-11eb-919e-057dd2fa81d4.png)

**Comment by maelvls** [comment] 2021-06-23 18:20
I just found what was wrong: the extension seems to need a "named" remote.

Without a named remote, the extension does not show the PR comments in-line:

```conf
[branch "certificate-shim"]
	remote = https://github.com/jakexks/cert-manager.git
	merge = refs/heads/certificate-shim
	github-pr-owner-number = "jetstack#cert-manager#4121"
```

But with a named remote, it works:

```conf
[remote "jakexks"]
	url = https://github.com/jakexks/cert-manager
	fetch = +refs/heads/*:refs/remotes/jakexks/*
	github-pr-remote = true
[branch "certificate-shim"]
	remote = jakexks
	merge = refs/heads/certificate-shim
	github-pr-owner-number = "jetstack#cert-manager#4121"
```

**Comment by maelvls** [comment] 2021-07-03 13:27
For anyone interested, you can create yourself a shell script to "force" the GitHub Pull Request extension to get activated using a one-liner.

One-liner to create the `git vscode` command:

```sh
#! /bin/bash

trace() {
  printf "\033[33m%s\033[0m %s\n" "$1" "${@:(-2):1}" >&2
  "$@"
}

trace git config "branch.$(git branch --show-current).github-pr-owner-number" \
  "$(gh pr view --json url | jq -r .url | sed 's@https://github.com/@@; s@/pull/@#@; s@/@#@g')"

if git config "branch.$(git branch --show-current).remote" | grep -q ^https://github.com; then
  exit
fi

trace git remote add "$(gh pr view --json author | jq -r .author.login)" "$(git config "branch.$(git branch --show-current).remote")"
trace git config "branch.$(git branch --show-current).remote" "$(gh pr view --json author | jq -r .author.login)"
```

Then, whenever you want to review a PR:

```sh
gh pr checkout 3456
git vscode
```

and the PR comments should show in VSCode.

**Comment by alexr00** [comment] 2023-12-15 16:26
This should be fixed since the October 2023 release!

**Closed by alexr00** 2023-12-15 16:26 UTC
Labels: feature-request

**Comment by Emilgardis** [comment] 2023-12-15 19:51
Can I ask how it was fixed? @alexr00 :D

**Comment by alexr00** [comment] 2023-12-18 08:54
Fix was here: https://github.com/microsoft/vscode-pull-request-github/pull/5351
Issue that tracked the fix is here: https://github.com/microsoft/vscode-pull-request-github/issues/4464
