### ISSUE TITLE
"GitHub Pull Requests and Issues" plugin causing a large number of requests to github enterprise installation

### ISSUE THREAD

**Issue by matschaffer-roblox** [microsoft/vscode-pull-request-github#4523] opened 2023-02-13 20:48 UTC
- Extension version: v0.58.1
- VSCode Version: Version: 1.75.1 (Universal) Commit: 441438abd1ac652551dbe4d408dfcec8a
- OS: macOS 12.6 (21G115)

Steps to Reproduce:

1. Open VS code with extension installed
2. Open the "github" sidebar
3. Check internal graph of requests to github enteprise server
4. Note increase of ~4k requests per minute to server

For the time being I've just disabled the plugin. If there's a way to enable some debug logging that might say more about the plugin activity please let me know.

**Comment by matschaffer-roblox** [comment] 2023-02-13 20:58
I can see from the request logs that these are graphql calls. They started around the time I updated to 0.58.1 and disabling the plugin stops the request flood.

**Comment by matschaffer-roblox** [comment] 2023-02-13 21:06
Here's a parsed sample from the github enterprise server logs

```
app=github
env=production
enterprise=true
auth_fingerprint=<redact>
limited_limit=90000
limited_ttl=60
limited=api/time-based
current_user=Mat-Schaffer
controller="Api::GraphQL"
path_info="/api/graphql"
query_string=nil
version=merge-info-preview
non_integer_id=nil
auth=oauth
oauth_access_id=59018
oauth_application_id=14
oauth_scopes="read:user,repo,user:email,workflow"
integration_id=nil
installation_id=nil
parent_installation_id=nil
user_programmatic_access_id=nil
x_real_ip=<redact>
x_forwarded_for=<redact>
route=/graphql
rate_limit=5000
rate_limit_remaining=5000
rate_limit_key=user-2175
rate_limit_used=0
rate_limit_reset=1676324529
rate_limit_family=graphql
graphql_global_id_type=legacy
now="2023-02-13T20:42:10+00:00"
request_id=ccf16617-0d5c-49b7-babb-6aaeb1681b86
datacenter=default
server_id=<redact>
remote_address=<redact>
request_method=post
request_host=<redact>
content_length=276
content_type="application/json;
charset=utf-8"
user_agent="node-fetch/1.0 (+https://github.com/bitinn/node-fetch)"
accept="*/*,application/vnd.github.merge-info-preview"
referer=
status=200
elapsed=0.147
url="https://<redact>/api/graphql"
worker_request_count=534721
request_category=api
```

**Comment by alexr00** [comment] 2023-02-14 16:34
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/4507

**Comment by alexr00** [comment] 2023-02-14 16:36
@matschaffer-roblox would you be able to share extension output?
- set the log level to "Debug" 
  - command: Developer: Set Log level 
  - choose "GitHub Pull Request"
  -  then click the little "Set as default log level" button to the right of the work "Debug")
- share the output from "GitHub Pull Request" next time you see the issue

That will contain some rate limit logging that should narrow down what's happening.

**Comment by matschaffer-roblox** [comment] 2023-02-15 01:36
I don't appear to have a "GitHub Pull Request" option in my set log level items.

![Screen Shot 2023-02-14 at 5 35 48 PM](https://user-images.githubusercontent.com/115565899/218905006-7032a83d-a84a-4b49-ac32-7f5745c7975f.png)

**Comment by matschaffer-roblox** [comment] 2023-02-15 01:49
The info logs had a _lot_ of activity though. Here's a redacted sample incase it's helpful. Knowing which output tab to select was helpful. If you have any ideas about how to be enable debug logging please let me know.

[logs.txt.gz](https://github.com/microsoft/vscode-pull-request-github/files/10738436/logs.txt.gz)

Looks like maybe some sort of authentication tight retry loop going on.

**Comment by alexr00** [comment] 2023-02-15 10:00
Sorry about that @matschaffer-roblox, I gave the pre-release build log level instructions. For the stable build:
- Set the setting "githubPullRequests.logLevel": "debug"
- Reproduce the issue
- Share the output from GitHub Pull Request

**Comment by alexr00** [comment] 2023-02-15 14:16
@matschaffer-roblox are you able to also share the logs from GitHub Authentication and GitHub Enterprise Authentication?

**Comment by Vasugupta946** [comment] 2023-02-17 15:50
Please fix this bug. I have also faced this issue on my Enterprise account and I had to uninstall the extension.

**Comment by alexr00** [comment] 2023-02-17 16:12
@Vasugupta946 can you share logs? I will release a fix as soon as I have one, but I'm not able to reproduce the issue and must rely on logs.
- Set the setting `"githubPullRequests.logLevel": "debug"`
- Reproduce the issue
- Share the output from GitHub Pull Request (if you don't want to share your repo name/url you will need to redact it from the logs).
- Share the output from GitHub Authentication
- Share the output from GitHub Enterprise Authentication

**Comment by dinofx** [comment] 2023-02-17 16:19
While there may be some bug specific to authentication, would its make sense for this extension to have its own client-side rate limit for all HTTP requests?  Even if a specific auth problem is addressed, companies might be hesitant to approve this extension's usage again if they think there is a future risk of request flooding.

**Comment by matschaffer-roblox** [comment] 2023-02-19 20:44
@alexr00 yep, here are those logs - [Archive.zip](https://github.com/microsoft/vscode-pull-request-github/files/10777909/Archive.zip)

I also tried v0.59.2023020215 and the behavior seems the same.

I noticed today that it's not all repos that trigger it, but one specific (unfortunately internal) repository. The repo in question is also fairly cross-team so like has many more contributors than the others I work on.

**Comment by matschaffer-roblox** [comment] 2023-02-19 20:55
v0.56.0 doesn't exhibit the problem. Also the repo in question has ~160 open PRs and ~8k closed PRs.

Here's a redacted pull request log from v0.56.0 - [github-pull-request-v0.56.0-debug.log.gz](https://github.com/microsoft/vscode-pull-request-github/files/10777941/github-pull-request-v0.56.0-debug.log.gz)

**Comment by jpspringall** [comment] 2023-02-19 22:06
> @alexr00 yep, here are those logs - ....
> 
> I also tried v0.59.2023020215 and the behavior seems the same.
> 
> I noticed today that it's not all repos that trigger it, but one specific (unfortunately internal) repository. The repo in question is also fairly cross-team so like has many more contributors than the others I work on.

Thanks @matschaffer-roblox For the v0.59.2023020215, would it be possible for you to reproduce the issue and provide the  the `Github Pull Request` log, as this should display when the calls are being to github

Also while I understand it's a private repo that it happens on, would it be possible for you to answer if the private repo is hosted on Github Enterprise? If not, you can just just ignore the question ;-)
So far I believe all reported instances have occurred on Github Enterprise, so it would be good to know if it's the same for you

@alexr00 I spent some time over weekend playing around with a vanilla instance of Github Enterprise, and was unable to recreate the issue.
I tried most things I could think of (Introducing extremely harsh rate limits, randomly pulling the network connection to the server), but for the life of me I couldn't reproduce the issue on 0.58 or 0.59

**Comment by matschaffer-roblox** [comment] 2023-02-19 22:50
@jpspringall yes, the repo is on the same github enterprise installation that's seeing elevated request load when I enable the plugin.

I tried running the plugin from `main` this morning and got these logs. I couldn't figure out how to launch the extension in debug mode but I could switch to debug logging partway through.

[main-logs-info-debug-1.txt.gz](https://github.com/microsoft/vscode-pull-request-github/files/10778182/main-logs-info-debug-1.txt.gz)

**Comment by matschaffer-roblox** [comment] 2023-02-19 22:57
Incase it's useful I ran a git bisect as well which landed on 295206885d4c1bbcae82f71335da2d932fc0d2d7

**Comment by matschaffer-roblox** [comment] 2023-02-19 23:06
@jpspringall yes, the repo is on the same github enterprise installation that's seeing elevated request load when I enable the plugin.

I tried running the plugin from main this morning and got these logs. I couldn't figure out how to launch the extension in debug mode but I could switch to debug logging partway through.

[main-logs-info-debug-1.txt.gz](https://github.com/microsoft/vscode-pull-request-github/files/10778205/main-logs-info-debug-1.txt.gz)

**Comment by jpspringall** [comment] 2023-02-19 23:48
@matschaffer-roblox That's great thanks!
From a quick look at the logs, the problem appears to be 3 fold:
1. Continuously calling /users
2. Attempting to Authenticate when it could resolve the remote host (I presume you have to connect via VPN, and weren't initially connected)
3. Then getting stuck in loop trying Initializing GitHub authentication provider

Out of interest, I presume you were starting VS Code from cold, when getting the logs, i.e you were starting a new instance of VS Code, not using a long running instance

**Comment by jpspringall** [comment] 2023-02-20 10:30
So good news, kinda:

I have managed to consistently recreate the issue by doing the following:

1. Open VS Code Insiders pointing at the vs-code-pull-request repo
2. rm -rf node_modules
3. Yarn and 
4. Sign out of Github Enterprise from within this instance of VS Code, so when you start the debugger you aren't signed in
5. Run the debugger
6. Make sure that the debugging instance of VS Code Insiders starts in Github Enterprise folder, so you may have debug twice
7. Click on the Github Extension
8. Go through the sign in process
9. Watch thousands of requests being sent to Github Enterprise

Confirmed that the above works as expected on 0.56

As for the actual problem, still working on that:
I think we can rule out #4420, as that was my first go to, but that didn't appear to fix anything
As for the actual problem it seems to stem from the fact that the function:
`doUpdateRepositories` in the file: src\github\folderRepositoryManager.ts is being called repeatedly
Though I haven't worked out why yet

I know that I started to have the issue on January 25th while it was on pre release, so I will probably look into PRs around that time to see if I can spot anything.

Though that will be tomorrow's task, I'm done for now

Cheers

J

**Comment by alexr00** [comment] 2023-02-20 10:42
@jpspringall and @matschaffer-roblox thank you both for your continued investigation into this. I'm going through the additional logs and trying to come up with a root cause now.

**Comment by jpspringall** [comment] 2023-02-20 12:16
So I may not have not waited until tomorrow.

The Problem PR is #4427, beyond that not done any investigation.
If I had to guess, I suspect it's this: https://github.com/microsoft/vscode-pull-request-github/pull/4427/files#diff-b0f6b0e92ac9fb7c8d22583477dc01f57b0f31d4f545489ea966548b6e1321b9

Will pick this up tomorrow

**Comment by alexr00** [comment] 2023-02-20 13:15
Got a repro thanks to the logs providing a clue.
- Run on a machine (or otherwise simulate) git initialization being slow
  - git initialization is done by the built in git extension and this extension relies on it for all git operations
- Have a PR from main/default branch to another branch

The bug has a few parts:
1. Here, we do something that will trigger auth when repos update:
https://github.com/microsoft/vscode-pull-request-github/blob/77ca4453f544687360ab4c5a5df5d76d9d307a5c/src/issues/stateManager.ts#L103-L104
2. Here, we do something that will trigger update repos when we get an auth token:
https://github.com/microsoft/vscode-pull-request-github/blob/77ca4453f544687360ab4c5a5df5d76d9d307a5c/src/github/folderRepositoryManager.ts#L172-L173
3. This triggers an endless loop, but only when git is initialized slowly. 
4. https://github.com/microsoft/vscode-pull-request-github/pull/4427/files#diff-b0f6b0e92ac9fb7c8d22583477dc01f57b0f31d4f545489ea966548b6e1321b9 did indeed cause the loop to happen.

I should have a fix today.

**Closed** 2023-02-20 15:10 UTC
Labels: bug, important

**Comment by alexr00** [comment] 2023-02-20 15:50
I've just released 0.58.2 (and a new pre-release version), which has a change that I'm fairly confident fixes the issue. If you could try it out and let me know if you still see the problem that would be very helpful!

Thank you for all the investigation effort!

**Comment by ghecadmin** [comment] 2023-02-20 16:38
Hope this version is stable and not going to bring down GHES

**Comment by alexr00** [comment] 2023-02-20 17:02
@ghecadmin I'm am fairly confident of the fix, but, given that I was only able to simulate one of the contributing factors to the bug, we won't know for sure until one of the folks who was experiencing the issue can reply here and let us know.

**Comment by matschaffer-roblox** [comment] 2023-02-20 20:21
I updated to 0.58.2 about 15 minutes ago. The logs are a _lot_ cleaner and I'm not seeing the GHE spikes I was before. Reloading the window a few times seems to have caused about GraphQL 400 requests from me in the server logs. This is 10x lower than before so I'd say you fixed it.

I'll keep an eye on the logs as I work today just incase and ping if I see trouble.

Nice work finding the repo @jpspringall and nice work finding the fix @alexr00 - thanks so much!

**Comment by dinofx** [comment] 2023-03-08 19:03
Is it possible to get a more general fix for this problem?  Back in August (which predates #4427) we saw thousands of requests to other endpoints, in that case it was `.... pulls/{number}/requested_reviewers`.

**Comment by alexr00** [comment] 2023-03-09 12:37
I'll be adding guards against this with https://github.com/microsoft/vscode-pull-request-github/issues/4546.
