### ISSUE TITLE
TypeError: Cannot read property 'toLocaleLowerCase' of undefined

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode-pull-request-github#216] opened 2018-08-16 07:58 UTC
Found this when selfhosting on pull request extension in latest:

```
/Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3238 TypeError: Cannot read property 'toLocaleLowerCase' of undefined
	at VSCodeConfiguration.getHost (/Users/bpasero/.vscode-exploration/extensions/microsoft.vscode-pull-request-github-0.0.10/out/authentication/vsConfiguration.js:46)
	at vscode.workspace.onDidChangeConfiguration (/Users/bpasero/.vscode-exploration/extensions/microsoft.vscode-pull-request-github-0.0.10/out/authentication/vsConfiguration.js:15)
	at e.fire (/Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:99)
	at e.$acceptConfigurationChanged (/Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:564)
	at e._doInvokeHandler (/Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:674)
	at e._invokeHandler (/Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:674)
	at e._receiveRequest (/Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:673)
	at e._receiveOneMessage (/Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:673)
	at /Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:671
	at /Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:675
	at /Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:98
	at e.fire (/Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:99)
	at a (/Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:164)
	at Socket._socketDataListener (/Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:164)
	at Socket.emit (/Applications/Visual%20Studio%20Code%20-%20Exploration.app/Contents/Resources/app/out/vs/workbench/electron-browser/bootstrap/events.js:182)
	at addChunk (/Applications/Visual%20Studio%20Code%20-%20Exploration.app/Contents/Resources/app/out/vs/workbench/electron-browser/bootstrap/_stream_readable.js:279)
	at readableAddChunk (/Applications/Visual%20Studio%20Code%20-%20Exploration.app/Contents/Resources/app/out/vs/workbench/electron-browser/bootstrap/_stream_readable.js:264)
	at Socket.Readable.push (/Applications/Visual%20Studio%20Code%20-%20Exploration.app/Contents/Resources/app/out/vs/workbench/electron-browser/bootstrap/_stream_readable.js:219)
	at Pipe.onread (/Applications/Visual%20Studio%20Code%20-%20Exploration.app/Contents/Resources/app/out/vs/workbench/electron-browser/bootstrap/net.js:636)
```

**Comment by RMacfarlane** [comment] 2018-08-16 16:31
Closing as a duplicate of https://github.com/Microsoft/vscode-pull-request-github/issues/191

**Closed by RMacfarlane** 2018-08-16 16:31 UTC
Labels: bug
