### ISSUE TITLE
Code review of PR - would like to be able to choose/limit which commits are being reviewed

### ISSUE THREAD

**Issue by davidrinnan** [microsoft/vscode-pull-request-github#4959] opened 2023-06-26 14:11 UTC
Sometimes we have multiple PRs where some of them has been checked out from another PR. 

In those cases, as a reviewer, you want to be able to limit the review to the branch commits. Otherwise many of the reviews will include code supposed to be reviewed in another PR making it difficult to review. 

This is possible to do when reviewing code via github in the browser. This control could exist on the overview/description page of the PR in visual code.

**Comment by alexr00** [comment] 2023-06-28 13:22
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/4315

**Closed by alexr00** 2023-06-28 13:22 UTC
