### ISSUE TITLE
Query fails when only applying an org filter: Element with id already registered

### ISSUE THREAD

**Issue by victor-marino** [microsoft/vscode-pull-request-github#5411] opened 2023-10-27 12:44 UTC
- Extension version: 0.74.1 (but has been happening since the first time I ever tried this extension, about a month ago)
- VSCode Version: 1.83.1
- OS: MacOS Ventura 13.6.1
- Repository Clone Configuration: I'm cloning a single repo, but I'm trying to list the pull requests from all repos in my organization.
- Github Product: GitHub Enterprise Server 3.8.3

Steps to Reproduce:

In the extension configuration settings, this query works fine:
```json
{
  "label": "I'm involved: MyOrg",
  "query": "is:open involves:${user} org:<MyFullOrgName>"
}
```
(it also works fine using `review-requested`, `author` or any similar filter instead of `involves`)

However, this does NOT work:
```json
{
  "label": "All Open: MyOrg",
  "query": "is:open org:<MyFullOrgName>"
}
```

The list for that query shows nothing when clicked (the arrow rotates, but nothing else), and I get a pop-up with this message:
> Element with id All Open: MyOrghttp://github.myorg.com/MyFullOrgName/RepoName/pull/PrNumber is already registered

(Note there's a missing space/new line between "MyOrg" and the URL. I left that in intentionally in case it helps.)

I tried the equivalent query in gh command line and it works just fine, returning the 22 open PRs within my org:
```
gh search prs org:<MyFullOrgName> is:open
```

**Edit:** In case it helps, some further info on the specific PR the extension seems to get stuck with.
* 3 people were added as reviewers to it, and the 3 of them have already approved it.
* We only require 2 people to approve each PR before merging, so the PR no longer requires any reviews.
* The PR contains 3 commits, and 3 files changed
* The PR tries to merge a feature branch into master
* However, the PR has conflicts that must be resolved before it can be merged, and so it's showing the "Resolve conflicts" button on the page.

**Edit 2:** Some more interesting findings while testing.
This query also fails with the same error:
```json
{
  "label": "Review required: MyOrg",
  "query": "is:open review:none org:<MyOrgFullName>"
},
```
However, the error message mentions a completely different PR from a different repo. This one has 3 people as reviewers, but 0 approvals.

As far as I can see, the only "distinctive" thing both PRs have in common is that they both have conflicts that need to be resolved before merging. So not sure if the bug might have something to do with that?

This query also works fine on gh cli, returning 7 PRs:
```
gh search prs org:<MyFullOrgName> is:open review:none
```

**Comment by alexr00** [comment] 2023-11-03 14:09
A few thoughts:

1. In the extension we try not to allow `org:` queries. We always add a `repo:` to each query you enter. However, I can see that this is actually not working. I'll need to fix this.
2.  Despite point 1, you shouldn't be seeing this error. Do you have more than 1 git repo open in this window of VS Code? The error is a duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/5321, which I just reopened.

**Comment by victor-marino** [comment] 2023-11-03 14:24
> Do you have more than 1 git repo open in this window of VS Code?

Nope, I don't.

Just to make sure, I completely killed VSCode, then ran `code <folder_name>` to open just one specific repo.

This keeps happening for every repo inside that organization, because it keeps hitting an open PR that it cannot parse. As far as I can see, it's always the same PR that comes up in the error message - the one with conflicts that cannot be merged.

Thanks for looking into this!

**Comment by alexr00** [comment] 2023-12-20 14:18
Thanks for your patience! I think this should be fixed with https://github.com/microsoft/vscode-pull-request-github/commit/c764f4b7b5195ed669be64e09c61476d5a29459a. If you're still seeing it please let me know!

**Closed by alexr00** 2023-12-20 14:18 UTC
Labels: info-needed

**Comment by victor-marino** [comment] 2023-12-27 17:56
Thank you. Is this release already in the stable channel? My extension is stuck on version 0.78.1 and isn't prompting for updates.

(sorry, not familiar with VSCode's release schedule)

**Comment by alexr00** [comment] 2024-01-08 15:45
Fix is available in pre-release (requires VS Code Insiders). The next stable release will be at the end of January.
