### ISSUE TITLE
emoji not rendered

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode-pull-request-github#131] opened 2018-08-01 16:52 UTC
Testing https://github.com/Microsoft/vscode/issues/55396

![image](https://user-images.githubusercontent.com/4674940/43536085-90b287a4-9570-11e8-9384-e205cd017253.png)

**Comment by RMacfarlane** [comment] 2018-08-01 16:53
Duplicate of https://github.com/Microsoft/vscode-pull-request-github/issues/53

**Closed by RMacfarlane** 2018-08-01 16:53 UTC
