### ISSUE TITLE
Clicking on the Reviewers button gives an error

### ISSUE THREAD

**Issue by satishvaltix** [microsoft/vscode-pull-request-github#1215] opened 2019-06-05 23:08 UTC
Issue Type: <b>Bug</b>

Cannot read property 'filter' of undefined

Extension version: 0.7.0
VS Code version: Code - Insiders 1.35.0-insider (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T00:11:00.788Z)
OS version: Darwin x64 18.5.0
Remote OS version: Linux x64 3.10.0-957.1.3.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|16.00GB (2.82GB free)|
|Process Argv|-psn_0_1081608|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: satish-dev|
|OS|Linux x64 3.10.0-957.1.3.el7.x86_64|
|CPUs|Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz (2 x 2299)|
|Memory (System)|3.70GB (0.60GB free)|
|VM|0%|
</details>

**Comment by meaghanlewis** [comment] 2019-06-06 13:34
Duplicate of #1181

**Closed by meaghanlewis** 2019-06-06 13:34 UTC
