### ISSUE TITLE
Create Pull Request command doesn't appear in RemoteHub workspace

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-pull-request-github#4151] opened 2022-11-03 19:39 UTC
1. Go to https://insiders.vscode.dev/github/microsoft/vscode
2. Create a branch 
3. Switch to branch
4. :bug: Create Pull Request command not available in command palette (GHPRI is activated)

**Comment by alexr00** [comment] 2022-11-04 16:46
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/3911

**Comment by joyceerhl** [comment] 2022-11-04 17:17
I think this is a different issue actually. #3911 is about the `scmProviderRootUri` having a `vscode-remote` scheme. RemoteHub is not a remote extension because it's not a resolver, so that problem doesn't apply. In this issue, I see that the `scmProviderRootUri` is correctly `vscode-vfs`, but the `github.reposNotInReviewMode` context key does not appear to be set, so the command is being hidden from the palette.

**Comment by alexr00** [comment] 2022-11-04 18:16
Sorry for prematurely closing I read the description to quickly 😳

**Comment by alexr00** [comment] 2022-11-11 09:57
I'm not able to repro this issue. My steps:
1. Go to https://insiders.vscode.dev/github/microsoft/vscode
2. Create a branch
3. Switch to branch
4. Run the Create Pull Request command from the command palette and see that the GHPRI Create view shows.

**Closed by alexr00** 2022-11-11 09:57 UTC
Labels: bug
