### ISSUE TITLE
Problems with GitHub Workflows

### ISSUE THREAD

**Issue by RMeli** [microsoft/vscode-pull-request-github#1803] opened 2020-05-13 14:57 UTC
Since I installed this extension, I get the following error when I try to `git push` changes to a GitHub Workflow:

```
! [remote rejected] master -> master (refusing to allow an OAuth App to create or update workflow `.github/workflows/flake8.yml` without `workflow` scope)
```

- Extension version: 0.16.0
- VSCode Version: 1.45.0
- OS: macOS / Ubuntu 18.04 via VSCode Remote

Steps to Reproduce:

1. Modify a Github workflow file in `.github/workflows`
2. Try to push the changes with `git push`

**Comment by RMacfarlane** [comment] 2020-05-13 18:54
Hey @RMeli, this looks like a duplicate of https://github.com/microsoft/vscode/issues/97396, so I will go ahead and close this

**Closed by RMacfarlane** 2020-05-13 18:54 UTC

**Comment by RMeli** [comment] 2020-05-13 19:07
Yes, I completely missed it with a quick search. Sorry!
