### ISSUE TITLE
Mark File As Viewed is broken

### ISSUE THREAD

**Issue by TristenFielding** [microsoft/vscode-pull-request-github#6013] opened 2024-05-22 18:41 UTC
- Extension version: 0.88.1
- VSCode Version: 1.89.1
- OS: Windows 11 Pro
- Repository Clone Configuration (single repository/fork of an upstream repository):
- Github Product (Github.com/Github Enterprise version x.x.x):

Steps to Reproduce:

1. Open a PR file in file review (diff) mode
2. Click on the button "Mark file as viewed"

Results:
1. The Diff file is closed.
2. the file in the tree control is **NOT** marked as viewed
3. An error pops up "Marked file as viewed failed: Error: GraphQL error: Filepath must be part of pull request" Source : GitHub Pull Requests.

Same problem, but from a different context, as reported here: #6012

**Comment by alexr00** [comment] 2024-05-27 14:29
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/6012

**Closed** 2024-05-27 14:29 UTC
Labels: *duplicate
