### ISSUE TITLE
Extension claims PR is closed although it is not

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode-pull-request-github#852] opened 2019-01-29 11:54 UTC
Testing https://github.com/Microsoft/vscode/issues/67299

Extension:

<img width="781" alt="capture" src="https://user-images.githubusercontent.com/1931590/51906656-e55ab500-23c4-11e9-9359-c580f6d02248.png">

Real:

<img width="617" alt="capture" src="https://user-images.githubusercontent.com/1931590/51906678-f6a3c180-23c4-11e9-91cb-e2da27109f21.png">

**Comment by dbaeumer** [comment] 2019-01-29 11:57
This only affects the nightly build. The normal build shows:

<img width="819" alt="capture" src="https://user-images.githubusercontent.com/1931590/51906835-6ade6500-23c5-11e9-81ed-ce58386d5b57.png">

**Comment by RMacfarlane** [comment] 2019-01-29 18:56
Duplicate of https://github.com/Microsoft/vscode-pull-request-github/issues/845

**Closed by RMacfarlane** 2019-01-29 18:56 UTC
