### ISSUE TITLE
extensions conflict

### ISSUE THREAD

**Issue by Tarrowren** [microsoft/vscode-pull-request-github#1441] opened 2019-11-13 01:15 UTC
- Extension version: 0.13.0
- VSCode Version: 1.40.0
- OS: Windows10

Steps to Reproduce:

1.install extensions SQL Server(mssql) 1.7.0
2.install extensions Github Pull Requests
3.there are two "+" here, the one on the right can't be used, click the one on the left
4.
![批注 2019-11-13 090924](https://user-images.githubusercontent.com/35626141/68724017-55a19280-05f5-11ea-8fe5-4365f3163ddc.png)

**Comment by RMacfarlane** [comment] 2019-11-13 01:39
This is being caused by the SQL Server extension: https://github.com/microsoft/vscode-mssql/issues/1455

It looks like they have already checked in a fix for it but haven't yet released a new version

**Closed by RMacfarlane** 2019-11-13 01:39 UTC
