### ISSUE TITLE
Support new changes since you last visited or specific commit changes

### ISSUE THREAD

**Issue by scrossan-crown** [microsoft/vscode-pull-request-github#934] opened 2019-02-08 15:09 UTC
Ability to view the changes since last visit or view only the changes in a specific commit. Currently I can see the commits that I need to review but it's showing me the all the changes in that file from the while branch not just in the selected commit.

Commit that contains new changes
![image](https://user-images.githubusercontent.com/30405149/52486612-801c7600-2bb3-11e9-92c8-6c618c9686f1.png)

vs 

Github's view of new changes
![image](https://user-images.githubusercontent.com/30405149/52486549-5b280300-2bb3-11e9-867e-5aedb39fcf5e.png)

**Comment by alexr00** [comment] 2020-11-11 14:47
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/363

**Closed by alexr00** 2020-11-11 14:47 UTC
Labels: feature-request
