### ISSUE TITLE
Commenting within a particular commit

### ISSUE THREAD

**Issue by thisissami** [microsoft/vscode-pull-request-github#1113] opened 2019-04-09 19:19 UTC
With the current version of GitHub Pull Requests (v0.6.0), you can right click on a pull request and click "check out" in order to see a more detailed view of the pull request in question.

There, you can separate the PR into the commits that comprise it, and see the changes made to each file as part of the commit. 

I'd love to be able to create a comment in the `diff` that opens for each of these files within a commit. It's possible to do this in the GitHub web view, so theoretically it should be possible here. This would certainly help my team & I with PRs (where currently, when we're reviewing specific commits - we have to use either the GitHub web view, or switch back and forth in VSCode between the `commit` specific view and the `PR` as a whole view.

**Comment by thisissami** [comment] 2019-04-09 19:19
I'm assuming this has yet to implemented. If it was implemented in a previous version, then I am reporting a bug :P

**Comment by queerviolet** [comment] 2019-04-10 05:59
This—and her sister, commenting on individual threads from within the PR overview—would indeed be quite nice.

**Comment by alexr00** [comment] 2021-11-19 14:02
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/141

**Closed by alexr00** 2021-11-19 14:02 UTC
Labels: feature-request
