### ISSUE TITLE
Override branch protection for owners

### ISSUE THREAD

**Issue by brianjmurrell** [microsoft/vscode-pull-request-github#5732] opened 2024-02-07 21:34 UTC
Type: <b>Feature Request</b>

On the GH UI, as an organization owner, I can override branch protection rules:
![image](https://github.com/microsoft/vscode-pull-request-github/assets/559317/c6e1ffa5-2c0c-40e3-82c4-5be809cbd886)

With VS Code and the GH Pull Requests and Issues extension, I don't seem to have this same abilty:
![image](https://github.com/microsoft/vscode-pull-request-github/assets/559317/0fde40c9-a496-4c74-a73e-04ad56645188)

I did look for some settings to adjust this behaviour but did not find any.  Google searching ended up being fruitless also.

Extension version: 0.78.1
VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:47:11.635Z)
OS version: Linux x64 6.5.5-200.fc38.x86_64
Modes:

**Comment by alexr00** [comment] 2024-02-19 17:19
duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/3996

**Closed by alexr00** 2024-02-19 17:19 UTC
