### ISSUE TITLE
Add "Start Review" feature with pending status comments

### ISSUE THREAD

**Issue by tisoap** [Microsoft/vscode-pull-request-github#495] opened 2018-09-17 13:21 UTC
Currently it's possible to add single comments to a PR, but I would like to have the same "Start Review" feature in GitHub, where all my added comments remain in "pending" status until I either approve, comment, or request changes.

**Comment by RMacfarlane** [comment] 2018-09-17 14:51
Duplicate of https://github.com/Microsoft/vscode-pull-request-github/issues/298, let's track it there

**Closed by RMacfarlane** 2018-09-17 14:51 UTC
