### ISSUE TITLE
Rate limit hit by leaving window open

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode-pull-request-github#4021] opened 2022-10-06 12:12 UTC
I was away from my computer for ~2 hours and left my window with the GHPRI view open as well as a PR Description editor open. I got back to the computer with the following errors:

![image](https://user-images.githubusercontent.com/22350/194309535-2629ced1-09fe-4262-a86d-ee757a830693.png)

**Comment by joaomoreno** [comment] 2022-10-11 11:29
Replied privately.

**Comment by alexr00** [comment] 2022-10-11 19:38
It looks like we're getting into some bad state where a couple hundred requests are made in a very short period (about a second). Still trying to determine what causes this state.

**Comment by alexr00** [comment] 2022-10-11 22:27
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/3847

**Closed by alexr00** 2022-10-11 22:27 UTC
Labels: bug
