### ISSUE TITLE
github pull requst extension not work on wsl2 ubuntu20.04

### ISSUE THREAD

**Issue by SimonTeo58** [microsoft/vscode-pull-request-github#3895] opened 2022-08-26 08:56 UTC
- Extension version: pre-release
- VSCode Version: 1.70.1
- OS: 
- 
![image](https://user-images.githubusercontent.com/46363359/186867130-7dd9ede6-5dc9-4076-8446-526c5a66099a.png)

![image](https://user-images.githubusercontent.com/46363359/186866992-9fad2956-5fce-464c-9677-83ca6504e379.png)

Steps to Reproduce:

1.
2.

**Comment by alexr00** [comment] 2022-09-20 15:48
I'm not able to reproduce this issue. This may be a duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/3891. @SimonTeo58 does signing out and back in again solve this?

**Comment by SimonTeo58** [comment] 2022-10-09 04:51
Even if I uninstalled this extension and then installed it again, still hit this error, I have never logged in. i gonna see #3891 details, many thx

**Closed** 2022-10-09 04:51 UTC
Labels: info-needed
