### ISSUE TITLE
Description view doesn't update if already opened

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#1137] opened 2019-04-26 19:02 UTC
Repro:

1. Open a PR description
2. Merge the PR (might not matter)
3. Focus another tab, keep the PR description open though
4. Open a different PR description

The tab title will update but the contents will not.

**Comment by RMacfarlane** [comment] 2019-10-16 01:38
Closing as I'm not able to reproduce with the latest version of the extension

**Closed by RMacfarlane** 2019-10-16 01:38 UTC
