### ISSUE TITLE
Remote Branch Not Deleted After PR Merge and Branch Delete

### ISSUE THREAD

**Issue by JustinGrote** [microsoft/vscode-pull-request-github#2272] opened 2020-11-10 00:03 UTC
Issue Type: <b>Bug</b>

1. Create a PR
1. Squash Merge the branch
1. Choose to delete both local and remote branch
1. Remote branch isn't deleted

![Capture](https://user-images.githubusercontent.com/15258962/98610656-ebbdd680-22a4-11eb-9520-cfe476771cdb.gif)

Extension version: 0.21.0
VS Code version: Code - Insiders 1.51.0-insider (fcac248b077b55bae4ba5bab613fd6e9156c2f0c, 2020-11-04T18:31:15.290Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1035G7 CPU @ 1.20GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.60GB (0.99GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/jgrote/Projects/AzurePrice --crash-reporter-id c46712d6-a98d-4728-ab12-732cb7b0c555|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by RMacfarlane** [comment] 2021-03-03 19:41
Closing as a duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/2504, have a PR out to fix this

**Closed by RMacfarlane** 2021-03-03 19:41 UTC
Labels: bug, duplicate
