### ISSUE TITLE
Do the full review on the comments view : add comments, modify code, navigate, intellisense

### ISSUE THREAD

**Issue by jonathanvila** [microsoft/vscode-pull-request-github#1698] opened 2020-04-27 16:21 UTC
I have been struggling to do my normal flow : 

CASE A
* I have a PR assigned
* I take a look but I need to navigate the code and have intellisense in the view with the comments and with the side by side diff with master
-> Now I can only see/add the comments but not navigate and have intellisense in the same view.

CASE B
* I create a PR
* my colleague introduce comments
* I respond with more comments and modify code and push again
-> Now I can not introduce code changes in the comments view
-> If I do checkout the PR, it creates a new local branch , so if I add changes to it it will be different than the real branch where I did all the changes

**Comment by RMacfarlane** [comment] 2020-05-01 21:19
Hey @jonathanvila 

For Case A, there is a way to do this currently, but is perhaps not immediately discoverable. If you open the description page of the PR and click "Checkout", a new view in the sidebar should appear titled "Changes in Pull Request". Here you can browse the diffs as before, or navigate to the file as it is on disk using this button:
<img width="421" alt="Screen Shot 2020-05-01 at 2 14 53 PM" src="https://user-images.githubusercontent.com/3672607/80842390-4a97ea00-8bb6-11ea-83fb-54c6b68bbac1.png">
You can see and add comments in both the diff and actual file, intellisense/navigation should work in both, and the right hand side of the diff editor should allow editing.

For Case B,
>If I do checkout the PR, it creates a new local branch 

This is not the expected behavior, it should reuse the branch you already have instead. I'll look into this!

**Comment by georgi-denchew** [comment] 2020-05-10 10:36
I had to find this comment from @RMacfarlane in order to find out how I can have the code diff, navigation and IntelliSense in the same view, so it's probably worth making this feature easier to discover from within VS Code or just enable it by default.

**Comment by jonathanvila** [comment] 2020-05-10 11:06
@RMacfarlane  I have already tried that but I dont see the differences ( old code vs new code ) 
![image](https://user-images.githubusercontent.com/1836434/81497488-1c559100-92bf-11ea-88ee-bbbafd6a3d0d.png)

**Comment by RMacfarlane** [comment] 2020-11-11 16:28
Closing as a duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/486

**Closed by RMacfarlane** 2020-11-11 16:28 UTC
