### ISSUE TITLE
Can't open a file from a diff

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode-pull-request-github#477] opened 2018-09-13 22:02 UTC
Issue Type: <b>Bug</b>

Click on a file in the tree to open a diff, then there is no way to quickly jump to the editable version of the file (assuming you have checked it out locally). I would expect an `Open File` button in the editor toolbar like the standard diff (and GitLens), as well as have a command right from the tree to open the file directly.

Extension version: 0.1.4
VS Code version: Code - Insiders 1.28.0-insider (8330a695712c43f861ce5c47533d82637d3cb374, 2018-09-13T11:25:00.283Z)
OS version: Windows_NT x64 10.0.17758

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.93GB (18.75GB free)|
|Process Argv|C:\Users\Eric\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by eamodio** [comment] 2018-09-13 22:06
I noticed that this works if I open the diff from the `Changes in Pull Request` tree, but not the other tree -- imo it should work the same for both (again assuming I have it checked out)

**Comment by RMacfarlane** [comment] 2018-09-14 00:37
Duplicate of https://github.com/Microsoft/vscode-pull-request-github/issues/268

Yeah, we should have this for both - the reason that the behavior is different between trees is that in the `GitHub Pull Requests` tree, the extension registers a document content provider and calculates and returns the content based on patches fetched from GitHub, since the commits in question might not exist locally. When checking out we do a fetch so we can just diff local commits in the `Changes in Pull Request` tree

**Closed by RMacfarlane** 2018-09-14 00:37 UTC
