### ISSUE TITLE
fatal: shallow file has changed since we read it . Please check git output for more details

### ISSUE THREAD

**Issue by brianjmurrell** [microsoft/vscode-pull-request-github#3482] opened 2022-04-21 19:26 UTC
Issue Type: <b>Bug</b>

When I try to check out a Pull Request I get a notification that says:

```
fatal: shallow file has changed since we read it . Please check git output for more details
```

I have no idea what that's telling me though.

Extension version: 0.40.0
VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:49:24.808Z)
OS version: Linux x64 5.16.18-200.fc35.x86_64
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz (12 x 2700)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|62.57GB (1.48GB free)|
|Process Argv|--unity-launch --crash-reporter-id d33a766b-28e9-45e5-942d-3a9085ddc0c0|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
pynewfile477:30463512

```

</details>

**Comment by AliAllomani** [comment] 2022-04-29 08:20
if you're using self-hosted runners, and having a shared workdir among multiple runners, it could be the cause of this issue
Github runs a single job per runner, and seems the runners are not designed to handle concurrent jobs per runner

**Comment by tty8747** [comment] 2022-05-01 06:23
I guess it is connected with [this](https://github.com/aBARICHELLO/godot-ci/issues/49), but it isn't solved too.

**Comment by tty8747** [comment] 2022-05-01 06:31
Did you try [it](https://community.sonarsource.com/t/shallow-clone-detected-but-my-repo-is-not-shallow/31321/6)?
```
Ok, another thing you can try is to go on your GitLab project settings > CI/CD > General pipelines and check that you use git  
 clone and not git fetch. Make sure as well that the .gitlab-ci.yml file you changed is the one on the branch you are building (I  
 don’t know how familiar you are with gitlab ^^)
```

**Comment by alexr00** [comment] 2022-05-03 11:34
duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/3096

**Closed by alexr00** 2022-05-03 11:34 UTC

**Comment by brianjmurrell** [comment] 2022-05-04 11:08
@tty8747 What is the correlation?  I don't see any.  I am not using any gitlab at all.
