### ISSUE TITLE
I cannot see any pull requests

### ISSUE THREAD

**Issue by tinganho** [microsoft/vscode-pull-request-github#1767] opened 2020-05-07 09:57 UTC
- Extension version: 0.15.0
- VSCode Version: 1.44.2
- OS: Mac

Steps to Reproduce:

1. Install extension and open the tab
I have 8 PRs:
![image](https://user-images.githubusercontent.com/1324476/81281224-d6e45a00-9059-11ea-95a6-650f5c43cadd.png)

But none of the is showing up:
![image](https://user-images.githubusercontent.com/1324476/81281156-bfa56c80-9059-11ea-8439-fa98bed7f121.png)

**Comment by RMacfarlane** [comment] 2020-05-07 21:13
Hi @tinganho, can you share what the result of running `git remote -v` in your currently opened folder is? It looks like the extension is having trouble finding the repository

**Comment by mzavattaro** [comment] 2020-05-08 06:09
I had a similar issue. My solution (whilst it may be more luck), was getting into one of my pull requests, assigning it to myself then restarting VSCode and they all appeared. I did notice that when I moved the Github Extension Icon around on the activity bar, it completely lost all the pull requests and I had to restart VSCode for them to appear again. Not sure what the cause or trigger is.

**Comment by tinganho** [comment] 2020-05-08 07:17
@RMacfarlane :
>git remote -v
origin	git@github.com:nordicfactory/Studio.git (fetch)
origin	git@github.com:nordicfactory/Studio.git (push)

**Comment by RMacfarlane** [comment] 2020-05-08 14:58
@tinganho Thanks! Can you open the output panel and select "GitHub Pull Request" and paste the log from there?

@mzavattaro This sounds like a different issue, I'll create a new issue for it. I'm having trouble reproducing it myself. Do you have multiple folders open in the workspace?

**Comment by tinganho** [comment] 2020-05-08 15:19
@RMacfarlane 
```
[Info] /Users/tinganho/.ssh/config: ENOENT: no such file or directory, open '/Users/tinganho/.ssh/config'
[Info] Looking for git repository
[Info] Git repository found, initializing review manager and pr tree view.
[Info] Review> Validate state in progress
[Info] Review> Validating state...
[Info] No remote with name 'upstream' found. Please update your 'githubPullRequests.remotes' setting.
[Info] No remote with name 'upstream' found. Please update your 'githubPullRequests.remotes' setting.
[Info] Found GitHub remote
[Info] Found GitHub remote
[Info] Review> no matching pull request metadata found for current branch master
```

**Comment by tinganho** [comment] 2020-05-08 15:20
We don't use Github flow, so no `upstream` remote. Is it a prerequesite?

**Comment by RMacfarlane** [comment] 2020-05-08 15:24
No, that should be ok. Just by default the extension will look for 'origin' and 'upstream' branches.

It looks like it's finding two github remotes - do you have multiple folders open in the workspace?

**Comment by tinganho** [comment] 2020-05-08 15:29
no,  I only use one:

![image](https://user-images.githubusercontent.com/1324476/81421199-5bfe6a80-9151-11ea-8185-c5db1df0b754.png)

**Comment by RMacfarlane** [comment] 2020-05-08 15:48
Hmm, ok. Thanks for your patience, I'm still not sure why this isn't working.

If you run the command `Developer: Toggle Developer Tools`, are there any errors in the console? If you click the "refresh" button at the top of the pull request view, do the results change?

**Comment by tinganho** [comment] 2020-05-08 15:52
I don't know if this one is relevant?
![image](https://user-images.githubusercontent.com/1324476/81423402-ab926580-9154-11ea-9cda-639a350d0487.png)

**Comment by onyekaa** [comment] 2020-05-08 20:15
Can confirm the same issue. 

At first I thought it was because I had two paths in my workspace (but other git-related tools work fine), so I removed one.  Still no remotes found.

Version: 1.45.0
Commit: d69a79b73808559a91206d73d7717ff5f798f23c
Date: 2020-05-07T15:57:33.467Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0

I get this under the Git output
`> git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git`

Under GithubPR:
```
[Info] Looking for git repository
[Info] Git repository found, initializing review manager and pr tree view.
[Info] Review> Validate state in progress
[Info] Review> Validating state...
[Info] GitHubServer> No response from host https://XXXXXX/git/: connect ECONNREFUSED XXX.XXX.XXX.XXX:443
[Info] GitHubServer> No response from host https://ssh.github.com/onyekaa/**: Client network socket disconnected before secure TLS connection was established
[Info] GitHubServer> No response from host https://ssh.github.com/onyekaa/**: Client network socket disconnected before secure TLS connection was established
[Info] Review> Queuing additional validate state
[Info] Review> Validating state...
[Info] No remote with name 'origin' found. Please update your 'githubPullRequests.remotes' setting.
[Info] No remote with name 'upstream' found. Please update your 'githubPullRequests.remotes' setting.
[Info] No remote with name 'github' found. Please update your 'githubPullRequests.remotes' setting.
[Info] No GitHub remotes found
[Info] Review> no matching pull request metadata found for current branch dj-3.2-upgrade
```

**Comment by RMacfarlane** [comment] 2020-05-08 20:29
@onyekaa Thanks for reporting this. It looks like your issue is a bit different. From the logs, it seems the extension isn't able to get a response from the remotes you have. Do you have something like this in your `~/.ssh/config` file?
```
Host github.com
  Hostname ssh.github.com
  Port 443
```

Is a firewall blocking the requests? If you change the remotes to be just https instead of ssh over https does it work?

**Comment by onyekaa** [comment] 2020-05-08 20:53
@RMacfarlane Indeed I do. Can't even remember why I added that in there but I'm not using a firewall so I'm not sure what the issue was. 

Taking that entry out and leaving only the `origin` remote in the VS settings seems to have resolved it, though, thanks.

**Comment by localjo** [comment] 2020-05-10 17:41
I have a similar problem. In the output panel under "GitHub Pull Request", I only see this: 

```
[Info] Looking for git repository
```

All I've done was install the extension, and open the folder of a GitHub repo, with the following remotes:

```
origin  git@github.com:localjo/react-tater.git (fetch)
origin  git@github.com:localjo/react-tater.git (push)
```

Maybe I'm missing some essential setup step?

**Comment by steven87vt** [comment] 2021-05-03 18:54
Just adding my two cents here, same issue but different cause:

- it appears ssh is not implemented and this is a hard requirement for me (internal vpn with dns and no real certs)
-- custom port over ssh as well
-- custom self signed certificate


```
[Info] Looking for git repository
[Info] Git repository found, initializing review manager and pr tree view.
[Info] Review> Validate state in progress
[Info] Review> Validating state...
[Info] GitHubServer> No response from host https://git.myserver.com/my_repo/some_project: request to https://git.myserver.com/api/v3/rate_limit failed, reason: unable to verify the first certificate
[Info] No remote with name 'origin' found.
[Info] No remote with name 'upstream' found.
[Info] No GitHub remotes found
[Info] Review> no matching pull request metadata found for current branch branch1
[Info] Review> no matching pull request metadata found on GitHub for current branch branch1
[Info] No remote with name 'origin' found.
[Info] No GitHub remotes found
```

**Comment by alexr00** [comment] 2021-06-14 09:44
@tinganho if you're still seeing this issue please post here and I will re-open the issue!

**Closed by alexr00** 2021-06-14 09:44 UTC
Labels: needs more info
