### ISSUE TITLE
Resolved conversation takes space but is hidden in an odd way

### ISSUE THREAD

**Issue by adrinjalali** [Microsoft/vscode-pull-request-github#1066] opened 2019-03-23 16:47 UTC
Looking at this conversation from the extension: https://github.com/scikit-learn/scikit-learn/pull/13483/files#r267814078

It looks like this:

![Screenshot from 2019-03-23 17-46-43](https://user-images.githubusercontent.com/1663864/54869054-a8db8200-4d93-11e9-9e26-0103729436c1.png)

**Comment by RMacfarlane** [comment] 2019-05-02 23:32
This is a duplicate of https://github.com/Microsoft/vscode-pull-request-github/issues/160. Thanks!

**Closed by RMacfarlane** 2019-05-02 23:32 UTC
