### ISSUE TITLE
Creating a PR when working on issue does not link 

### ISSUE THREAD

**Issue by silveiralsv** [microsoft/vscode-pull-request-github#2888] opened 2021-08-06 18:56 UTC
- Extension version: v0.29.0
- VSCode Version: 1.59.0
- OS: Linux x64 5.11.0-25-generic snap

Steps to Reproduce:

1. create an Issue, and starting work on it
2. create a PR from working issue

**Comment by alexr00** [comment] 2021-11-22 14:22
duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/2676

**Closed by alexr00** 2021-11-22 14:22 UTC
Labels: feature-request
