### ISSUE TITLE
Unable to checkout branch for review

### ISSUE THREAD

**Issue by misolori** [Microsoft/vscode-pull-request-github#860] opened 2019-01-29 19:08 UTC
Refs: https://github.com/Microsoft/vscode/issues/67297

All of the PRs are saying that they are "closed" and the "checkout" button is disabled. This is happening across multiple repos. Using `Nightly Build v1.29.0`

<img width="1297" alt="image" src="https://user-images.githubusercontent.com/35271042/51933348-f64ffa00-23b5-11e9-88a8-1a86ac7987f4.png">

**Comment by RMacfarlane** [comment] 2019-01-29 19:11
Duplicate of https://github.com/Microsoft/vscode-pull-request-github/issues/845, I just checked in a fix for this. You should still be able to checkout by right-clicking on the tree

**Closed by RMacfarlane** 2019-01-29 19:11 UTC

**Comment by misolori** [comment] 2019-01-29 19:41
@RMacfarlane I think this is also preventing me from leaving comments since it's closed?
