### ISSUE TITLE
Unable to complete sign in

### ISSUE THREAD

**Issue by MarkBennett** [microsoft/vscode-pull-request-github#4962] opened 2023-06-26 16:26 UTC
Type: <b>Bug</b>

I just installed VS Code Insiders and the GitHub Pull Requests and Issues extension.

Now, whenever VS Code starts up it asks me to sign in. I do and then it seems to work, but when I come back to VS Code it's still not signed in. The little person icon in the bottom left still has the "(1)" notification saying I'm not signed in and need to sign in.

Everything works fine on the stable VS Code install.

Extension version: 0.67.2023062609
VS Code version: Code - Insiders 1.80.0-insider (Universal) (b4952d14a465572e33f0635ef58de089227b8876, 2023-06-26T05:33:50.204Z)
OS version: Darwin arm64 22.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.05GB free)|
|Process Argv|--crash-reporter-id fef71f47-6431-4666-8871-ce339be46eee|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
py29gd2263:30773603
vscaac:30438845
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
pylantcb52:30590116
pyind779:30611226
pythonsymbol12:30651887
2i9eh265:30646982
showlangstatbar:30737417
pythonms35:30671666
03d35959:30757351
ecj1e332:30687743
pythonfmttext:30716741
pythoncmvfstr:30726892
fixshowwlkth:30771523
showindicator:30766888
pythongtdpath:30726887
i26e3531:30769768
gsof1:30771514
e440d664:30776459
pythonnosmt12:30773574
pythonidxpt:30768918
pythondjangots:30768917
pythonnoceb:30776497
copilotsettingc:30767685
e537b577:30772214

```

</details>

**Comment by alexr00** [comment] 2023-06-28 13:23
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/4951

**Closed by alexr00** 2023-06-28 13:23 UTC
