### ISSUE TITLE
Provide Refresh on Overview page

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode-pull-request-github#721] opened 2018-12-04 22:11 UTC
Issue Type: <b>Feature Request</b>

Testing https://github.com/Microsoft/vscode/issues/64262.

When you make changes such as `Suggest Edit` while the overview page is open, the overview page is not updated. I have to close it and reopen it to get the latest content. We should have a Refresh action on the page.

Extension version: 0.337.0
VS Code version: Code - Insiders 1.30.0-insider (fa87e67ebfd6b8014ba697ddbc6c2d6c0e2cb970, 2018-12-04T09:26:33.257Z)
OS version: Darwin x64 18.0.0

**Comment by RMacfarlane** [comment] 2019-01-04 18:45
Duplicate of https://github.com/Microsoft/vscode-pull-request-github/issues/103, fixed

**Closed by RMacfarlane** 2019-01-04 18:45 UTC
Labels: enhancement, overview
