### ISSUE TITLE
no PRs displayed in a project with multiple submodules

### ISSUE THREAD

**Issue by matejcik** [microsoft/vscode-pull-request-github#1069] opened 2019-03-25 13:05 UTC
- Extension version: 0.5.1
- VSCode Version: 1.32.3
- OS: Linux Mint x64

In a project with many submodules ([this one](https://github.com/trezor/trezor-core)), when I initially launch vscode, no pull requests would be shown.

Console says this:
`[Info] Review> no matching pull request metadata found for current branch undefined`

The repo is on master branch, and possibly the submodules in detached-head state are confusing the plugin?

When I go to Git sidebar and switch to a different submodule and then back to the top-level one, the plugin recovers and successfully loads the list of PRs.
The following output goes to the console:
1. when launching vscode: `no matching pull request metadata found for current branch undefined`
2. when switching to a detached-head submodule: `no matching pull request metadata found for current branch undefined`
3. when switching back to top-level: `no matching pull request metadata found for current branch master`
(but despite that last one, PRs load successfully)

**Comment by matejcik** [comment] 2019-04-08 12:57
with VSCode March update, it's necessary to reload vscode because simply switching the source control provider will no cause GitHubPR to refresh its idea of current branch

**Comment by JeffSpies** [comment] 2019-04-25 11:37
I'm now having this same issue: one submodule and the top-level repository's PR's won't show up. I've tried reinstalling and reloading.

- Extension version: 0.6.0
- VSCode Version: 1.33.1
- OS: Windows 10

@matejcik is this still an issue for you?

**Comment by loginx** [comment] 2019-04-25 16:54
I'm also experiencing this issue. Only the submodule PRs show up for me, the parent repo PRs never do.

* extension: 0.6.0
* vscode 1.34.0
* OS: OSX 10.14.4

**Comment by BuddyLReno** [comment] 2019-05-07 14:50
I'm experiencing this as well. Same versions as @loginx

**Comment by forstermatth** [comment] 2019-05-31 16:43
I'm having the same issue - multi source workspace always defaults, and I cannot switch, even if I remove the other sources.

I have attempted on both the insiders and GA versions of VS Code.

Related issues:
* https://github.com/microsoft/vscode-pull-request-github/issues/1179
* https://github.com/microsoft/vscode-pull-request-github/issues/1090
* https://github.com/microsoft/vscode-pull-request-github/issues/1069
* https://github.com/microsoft/vscode-pull-request-github/issues/1033

----

Extension version: 0.7.0
VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:22.738Z)
OS version: Darwin x64 18.6.0

----

Extension version: 0.7.0
VS Code version: Code - Insiders 1.35.0-insider (4ca38ce5584d7cd67b435b3c32ef1240c6a29628, 2019-05-21T05:17:12.031Z)
OS version: Darwin x64 18.6.0

---

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz (4 x 3500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.20GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by jaladh-singhal** [comment] 2020-05-15 17:58
Is there any progress on this issue?

I'm facing same problem with a project having one submodule. Only submodule PRs/issues are shown, none of parent repository which is what I want!

**Comment by hediet** [comment] 2020-05-18 09:51
It works if I open a sibling of the submodule in a new VS Code window that does not contain any other submodule.
But that's not a good work around.

**Comment by RMacfarlane** [comment] 2020-10-13 21:59
Closing as a duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/436. This should be fixed in version 0.20.0 of the extension. Thanks!

**Closed by RMacfarlane** 2020-10-13 21:59 UTC
