### ISSUE TITLE
Notification to pull from a branch to which we just pushed is not needed

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode-pull-request-github#316] opened 2018-08-29 06:52 UTC
- Check out a PR
- Make some changes, commit, push

You get the below

<img width="559" alt="screen shot 2018-08-28 at 11 51 04 pm" src="https://user-images.githubusercontent.com/16890566/44770588-5c8dd380-ab1d-11e8-8d37-1d6be056c465.png">

This is unnecessary as I just pushed the commit that the notification wants me to pull

**Comment by RMacfarlane** [comment] 2018-08-29 16:07
Duplicate of https://github.com/Microsoft/vscode-pull-request-github/issues/287

@ramya-rao-a What version of the extension were you using? This should be fixed in 0.0.18

**Closed by RMacfarlane** 2018-08-29 16:07 UTC
