### ISSUE TITLE
No comments in the editor when visiting file changes from commits

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-pull-request-github#141] opened 2018-08-08 04:08 UTC
- VSCode version: 1aab8e140e17f30a60b95df32264a39eb155765d
- Extension version: 0.0.7

Reproduce steps:
* Checkout Pull Request from the tree view https://github.com/Microsoft/vscode-pull-request-github/pull/94
* Expand Commits node from Changes In Pull Request section
* Expand Commit "Tweak the authentication user messages"
* One file change `src/github/credentials` is shown and it has a comment icon
* Click the file change, a diff editor is opened. No comment is shown in the editor

**Comment by rebornix** [comment] 2018-08-08 04:09
A DocumentCommentsProvider should be registered when visiting commits which have comments.

**Comment by rebornix** [comment] 2018-08-08 18:39
As there is no comments, we don't see commenting range decorations as well.

**Comment by alexr00** [comment] 2023-12-18 16:30
Viewing comments works, but adding them still does not.

**Comment by alexr00** [comment] 2024-12-17 11:54
Adding comments is a duplicate of the more popular https://github.com/microsoft/vscode-pull-request-github/issues/2793

**Closed by alexr00** 2024-12-17 11:54 UTC
Labels: bug
