### ISSUE TITLE
"Unable to open 'filename': resource is not available" for image diff views

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode-pull-request-github#1461] opened 2019-12-09 18:36 UTC
Issue Type: <b>Bug</b>

1. In the GitHub Pull Requests tree, expand a PR that has images or gifs in it and open one of these files

Error is shown and image is not opened. Also happens when the PR is checked out

Extension version: 2019.12.12573 (Nightly)
VS Code version: Code - Insiders 1.41.0-insider (87c2e0be5d7359ce110c4c9ec9f6df71be996f8a, 2019-12-06T21:34:49.305Z)
OS version: Darwin x64 18.7.0

**Comment by alexr00** [comment] 2020-11-11 15:36
The error appears to be gone. So duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/454

**Closed by alexr00** 2020-11-11 15:36 UTC
Labels: bug
