### ISSUE TITLE
fatal: shallow file has changed since we read it . Please check git output for more details

### ISSUE THREAD

**Issue by youngjuning** [microsoft/vscode-pull-request-github#3096] opened 2021-11-11 10:18 UTC

**Comment by brianjmurrell** [comment] 2022-04-21 17:15
Why was this closed invalid?  I am seeing this error also but have no idea what it's trying to tell me.

**Comment by alexr00** [comment] 2022-04-22 10:56
Can you share a screen shot of where you see this error as well as the git output?

**Comment by brianjmurrell** [comment] 2022-04-22 11:53
It was showing up on the bottom right in a standard notification popup.  It seems to be happening when I try to check out a PR into review mode.  Review mode is never started.  This is all specific to a particular repo.  Review mode works in other repos.

Git output when I click the **Checkout** button on PR Description tab:

```
[2022-04-22T11:52:17.200Z] > git ls-tree -l b91ee1e920f5d5bad16ae29130eb9d19e8d1d55c -- Jenkinsfile [3ms]
[2022-04-22T11:52:23.980Z] > git config --local -l [1ms]
[2022-04-22T11:52:24.064Z] > git symbolic-ref --short HEAD [2ms]
[2022-04-22T11:52:24.086Z] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track) refs/heads/corci-1162a refs/remotes/corci-1162a [4ms]
[2022-04-22T11:52:24.128Z] > git remote --verbose [3ms]
[2022-04-22T11:52:24.129Z] > git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname) [22ms]
[2022-04-22T11:52:24.154Z] > git config --get commit.template [2ms]
[2022-04-22T11:52:24.213Z] > git checkout -q corci-1162a [42ms]
[2022-04-22T11:52:24.265Z] > git symbolic-ref --short HEAD [2ms]
[2022-04-22T11:52:24.286Z] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track) refs/heads/corci-1162a refs/remotes/corci-1162a [3ms]
[2022-04-22T11:52:24.323Z] > git remote --verbose [2ms]
[2022-04-22T11:52:24.328Z] > git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname) [24ms]
[2022-04-22T11:52:24.353Z] > git config --get commit.template [2ms]
[2022-04-22T11:52:25.072Z] > git fetch origin refs/heads/corci-1162a [703ms]
[2022-04-22T11:52:25.072Z] From github.com:daos-stack/daos
 * branch                  corci-1162a -> FETCH_HEAD
[2022-04-22T11:52:25.124Z] > git symbolic-ref --short HEAD [2ms]
[2022-04-22T11:52:25.141Z] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track) refs/heads/corci-1162a refs/remotes/corci-1162a [2ms]
[2022-04-22T11:52:25.175Z] > git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname) [19ms]
[2022-04-22T11:52:25.181Z] > git remote --verbose [7ms]
[2022-04-22T11:52:25.201Z] > git config --get commit.template [2ms]
[2022-04-22T11:52:25.222Z] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track) refs/heads/corci-1162a refs/remotes/corci-1162a [3ms]
[2022-04-22T11:52:25.280Z] > git symbolic-ref --short HEAD [2ms]
[2022-04-22T11:52:25.298Z] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track) refs/heads/corci-1162a refs/remotes/corci-1162a [3ms]
[2022-04-22T11:52:25.334Z] > git remote --verbose [3ms]
[2022-04-22T11:52:25.336Z] > git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname) [20ms]
[2022-04-22T11:52:25.362Z] > git config --get commit.template [2ms]
```

And review mode is not active after that.  In this particular repo.

**Comment by alexr00** [comment] 2022-04-25 12:14
Thanks. I don't see the error in the git output, so it's no clear where it's happening. Is the error in the git output, but just no part of the section that you shared?

**Comment by brianjmurrell** [comment] 2022-04-25 13:06
No.  I have not seen it in git output.

But ultimately, it seems to be a symptom of the greater problem which is that in this one repo, I cannot **Checkout** and get into review mode.  Maybe if we figure out the cause of that, this issue will go away with the solution.

**Comment by alexr00** [comment] 2022-04-25 13:10
I agree. Are you able to checkout other branches via the command line?

**Comment by alexr00** [comment] 2022-04-25 14:32
> Note that I am checking out PRs, not branches (directly). To be clear I navigate to the "Github" plugin->Waiting For My Review and choose a PR. I then click on the PR's Description and click the Checkout button on the top right.

Behind the scenes, checking out a a PR is the same as checking out a branch. I am curious if you get the same error when just checking out a branch too.

**Comment by alexr00** [comment] 2022-04-25 15:16
> It does check out the PR/branch. It just doesn't open the Pull Request extension in review mode.

In that case, can you reproduce the issue then share the output of "GitHub Pull Request"?

**Comment by brianjmurrell** [comment] 2022-04-26 12:56
```
[Info] Review> switch to Pull Request #8821 - start
[Info] PullRequestGitHelper> Branch origin/shilongw/DAOS-10233 doesn't exist on local disk yet.
[Info] PullRequestGitHelper> Fetch tracked branch refs/remotes/origin/shilongw/DAOS-10233
[Info] PullRequestGitHelper> associate shilongw/DAOS-10233 with Pull Request #8821
[Info] Review> Review> switch to Pull Request #8821 - done
[Info] Review> Queuing additional validate state
```

At this point, VS Code is still in the Github extension and on the PR description.  It did not switch to the Github Pull Request extension in review mode.  If I manually switch to that extension, it's in review mode but for some other PR.

**Comment by alexr00** [comment] 2022-04-26 13:22
>  it's in review mode but for some other PR.

Have you used branch `shilongw/DAOS-10233` for a different PR before?

**Comment by brianjmurrell** [comment] 2022-04-26 13:23
No.  But this is not unique to that branch.  It happens on any branch I try to check out for review, whether I have tried it before or not.

**Comment by brianjmurrell** [comment] 2022-04-28 16:04
Any more progress we can make here?

**Comment by brianjmurrell** [comment] 2022-05-04 11:14
[Developer tools console log after trying to check out a PR](https://github.com/microsoft/vscode-pull-request-github/files/8619740/vscode-app-1651662662732.log).

There is a lot of noise at the start.  The end of the log is the result of trying to do a checkout.

**Comment by alexr00** [comment] 2022-05-04 12:35
Thanks @brianjmurrell. Based on the logs, the "Pull Request" view, which is supposed to open when you checkout a PR is not able to be registered properly. Does your workspace have multiple folders with GitHub repos in it?

**Comment by alexr00** [comment] 2022-05-04 14:44
Ok, I've opened a new issue for that since it's not related to the shallow error: https://github.com/microsoft/vscode-pull-request-github/issues/3515

**Comment by brianjmurrell** [comment] 2022-05-04 16:06
Awesome, thanks @alexr00!  I have subscribed to #3515.

**Comment by alexr00** [comment] 2022-05-13 12:43
@youngjuning Can you share a screen shot of where you see this error as well as the git output?

**Comment by alexr00** [comment] 2022-12-12 10:32
Closing because of missing info.

**Closed** 2022-12-12 10:32 UTC
Labels: info-needed
