### ISSUE TITLE
Use `circle-filled` icon for "Needs review"?

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode-pull-request-github#4272] opened 2022-11-29 23:22 UTC
Testing #4257

Should this use `circle-filled` instead if we're trying to look closer to the GH version?

<img width="335" alt="CleanShot 2022-11-29 at 15 19 27@2x" src="https://user-images.githubusercontent.com/25163139/204669952-4c6c3a2e-df9b-4ae9-a8c1-ad554627beb9.png">

<img width="132" alt="CleanShot 2022-11-29 at 15 21 27@2x" src="https://user-images.githubusercontent.com/25163139/204670098-9e4962a5-5007-4421-ab31-dd9850dcf673.png">

<img width="271" alt="CleanShot 2022-11-29 at 15 22 32@2x" src="https://user-images.githubusercontent.com/25163139/204670162-ea113228-d049-405d-94e6-bce8d710b911.png">

**Comment by alexr00** [comment] 2022-11-30 15:40
Closing as a duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/4259

**Closed** 2022-11-30 15:40 UTC
