### ISSUE TITLE
Comments panel should collapse when focused and escape is pressed

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode-pull-request-github#391] opened 2018-09-10 18:42 UTC
<img width="1011" alt="screen shot 2018-09-10 at 11 41 44 am" src="https://user-images.githubusercontent.com/2193314/45317329-8d431500-b4ee-11e8-8a42-fcc24ec1a053.png">

**Comment by Tyriar** [comment] 2018-09-10 18:42
Also the escape key no longer closes it.

**Comment by Tyriar** [comment] 2018-09-10 18:43
I'm on v0.1.1, Insiders a3f9f2e7240106aeec2f1d4bc03d7876bd42e2e4, 2018-09-07T05:05:38.205Z

**Comment by Tyriar** [comment] 2018-09-10 18:45
The button is fixed after updating Insiders but escape doesn't clear it, maybe this wasn't the behavior before but I expect it to collapse if I press escape when focused.

**Comment by RMacfarlane** [comment] 2018-09-10 18:49
Closing as a duplicate of https://github.com/Microsoft/vscode-pull-request-github/issues/88

Escape does work to dismiss the widget when it's a new comment with no text entered in it, we should make it work for existing comments 👍

**Closed by RMacfarlane** 2018-09-10 18:49 UTC
