### ISSUE TITLE
Pressing "Esc" on a comment being written deletes the comment content while keeping the line range

### ISSUE THREAD

**Issue by jmg-duarte** [microsoft/vscode-pull-request-github#6235] opened 2024-09-18 13:08 UTC
- Extension version: 0.96.0
- VSCode Version: 1.93.1
- OS: MacOS Catalina
- Repository Clone Configuration (single repository/fork of an upstream repository): Single repo
- Github Product (Github.com/Github Enterprise version x.x.x): Github.com

Steps to Reproduce:

1. Open a comment for a line range or even a single line
2. Write something
3. Close the box with "Esc"
4. Re-open the same box

Expected outcome: 
* Either for Esc not to close it (can probably be configured with focus settings)
* For a single line: if I re-open the same line I expect the text I was writing to still be there *while I have the diff/file open*, if the file is closed, the text can be gone
* For multiple lines: since it already keeps the line range, just keep the text around for the same text range until de-selected

In other, much simpler words: please don't delete the text I have because I pressed "Esc" — I'm using VSCode Vim and just deleted a big comment *twice* 😭

If you give me some pointers where I can look to investigate how to solve this, I can take some time to try and help!

Note: it seems that this doesn't always happen, I had a comment that was kept but I'm not sure if I left it with "Esc", but it's definitely not consistent.

**Comment by fhdiaze** [comment] 2024-09-24 23:11
I had the same problem? Have you found a work around?

**Comment by jmg-duarte** [comment] 2024-09-25 08:34
> I have the same problem? Have you found a work around?

Not clicking "Esc" — I wish I was joking

**Comment by jamesgecko** [comment] 2024-10-03 16:55
This is a huge show-stopper for users with [vim keybindings](https://github.com/VSCodeVim/Vim). I can't even exit insert mode without deleting the comment.

An application should _never_ delete text without either prompting or an undo option.

**Comment by alexr00** [comment] 2024-10-22 14:20
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/1455

**Closed by alexr00** 2024-10-22 14:20 UTC
