### ISSUE TITLE
Highlighting/intellisense is wrong for the change in C# PRs

### ISSUE THREAD

**Issue by ahmelsayed** [microsoft/vscode-pull-request-github#1533] opened 2020-02-29 20:32 UTC
I tried searching for 'highlight', 'hover', 'tooltip' but couldn't find any issues that seemed related. I could be wrong.

- Extension version: 0.14.0
- VSCode Version: 1.42.1
- OS: Windows (Using WSL2)

Steps to Reproduce:

1. Open a C# PR, I was looking at this one in particular https://github.com/Azure/azure-functions-core-tools/pull/1857, but it happens for all C# PRs I tried. Works fine for a Go PR
2. See gif

![QQfDOKI1oc](https://user-images.githubusercontent.com/645740/75614623-8d264300-5aef-11ea-8782-1ac2cb1474c4.gif)

**Comment by RMacfarlane** [comment] 2020-11-10 16:11
Closing as a duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/486 - currently it is expected that intellisense does not work for these files. The content comes from GitHub instead of the local disk. When the PR is checked out, intellisense should work

**Closed by RMacfarlane** 2020-11-10 16:11 UTC
