### ISSUE TITLE
Not obvious how to finish review

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode-pull-request-github#2686] opened 2021-04-28 00:26 UTC
Refs https://github.com/microsoft/vscode/issues/122245

1. Open a PR (not checked out)
2. Start a review
3. :bug: unable to figure out how to close review

The comments each have a "Open Review" which seems weird as actions next to "Add Comment". That's more of a navigational element. I expected a "Go To" icon in the top right toolbar of the editor (like in diffing).

<img width="550" src="https://user-images.githubusercontent.com/35271042/116327975-c5b9bf00-a77c-11eb-9787-ec68115a176f.png">

There are multiple "Comment" actions on the description and it's not clear how finish the review:

<img width="550" src="https://user-images.githubusercontent.com/35271042/116328396-c6068a00-a77d-11eb-99f4-e670e2e45d10.png">

Might I suggest using what github.com uses:

Using a `Finish your review (#)` button instead of "Comment"

<img width="550" src="https://user-images.githubusercontent.com/35271042/116328225-6c9e5b00-a77d-11eb-82b3-846be823a39b.png">

**Comment by clair-ross** [comment] 2021-05-06 20:07
+1 but I think this is a duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/1078

**Comment by alexr00** [comment] 2021-11-22 13:50
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/1078

**Closed by alexr00** 2021-11-22 13:50 UTC
