### ISSUE TITLE
Editing a PR comment wipes changes on document change within same pane

### ISSUE THREAD

**Issue by jaminthorns** [microsoft/vscode-pull-request-github#4451] opened 2023-01-24 17:41 UTC
- Extension version: 0.56.0
- VSCode Version: 1.74.3
- OS: macOS 13.1 (22C65)

Steps to Reproduce:

1. Comment on file `A` in a PR.
2. Edit the comment and modify the comment text in some way, but don't save.
3. Switch to file `B` within the same pane so that file `A` is out-of-view.
4. Switch back to file `A`.
5. Observe that the changes to the comment have been reverted.

**Comment by alexr00** [comment] 2023-02-17 13:45
Duplicate of upstream issue: https://github.com/microsoft/vscode/issues/166693

**Closed by alexr00** 2023-02-17 13:45 UTC
Labels: bug
