### ISSUE TITLE
Do not post comments immediately

### ISSUE THREAD

**Issue by igor-egorov** [Microsoft/vscode-pull-request-github#702] opened 2018-11-26 11:15 UTC
- Extension version: 0.3.0
- VSCode Version: 1.29.1
- OS: macOS HS 10.13.6

Steps to Reproduce:

1. Check-out any PR via the extension 
2. Add a comment to some changed line
3. Open Github page of the PR in a web browser

Expected result: the comment is not posted till Approve/Reject(request changes)/Comment button pressed on PR overview tab in vscode

Actual result: the comment is posted immediately.
It counts as a separate review, thus the PR will disappear from the list of pull requests awaiting my review.

Please make it possible to submit several review comments at once, not one by one as separate reviews.

**Comment by rebornix** [comment] 2018-11-26 19:39
duplicate of https://github.com/Microsoft/vscode-pull-request-github/issues/546, we are now looking into this one already, thanks!

**Closed by rebornix** 2018-11-26 19:39 UTC
