### ISSUE TITLE
Issue number intellisense does not work consistently

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode-pull-request-github#1531] opened 2020-02-26 09:40 UTC
Type `Fixes #` in the commit message. A list of issues appears:
![image](https://user-images.githubusercontent.com/5047891/75332072-120d2480-5884-11ea-935a-da1b87071407.png)

Type `91`. The list of issues narrows down:
![image](https://user-images.githubusercontent.com/5047891/75332205-48e33a80-5884-11ea-9a99-8546a7e0fd45.png)

Close the suggestions and retrigger them via Ctrl+Space. The list of issues does not appear:
![image](https://user-images.githubusercontent.com/5047891/75332159-3832c480-5884-11ea-8476-ac68a6fa7b06.png)

**Comment by alexr00** [comment] 2020-02-26 09:42
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/1504

**Comment by alexr00** [comment] 2020-02-26 09:43
I don't show the issue suggestion when triggered manually. But if the text looks like `#91` (# followed by numbers) it should show the issues when triggered.

**Closed by alexr00** 2020-02-26 09:43 UTC
