### ISSUE TITLE
Only the first code snippet in a review is shown

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode-pull-request-github#55] opened 2018-06-27 02:00 UTC
Review: https://github.com/xtermjs/xterm.js/pull/1460#pullrequestreview-130283025

![image](https://user-images.githubusercontent.com/2193314/41948766-24c9bdc8-7973-11e8-9728-5c440935ad0c.png)

**Comment by RMacfarlane** [comment] 2018-07-17 21:07
Duplicate of https://github.com/Microsoft/vscode-pull-request-github/issues/81

**Closed by RMacfarlane** 2018-07-17 21:07 UTC
Labels: bug, overview
