### ISSUE TITLE
Support for company github servers

### ISSUE THREAD

**Issue by Semitalis** [microsoft/vscode-pull-request-github#1925] opened 2020-06-19 16:08 UTC
Could you please support other instances of github, i.e. companies setup their own github servers and it would really help to be able to configure the github server the extension communicates with. Maybe on a per-repository basis.

Note that the company github servers might lag behind in the used version.

**Comment by RMacfarlane** [comment] 2020-06-23 15:24
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/1793

**Closed by RMacfarlane** 2020-06-23 15:24 UTC
