### ISSUE TITLE
Diffs are not showing

### ISSUE THREAD

**Issue by st-schneider** [microsoft/vscode-pull-request-github#964] opened 2019-02-18 07:47 UTC
Issue Type: <b>Bug</b>

Currently in the side by side view of commits there are no changes marked as changes. Also, you cannot step to the next change.

Extension version: 0.4.0
VS Code version: Code - Insiders 1.32.0-insider (4e68ba25fbc752e3d7da488b8d3db374029577d6, 2019-02-18T06:15:59.901Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|-psn_0_1724837|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by RMacfarlane** [comment] 2019-02-22 00:37
@bm-stschneider This is happening for files under the "Commits" node in the "Changes in Pull Request" tree? Do you have an example PR this happens for?

**Comment by bm-stschneider** [comment] 2019-02-28 06:53
there are all private, but it happens to all of them. Under the files node in changes in pull request.

**Comment by RMacfarlane** [comment] 2020-11-10 18:55
Closing as I'm not able to reproduce this in the latest version of the extension. Please let me know if you see this again! Thanks.

**Closed by RMacfarlane** 2020-11-10 18:55 UTC
