### ISSUE TITLE
Revoking the App Permissions in GitHub Results in the Plugin Being Unusable

### ISSUE THREAD

**Issue by ScottFinlaysonGMSL** [microsoft/vscode-pull-request-github#2209] opened 2020-10-12 12:05 UTC
Description:
After revoking the plugin permissions within GitHub, the plugin never prompts the user to sign in again. This survives plugin re-installs as well as VS Code re-installs. I would expect the plugin to recognize the credentials have been revoked and ask the user to sign in again (where its an explicit failure due to permissions having been revoked, rather than a temporary issue with the API).

Version Info:
- Extension version: 0.20.0
- VSCode Version: 1.49.3
- OS: Windows 10

Steps to Reproduce:

1. Install plugin and connect to Github via plugin
2. Navigate to "Settings" > Applications > "Authorized OAuth Apps"
3. Expand options > Select "Revoke" and confirm
4. Restart VS Code. Panels will fail to refresh and will always be blank (shown below)

![Capture](https://user-images.githubusercontent.com/54799908/95744590-77831980-0c8b-11eb-96bf-f608fc8d1918.JPG)

Workaround:
In Windows 10:
- Navigate to the "Credentials Manager"
- Find the credential "vscode-github.login/account"
- Select to remove
- Plugin within VSCode should now show the "Sign In" option again

**Comment by emakryo** [comment] 2021-09-09 02:39
The same thing happens on Linux. Are there any workarounds on Linux?

**Comment by ScottFinlaysonGMSL** [comment] 2021-09-09 06:50
I have access to a mac so had a quick check. You need to have a look at the credential store that git is configured to use by the looks of it. You can check this by going opening a terminal in the location of your repo and typing:
```
git config -l
```
If you don't see an option for `credential.helper` then add `--global` onto the command above.

Assuming the value is `osxkeychain` then go into your key chain and search for github. You should have an entry named `vscodevscode.github-authentication`. Delete that entry and restart VS Code. At this point, it should ask you to sign in again.

**Comment by emakryo** [comment] 2021-09-09 06:56
Thank you, it works perfectly!

**Comment by TylerLeonhardt** [comment] 2021-11-25 17:11
Yes I imagine this is very similar and the same root cause to #104816 in otherwords, we need to verify that the token is still valid. Let's close this as a duplicate

**Closed by TylerLeonhardt** 2021-11-25 17:11 UTC
Labels: bug, authentication

**Comment by jenschr** [comment] 2022-11-16 15:27
@TylerLeonhardt FYI the link to the other issue no longer works and I just got this bug now, so it's not fixed per 2022. The comment by @ScottFinlaysonGMSL + a restart of VS Code solved it for me.

**Comment by MichaelWoodc** [comment] 2024-01-16 04:34
> Description: After revoking the plugin permissions within GitHub, the plugin never prompts the user to sign in again. This survives plugin re-installs as well as VS Code re-installs. I would expect the plugin to recognize the credentials have been revoked and ask the user to sign in again (where its an explicit failure due to permissions having been revoked, rather than a temporary issue with the API).
> 
> Version Info:
> 
> * Extension version: 0.20.0
> * VSCode Version: 1.49.3
> * OS: Windows 10
> 
> Steps to Reproduce:
> 
> 1. Install plugin and connect to Github via plugin
> 2. Navigate to "Settings" > Applications > "Authorized OAuth Apps"
> 3. Expand options > Select "Revoke" and confirm
> 4. Restart VS Code. Panels will fail to refresh and will always be blank (shown below)
> 
> ![Capture](https://user-images.githubusercontent.com/54799908/95744590-77831980-0c8b-11eb-96bf-f608fc8d1918.JPG)
> 
> Workaround: In Windows 10:
> 
> * Navigate to the "Credentials Manager"
> * Find the credential "vscode-github.login/account"
> * Select to remove
> * Plugin within VSCode should now show the "Sign In" option again

Wow, saved the day for me!  I reset my whole pc, couldn't for the life of me understand how on earth it could persist through a reset.  I never even logged into this other account.  The credentials persisted across installs, synced through my microsoft account I guess.
