### ISSUE TITLE
"loading" forever in intellisense in markdown file

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-pull-request-github#3387] opened 2022-03-10 00:57 UTC
Issue Type: <b>Bug</b>

- Open a markdown file
- Press ctrl+space
- The suggest widget says "loading" forever which probably means that a completion provider is not resolving

I used the extension bisect to find that this is from the GHPRI extension. I see it in stable but not insiders. But it might be due to some user data or something rather than a vscode bug. I don't see any errors or relevant logs in the GitHub Pull Request output panel. I'm happy to try things or investigate. Looks like I am logged in to github.

Extension version: 0.39.2022030911
VS Code version: Code 1.65.1 (8908a9ca0f221f36507231afb39d2d8d1e182702, 2022-03-08T02:20:11.670Z)
OS version: Darwin x64 21.3.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|32.00GB (0.82GB free)|
|Process Argv|--crash-reporter-id 567ec56b-f993-44f3-86fb-0f8a5925f34b|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30448491
dsvsc009:30440023
pythonvspyt640:30450904
vsbas813:30436447
vscscmwlcmt:30438805
vscgsvid1:30447480
helix:30440343
vscaac:30438847
pynewfile477:30450038

```

</details>

**Comment by alexr00** [comment] 2022-03-21 12:57
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/3359

**Closed by alexr00** 2022-03-21 12:57 UTC
