### ISSUE TITLE
Partially missing successful PR checks

### ISSUE THREAD

**Issue by radu-matei** [microsoft/vscode-pull-request-github#813] opened 2019-01-11 16:31 UTC
#790 mentions that failing checks are missing from the check list in the extension. However, some passing checks are also missing from the `Description` pane:

![image](https://user-images.githubusercontent.com/13103165/51046524-f470f300-15ce-11e9-8eaf-546ad02352b7.png)

Note there are three total checks for this particular PR:

![image](https://user-images.githubusercontent.com/13103165/51046560-10749480-15cf-11e9-907a-f0019256250b.png)

- Extension version: 0.3.2
- VSCode Version: 1.31.0-insider
- OS: Windows 10

Thanks for the awesome extension!

**Comment by leegenes** [comment] 2019-03-08 18:33
also running into this. all jenkins ci checks are displayed in Description pane, but all custom ci app checks are not.
* Extension version: 0.5.0
* VSCode Version: 1.32.1
* OS: osx 10.14.3

**Comment by phstc** [comment] 2019-08-15 14:37
Sorry for the off-topic, but how did you manage to see checks using this extension? I don't see any in my PR description view - that's a feature I would love to have.

**Comment by RMacfarlane** [comment] 2020-08-13 20:15
I believe this is actually a duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/790, and should be fixed with the change I just checked in: https://github.com/microsoft/vscode-pull-request-github/commit/f821fc0180415d96541c08f4e15868899a79be7a

**Closed by RMacfarlane** 2020-08-13 20:15 UTC
Labels: bug
