### ISSUE TITLE
Copy/paste images in PR description

### ISSUE THREAD

**Issue by BenjaVR** [microsoft/vscode-pull-request-github#2760] opened 2021-06-02 10:15 UTC
If we make a PR on the Github website, we can paste an image in the text editor and it will automatically upload the image and put it inline.

It would be nice if we could do the same from the vscode plugin. Now I have to leave placeholders and open the PR in the browser after creation, just to add the images.

**Comment by alexr00** [comment] 2021-06-03 13:27
duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/320

**Closed by alexr00** 2021-06-03 13:27 UTC
