### ISSUE TITLE
Missing padding after Reply button

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#785] opened 2019-01-07 18:56 UTC
ext version: 1.7.1

I made a comment via the extension and I got this:

![image](https://user-images.githubusercontent.com/2193314/50787250-c1df9700-126a-11e9-8328-a8da54333d76.png)

Not sure why the padding below "Reply" is missing, but it's fine on other comments:

![image](https://user-images.githubusercontent.com/2193314/50787263-cdcb5900-126a-11e9-98eb-bc93faa05a81.png)

**Comment by RMacfarlane** [comment] 2019-10-16 22:50
I've been unable to reproduce this in the latest version of VSCode (with that comment text), so will close this out

**Closed by RMacfarlane** 2019-10-16 22:50 UTC
Labels: upstream/vscode
