### ISSUE TITLE
Cannot read property 'toLocaleLowerCase' of undefined

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode-pull-request-github#226] opened 2018-08-16 20:14 UTC
```
Cannot read property 'toLocaleLowerCase' of undefined: TypeError: Cannot read property 'toLocaleLowerCase' of undefined
    at VSCodeConfiguration.getHost (/Users/penlv/.vscode-insiders/extensions/microsoft.vscode-pull-request-github-0.0.11/out/authentication/vsConfiguration.js:46:37)
```

**Comment by RMacfarlane** [comment] 2018-08-17 00:32
Duplicate of https://github.com/Microsoft/vscode-pull-request-github/issues/191 😄

**Closed by RMacfarlane** 2018-08-17 00:32 UTC
Labels: authentication, bug, important
