### ISSUE TITLE
Show comment creation dates within the pull request

### ISSUE THREAD

**Issue by jmredfern** [microsoft/vscode-pull-request-github#3024] opened 2021-10-07 16:09 UTC
I miss the ability to see when a comment was made - maybe it's very old and outdated, maybe it's brand new and there's a fresh conversation to be had. So the idea is within comment boxes that appears in the pull request there, to show the creation date.

Thanks!

**Comment by laurentlb** [comment] 2021-11-09 17:25
I think it's a duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/121

**Comment by alexr00** [comment] 2021-11-09 17:31
It is, thank you @laurentlb.

**Closed by alexr00** 2021-11-09 17:31 UTC
Labels: feature-request
