### ISSUE TITLE
Cannot do select all in search box while PR overview is open

### ISSUE THREAD

**Issue by JeffreyCA** [Microsoft/vscode-pull-request-github#630] opened 2018-10-26 15:34 UTC
- Extension version: 0.2.1
- VSCode Version: 1.28.2
- OS: macOS 10.14

Steps to Reproduce:

1. Open PR in overview
2. Open search pane and focus search box
3. Type something in search box
4. Press Cmd+A to select all text in search box

It selects all of the text in the PR overview instead of the search box

<img width="1375" alt="screen shot 2018-10-26 at 11 33 47 am" src="https://user-images.githubusercontent.com/9157833/47576650-049ffd00-d913-11e8-95b1-1c8821c9f92b.png">

**Comment by RMacfarlane** [comment] 2018-11-01 00:32
This is an interesting issue, I can also repo this in the extensions search and debug console. The "Selection" menu doesn't visibly trigger.

I'm not able to reproduce this using the VSCode insiders version, so I believe this is an upstream issue that has already been fixed

**Comment by RMacfarlane** [comment] 2018-11-05 19:08
This happens with webviews contributed by other extensions, so I'll close this as it isn't an issue with the extension itself. Will be fixed in VSCode version 1.29.

**Closed by RMacfarlane** 2018-11-05 19:08 UTC
