### ISSUE TITLE
Unable to turn off auto-fetching behaviour for PRs in review

### ISSUE THREAD

**Issue by liamdawson** [microsoft/vscode-pull-request-github#4296] opened 2022-12-07 01:12 UTC
It appears that the "GitHub Pull Requests and Issues" extension ignores all settings governing automatic repository fetches in VS Code. My setup relies on a physical interaction (touching my Yubikey) for SSH authentication to the remote, so any actions I haven't personally initiated are likely to fail. For this reason, I'd like to turn off automatic fetch behaviour.

- Extension version: v0.54.1
- VSCode Version: 1.73.1
- OS: Darwin arm64 22.1.0

Steps to Reproduce:

1. Set `git.autofetch` and `githubRepositories.autoFetch.enabled` to false
2. Check out a PR for review

**Expected:**

No `git fetch` or `git pull` operations occurring, no notifications

**Actual**

Error notifications appear periodically saying `An error occurred when fetching the repository`, as SSH authentication fails.

**Comment by alexr00** [comment] 2022-12-07 15:09
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/4202

**Closed by alexr00** 2022-12-07 15:09 UTC
