### ISSUE TITLE
Cannot configure the extension

### ISSUE THREAD

**Issue by FrankHuy** [microsoft/vscode-pull-request-github#1331] opened 2019-09-09 07:58 UTC
Issue Type: <b>Bug</b>

Open the setting of the extension,then throw an error like that:command 'pr.configurePRViewlet' not found

Extension version: 0.10.0
VS Code version: Code 1.38.0 (3db7e09f3b61f915d03bbfa58e258d6eee843f35, 2019-09-03T21:49:13.459Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.85GB (1.15GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by RMacfarlane** [comment] 2019-09-09 17:31
@FrankHuy I haven't been able to reproduce this yet - how are you opening the settings of the extension? Is it from clicking a button the the "GitHub Pull Requests" view, from running a command, or something else?

**Comment by nschonni** [comment] 2019-09-10 04:55
Also seeing this now. When selecting "GitHub Pull Requests: Configure Remotes" an error alert pops up with "command 'pr.configureRemotes' not found"
Looking at the logs there is the followinng message
```
[Info] /Users/nschonni/.ssh/config: ENOENT: no such file or directory, open '/Users/nschonni/.ssh/config'
[Info] Looking for git repository
```

**Comment by nschonni** [comment] 2019-09-10 04:56
Just started happening, so it would be something in the 0.11 release

**Comment by icel21m** [comment] 2019-09-11 11:58
I'm having the same issue.

**Comment by nschonni** [comment] 2019-09-11 15:49
It started working for me again with the 0.11.1 release

**Comment by RMacfarlane** [comment] 2019-09-11 21:34
yeah, I was also able to repro yesterday on 0.11.0, should have been fixed with https://github.com/microsoft/vscode-pull-request-github/commit/999b7eeb2e6362e36e8294a27d80fdced9ddd3fe

However, the original bug report was for 0.10.0, which didn't have the issue that 0.11.0 did. I'm going to tentatively close this since I can no longer reproduce this in 0.11.1, but please let me know if you encounter this again. Thanks everyone!

**Closed by RMacfarlane** 2019-09-11 21:34 UTC
Labels: needs more info

**Comment by BenudharSahoo** [comment] 2019-11-04 09:12
facing the same issue on vs code 1.39.2 version

**Comment by n00ne1mportant** [comment] 2019-12-03 10:11
Same issue on Arch, can't open any settings or configs. Just gives me the message as OP described.
Please reopen this

**Comment by brettinternet** [comment] 2020-07-14 22:45
For Arch users, or others using the OSS build of VSCode, @RMacfarlane [recently mentioned](https://github.com/microsoft/vscode-pull-request-github/issues/1942#issuecomment-658431501) that you will need to run `code` with a flag:

```
code --enable-proposed-api GitHub.vscode-pull-request-github
```

Alternatively, you can edit your `product.json` file (code installs this to `/usr/lib/code/product.json`).

```
"extensionAllowedProposedApi": [
    "GitHub.vscode-pull-request-github"
]
```

This issue is [documented in the wiki](https://github.com/Microsoft/vscode-pull-request-github/wiki#3-why-isnt-the-extension-starting) and [in other extensions' documentation](https://wiki.archlinux.org/index.php/Visual_Studio_Code). I have updated the Arch Wiki with this information and consolidated [related errors under a single troubleshooting heading](https://wiki.archlinux.org/index.php/Visual_Studio_Code#Command_%22...%22_not_found) to help users understand the effect of the OSS build missing Microsoft's `product.json`.

**Comment by scottwallacesh** [comment] 2020-11-13 11:27
What got this working for me was adding an entry to `~/.vscode/argv.json`:
```javascript
{
    // Allow Github Pull Request to work
    "enable-proposed-api": [
        "GitHub.vscode-pull-request-github"
    ]
}
```
