### ISSUE TITLE
Install this plugin then create new PR and got this message

### ISSUE THREAD

**Issue by SwapCursor** [microsoft/vscode-pull-request-github#2139] opened 2020-09-20 11:23 UTC
- Extension version:
0.20.0
- VSCode Version:
_Version: 1.49.1 (user setup)
Commit: 58bb7b2331731bf72587010e943852e13e6fd3cf
Date: 2020-09-16T23:27:51.792Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18363
- OS:_

Steps to Reproduce:
- In GitHub Fork a repo called FOO
- Clone it using GitHub Desktop
- Install this plugin, login authorize ..
- Make a change in the clone FOO version, stage and commit locally
- Now create a PR using GitHub Pull Requests and Issues plugin from this last commit and select master branch at FOO origin

The result is below error message;
![image](https://user-images.githubusercontent.com/34265065/93710014-6854f400-fb43-11ea-8eb2-33ac88e28784.png)

I tried two times sign out from GitHub Pull Requests and Issues plugin and sign in again

**Comment by RMacfarlane** [comment] 2020-09-23 19:13
This looks like a duplicate of #2100 - I have checked in a fix for this to show an option to push your local changes in this case. The fix will be available in our next release, which should be in a couple of weeks. Thank you!

**Closed by RMacfarlane** 2020-09-23 19:13 UTC
