### ISSUE TITLE
Checking the draft PR checkbox doesn't work

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode-pull-request-github#3989] opened 2022-09-27 03:49 UTC
Type: <b>Bug</b>

Just tried to create https://github.com/microsoft/vscode/pull/161881 as draft but it didn't work and I had to manually switch to draft after I created it

Extension version: 0.51.2022092609
VS Code version: Code - Insiders 1.72.0-insider (831678f718c8e998adc40d4854d9d35d9586a09f, 2022-09-26T09:36:38.583Z)
OS version: Darwin x64 21.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 3, 3|
|Memory (System)|64.00GB (0.54GB free)|
|Process Argv|--enable-proposed-api donjayamanne.kusto --log trace --crash-reporter-id 4cf0a6f0-aaf8-4da3-9b2b-81f6c639c12b|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
cmake_vspar411cf:30557515
vsaa593:30376534
pythonvs932:30404738
cppdebug:30492333
vscaac:30438845
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pylantcb52:30568093
vscccc:30564267
pyindex848:30568094

```

</details>

**Comment by alexr00** [comment] 2022-09-29 15:28
Most likely a duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/3977

**Closed by alexr00** 2022-09-29 15:28 UTC
