### ISSUE TITLE
Lots of duplicate files in PR changes view

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#3297] opened 2022-02-04 20:10 UTC
![image](https://user-images.githubusercontent.com/2193314/152596330-e7d27dae-e241-4459-901b-34b1727dfbcb.png)

PR: https://github.com/microsoft/vscode/pull/142211

Log

```
[Info] Review> switch to Pull Request #142211 - start
[Info] PullRequestGitHelper> associate pr/LuanVSO/142211 with Pull Request #142211
[Info] Review> Review> switch to Pull Request #142211 - done
[Info] Review> Queuing additional validate state
[Info] Review> Validating state...
[Info] Found GitHub remote
[Info] Review> current branch pr/LuanVSO/142211 is associated with pull request #142211
[Info] Review> Resolving pull request
[Info] Review> Fetching pull request data
[Info] Review> register comments provider
[Info] Review> display pull request status bar indicator and refresh pull request tree view.
[Info] Review> using focus mode = true.
[Info] Review> state validation silent = false.
[Info] Review> PR show should show = false.
[Info] PullRequestChangesTreeDataProvider> Error: TreeError [prStatus:github] Data tree node not found: [object Object]
```

ext version: 0.37.2022020316 Pre-Release

Version: 1.65.0-insider (user setup)
Commit: 62de8dc3f78b8bef1eb62deeb093164a8d76c254
Date: 2022-02-04T11:47:20.200Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

**Comment by Tyriar** [comment] 2022-02-04 20:11
Clicking the refresh button fixed it

![image](https://user-images.githubusercontent.com/2193314/152596614-e877e0bd-5ffe-46b9-aaaa-49068c30edba.png)

**Comment by alexr00** [comment] 2022-02-07 13:04
@Tyriar do you know what you were doing when that happened? Had you just pushed a change to the branch?

Might be related to https://github.com/microsoft/vscode-pull-request-github/issues/3294. I just pushed a fix for that, so it will be in the next pre-release build.

**Comment by Tyriar** [comment] 2022-02-07 13:17
I remember there were changes I hadn't pulled. Either on my other computer I was working or it or I hit the update branch button, can't remember the specifics.

**Comment by alexr00** [comment] 2022-02-10 13:06
I'm pretty sure this is a duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/3294

If we see it again we can re-open.

**Closed by alexr00** 2022-02-10 13:06 UTC
Labels: needs more info
