### ISSUE TITLE
Can select with repository to create a PR when on workspace with multiple repositories

### ISSUE THREAD

**Issue by mtxr** [microsoft/vscode-pull-request-github#1090] opened 2019-03-29 12:22 UTC
Issue Type: <b>Bug</b>

When I click on create pull request, i see it detects the repository. But I want to create the pull request for the other repository in the workspace I`m working on

Extension version: 0.5.1
VS Code version: Code - Insiders 1.33.0-insider (b5f5db349f211f5045e7dad6fd1672010d2d00de, 2019-03-28T10:44:04.956Z)
OS version: Linux x64 5.0.3-200.fc29.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 3449)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.44GB (8.38GB free)|
|Process Argv|-r project.code-workspace|
|Screen Reader|no|
|VM|0%|

</details>

related to #493 (possible duplication)

**Comment by mtxr** [comment] 2019-03-29 12:23
Just to add some info, It always take the first open repository to create a PR

**Comment by forstermatth** [comment] 2019-05-31 16:43
I'm having the same issue - multi source workspace always defaults, and I cannot switch, even if I remove the other sources.

I have attempted on both the insiders and GA versions of VS Code.

Related issues:
* https://github.com/microsoft/vscode-pull-request-github/issues/1179
* https://github.com/microsoft/vscode-pull-request-github/issues/1090
* https://github.com/microsoft/vscode-pull-request-github/issues/1069
* https://github.com/microsoft/vscode-pull-request-github/issues/1033

----

Extension version: 0.7.0
VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:22.738Z)
OS version: Darwin x64 18.6.0

----

Extension version: 0.7.0
VS Code version: Code - Insiders 1.35.0-insider (4ca38ce5584d7cd67b435b3c32ef1240c6a29628, 2019-05-21T05:17:12.031Z)
OS version: Darwin x64 18.6.0

---

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz (4 x 3500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.20GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by DavidGriswoldTeacher** [comment] 2019-09-17 13:21
Is there a reason this bug, and the many other ones @forstermatth mentions that are the same bug, have not been addressed? I am encountering it now and find myself needing to manually open my sub-folders in separate windows to use the extension effectively. It is not ideal.

**Comment by RMacfarlane** [comment] 2019-09-18 18:49
@DavidGriswoldTeacher Sorry for the inconvenience, using this extension in a multi-repository workspace still needs some more.

You should be able to change which repository the extension is using by changing the selection in the Source Control viewlet:
![Screen Shot 2019-09-18 at 11 48 03 AM](https://user-images.githubusercontent.com/3672607/65176715-3679f080-da0a-11e9-804b-50ec3a42a941.png)

**Comment by pelletier** [comment] 2019-11-15 17:02
@RMacfarlane this workaround does not seem to be working for me. Regardless of which repository I select in the "Source Control" list, the Create Pull Request dialog always selects the same repository.

**Comment by neils95** [comment] 2019-11-22 17:42
@RMacfarlane I am experiencing the same. Using version 0.12 of the extension (had to downgrade because of another open PR) 

When I try to create a pull request from a multi root workspace, it always selects the first repo. I can never create a PR for another repo in the workspace.

**Comment by reflog** [comment] 2019-11-30 15:16
Same here. In multi-repo workspace only one repository's pull requests are shown, no matter what is selected in SCM viewlet

**Comment by RMacfarlane** [comment] 2019-12-02 22:42
Thanks all, I'm able to reproduce and have created this upstream issue: https://github.com/microsoft/vscode/issues/85975

However, I'm still able to get this to work currently if I change the selection more than once.

**Comment by westbury** [comment] 2020-01-27 14:25
The underlying problem in vscode is fixed: https://github.com/microsoft/vscode/commit/afa24c3c042927973ac88935b173187b89f510d4

Once this makes it to the vs-code release you will no longer need to switch multiple times.  The other problem that @forstermatth and @mtxr have, however, still remains.

**Comment by RMacfarlane** [comment] 2020-11-10 19:40
Closing, as this has now been fixed. A quick pick should be shown at the start of the create process to choose which folder to use

**Closed by RMacfarlane** 2020-11-10 19:40 UTC
Labels: ux
