### ISSUE TITLE
"Files" are empty even though commits are not empty

### ISSUE THREAD

**Issue by vegerot** [microsoft/vscode-pull-request-github#3003] opened 2021-09-23 17:46 UTC
Issue Type: <b>Bug</b>

I think this should show pretty clearly the issue:  

<img width="487" alt="image" src="https://user-images.githubusercontent.com/5297725/134558039-b1e97934-687b-4221-b7bf-5fbe6df9245e.png">

I try toggling "Files" multiple times, refreshing the PR, restarting VSCode, etc. nothing works.

I'd be glad to help debug this; if someone could give me some assistance on where to start

Relevant settings:

```jsonc
"githubPullRequests.remotes": [
  "walmart",
  "origin",
  "upstream",
  "github"
],
"github-enterprise.uri": "https://gecgithub01.walmart.com/",
"githubPullRequests.fileListLayout": "flat",
```

Extension version: 2021.9.32225
VS Code version: Code - Insiders 1.61.0-insider (5df296407363de70e9d7b455e1fcb004ceaa6b75, 2021-09-22T12:08:03.527Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|7, 9, 7|
|Memory (System)|32.00GB (0.14GB free)|
|Process Argv|. --crash-reporter-id bfe0ad98-0944-4b3f-85e6-50aa79288bed|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
vsc_aacf:30263846
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
pythonvsuse255:30319630
vscod805cf:30301675
pythonvspyt200:30323110
vsccppwt:30364496
pythonvssor306:30340298
bridge0708:30335490
pygetstartedt2:30353727
dockerwalkthru:30364418
bridge0723:30353136
pythonrunftest32:30365365
pythonf5test824:30361779
javagetstartedt:30350119
pythonvspyt187:30365360
pydsgst2:30361790
vssur157:30367808

```

</details>

**Comment by alexr00** [comment] 2021-09-27 09:26
Can you please reproduce the issue then share the following:

- Output from "GitHub Authentication"
- Output from "GitHub Pull Request"

Output can be found by running the command "Output: Focus on Output View"

**Comment by vegerot** [comment] 2021-09-27 16:12
Output from "Github Authentication":

```log
[Info  - 16:08:21.788] Reading sessions from keychain...
[Info  - 16:08:21.980] Getting sessions for all scopes...
[Info  - 16:08:21.981] Getting sessions for all scopes...
[Trace  - 16:08:21.982] Token acquired from secret storage.
[Info  - 16:08:21.982] Got stored sessions!
[Trace  - 16:08:21.982] Read the following session from the keychain with the following scopes: user:email
[Trace  - 16:08:21.982] Read the following session from the keychain with the following scopes: read:user
[Trace  - 16:08:21.982] Read the following session from the keychain with the following scopes: repo
[Trace  - 16:08:21.982] Read the following session from the keychain with the following scopes: repo
[Trace  - 16:08:21.982] Read the following session from the keychain with the following scopes: read:user,user:email,repo
[Info  - 16:08:21.982] Got 5 verified sessions.
[Info  - 16:08:22.0] Got 5 sessions for all scopes...
[Info  - 16:08:22.0] Got 5 sessions for all scopes...
[Info  - 16:08:22.5] Getting sessions for read:user...
[Info  - 16:08:22.5] Getting sessions for read:user,user:email,repo...
[Info  - 16:08:22.7] Got 1 sessions for read:user...
[Info  - 16:08:22.7] Got 1 sessions for read:user,repo,user:email...
```

Output from "GitHub Enterprise Authentication":

```log
[Info  - 16:08:21.789] Reading sessions from keychain...
[Trace  - 16:08:21.982] Token acquired from secret storage.
[Info  - 16:08:21.982] Got stored sessions!
[Trace  - 16:08:21.982] Read the following session from the keychain with the following scopes: read:user,user:email,repo
[Info  - 16:08:21.982] Got 1 verified sessions.
[Info  - 16:08:24.459] Getting sessions for read:user,user:email,repo...
[Info  - 16:08:24.459] Got 1 sessions for read:user,repo,user:email...
```

Output from "GitHub Pull Request":

```log
[Info] /Users/m0c0j7y/.ssh/config: ENOENT: no such file or directory, open '/Users/m0c0j7y/.ssh/config'
[Info] Registering git provider
[Info] Looking for git repository
[Info] Found 1 repositories during activation
[Info] Git repository found, initializing review manager and pr tree view.
[Info] Review> Validate state in progress
[Info] Review> Validating state...
[Info] No remote with name 'origin' found.
[Info] No remote with name 'upstream' found.
[Info] No remote with name 'github' found.
[Info] Found GitHub remote
[Info] Review> current branch CELISTS-14664-upgrade-typescript is associated with pull request #522
[Info] Review> Resolving pull request
[Info] Review> Fetching pull request data
[Info] Failed to get pull request review comments: Error: GraphQL error: Field 'path' doesn't exist on type 'PullRequestReviewThread'
GraphQL error: Field 'isOutdated' doesn't exist on type 'PullRequestReviewThread'
[Info] Failed to get pull request review comments: Error: GraphQL error: Field 'path' doesn't exist on type 'PullRequestReviewThread'
GraphQL error: Field 'isOutdated' doesn't exist on type 'PullRequestReviewThread'
[Info] Review> Error: GraphQL error: Field 'viewerViewedState' doesn't exist on type 'PullRequestChangedFile'
[Info] Review> register comments provider
[Info] Review> display pull request status bar indicator and refresh pull request tree view.
[Info] Review> using focus mode = true.
[Info] Review> state validation silent = true.
[Info] Review> PR show should show = false.
[Info] Failed to get pull request review comments: Error: GraphQL error: Field 'path' doesn't exist on type 'PullRequestReviewThread'
GraphQL error: Field 'isOutdated' doesn't exist on type 'PullRequestReviewThread'
[Info] Error: GraphQL error: Field 'viewerViewedState' doesn't exist on type 'PullRequestChangedFile'
[Info] Failed to get pull request review comments: Error: GraphQL error: Field 'path' doesn't exist on type 'PullRequestReviewThread'
GraphQL error: Field 'isOutdated' doesn't exist on type 'PullRequestReviewThread'
```

Console log from dev tools:

[vscode-app-1632759095809.log](https://github.com/microsoft/vscode-pull-request-github/files/7237811/vscode-app-1632759095809.log)

**Comment by alexr00** [comment] 2021-09-28 13:43
Thank you @vegerot! This is a duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/2772.

**Closed by alexr00** 2021-09-28 13:43 UTC
Labels: needs more info
