### ISSUE TITLE
Seeing duplicate review comments appearing

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-pull-request-github#2131] opened 2020-09-15 15:15 UTC
I am using the nightly PR extension in web selfhost and often comments appear multiple times:

![image](https://user-images.githubusercontent.com/900690/93229631-15f88980-f777-11ea-901e-5e66251dd381.png)

Looks like maybe comments are not disposed properly? Could also be a VSCode issue.

//cc @alexr00

**Comment by alexr00** [comment] 2020-09-16 13:41
@bpasero do you remember exactly where you opened that diff from (which view)?

**Comment by alexr00** [comment] 2020-09-16 13:47
Got it to repro.

**Comment by bpasero** [comment] 2020-09-16 14:30
Btw I think I see this in desktop too.

**Comment by alexr00** [comment] 2020-09-23 13:52
@bpasero I haven't changed anything, but now I cannot repro the issue. It happened pretty reliably before. Are you still seeing it?

**Comment by bpasero** [comment] 2020-09-23 14:27
True, seems better today. I will keep an eye open.

**Comment by bpasero** [comment] 2020-09-24 06:44
@alexr00 happened again today:

![image](https://user-images.githubusercontent.com/900690/94109968-1d3c2900-fe42-11ea-81b4-bbfc1fb4b84c.png)

**Comment by opethe1st** [comment] 2020-10-08 16:20
Just +1 that I see this happen a lot and it would be nice if it got fixed. Might try to take a stab at it for Hackokberfest :)

**Comment by egamma** [comment] 2020-10-09 07:27
Could have the same root cause. I also see duplicate comments in the Comments view

![image](https://user-images.githubusercontent.com/172399/95555092-8eb6d280-0a11-11eb-8f69-44af850c358d.png)

**Comment by alexr00** [comment] 2020-10-09 08:14
@RMacfarlane FYI in case you have any ideas here. I haven't gotten a consistent repro to figure out what's going on.

**Comment by opethe1st** [comment] 2020-10-20 13:43
I was able to reproduce this consistently by switching between these two views. 
- Created by me and
- All
<img width="366" alt="Screenshot 2020-10-20 at 14 15 17" src="https://user-images.githubusercontent.com/7265129/96591071-babe3780-12de-11eb-8585-c4210d5dac0e.png">

I created the gif below to illustrate how. I select the PR under the Created by me section, go the file I know has a comment. Go to a different file in that PR and then go the All section, select the same PR and go the file I know has a comment and then there is a duplicate. 

![githubprbug](https://user-images.githubusercontent.com/7265129/96593989-09b99c00-12e2-11eb-896c-d793022db301.gif)

P.S I really wanted to have a go at fixing this for Hackoberfest but I can't seem to get tests running locally. Cheers!

**Comment by alexr00** [comment] 2020-10-28 15:19
@RMacfarlane I found the problem, but as far as I can see I would need to rewrite the entire Pull Requests tree to fix it.

The issue arises from the fact that a PR can appear in the tree more than once (for example once in Created By Me and once in All). When this happens, a `PRNode` that handles adding comment threads to documents gets created for each time the PR appears in the tree. So when a file that appears in both `PRNode`s is opened, both `PRNode`s add a comment thread.  

On the surface this seemed like a simple fix: just only create one `PRNode`. However, the tree API (correctly) doesn't allow you to add the same item to the tree twice. Ok. Then we just separate the tree portion of `PRNode` from the comment handling portion. I started this, but it is several days of work, since the tree/comment/pr portions of all the tree elements are totally intertwined. 

If you see a better solution then that is a relief. I don't understand the commenting portion well enough to feel comfortable rewriting the Pull Requests tree quickly, so I've assigned to you.

**Comment by RikkiGibson** [comment] 2021-03-10 20:15
Is it possible that there's more than one cause for this? I am using only a single "instance" of a particular PR in the tree view, navigating around and commenting, and I'm finding the comments are duplicating

![image](https://user-images.githubusercontent.com/5833655/110691593-2e7fb480-819a-11eb-9d3b-09de782aa271.png)

In my case I am using the "review mode" where the comments are all pending until the review is submitted, which could be relevant.

**Comment by RikkiGibson** [comment] 2021-03-10 20:20
The duplicates are getting out of hand 😭

![duplicates](https://user-images.githubusercontent.com/5833655/110692199-f0cf5b80-819a-11eb-83d7-5040fa9706c4.gif)

**Comment by jakoss** [comment] 2021-03-23 19:31
Is there any way this is getting solved? For me this is a killer bug, making whole plugin practically unusable. Constant milestone pushback does not seem to be very promising

**Closed** 2021-04-12 16:41 UTC
Labels: bug
