### ISSUE TITLE
Not able to authenticate via Manually Provide Authentication Response

### ISSUE THREAD

**Issue by sk-gaurav** [microsoft/vscode-pull-request-github#2222] opened 2020-10-22 07:44 UTC
[

- Extension version: 0.15.0
- VSCode Version: 1.50.1
- OS: MAC OS Cataline 10.15.7

Steps to Reproduce:
I am trying to enter token for enterprise github via " Manually Provide Authentication Response"  but getting error as 
"Command 'GitHub Pull Requests: Manually Provide Authentication Response' resulted in an error (command 'auth.inputTokenCallback' not found)"
![Screenshot 2020-10-22 at 4 16 14 PM](https://user-images.githubusercontent.com/30268409/96861665-08bf7080-1482-11eb-866c-16a7273a2b02.png)

**Comment by RMacfarlane** [comment] 2020-10-29 15:54
I think this is actually a duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/2206 - this very of the extension is not successfully loading in VSCode 1.50.1 because of an API change there

**Closed by RMacfarlane** 2020-10-29 15:54 UTC

**Comment by sk-gaurav** [comment] 2020-10-29 16:07
> I think this is actually a duplicate of #2206 - this very of the extension is not successfully loading in VSCode 1.50.1 because of an API change there

Okay, thanks for info
