### ISSUE TITLE
"Unexpectedly low rate limit" affecting comment review

### ISSUE THREAD

**Issue by JustinGrote** [microsoft/vscode-pull-request-github#4712] opened 2023-04-10 22:20 UTC
Type: <b>Bug</b>

When doing comment review, keep hitting rate limits, making resolve conversation buttons/etc. an issue. Not sure why or what the rate limit is but there should at least be a dialog popup letting you know a rate limit was hit, rather than just getting flaky behavior in the app.

```
2023-04-10 15:12:59.610 [info] RateLimit> Unexpectedly low rate limit: 30
2023-04-10 15:12:59.610 [warning] RateLimit> REST Rate limit remaining: 27, /search/issues
2023-04-10 15:12:59.676 [info] RateLimit> Unexpectedly low rate limit: 30
2023-04-10 15:12:59.676 [warning] RateLimit> REST Rate limit remaining: 26, /search/issues
2023-04-10 15:13:03.523 [info] RateLimit> Unexpectedly low rate limit: 30
2023-04-10 15:13:03.523 [warning] RateLimit> REST Rate limit remaining: 25, /search/issues
2023-04-10 15:13:03.543 [info] RateLimit> Unexpectedly low rate limit: 30
2023-04-10 15:13:03.543 [warning] RateLimit> REST Rate limit remaining: 24, /search/issues
```

Extension version: 0.62.0
VS Code version: Code 1.77.1 (b7886d7461186a5eac768481578c1d7ca80e2d21, 2023-04-04T23:21:11.906Z)
OS version: Windows_NT x64 10.0.22624
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2600 Six-Core Processor             (12 x 3850)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.95GB (4.49GB free)|
|Process Argv|--file-uri file:///c%3A/Users/jgrote/Projects/vscode-powershell/extension-dev.code-workspace --crash-reporter-id 055c3f47-3375-4290-b452-9e04970046fe|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
nodejswelcome1:30587005
2e4cg342:30602488
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
vsccsb:30705552
functionswalk:30687959
pythonms35:30701012

```

</details>

**Comment by alexr00** [comment] 2023-04-14 09:47
That rate limit comes from GitHub, and it can be triggered by too many requests in a short period of time. This shouldn't happen with this extension and it indicates that we're not being careful enough with firing off requests.

Can you do the following to help me understand where we're firing too many requests to GitHub?
- Command: Developer: Set Log Level -> GitHub Pull Request -> Click the little double check mark next to "Debug"
- Next time you see the problem, can you share the last 5 minutes of output from GitHub Pull Request

**Comment by Danp2** [comment] 2023-04-20 17:24
I've been seeing this recent. Here's a log showing approx 20 mins of output --

[ghpr.log](https://github.com/microsoft/vscode-pull-request-github/files/11288862/ghpr.log)

**Comment by alexr00** [comment] 2023-04-21 13:33
@Danp2 thank you for the logs! The logs indicate that the problem is coming from the queries that we use in the "Pull Requests" view, which is odd because we only fetch 20 PRs at a time. Have you modified the setting `githubPullRequests.queries`?

**Comment by Danp2** [comment] 2023-04-21 13:43
@alexr00 No, I haven't made any changes. This is from `settings.json` --

```json
		"githubPullRequests.queries": [
			{
				"label": "Waiting For My Review",
				"query": "is:open review-requested:${user}"
			},
			{
				"label": "Assigned To Me",
				"query": "is:open assignee:${user}"
			},
			{
				"label": "Created By Me",
				"query": "is:open author:${user}"
			}
		]
```

**Comment by alexr00** [comment] 2023-04-21 14:07
Interesting. I'll see if any of the folks over in GitHub can help me understand what's going on. I though that rate limit of 30 was just for when they get flooded with requests, but based on your logs we are not flooding them.

**Comment by 1christianhall** [comment] 2023-04-22 11:51
Getting the same thing. Was wondering why the comments were not being refreshed. This has only recently been an issue as far as I recall.

**Comment by alexr00** [comment] 2023-04-24 12:54
Further investigation shows that these log lines are a red herring:
```
2023-04-10 15:12:59.610 [info] RateLimit> Unexpectedly low rate limit: 30
2023-04-10 15:12:59.610 [warning] RateLimit> REST Rate limit remaining: 27, /search/issues
```

The REST rate limit for `/search` is just super low. It should only be an issue for searching for PRs to show in the Pull Requests view. This rate limit does not appear to apply to anything else, so making and resolving comments should not be affected. I am updating the logging to reflect this.

If you're seeing issues with making and resolving comments, can you reproduce the issue and share debug level logs (https://github.com/microsoft/vscode-pull-request-github/issues/4712#issuecomment-1508246999)? 

Comments for checked out PRs should be refreshed every 2 minutes.

**Closed** 2023-12-12 16:08 UTC
Labels: info-needed
