### ISSUE TITLE
Assign a Pull Request

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode-pull-request-github#1754] opened 2020-05-05 03:09 UTC
I would like the ability to assign a PR to a person from VS Code.  I can do this from the browser, it seems like its missing from the tool (Reviewers is there).

**Comment by RMacfarlane** [comment] 2020-05-05 16:42
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/1063

**Closed by RMacfarlane** 2020-05-05 16:42 UTC
