### ISSUE TITLE
Duplicate Comments

### ISSUE THREAD

**Issue by Icantjuddle** [microsoft/vscode-pull-request-github#1341] opened 2019-09-17 00:35 UTC
Everytime I reload the PR or open a file again, another copy of a comment is added to each comment thread giving many duplicates. 

- Extension version: 0.11.1
- VSCode Version: 1.38.0
- OS:Ubuntu 16.04
- Github Enterprise: 1.17.3
Steps to Reproduce:

1.Click on file in sidebar to bring up diff.
2.Close diff
3. Open diff again

**Comment by RMacfarlane** [comment] 2019-09-17 18:00
Thanks for reporting this, taking a look into this now. This is a duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/1337 so let's track the problem there.

**Closed by RMacfarlane** 2019-09-17 18:00 UTC
