### ISSUE TITLE
some UI / editing features that already exist in pull requests should also be available in issues 

### ISSUE THREAD

**Issue by maddes8cht** [microsoft/vscode-pull-request-github#4581] opened 2023-02-28 15:36 UTC
In "Pull Requests" you can use a feature-rich interface directly inside VSCode to view pull requests, write follow up comments etc.

In Issues I only get a small popup window and a link to leave VSCode.

I would really like to be able to edit existing issues within VScode, as well as view and reply to follow up comments. 

The "Pull Requests" part of the plugin is considerably more extensive than the "Issues" part.

For Issues there is no comparable functionality as for Pull Requests yet.

There was a feature request for this, #3433, which was a repeat of an already closed #3428 where the requester provided additional information, and #4023, which was marked as a duplicate of #3433.

All of these have been closed, without even mentioning that there is no intention of giving issues as much love as pull requests.

**Comment by grimsteel** [comment] 2023-02-28 23:01
#3433 was never closed

**Comment by alexr00** [comment] 2023-03-06 14:31
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/3433

**Closed by alexr00** 2023-03-06 14:31 UTC
