### ISSUE TITLE
PR creation view broken

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-pull-request-github#4174] opened 2022-11-09 18:48 UTC
Type: <b>Bug</b>

It has been broken for me for a few days, the view is blank and got following errors in dev tools

```
webview-create-pr-view.js:359 TypeError: Cannot read properties of undefined (reading 'availableBaseRemotes')
    at get initialized [as initialized] (webview-create-pr-view.js:377:19653)
    at webview-create-pr-view.js:377:54232
    at Root (webview-create-pr-view.js:377:57061)
    at oh (webview-create-pr-view.js:359:51845)
    at Rj (webview-create-pr-view.js:361:8389)
    at Qj (webview-create-pr-view.js:361:928)
    at Kj (webview-create-pr-view.js:361:831)
    at yj (webview-create-pr-view.js:359:88617)
    at Ig (webview-create-pr-view.js:359:85303)
    at bk (webview-create-pr-view.js:361:16511)
```

Extension version: 0.55.2022110809
VS Code version: Code - Insiders 1.74.0-insider (Universal) (96db0b339360bc72d27d869d81a557540ad5f800, 2022-11-09T05:21:15.464Z)
OS version: Darwin x64 22.1.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 3, 4|
|Memory (System)|32.00GB (0.04GB free)|
|Process Argv|--enable-proposed-api ms-vscode.vscode-notebook-history --enable-proposed-api vscode.notebook-editing --enable-proposed-api vscode.vscode-test-resolver --enable-proposed-api donjayamanne.kusto --enable-proposed-api donjayamanne.jupyterpowertools --enable-proposed-api rebornix.better-jupyter-errors --enable-proposed-api rchiodo.jupyter-tools --crash-reporter-id 1a907bbd-fa02-4595-81e0-63e1648afb31|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
vsc_aa:30263845
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30404738
cppdebug:30492333
vscaat:30438846
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pylantcb52:30590116
vsccc:30564266
pyindex848:30577858
nodejswelcome1:30587009
gswce1:30602633
34cci188:30599831
pyind779:30600159
dbltrim-noruby:30604474

```

</details>

**Comment by alexr00** [comment] 2022-11-10 13:12
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/4172

**Closed by alexr00** 2022-11-10 13:12 UTC
Labels: bug, important
