### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by HusseinAliOfficial** [microsoft/vscode-pull-request-github#3222] opened 2022-01-02 09:46 UTC
- Issue Type: `Performance`
- Extension Name: `vscode-pull-request-github`
- Extension Version: `0.34.2`
- OS Version: `Linux x64 5.11.0-43-generic`
- VS Code version: `1.63.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/tmp/GitHub.vscode-pull-request-github-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by HusseinAliOfficial** [comment] 2022-01-02 09:47
Issue Report V1.0

**Comment by alexr00** [comment] 2022-01-03 10:55
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/841

**Closed by alexr00** 2022-01-03 10:55 UTC
