### ISSUE TITLE
Tree gets collapsed when you checkout

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#793] opened 2019-01-07 19:19 UTC
ext version: 1.7.1

Repro:

1. Checkout branch `a`
2. Checkout branch `b`

I'd prefer nothing to be collapsed but it certainly shouldn't collapse the PR being checked out. I'm guessing this is related to checking the text content of the tree.

Before:

![image](https://user-images.githubusercontent.com/2193314/50788359-09b3ed80-126e-11e9-8ebb-9a4c41d4dbc7.png)

After:

![image](https://user-images.githubusercontent.com/2193314/50788370-0f113800-126e-11e9-9dd2-72fc16b5fc20.png)

**Comment by RMacfarlane** [comment] 2019-10-10 17:09
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/238

**Closed by RMacfarlane** 2019-10-10 17:09 UTC
