### ISSUE TITLE
Showing participants is not helpful if there is only 1 participant

### ISSUE THREAD

**Issue by ramya-rao-a** [microsoft/vscode-pull-request-github#428] opened 2018-09-11 17:59 UTC
![image](https://user-images.githubusercontent.com/16890566/45378238-be384e00-b5b1-11e8-8cde-e7f1b7779382.png)

**Comment by alexr00** [comment] 2020-11-10 13:46
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/169

**Closed by alexr00** 2020-11-10 13:46 UTC
Labels: upstream/vscode, ux
