### ISSUE TITLE
No longer works with Github Enterprise

### ISSUE THREAD

**Issue by Velyks** [microsoft/vscode-pull-request-github#1850] opened 2020-06-03 10:31 UTC
Issue Type: <b>Bug</b>

I have a repo with ssh remotes to GHE, yet the plugin still wants me to sign into github.com and now throws errors when trying to fetch from remotes.

Fetching pull requests for remote 'upstream' failed, please check if the url git@git.mycompany.com:company/repo.git is valid.

Extension version: 0.16.0
VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:33:47.663Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.21GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by MadaraUchiha** [comment] 2020-06-07 15:35
Possible duplicate of #1793. I'm waiting for a fix or guidance on how to fix it as well.

For now, as a workaround, you can downgrade back to 0.15.

**Comment by RMacfarlane** [comment] 2020-06-11 18:03
Hey @Velyks, this is a duplicate of #1793. GHE support was discontinued with version 0.16.0 of the extension, please see the wiki: https://github.com/Microsoft/vscode-pull-request-github/wiki#2-is-github-enterprise-supported

I will be doing exploratory work on how we can reenable this with the changes we have made to authentication, but for now the workaround is to explicitly downgrade to version 0.15.0. I'm very sorry about this.

**Closed by RMacfarlane** 2020-06-11 18:03 UTC

**Comment by philipcraig** [comment] 2020-07-15 13:51
Hi @RMacfarlane is there an open issue that we can track about re-enabling GitHub Enterprise support?
