### ISSUE TITLE
Disable Approve button when a user is viewing their own PR

### ISSUE THREAD

**Issue by igbominadeveloper** [microsoft/vscode-pull-request-github#1786] opened 2020-05-11 10:53 UTC
- Extension version: 0.16.0
- VSCode Version: 1.45.0
- OS: Windows

Steps to Reproduce:

1. View a PR that you submitted
2. The Approve Button is active on the PR

Screenshot:
![Annotation 2020-05-11 115031](https://user-images.githubusercontent.com/12516195/81554017-f642f600-937d-11ea-81cf-e97a15c9c19f.png)

**Comment by RMacfarlane** [comment] 2020-05-11 15:53
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/888

**Closed by RMacfarlane** 2020-05-11 15:53 UTC
