### ISSUE TITLE
Description buttons get very fall when header wraps

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode-pull-request-github#884] opened 2019-01-30 16:38 UTC
https://github.com/Microsoft/vscode/issues/67509

![image](https://user-images.githubusercontent.com/2193314/51996803-5a33fa80-246a-11e9-90e5-8ea67ef897c3.png)

**Comment by Tyriar** [comment] 2019-01-30 17:02
Variant on this:

![image](https://user-images.githubusercontent.com/2193314/51998607-d2e88600-246d-11e9-8098-a07664cbd3df.png)

**Comment by RMacfarlane** [comment] 2019-01-30 19:40
Duplicate of https://github.com/Microsoft/vscode-pull-request-github/issues/850

**Closed by RMacfarlane** 2019-01-30 19:40 UTC
