### ISSUE TITLE
Expand all comments AND expand all unresolved comments

### ISSUE THREAD

**Issue by eliasyishak** [microsoft/vscode-pull-request-github#4418] opened 2023-01-19 18:14 UTC
Hi, this is a great new feature and I have been loving how easily it is integrated! Just one idea, currently we have commands from the command palette to `expand all comments` and `collapse all comments`. And once we view these comments, we can resolve them from within IDE (whoa!)

It would be great if we can have an additional command in the palette that says `expand all unresolved comments`. This would save tons of time for developers!

<img width="533" alt="image" src="https://user-images.githubusercontent.com/42216813/213526794-8e1349e9-cfc5-484f-86bc-234176fb1401.png">

**Comment by alexr00** [comment] 2023-01-24 14:37
Duplicate of https://github.com/microsoft/vscode/issues/169928

**Closed** 2023-01-24 14:37 UTC
Labels: duplicate
