### ISSUE TITLE
Add Issues Description view

### ISSUE THREAD

**Issue by LBF38** [microsoft/vscode-pull-request-github#4945] opened 2023-06-23 10:31 UTC
_No similar issues found on the topic. Please feel free to comment or edit this message if it's a duplicate._

## Feature: Add Issues Description View
The idea is to reproduce the PR Description that we can easily access through the extension but with the Issues Description.
Therefore, it will allow a better integration and seemless experience as we don't necessary need to jump between the browser and VS Code.

Here is a screenshot of the PR Description in VS Code:
![image](https://github.com/microsoft/vscode-pull-request-github/assets/96347823/5b779343-a16f-4ef4-95f5-88215b392c95)

It would be great to have the same feature for issues.

**Comment by alexr00** [comment] 2023-06-28 10:57
duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/3433

**Closed by alexr00** 2023-06-28 10:57 UTC
