### ISSUE TITLE
Cannot login to github when using two browsers

### ISSUE THREAD

**Issue by alexanderkjeldaas** [microsoft/vscode-pull-request-github#1811] opened 2020-05-15 13:27 UTC
- Extension version: 0.16.0
- VSCode Version: 1.45.1
- OS: X

Steps to Reproduce:

1. Open URLs by default in Chrome
2. Be logged in on github in Firefox
3. Get vscode to open the login url
4. It opens in Chrome
5. Copy the URL to Firefox to continue the login process
6. Error 801 is given by github

<img width="510" alt="Screenshot 2020-05-15 at 15 26 30" src="https://user-images.githubusercontent.com/339369/82055228-7a6be500-96c0-11ea-8b01-c64f69805dbf.png">

It seems that github does not like the URL being opened twice.  It would be great if VSCode could show the URL so it could be copied before opening the browser.  Or have an alternative command that just shows the URL.

**Comment by RMacfarlane** [comment] 2020-11-09 18:24
Closing as a duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/1221

**Closed by RMacfarlane** 2020-11-09 18:24 UTC
Labels: authentication
