### ISSUE TITLE
Support for CI in description

### ISSUE THREAD

**Issue by PierreMarchand20** [microsoft/vscode-pull-request-github#2010] opened 2020-07-17 12:22 UTC
I am not sure if it is a feature request or a bug, but when I look at the description of the pull request:
<img width="475" alt="image" src="https://user-images.githubusercontent.com/15056323/87785604-bcd4ae00-c838-11ea-9a22-25622cc79a3f.png">

It is said that there is no conflict and that I could merge. But on GitHub:
<img width="925" alt="image" src="https://user-images.githubusercontent.com/15056323/87785653-d4139b80-c838-11ea-9d48-da5f12c2fc61.png">

I still have checks running (travis tests). It would be nice to see them directly in the description of the pull request.

**Comment by RMacfarlane** [comment] 2020-08-12 17:52
This looks like a duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/457, let's track it there

**Closed by RMacfarlane** 2020-08-12 17:52 UTC
