### ISSUE TITLE
Spurious "There are updates available for this pull request" notifs

### ISSUE THREAD

**Issue by asktree** [microsoft/vscode-pull-request-github#2829] opened 2021-07-07 21:09 UTC
- Extension version: 0.27.1

While working I regularly get spurious "There are updates for this pull request" notifications. No comments or anything are taking place. It could be mistaking Vercel's deployment notifications on the PR as updates, but certainly no sourcecode is changing. Sorry I haven't troubleshot this more. However, at the very least, an option to disable these notifications would be nice.

**Comment by alexr00** [comment] 2021-07-08 16:03
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/2628, which is fixed in 0.28.0 (which went out a few hours ago) and includes an option so disable that notification.

**Closed by alexr00** 2021-07-08 16:03 UTC
