### ISSUE TITLE
Inconsistent textboxes

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#299] opened 2018-08-28 18:20 UTC
https://github.com/Microsoft/vscode/issues/57301

One is monospace, the other isn't.

<img width="404" alt="screen shot 2018-08-28 at 11 19 35 am" src="https://user-images.githubusercontent.com/2193314/44742263-47308f00-aab4-11e8-8895-f49fc9e7d0fb.png">
<img width="247" alt="screen shot 2018-08-28 at 11 19 57 am" src="https://user-images.githubusercontent.com/2193314/44742279-50216080-aab4-11e8-99ed-97f382ef968c.png">

**Comment by alexr00** [comment] 2022-12-14 14:24
IIRC this was by design with the reasoning being that when leaving a comment in a file, you're more likely to want to write code and have a monospace font.

**Comment by Tyriar** [comment] 2022-12-14 15:11
Shouldn't we align with github.com here? If we have 2 different fonts, not only are we inconsistent with github but we're inconsistent in our own product.

**Comment by alexr00** [comment] 2023-12-18 16:25
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/167

**Closed by alexr00** 2023-12-18 16:25 UTC
Labels: feature-request, ux
