### ISSUE TITLE
Cannot display all open review requests

### ISSUE THREAD

**Issue by dolatabadi** [microsoft/vscode-pull-request-github#2235] opened 2020-10-27 16:47 UTC
- Extension version: 0.20.1
- VSCode Version: 1.50.1
- OS: MacOS

Steps to Reproduce:

1. Click `Waiting for my review`
2. Cannot see all the requests which are visible here: https://github.com/pulls/review-requested

Already tried to create a new query `is:open is:pr review-requested:${user} archived:false` but still cannot display all open review requests

**Comment by RMacfarlane** [comment] 2020-11-11 15:55
@dolatabadi This may be a duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/1025, do the pull requests that are missing show "UNKNOWN" for the source repo?

**Comment by dolatabadi** [comment] 2020-11-11 16:06
@RMacfarlane 
No, they don't even show up on the list at all. I have to mention that I am trying to view a list of open review requests for my account and not a particular repo. So If I go here https://github.com/pulls/review-requested I can see bunch of requests for different repos.

**Comment by RMacfarlane** [comment] 2020-11-11 18:25
Ah, I see! This is currently not supported in the extension, existing feature request: https://github.com/microsoft/vscode-pull-request-github/issues/1458

**Closed by RMacfarlane** 2020-11-11 18:25 UTC
Labels: needs more info
