### ISSUE TITLE
No assignee suggestions on PR page

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-pull-request-github#2213] opened 2020-10-16 19:08 UTC
I would like to have the suggestion popup when typing `@` in a comment on the PR description page, if possible, but I don't see it.

**Comment by RMacfarlane** [comment] 2020-10-20 21:47
Closing as a duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/1206

**Closed by RMacfarlane** 2020-10-20 21:47 UTC
