### ISSUE TITLE
Issues section stuck in 'Loading...' in an empty workspace

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-pull-request-github#2614] opened 2021-03-24 15:47 UTC
Open the GHPRI view container in an empty workspace.
The Issues section is stuck in the 'Loading...' state, see below

![image](https://user-images.githubusercontent.com/172399/112340112-8cdf8380-8cc0-11eb-9280-92795434c9d2.png)

**Comment by RMacfarlane** [comment] 2021-03-24 15:48
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/2581

**Closed by RMacfarlane** 2021-03-24 15:48 UTC
