### ISSUE TITLE
Wrong diff is shown

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode-pull-request-github#369] opened 2018-09-06 13:30 UTC
There's a line missing in the file fetched from GitHub:

<img width="1440" alt="screen shot 2018-09-06 at 15 29 21" src="https://user-images.githubusercontent.com/22350/45160409-aba4ca00-b1e9-11e8-800b-c5b3cd97931d.png">

<img width="1427" alt="screen shot 2018-09-06 at 15 29 47" src="https://user-images.githubusercontent.com/22350/45160443-c414e480-b1e9-11e8-896f-39b7b0c50f05.png">

**Comment by RMacfarlane** [comment] 2018-09-06 14:50
Duplicate of https://github.com/Microsoft/vscode-pull-request-github/issues/361

**Closed by RMacfarlane** 2018-09-06 14:50 UTC
