### ISSUE TITLE
There are updates available for this branch appears when you push to remote

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode-pull-request-github#312] opened 2018-08-28 21:31 UTC
Repro:

1. Checkout PR
2. Make a commit
3. `git push` in terminal

This will appear despite you being on the latest:

![image](https://user-images.githubusercontent.com/2193314/44752126-fd08d700-aace-11e8-8e58-7bbe61449eed.png)

**Comment by RMacfarlane** [comment] 2018-08-29 00:09
Closing as duplicate of https://github.com/Microsoft/vscode-pull-request-github/issues/287

**Closed by RMacfarlane** 2018-08-29 00:09 UTC
Labels: bug
