### ISSUE TITLE
Sign In popup never appear

### ISSUE THREAD

**Issue by fabien-kerinec** [Microsoft/vscode-pull-request-github#409] opened 2018-09-11 10:55 UTC
- Extension version:0.1.2
- VSCode Version:1.27.1
- OS:Ubuntu 18.04.1 LTS

Steps to Reproduce:

1.Install the extension (with marketplace or vsix)
2.Popup never appear

**Comment by jayflaherty75** [comment] 2018-09-11 13:18
Same here but on Debian Sid.

Steps to Reproduce:

1. Upgrade to 1.27.1
2. Install from marketplace
3. Restart VS Code
4. Open repo (my last repo opens automatically, could be important?)
5. Switch to SCM view
6. "GitHub Pull Request" treeview does not appear.

**Comment by fabien-kerinec** [comment] 2018-09-11 13:32
i try also : 
to get a new window and open a repo
to open project width a worksapce

I see on another issue (for those who have a login error) to do "sign in with github" in command pannel. but it doesn't seems to exist

**Comment by trivedir** [comment] 2018-09-11 21:41
Having the same issue on Windows 10.
Upon clicking on the "Sign In" button on the prompt, nothing happens. 
clicking on the "Sign in to <domain>" button in the bottom bar just makes it disappear with no other action.

**Comment by Zoe7** [comment] 2018-09-21 12:33
Similar issue here on Windows 10.
I installed the extension and signed in successfully, but after that the treeview isn't shown. I can checkout PRs, but I can't enter the review mode since it requires to see the treeview 😞 
I tried the obvious windows "turn it on and off" again with no success.

**Comment by fabien-kerinec** [comment] 2018-09-21 12:38
here i can't login at all. I mean the extention doesn't change anything on my VSC, no connection popup or anything.

**Comment by jayflaherty75** [comment] 2018-09-22 14:31
UPDATE: I installed this while working on a very large project.  After switching to a new project with few files, the dialog popped up asking me to sign in to GitHub and, so far, appears to be working.

I have another ticket open with VS Code for performance issues on large projects.  Perhaps this is related (at least in my case)?

**Comment by fabien-kerinec** [comment] 2018-09-22 14:45
I'm working on large project to.
I tried to start a new repo with new files and it works

After that i try to launch my app folder (of the large app) and it didn't work.
I realise that the plugin is working with only one folder open by window and i was opening a global folder for back and front part of the app)

So seems to be fix for me

**Comment by RMacfarlane** [comment] 2018-09-24 16:13
Closing this since the issue seems resolved. Thanks!

**Closed by RMacfarlane** 2018-09-24 16:13 UTC
Labels: bug, linux
