### ISSUE TITLE
Hitting "API rate limit exceeded" for most PR listing operations

### ISSUE THREAD

**Issue by IgorMinar** [microsoft/vscode-pull-request-github#745] opened 2018-12-09 17:29 UTC
- Extension version: 0.2.3
- VSCode Version: 1.29.1
- OS: Mac OS 10.14.1

Steps to Reproduce:

1. checkout angular/angular
2. try to expand any of the PR categories under Source Control / Github Pull Requests  (`Assigned To Me`, `Awaiting For My Review`, `Created By Me`)

What I get is:
<img width="503" alt="screen shot 2018-12-09 at 9 24 16 am" src="https://user-images.githubusercontent.com/216296/49700530-abbfb780-fb94-11e8-8b64-473797385f5f.png">

And the listing expands with 0 pull requests:
<img width="373" alt="screen shot 2018-12-09 at 9 32 46 am" src="https://user-images.githubusercontent.com/216296/49700582-6ea7f500-fb95-11e8-82c7-426d8afd16d3.png">

Surprisingly, if I try to expand the `All` category, the list does expand:

<img width="359" alt="screen shot 2018-12-09 at 9 32 25 am" src="https://user-images.githubusercontent.com/216296/49700575-5b952500-fb95-11e8-8ea4-17c70719a7da.png">

**Comment by RMacfarlane** [comment] 2018-12-10 19:16
@IgorMinar 	Can you run `git remote -v` to see how many remotes you have? For these categories, we search the issues of each remote until we have a page size of results, so I'm wondering if that's the problem

**Comment by RMacfarlane** [comment] 2018-12-11 00:30
Thanks for the info!

To clarify, we're not searching remotes, we're searching the issues in remotes. We are using the github api for search, since the api for listing PRs doesn't support querying by user

**Comment by IgorMinar** [comment] 2018-12-11 15:01
@RMacfarlane is this because you don't know what is the upstream/main repo with the issues?

could you rely on conventions like "origin" and "upstream" and search just those? And if users want other remotes to be search they'd have to explicitly configure the extension to do so.

**Comment by IgorMinar** [comment] 2018-12-11 15:10
oh no. I've just hit the rate limit even on my clone with few remotes because the extension refreshes any of the expanded lists every time I switch branches, pull from remote and update my current branch, or even simply rebase or make a commit.

**Comment by RMacfarlane** [comment] 2018-12-11 17:47
@IgorMinar 	Yeah, I have a PR open with the mitigation you suggest, searching for "upstream" and "origin" remotes and using those first. I think having clearer UI about what remote is being used and a setting to configure it would be good to add.

**Comment by RMacfarlane** [comment] 2020-11-09 19:07
Closing since this should be fixed in the latest version of the extension, we do only search for "upstream" and "origin" remotes by default now

**Closed by RMacfarlane** 2020-11-09 19:07 UTC
Labels: bug

**Comment by AngelOnFira** [comment] 2021-07-05 16:53
I just started getting `API rate limit exceeded` errors today while using github-cli today. The problem is, I've never had this before, and I just installed `vscode-pull-request-github` today. Is there some way for me to check how frequently this plugin is making requests to the API? It would be nice to try and diagnose why this might still be occuring.
