### ISSUE TITLE
Completion of merge action is not immediately obvious when done from sidebar

### ISSUE THREAD

**Issue by burkeholland** [microsoft/vscode-pull-request-github#2745] opened 2021-05-21 17:47 UTC
When completing a merge, it's not obvious that the action is finished. You have to have the sidebar open and notice that the text changes. It took me about 15 seconds to realize that the operation was successful.

Is it possible to have a notification in the instance that the merge is performed from the sidebar and not description?

![image](https://user-images.githubusercontent.com/686963/119177955-a8ea7180-ba32-11eb-8a3a-93295d4e1c06.png)

**Comment by alexr00** [comment] 2021-06-18 14:29
Generally we try to provide UI feedback in the same place the user action took place (when possible). Because of that, I don't think a notification is a good fit. What if I added a "merged" icon? This is kind of like what GitHub.com does.

![image](https://user-images.githubusercontent.com/38270282/122576730-46e15400-d052-11eb-9d1e-bccf9f87b7bc.png)

**Comment by connor4312** [comment] 2021-06-30 18:30
This... works, and is slightly better, but I still see the confusion. Here's one suggestion that might be a little easier to see: keeping the "merge" button to avoid changing "contexts", but updating the message. I think 95% of the time people want to delete the branch after merging, so that could become a more prominent action as well:

Before merging (for reference):

![image](https://user-images.githubusercontent.com/2230985/124012948-90a53500-d996-11eb-9a27-9c08e8ce8769.png)

After merge:

![image](https://user-images.githubusercontent.com/2230985/124012902-83884600-d996-11eb-8361-7fd1023a92b7.png)

cc @misolori for thoughts

**Comment by misolori** [comment] 2021-06-30 20:47
I like the suggestion, would also add the making the `Delete Branch` button a secondary button would help make the changes a little more obvious.

**Comment by alexr00** [comment] 2021-07-01 08:44
Great suggestions, I will make these changes!

**Closed** 2021-07-08 14:26 UTC
Labels: feature-request, ghcs-scenario-found

**Comment by stuartleeks** [comment] 2021-07-28 14:46
Confirmed merged indicators and Delete Branch button on nightly build v2021.7.39424
