### ISSUE TITLE
PR view was blank

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode-pull-request-github#4164] opened 2022-11-07 19:23 UTC
Not sure how I got here but felt like I should document it 

<img width="792" alt="image" src="https://user-images.githubusercontent.com/4544166/200396613-143976b5-52fd-469d-b073-68222ea34d75.png">

**Comment by lramos15** [comment] 2022-11-07 19:24
Reloading didn't fix this, this PR had to be made on github.com

**Comment by roblourens** [comment] 2022-11-08 23:36
Same

**Comment by alexr00** [comment] 2022-11-10 13:46
This is the Create view? Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/4174

**Closed by alexr00** 2022-11-10 13:46 UTC
