### ISSUE TITLE
Unable to sign in to github - TypeError: t.message.contains is not a function

### ISSUE THREAD

**Issue by vishnurpiper** [microsoft/vscode-pull-request-github#3745] opened 2022-07-20 16:58 UTC
- Extension version: 0.47.2022072010 (pre-release)
- VSCode Version:1.69.2
- OS:Windows 10 (running WSL)

Steps to Reproduce:
1. Launch VSCode
2. Click on the github pull requests extension
3. Click Sign In

This appears to be very similar to https://github.com/microsoft/vscode-pull-request-github/pull/3708 which is why I pulled the pre release version. Still running into the same issue , error stack below: 

[Info] TypeError: t.message.contains is not a function
	at _1.setCurrentUser (/home/<user>/.vscode-server/extensions/github.vscode-pull-request-github-0.47.2022072010/dist/extension.js:1136:16985)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async _1.createHub (/home/<user>/.vscode-server/extensions/github.vscode-pull-request-github-0.47.2022072010/dist/extension.js:1136:18318)
	at async _1.login (/home/<user>/.vscode-server/extensions/github.vscode-pull-request-github-0.47.2022072010/dist/extension.js:1136:15988)
	at async Em.authenticate (/home/<user>/.vscode-server/extensions/github.vscode-pull-request-github-0.47.2022072010/dist/extension.js:1253:18203)
	at async /home/<user>/.vscode-server/extensions/github.vscode-pull-request-github-0.47.2022072010/dist/extension.js:1253:6647
	at async o._executeContributedCommand (/home/<user>/.vscode-server/bin/3b889b090b5ad5793f524b5d1d39fda662b96a2a/out/vs/workbench/api/node/extensionHostProcess.js:85:62863)

**Comment by alexr00** [comment] 2022-07-27 08:06
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/3692, which was re-fixed in pre-release yesterday.

**Closed by alexr00** 2022-07-27 08:06 UTC
