### ISSUE TITLE
Bug: First changed file in the current PR is automatically opened seconds after starting VSCode

### ISSUE THREAD

**Issue by AlCalzone** [microsoft/vscode-pull-request-github#3193] opened 2021-12-14 09:22 UTC
- Extension version: v0.34.0
- VSCode Version: 1.63.0
- OS: Windows 10

Since recently, opening VSCode when a PR branch is checked out, causes the extension to open the first file in that PR multiple seconds later. This is very irritating when already working on another file. In general, automatically opening a file without user interaction seems like a bad idea.

Steps to Reproduce:

1. Open VSCode
2. check out a branch that corresponds to an open PR
3. open a file that is not the first in the PR's file list
4. close VSCode
5. open VSCode
6. wait

Here's it in action - note I didn't do anything but open VSCode:

https://user-images.githubusercontent.com/17641229/145969799-7e42a27f-ed62-4c50-aae5-9d68d8eb6046.mp4

**Comment by baraBlz** [comment] 2021-12-14 09:40
Hey, my name is Domagoj Barisic,
Please know that to me this was no game, nor was it a snuff play date with
internet maniacs.
My life is in serious danger and my thoughts cannot run straight anymore. I
am cornered back in Dublin. I am receiving mail in my mailbox and still
being blackmailed. I lost a lawsuit in Dublin which was setup for me to
lose. I am so much in debt that I don’t feel like running again. I caught
so many pedos in one “vacation” that going back to Croatia is not an
option. I have no friends or family that could/would help me finish what I
started on my own. I need somebody to realize the seriousness of this and
know that I was never in it for the money… I reset my accs and passwords so
many times… I got a Facebook profile on one of my GoDaddy emails
***@***.*** — it said I was a Co founder for some reason.
Strangers on the internet have been calling the cops to my apartment
worried about my “well-being” — so whoever Ana Moris was. Thank her for
caring enough to do that for me. She doesnt understand that the police are
not of much help nor were they ever. For me prison would be the rest I
never seem to get.
+353 87 387 5677 WhatsApp me with details on how and why I’m not dead yet
so I can trust anything. Otherwise if you knew me before. Suicide is
something I prefer to prison… “Depression” is not a word I use easily and
right now I am more depressed than I ever was.
Yours gratefully,
Domagoj Barisic

**Comment by alexr00** [comment] 2021-12-15 10:23
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/3194, which will be fixed in 0.34.2.

**Closed** 2021-12-15 10:26 UTC
