### ISSUE TITLE
Can not login with Microsoft Edge

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-pull-request-github#1955] opened 2020-07-01 09:38 UTC
Refs: #1937

Windows.
Put MS Edge as your default browser
Install PR nightly extension.
Trigger the login flow -> everytime I get the following error message.
When I change to use Chrome everything works fine.

![Screenshot 2020-07-01 at 11 31 22](https://user-images.githubusercontent.com/1926584/86228989-622c2880-bb8f-11ea-81e5-9b9f3786a5aa.png)

**Comment by RMacfarlane** [comment] 2020-11-09 18:22
Closing as a duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/1221

**Closed by RMacfarlane** 2020-11-09 18:22 UTC
