### ISSUE TITLE
Disable "Request changes" and "Approve" buttons for authored PRs

### ISSUE THREAD

**Issue by kuychaco** [microsoft/vscode-pull-request-github#1184] opened 2019-05-30 05:42 UTC
- Extension version: 0.7.0 (0248f28)
- VSCode Version: 1.35.0-insider
- OS: macOS High Sierra

<img width="352" alt="Fullscreen_5_29_19__10_39_PM" src="https://user-images.githubusercontent.com/7910250/58611065-ba914800-8262-11e9-85f1-5d029fc3ef4d.png">

PR authors cannot request changes or approve their own PRs. We should disable these buttons, to mirror dotcom's UX

Steps to Reproduce: 

1. Click "Request changes" or "Approve"

Expected: The buttons are disabled
Actual: Get an "Unprocessable Entity" error

**Comment by RMacfarlane** [comment] 2019-07-02 17:41
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/888

**Closed by RMacfarlane** 2019-07-02 17:41 UTC
