### ISSUE TITLE
Feature: make the PR view functional even without PR

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-pull-request-github#3215] opened 2021-12-30 09:23 UTC
One of the best features for me is this view:

![image](https://user-images.githubusercontent.com/900690/147738601-0a75799e-4328-4f94-97b5-a418bfaa9ff9.png)

As it gives me a diff from my branch to `main` while still allowing me to make changes, wonderful 👏 

How about enabling this view even when I did not create a PR for the branch yet? Something like a "Untitled PR" scenario where I see the changes and I can open a PR but I don't have to do that. This view would be incredibly useful for me to review changes from my branch to `main`. And on top of that it would maybe be a nice way for new-comers to explore how to open a new PR from a branch?

I know @alexdima has a similar extension only for the part of seeing the diff (not sure if you can edit though): https://marketplace.visualstudio.com/items?itemName=alexdima.git-branch

**Comment by alexr00** [comment] 2021-12-30 10:34
@bpasero we have a "Compare Changes" view that shows when you are in the process of creating a PR. Does this do what you're looking for?

![image](https://user-images.githubusercontent.com/38270282/147744023-7c162cc5-325d-43a1-a226-6e5bfd4c5095.png)

**Comment by bpasero** [comment] 2021-12-30 10:37
@alexr00 my understanding is that I first have to run "Create PR" command right? To get this view:

![image](https://user-images.githubusercontent.com/900690/147744261-85267419-1904-4b71-89c5-279a06df4e0b.png)

And the right hand side does not seem to be editable?

**Comment by alexr00** [comment] 2021-12-30 10:49
Correct, you must first run the "Create PR" command, but you don't need to submit the PR. 

It does seem that the right isn't editable. I should be able to fix that though.

**Comment by bpasero** [comment] 2021-12-30 11:00
Is there any harm in just always being in that mode even without running this command?

**Comment by alexr00** [comment] 2021-12-30 12:55
We won't always know which remote + branch to compare with. The "Create PR" command makes it very clear which remote + branch is used since the UI for that is shown at the same time.

**Comment by alexr00** [comment] 2023-12-15 15:07
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/5163

**Closed by alexr00** 2023-12-15 15:07 UTC
Labels: feature-request
