### ISSUE TITLE
Upload files while creating pull request

### ISSUE THREAD

**Issue by vikrantpg** [microsoft/vscode-pull-request-github#5015] opened 2023-07-07 11:31 UTC
While creating pull requests it will be great if uploading file functionality is provided
Drag n drop will be cherry on the cake

Extension version:

OS: Mac
Steps to Reproduce:

Try to create a new PR
Try to add any file in description

https://github.com/microsoft/vscode-pull-request-github/assets/107181894/0b37972a-d3fc-4527-9147-099b25305bca

**Comment by alexr00** [comment] 2023-07-10 09:15
I would love to add this, but sadly GitHub's API does not provide a way to do this. Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/320

**Closed by alexr00** 2023-07-10 09:15 UTC
