### ISSUE TITLE
Clicking on `Account Preferences` on the gear icon on the GitHub Pull Requests Extension should open a quick pick to choose a different account

### ISSUE THREAD

**Issue by aiday-mar** [microsoft/vscode-pull-request-github#6241] opened 2024-09-24 08:18 UTC
Testing [#229420](https://github.com/microsoft/vscode/issues/229420)

- View the extensions in the extension view
- Find the Github Pull Requests
- Click on the gear icon and click on `Account Preferences`
- A quick pick with the possible accounts does not show. From what I understood from the TPI, there should be a quick pick that should appear listing the possible accounts. The TPI mentions that if this happens then it is possible the extension does not handle the Authentication API properly.🐛

**Comment by aiday-mar** [comment] 2024-09-24 08:29
On rereading the TPI, I am not sure if this is a bug or not. Is it expected the quick pick does not open when an account has not been set yet for an extension? @TylerLeonhardt

**Comment by TylerLeonhardt** [comment] 2024-09-25 21:02
this is basically the same root cause as https://github.com/microsoft/vscode/issues/229503 marking as duplicate

**Closed by TylerLeonhardt** 2024-09-25 21:02 UTC
