### ISSUE TITLE
Better visibility for "viewed" file trees

### ISSUE THREAD

**Issue by OmarTawfik** [microsoft/vscode-pull-request-github#3685] opened 2022-07-04 22:08 UTC
It is great that you can mark files as "viewed" when reviewing pull requests from VS Code. Example:

<img width="227" alt="image" src="https://user-images.githubusercontent.com/15987992/177220206-cbd2eaa8-90e6-4538-b377-095a3b88e004.png">

When reviewing large PRs, users typically collapse folders they are done with. It would be great if the collapsed folders show the same "viewed" tick icon as well (only when all of its children are marked as such). This should go all the way up to the "Files" root node, to make sure all files are reviewed:

<img width="210" alt="image" src="https://user-images.githubusercontent.com/15987992/177220790-ddf2c092-c1f7-4e5d-89be-81a519f0a930.png">

It would also be great to have the ability to mark whole folders as "viewed", by having the same button on folder nodes as well. This is really important for folders with many automatically-generated/lock files.

Thanks!

**Comment by alexr00** [comment] 2022-07-05 13:58
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/3274

**Closed by alexr00** 2022-07-05 13:58 UTC
Labels: feature-request
