### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by johnsonlukose** [microsoft/vscode-pull-request-github#2476] opened 2021-02-07 03:01 UTC
- Issue Type: `Bug`
- Extension Name: `vscode-pull-request-github`
- Extension Version: `0.23.0`
- OS Version: `Windows_NT x64 6.1.7601`
- VSCode version: `1.53.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 74,
		"activateCallTime": 5,
		"activateResolvedTime": 2167,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "GitHub.vscode-pull-request-github",
				"_lower": "github.vscode-pull-request-github"
			},
			"activationEvent": "onStartupFinished"
		}
	},
	"runtimeErrors": []
}
```

**Comment by RMacfarlane** [comment] 2021-02-08 16:14
This looks like a duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/2475, so I'm going to go ahead and close this one

**Closed by RMacfarlane** 2021-02-08 16:14 UTC
