### ISSUE TITLE
Allow commenting on commit file changes

### ISSUE THREAD

**Issue by PeterBenc** [microsoft/vscode-pull-request-github#3266] opened 2022-01-24 14:25 UTC
Current behavior: 
If I want to review the PR commits I can't comment on the files, I opened through the `commits` view, I must find these changes in the `Files` view and comment on them there. 

Example: 

I cant comment in the `StakeModalValidatorInfo` if I opened it through commits but I can if I opened it through files(containing all the changes) 

![image](https://user-images.githubusercontent.com/22474126/150800788-ab020816-1f84-49dd-b811-d1aef35e098e.png)

FYI: It seems there is no problem if there is only one commit.

**Comment by PeterBenc** [comment] 2022-04-06 10:59
Hi, any updates on this? I suppose that reviewing commit by commit is pretty standard procedure, until this is resolved it's basically impossible.

**Comment by ELLIOTTCABLE** [comment] 2022-04-13 20:51
(Duplicate of #2793?)

**Comment by alexr00** [comment] 2022-04-14 08:02
Thank you for the duplicate tagging!

**Closed by alexr00** 2022-04-14 08:02 UTC
Labels: feature-request
