### ISSUE TITLE
Sticky comment affordances

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode-pull-request-github#171] opened 2018-08-10 08:05 UTC
I cannot reliably reproduce but it has happened at least a couple times:

1. Click the sidebar to add a new comment
2. Cancel it with <kbd>Escape</kbd>

The comment affordance with the dot stays there, even though I didn't add any comments.

<img width="242" alt="screen shot 2018-08-10 at 10 03 46" src="https://user-images.githubusercontent.com/22350/43946144-baa07b1e-9c84-11e8-9d6a-4270ce9fec8f.png">

**Comment by rebornix** [comment] 2018-08-10 19:50
Reproduce steps for this issue

* Create a new comment
* Type in some characters to ensure that the comment textarea is not empty
* Click on the gutter decoration
* The comment widget is collapsed
* Click on gutter area of another line
* A new comment widget is being opened

The last step is the bug described above. Now I changed the behavior to

* Click on gutter area of another line, we show a warning and ask users to submit the draft comment.

It's a workaround and we need to think about how we handle this case.

**Comment by RMacfarlane** [comment] 2019-07-05 21:38
Closing this, since with the new API there is no restriction on the number of empty comment threads created

**Closed by RMacfarlane** 2019-07-05 21:38 UTC
Labels: upstream/vscode, ux
