### ISSUE TITLE
Clicking into comments field in code does not focus editor

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode-pull-request-github#1073] opened 2019-03-26 11:33 UTC
Refs: https://github.com/Microsoft/vscode/issues/71103

It looks like clicking anywhere below the first line does not focus that line:

![image](https://user-images.githubusercontent.com/900690/54993937-5e404c80-4fc3-11e9-9817-88c8d7e2cbfc.png)

**Comment by RMacfarlane** [comment] 2019-03-27 17:57
Duplicate of https://github.com/Microsoft/vscode/issues/71156

**Closed by RMacfarlane** 2019-03-27 17:57 UTC
Labels: upstream/vscode
