### ISSUE TITLE
Pull Requests icon is invisible (but functional) in the activity bar

### ISSUE THREAD

**Issue by pschlette** [microsoft/vscode-pull-request-github#1256] opened 2019-07-05 22:10 UTC
- Extension version: 0.8.0 (installed on WSL Ubuntu)
- Version: 1.36.0 (user setup)
Commit: 0f3794b38477eea13fb47fbe15a42798e6129338
Date: 2019-07-03T13:25:46.372Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

The Github Pull Requests icon is present and functional but not visible. I've tried disabling and enabling the extension, uninstalling and reinstalling, closing and re-opening VS Code. As far as I can tell everything still functions fine otherwise.

![image](https://user-images.githubusercontent.com/758437/60746975-cc43ca80-9f47-11e9-810f-9e59edc93633.png)

**Comment by RMacfarlane** [comment] 2019-07-12 17:11
Hey @pschlette, this sounds like a duplicate of https://github.com/microsoft/vscode-remote-release/issues/806. Let’s track it there.

**Closed by RMacfarlane** 2019-07-12 17:11 UTC
