### ISSUE TITLE
Allow to comment in threads on the overview page

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode-pull-request-github#741] opened 2018-12-07 17:58 UTC
Issue Type: <b>Feature Request</b>

See attached image. I wanted to respond to the comment thread but couldn't. 

![image](https://user-images.githubusercontent.com/4674940/49664401-a7fe2a80-fa06-11e8-9db4-3c822ad31ad7.png)

Extension version: 0.3.1
VS Code version: Code - Insiders 1.30.0-insider (a152a5c7818a13666a5879b4450eb26a4d45fbde, 2018-12-07T10:25:53.709Z)
OS version: Darwin x64 18.0.0

**Comment by RMacfarlane** [comment] 2018-12-07 18:23
Duplicate of https://github.com/Microsoft/vscode-pull-request-github/issues/601

**Closed by RMacfarlane** 2018-12-07 18:23 UTC
