### ISSUE TITLE
Show status of actions as icon in PR list

### ISSUE THREAD

**Issue by Agreon** [microsoft/vscode-pull-request-github#2200] opened 2020-10-07 08:18 UTC
I would love to have an overview of the action-status of PRs like in the Web PR list. This could be done with :heavy_check_mark: and :x: like in the web.

**Comment by RMacfarlane** [comment] 2020-11-09 18:16
Closing as a duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/681

**Closed by RMacfarlane** 2020-11-09 18:16 UTC
