### ISSUE TITLE
Hover breaks if @username ends in period or colon

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode-pull-request-github#2062] opened 2020-08-16 17:28 UTC
- Extension version:  2020.8.21061
- VSCode Version: 1.49.0-insider
- OS: MacOS

Steps to Reproduce:

1. In the VS Code repo
2. In a JS file, add a comment such as:

    ```js
	//#region @mjbvz.
    ```

3. Try hovering over `@mjbvz`

**Bug**
The hover does not show up. It does show up if you remove the trailing `.`

I also saw this behavior for `:`, such as `@mjbvz:`

**Comment by alexr00** [comment] 2020-09-03 12:33
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/2085

**Closed by alexr00** 2020-09-03 12:33 UTC
