### ISSUE TITLE
PRs from unknown repository are not shown in list

### ISSUE THREAD

**Issue by jongio** [microsoft/vscode-pull-request-github#1025] opened 2019-03-04 21:21 UTC
Version: 1.31.1 (system setup)
Commit: 1b8e8302e405050205e69b59abb3559592bb9e60
Date: 2019-02-12T02:20:54.427Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

Version: 0.4.0

This PR: 
https://github.com/jongio/gitawesome/pull/1

Doesn't show up in the extension:
![image](https://user-images.githubusercontent.com/2163001/53763761-64d61b00-3e80-11e9-930d-a7e9aa45a208.png)

**Comment by IllusionMH** [comment] 2019-03-06 15:14
@jongio do you have this repo as part of VS Code workspace?

**Comment by jongio** [comment] 2019-03-06 15:57
I was able to manage a diff PR via extension, so I believe so. 

The source repo on this PR says unknown repository.

**Comment by RMacfarlane** [comment] 2019-03-06 17:12
We're filtering out PRs that don't have a base reference, ex. that have had their repository deleted, since we won't be able to pull any files and nothing can be merged. So currently this behavior is expected. It would be clearer to still show the PR and have functionality disabled on the description page, we would need to be careful with this change since right now the assumption is that anything we fetch has a valid base

**Comment by IllusionMH** [comment] 2019-03-06 17:18
Then it looks like I have another issue - will create separate issue for my case.

**Comment by jongio** [comment] 2019-03-06 19:25
@RMacfarlane - I was able to merge this PR via the GitHub UI.   At the surface, I think if I can do that via the GitHub website, then I should be able to via the extension as well.

Thanks a lot.  Loving the extension!

**Comment by amundv** [comment] 2020-02-23 19:03
This seems to still be the case:
```
Version: 1.42.1
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:44:27.652Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 17.7.0
```

**Comment by alexr00** [comment] 2023-12-18 11:54
Marking as duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/4613, since https://github.com/microsoft/vscode-pull-request-github/issues/4613 has more 👍

**Closed by alexr00** 2023-12-18 11:54 UTC
Labels: feature-request
