### ISSUE TITLE
Description view item clicking doesn't work sometimes

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-pull-request-github#1057] opened 2019-03-15 22:29 UTC
Issue Type: <b>Bug</b>

Sometimes clicking Description node in the tree view doesn't bring up the webview.

![descriptionview](https://user-images.githubusercontent.com/876920/54465199-2d485800-4737-11e9-863d-67e9110b4ce3.gif)

Extension version: 0.5.1
VS Code version: Code - Insiders 1.33.0-insider (5a88160c7dc5db820a564e3872e0de087ff3563d, 2019-03-15T15:48:56.158Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.05GB free)|
|Process Argv|-psn_0_16133986|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by RMacfarlane** [comment] 2019-10-09 23:19
Closing since I'm unable to reproduce in the latest version of the extension (0.12.0)

**Closed by RMacfarlane** 2019-10-09 23:19 UTC
Labels: bug
