### ISSUE TITLE
Show Changes Since Last Review should not include changes from other branches

### ISSUE THREAD

**Issue by Neighborkid01** [microsoft/vscode-pull-request-github#6281] opened 2024-10-15 19:28 UTC
Type: <b>Bug</b>

When I checkout a PR with this extension and view the list of files, if I have previously reviewed the PR and click the option to "Show Changes Since Last Review", not only do I see changes to files in this PR, I see any file that has changed since I last reviewed the PR even if it was a merge commit.

I would expect the change list to match GitHub when I select the same option.
I actually see all aditional changes that have been merged into this branch since my last review.

To reproduce this, have a main branch and a feature branch.
Create a PR for the feature branch and review it.
Implement changes on the feature branch and the main branch and merge main into feature.
Now both changes from main and feature show as changes since last review even though the changes on main are in the source and target branch of the PR.

Extension version: 0.98.0
VS Code version: Code 1.94.2 (Universal) (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Darwin arm64 24.0.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Pro (10 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|3, 13, 15|
|Memory (System)|16.00GB (0.40GB free)|
|Process Argv|--crash-reporter-id c192492d-d092-475b-bbc4-9282a9140e2d|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
9c06g630:31013171
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
defaultse:31146405
iacca1:31156133
notype1:31151523
5fd0e150:31155592

```

</details>

**Comment by alexr00** [comment] 2024-12-16 17:10
duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/4510

**Closed by alexr00** 2024-12-16 17:10 UTC
Labels: bug
