### ISSUE TITLE
We couldn't find commit

### ISSUE THREAD

**Issue by YaLTeR** [microsoft/vscode-pull-request-github#4537] opened 2023-02-17 17:56 UTC
Type: <b>Bug</b>

After checking out a pull request, I am unable to view changes for individual commits (it says "We couldn't find commit \<hash\>"). I checked with the commandline git and it appears that the repository is grafted:

```
┌ (pr/SmileyAG/414) ~/s/c/BunnymodXT
└─ git log --oneline
734a411 (grafted, HEAD -> pr/SmileyAG/414, SmileyAG/collision_depth_map_fov) hud_custom: apply changes for 'bxt_collision_depth_map_fov'
```

Looks like the extension didn't check out the pull request properly.

Looking at the past issues, it might be relevant information that I have several submodules in this repo, but other functionality seems to be working.

Extension version: 0.58.1
VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:35:30.018Z)
OS version: Linux x64 6.2.0-0.rc8.57.fc38.x86_64
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 PRO 3500U w/ Radeon Vega Mobile Gfx (8 x 3487)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 2|
|Memory (System)|13.53GB (5.28GB free)|
|Process Argv|--ozone-platform-hint=auto --enable-features=WaylandWindowDecorations . --crash-reporter-id 1203ed8c-635a-415f-9e47-b59498cac04c|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|wayland|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewvextcfv2:30660300
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1cf:30587006
2e4cg342:30602488
pyind779cf:30662993
89544117:30613380
pythonsymbol12cf:30657549
a9j8j154:30646983

```

</details>

**Comment by alexr00** [comment] 2023-11-22 12:42
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/1499. The change that fixed https://github.com/microsoft/vscode-pull-request-github/issues/1499 will be available in tomorrow's pre-release version of the extension.

**Closed by alexr00** 2023-11-22 12:42 UTC
Labels: bug
