### ISSUE TITLE
Should not have option to Approve my own PR

### ISSUE THREAD

**Issue by tanhakabir** [microsoft/vscode-pull-request-github#2512] opened 2021-02-19 19:25 UTC
For my own PR:
![image](https://user-images.githubusercontent.com/12758612/108551531-efe69080-72a4-11eb-8f10-1e46f7d701ae.png)

Request Changes should remain grayed out and and Approve should also be greyed out to be consistent with GitHub: 
![image](https://user-images.githubusercontent.com/12758612/108551700-258b7980-72a5-11eb-8961-0983a24279b3.png)

**Comment by RMacfarlane** [comment] 2021-02-19 19:26
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/888

**Closed by RMacfarlane** 2021-02-19 19:26 UTC
Labels: polish
