### ISSUE TITLE
Since `v0.76` the plugin conflicts with copilot plugin in combination with multiple github accounts

### ISSUE THREAD

**Issue by bavarianbidi** [microsoft/vscode-pull-request-github#5787] opened 2024-02-28 07:15 UTC
- Extension version: `v0.80.1` (issue affect all versions since `v0.76`
- VSCode Version:
  Version: 1.86.2
  Commit: 903b1e9d8990623e3d7da1df3d33db3e42d80eda
  Date: 2024-02-13T19:41:37.860Z
  Electron: 27.2.3
  ElectronBuildId: 26908389
  Chromium: 118.0.5993.159
  Node.js: 18.17.1
  V8: 11.8.172.18-electron.0
- OS: Linux x64 6.5.0-21-generic
- Repository Clone Configuration (single repository/fork of an upstream repository): every repository
- Github Product (Github.com/Github Enterprise version x.x.x): github.com

Steps to Reproduce:

1. Having two dedicated github accounts
2. One enterprise based account where just a `Copilot` license is installed/granted
3. One account/profile which get used for contributions - my main contributor account
4. Install `GitHub Copilot` (and/or `GitHub Copilot Chat`) plugin
5. Install `GitHub Pull Requests` plugin
6. Grant Access to the Pull Request Plugin with the main contributor account
7. Grant Access to the Copilot account with the enterprise based account
8. As the main contributor account doesn't have the copilot license - it's not possible to use Copilot anymore

**My current findings so far:**
* since [v0.76.0](https://github.com/microsoft/vscode-pull-request-github/releases/tag/v0.76.0) the PR plugin has support for Copilot generated PR/Issue titles ([commit in this Repository](https://github.com/microsoft/vscode-pull-request-github/commit/35c2c6b7123bd942a86e8038dbcb24afe6cacb99))
* This requires copilot-scope access
* any previous granted copilot access (e.g. from another account) will get revoked - and with that copilot doesn't work anymore

**My current solution:**
I've downgraded PR plugin to version `v0.74.1` and with that, the Plugin only needs permissions to PullRequests.
And my enterprise-managed account (with the Copilot license) is still able to stay logged in.

**What else i've already tried:**
* tried to set setting `"githubPullRequests.pullRequestDescription"` to `none` (supported values - [commit](https://github.com/microsoft/vscode-pull-request-github/blob/743d6bcc68de2b095c120050b860514723e790b3/package.json#L80-L92
)/[main](https://github.com/microsoft/vscode-pull-request-github/blob/main/package.json#L80-L92
))but this doesn't had any affect
  The documentation is quite clear on that regarding the copilot feature ([commit](https://github.com/microsoft/vscode-pull-request-github/blob/743d6bcc68de2b095c120050b860514723e790b3/package.nls.json#L8
)/ [main](https://github.com/microsoft/vscode-pull-request-github/blob/main/package.nls.json#L8)):
  ```
  "Generate a pull request title and description from GitHub Copilot. Requires that the GitHub Copilot extension is installed and authenticated. Will fall back to `commit` if Copilot is not set up.",
  ```

**related issue:**
https://github.com/microsoft/vscode-pull-request-github/issues/5785#issuecomment-1966336171

**Comment by alexr00** [comment] 2024-03-11 14:03
I think being signed in with multiple GitHub accounts is just not supported. I starting adding support in https://github.com/microsoft/vscode-pull-request-github/pull/5699, but it also requires support in VS Code. @TylerLeonhardt FYI.

**Comment by TylerLeonhardt** [comment] 2024-03-11 15:32
Being signed in to multiple GitHub Accounts may be possible (which is a bug), but it's not officially supported. Support for that is tracked here: https://github.com/microsoft/vscode/issues/127967

**Comment by alexr00** [comment] 2024-03-11 16:22
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/5159

**Closed by alexr00** 2024-03-11 16:22 UTC

**Comment by princeofdarkness76** [comment] 2025-03-22 22:05
[README.md](https://github.com/user-attachments/files/19405799/README.md)
[readme.txt](https://github.com/user-attachments/files/19405800/readme.txt)
