### ISSUE TITLE
Error toast on PR creation

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode-pull-request-github#4090] opened 2022-10-20 17:06 UTC
Seeing this from time to time. This was from a one-line change:

<img width="510" alt="CleanShot 2022-10-20 at 10 05 20@2x" src="https://user-images.githubusercontent.com/25163139/197013468-57be72f2-9b38-4b3d-8e61-9782c8a7a517.png">

**Comment by alexr00** [comment] 2022-10-27 16:31
duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/4002

**Closed by alexr00** 2022-10-27 16:31 UTC
