### ISSUE TITLE
Should edit pencil be disabled on suggestions?

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode-pull-request-github#4457] opened 2023-01-24 23:56 UTC
Testing #4434

I might be misunderstanding use of the pencil button on a suggestion but if you edit the suggestion and select Save, the edits are not kept.

Step 8 of the test plan item makes it sound like this is "by design" but I'm confused why there is an enabled pencil button if that is the case.

**Comment by alexr00** [comment] 2023-01-25 10:54
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/4454

**Closed by alexr00** 2023-01-25 10:54 UTC
