### ISSUE TITLE
Include green bars in "Open modified file"

### ISSUE THREAD

**Issue by RikkiGibson** [microsoft/vscode-pull-request-github#4000] opened 2022-09-28 22:43 UTC
- Extension version: v0.50.0
- VSCode Version: 1.71.2
- OS: Not applicable

When reviewing a PR which makes large edits, it can be quite difficult to follow the lines added/removed, due to large gaps between lines in each respective view in the split view, or large interleaving of unrelated lines added/removed in the unified view. 

![image](https://user-images.githubusercontent.com/5833655/192899929-d4466cbb-ef91-4216-af49-4ce5d96f783b.png)

Sometimes in these scenarios it is easier to ignore the lines removed and focus on the lines added. The "Open Modified File" command can be useful for this purpose. It even includes the PR comments on added lines (see the little message bubble glyphs on the left).

![image](https://user-images.githubusercontent.com/5833655/192900050-52849f95-a21a-4099-89a9-388b048ba151.png)

Unfortunately, the "modified file" lacks the green bars which indicate that a line was newly added in the PR. This means it's difficult to see the boundaries between unmodified code and added code. That means it's hard to tell what parts of the file we need to review. It looks like the "add comment" bar (the thicker gray bar on the left) somewhat indicates which lines were edited, but it is imprecise and difficult to see.

Similarly, it would also be handy if red bars would show up for deleted lines when using the "Open Original File" command. It looks like a similar situation, with comments on deleted lines showing up, etc.

It would be great to know if you have any sense of whether the team thinks this change would be worthwhile, and if so whether you would accept a contribution for it. Thanks!

**Comment by alexr00** [comment] 2022-12-09 10:09
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/392

**Closed by alexr00** 2022-12-09 10:09 UTC
Labels: feature-request
