### ISSUE TITLE
Mark files as "viewed"

### ISSUE THREAD

**Issue by jonathanvila** [microsoft/vscode-pull-request-github#1697] opened 2020-04-27 16:00 UTC
In Github you can mark a file as viewed and it collapses its content and also gives you an idea of what you have done in long PRs

**Comment by RMacfarlane** [comment] 2020-04-27 16:22
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/1278

**Closed by RMacfarlane** 2020-04-27 16:22 UTC
