### ISSUE TITLE
Error: Webview is disposed

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode-pull-request-github#5037] opened 2023-07-11 12:44 UTC
Not always, but I often get this error once a PR gets created and the PR creation view goes away:

<img width="481" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/22350/d4f5ccd3-c987-4f55-a78b-8e9280c2e7e0">

**Comment by austinbutler** [comment] 2023-07-11 21:54
I'm getting this every time I add a comment to a thread.

**Comment by alexr00** [comment] 2023-07-13 12:28
I have seen this, but I cannot reproduce it on demand. There's only one place it can be coming from though.

**Comment by mjbvz** [comment] 2023-07-26 18:58
I can still repro this pretty consistently on `v0.69.2023072609`:

1. In PR view, click on a description
2. Before the view loads, close it with using ctrl+w
3. A few seconds later the error notification should show up

**Closed** 2023-08-30 13:28 UTC
Labels: bug
