### ISSUE TITLE
Keeps adding back upstream remote

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-pull-request-github#4930] opened 2023-06-19 07:16 UTC
Type: <b>Bug</b>

When I remove the `upstream` remote using the Git CLI, the GitHub PR extension appears to add it back automatically. It does not get added back when I disable the PR extension. The `upstream` remote is shown on the GitHub repo page as the "forked from" repo.

Extension version: 0.67.2023061509
VS Code version: Code - Insiders 1.80.0-insider (e985f74f31afcf546a87b8e08ef8e47c73c02e64, 2023-06-18T20:41:13.979Z)
OS version: Darwin arm64 22.5.0
Modes:
Remote OS version: Linux arm64 5.15.49-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 5, 8|
|Memory (System)|64.00GB (0.24GB free)|
|Process Argv|--log debug|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: Node.js & TypeScript|
|OS|Linux arm64 5.15.49-linuxkit|
|CPUs|unknown (5 x 0)|
|Memory (System)|7.67GB (5.54GB free)|
|VM|0%|
</details>

**Comment by chrmarti** [comment] 2023-06-19 07:20
The `upstream` remote is also added when I freshly clone the repo (https://github.com/microsoft/vscode-proxy-agent). This repository has been independent of its original for some time, it doesn't make sense to keep the upstream around.

**Comment by nat212** [comment] 2023-06-20 06:46
Encountering this issue as well when cloning a work project that was originally forked from another company. I then get errors trying to fetch/pull since I don't have permission for the original repo.

**Comment by alexr00** [comment] 2023-06-20 09:21
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/4209, which I'll try to do for July.

**Closed** 2023-06-20 09:21 UTC
Labels: duplicate
