### ISSUE TITLE
Support GitHub's suggested changes

### ISSUE THREAD

**Issue by Tadaboody** [microsoft/vscode-pull-request-github#603] opened 2018-10-23 13:19 UTC
Github announced a new [suggestion](https://blog.github.com/page/2/#suggested-changes-public-beta) api that started being added to the code review tools.
Right now the extension takes these at face value as text.

For example take [this comment](https://github.com/Tadaboody/doctree/pull/7/files/3e585d1fa29aa181e60d78eac26382fe71e0216f#r226988399). 
### In github:
![image](https://user-images.githubusercontent.com/6463334/47363350-3df02700-d6df-11e8-8c01-d54f2e997f1a.png)
### In vscode:
![image](https://user-images.githubusercontent.com/6463334/47363391-53fde780-d6df-11e8-8549-846b9587440f.png)
Maybe have the suggested changes be shown as a diff? maybe even have a prompt to incorporate the changes, similarly to a merge conflict.

**Comment by glemaitre** [comment] 2019-01-28 13:19
This would be really useful to have it when making reviews through the VS code.

**Comment by mledom** [comment] 2019-01-30 14:20
With [589](https://github.com/Microsoft/vscode-pull-request-github/pull/589) and this functionality you would be pretty much be able to do the whole PR from VS code!

**Comment by melink14** [comment] 2019-09-14 21:02
Does this FR, only cover displaying the suggestions made elsewhere or also being able to make suggestions from VS code? Both would be great!

**Comment by jonathanvila** [comment] 2020-04-17 15:46
I found this feature very interesting.... is it gonna be put in the roadmap ?

**Comment by arubtsov** [comment] 2020-04-21 13:08
It would be very handy if I could just open a file, make some changes in it and post them as a suggestion.

**Comment by Draal** [comment] 2020-08-27 00:12
It would be really big improvements for dev productivity

**Comment by ankitbko** [comment] 2021-04-12 16:31
Any update on this? Currently the suggestion overflow the width of the comment box without anyway to scroll
![image](https://user-images.githubusercontent.com/3169316/114429068-9468bd00-9bda-11eb-9439-4055d2c22498.png)

**Comment by sahmadi-wave** [comment] 2021-04-16 21:04
Yes, this feature would be very useful. Currently we can add suggestions (using ```suggestion) but they don't show up properly. For example, the suggestion to remove a line does is not displayed at all.

**Comment by georgfaust** [comment] 2021-06-17 16:35
this would also require https://github.com/microsoft/vscode-pull-request-github/issues/1376

without these two features this plugin is just useless.

**Comment by glemaitre** [comment] 2021-06-22 16:29
> without these two features this plugin is just useless.

Your comment is extremely toxic. It does not bring any value to the discussion.

**Comment by georgfaust** [comment] 2021-07-03 15:55
> > without these two features this plugin is just useless.
> 
> Your comment is extremely toxic. It does not bring any value to the discussion.

you're right sorry. Just being frustrated finding no tools to make reviews outside of the Github webgui. Even jetbrains can't do it.

**Comment by EthanJStark** [comment] 2021-09-02 14:48
++ for this suggestion! 

I'd also note that it could be extremely useful if a user shifts into "PR Review Suggestion Mode" so that any code changes made in VS Code's editors were batched as PR Comment code change suggestions.

(but even a basic implementation would be extremely helpful)

**Comment by Lovkush-A** [comment] 2021-09-05 08:52
So just to check my understanding, currently the best way to make code suggestions (especially code suggestions for multiple lines of code) is to use GitHub's online GUI. Is that right?

**Comment by 0x24a537r9** [comment] 2021-10-02 05:08
For single line changes (since #1376 is still open), you can manually type:
```
```suggestion
  your suggestion
\```
```
(ignore that slash though—I just don't know how to escape backticks in markdown)

**Comment by alexr00** [comment] 2021-11-17 14:36
We actually have this feature already (though it's a bit difficult to find)! To use:
1. Check out the pull request you want to make a suggestion on.
2. Make the code change and stage your suggestion.
3. Run the "Suggest Edit" command from either the command palette or the git ... menu. 
4. The suggestion will show up on the description page as a patch which can be applied.

**Comment by glemaitre** [comment] 2021-11-17 16:01
Thanks @alexr00 for the info. However, this is not corresponding to the feature that was requested.

Here, the "Suggest Edit" will create a patch. Via the extension interface, it can be applied but via the web interface, it cannot. Thus, a contributor that does not use the GitHub extension cannot accept the suggestion and he will just end up with a `git diff`. Depending on the expertise of the contributor with `git`, I am not sure that dealing with such a patch is easy.

In addition, a suggestion is sometimes coming with an additional explanation to argue the importance of the suggestion or the reasons to suggest such a modification. Currently, the proposed methodology is not allowing such a feature.

I see it maybe as an incomplete workaround and I would suggest to let the issue open until the exact same feature on the web interface and vs code extension is implemented.

**Comment by glemaitre** [comment] 2021-11-18 09:29
Thanks @alexr00 for reopening.

**Comment by milesrichardson** [comment] 2022-01-04 22:32
> We actually have this feature already (though it's a bit difficult to find)! To use:
> 
> 1. Check out the pull request you want to make a suggestion on.
> 2. Make the code change and stage your suggestion.
> 3. Run the "Suggest Edit" command from either the command palette or the git ... menu.
> 4. The suggestion will show up on the description page as a patch which can be applied.

Great tip, thanks! This is better than nothing, but as others have mentioned, it doesn't result in a patch that can be applied in the web UI. In case anyone is wondering what it looks like, this is the result:

![image](https://user-images.githubusercontent.com/835921/148132528-16f46b1e-2d2e-4dd9-b962-89749f23b314.png)

i.e. It posts a comment containing a markdown code block formatted with the `diff` lang.

Another quirk I noticed is that this applies the comment immediately, even if you are in PR review mode. This can be a bit confusing as the author of the PR will get notification spam for each suggestion, and then only later when you submit the review will they see the rest of the comments. In addition to the spam problem, this can be confusing when reading comments, because the author simply sees a "suggested change" with no context as to why you're suggesting it.

Perhaps a "suggestion" (😏 ) for improving this feature would be to allow posting a message along with the diff. Maybe it could be implemented as a second step in the command palette.

Anyway, the feature that leaves a diff in a comment is not too bad – thanks for the extension!

**Comment by brianjmurrell** [comment] 2022-02-12 20:32
> We actually have this feature already (though it's a bit difficult to find)! 

Not really.  You have a feature to suggest a change as a patch in a comment but it's not using GitHub's _suggestion_ facility as it does not provide the reader with the tools that _suggestion_ facility provides to be able to apply the suggestion right from the UI.

So while you have similar feature, it does not satisfy the original request, IMO.

**Comment by lrweck** [comment] 2022-04-17 23:17
Is this suggestion being considered?

**Comment by brianjmurrell** [comment] 2022-04-21 16:32
Now that microsoft/vscode#146510 is landed this feature is closer to being achievable.

I wonder if the UX for it can be nicer than GitHub's.  Maybe by allowing some kind of in-place/in-editor changing while reviewing and some button that makes that a ` ```suggestion` in the comment.

**Comment by glemaitre** [comment] 2022-04-21 16:36
> Now that https://github.com/microsoft/vscode/issues/146510 is landed this feature is closer to being achievable.

This is super nice.

> Some button that makes that a ```suggestion in the comment.

With a small keyboard shortcut ;)

**Comment by ant0nsc** [comment] 2022-05-30 09:25
+1 on adding the ability to make code suggestions as comments, this would be super helpful.

**Comment by danipoma** [comment] 2022-06-05 10:10
+1 for button that would wrap content with ```suggestion ``` block like it is done on GitHub.

**Comment by albertusdev** [comment] 2022-11-07 14:25
+1, ```suggestion block with shortcut/button would be very helpful!

**Comment by alexr00** [comment] 2022-11-25 16:37
There are several parts that will need to be done here:
- Show ```suggestion blocks in some way in the comment widget (https://github.com/microsoft/vscode-pull-request-github/pull/4248)
  - The comment widget just allows markdown, no HTML, so we will likely not be able to show a nice little diff like GitHub does
- Apply ```suggestion blocks in the comment widget (also in progress in https://github.com/microsoft/vscode-pull-request-github/pull/4248)
- Have a button that inserts the ```suggestion + text editor content for when you're authoring a comment
  - Requires new API in VS Code

**Comment by alexr00** [comment] 2022-12-21 16:58
Unintentionally closed by the PR!

**Closed** 2022-12-23 09:42 UTC
Labels: feature-request

**Comment by alexr00** [comment] 2022-12-23 12:55
There's still room for lots of polish, but the feature is now fully available in the latest pre-release build.

**Comment by glemaitre** [comment] 2022-12-23 14:37
Nice. Thanks @alexr00. Going to test it ;)

**Comment by JustinGrote** [comment] 2023-04-06 01:37
@alexr00 this is great! One feature I would like is a settings option to create a commit on every applied suggestion. Right now, you can apply a suggestion and resolve a conversation, but then if something happens in between, that change gets lost. Should I file this as a separate issue?

**Comment by alexr00** [comment] 2023-04-11 13:17
@JustinGrote a separate issue for that makes sense.  Personally, I don't want to have a separate commit per suggestion as that feels like an implementation detail from when you could only accept suggestions on github.com. I'd like to gauge interested in having separate commits like this though, as others like yourself may prefer to have many smaller commits.

**Comment by Dru01** [comment] 2023-05-19 20:05
@alexr00 Is there anyway to commit suggestions? Like in comment suggestions made in github? Something like I agree with it so I apply it. I found a "Apply patch" button when a suggestion is made inside vscode, but anything when it was send by github.

**Comment by alexr00** [comment] 2023-05-22 10:04
@Dru01 that is what is requested in https://github.com/microsoft/vscode-pull-request-github/issues/603#issuecomment-1498375128. Currently, the suggestion will be applied locally, but not committed.

**Comment by lgruen** [comment] 2023-05-23 01:48
@alexr00 Thanks for your work on this! I can't seem to find a button in the review comment to invoke the `pr.applySuggestion` command, even in an up-to-date Insiders build:

![CleanShot 2023-05-23 at 11 47 24@2x](https://github.com/microsoft/vscode-pull-request-github/assets/2876012/86ddac07-4b5f-494d-9cbe-540fd8453feb)

**Comment by alexr00** [comment] 2023-05-23 11:51
@lgruen do you have the PR checked out? We only support accepting a suggestion in a checked out PR.

**Comment by alexr00** [comment] 2023-05-23 12:17
@lgruen it shouldn't make a difference. Is this a public PR that you could share a link to? There's likely something about this specific comment that we're not parsing correctly.

**Comment by alexr00** [comment] 2023-05-23 12:33
@lgruen thanks! I found a way to reproduce the issue that might be what you're hitting: https://github.com/microsoft/vscode-pull-request-github/issues/4839
