### ISSUE TITLE
Hide comments by default

### ISSUE THREAD

**Issue by dwelle** [microsoft/vscode-pull-request-github#2492] opened 2021-02-13 19:21 UTC
Related to https://github.com/microsoft/vscode-pull-request-github/issues/665, but I'd like the comments to be hidden by default when a diff is opened. A setting for this would be nice.

**Comment by alexr00** [comment] 2021-08-04 13:49
I'm going to call this a dupe of https://github.com/microsoft/vscode-pull-request-github/issues/665, and make sure that includes a setting and a command.

**Closed** 2021-08-04 13:49 UTC
Labels: feature-request
