### ISSUE TITLE
Add code navigation on diff tab

### ISSUE THREAD

**Issue by AlexanderYAPPO** [microsoft/vscode-pull-request-github#1147] opened 2019-05-08 09:53 UTC
When I'm looking through a diff of a PR I can't navigate to definitions of variables and functions. A simple use case: a PR author added a new function and use it in code. I see a usage of a function but can't go to the definition by right click or by ctrl (cmd) + left click. However code navigation like this works if I use it in a regular tab with a source code. I think this'd make reviewing code even easier.

I didn't find information about existence of this feature already. If it exists then maybe I'm having a bug.

Python 2.7
Python extension 2019.1.0
Github Enterprise
macOS Mojave 10.14.2
VSC Version 1.30.2
Github PR 0.3.2

**Comment by RMacfarlane** [comment] 2019-10-07 21:42
This looks like a duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/486, let's track it there

**Closed by RMacfarlane** 2019-10-07 21:42 UTC
