### ISSUE TITLE
Copy github permalink should not work or be disabled for files that used to be tracked by git but now aren't

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-pull-request-github#3547] opened 2022-05-10 23:12 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.68-insiders
- OS Version: Windows 10

Steps to Reproduce:

1. Add a file to .gitignore or open a file not in the repo
2. Pick 'Copy github permalink' from the context menu
3. Try to open that link

It will fail because the file doesn't exist.

**Comment by rchiodo** [comment] 2022-05-11 16:32
No I get the link. The link is just invalid. 

Here's an example:

https://github.com/microsoft/vscode-jupyter/blob/61ba6bdfa9768566aa79f36e9b64dee073751beb/vscode.d.ts#L4192

**Comment by rchiodo** [comment] 2022-06-07 16:15
Repro steps for me:

1. Git clone 'vscode-jupyter' 
2. npm install
3. Open vscode.d.ts
4. Right click 'github permalink'

It gives me this:
https://github.com/microsoft/vscode-jupyter/blob/61ba6bdfa9768566aa79f36e9b64dee073751beb/vscode.d.ts#L1990

**Comment by alexr00** [comment] 2022-06-08 12:15
Thanks!

The reason I couldn't reproduce it is because vscode.d.ts actually _was_ tracked by git in that repository at one point. The commit referenced in the link that's create is actually the commit at which it was removed. 

@lszomoru is there some git extension API that I'm missing that can tell me if a file is currently tracked by git or if the file is git-ignored? Currently we use `log` with a path to determine if a file is tracked, but that doesn't work for a file that used to be tracked but is now git-ignored.

**Comment by lszomoru** [comment] 2022-07-28 14:47
@alexr00, I am not aware of such extension API but if needed it is something that can be explored.

**Comment by alexr00** [comment] 2022-07-29 08:30
@lszomoru it's an edge case. Let's leave the issue open and see how many others hit it before adding new API for it.

**Comment by alexr00** [comment] 2022-12-09 14:44
Closing as we do handle this most of the time.

**Closed by alexr00** 2022-12-09 14:44 UTC
Labels: bug, upstream/vscode

**Comment by shsmith330** [comment] 2024-08-23 02:56
Having the same issue actually, I believe it has to do with when you set your .gitignore for a folder that isn't the root folder.
