### ISSUE TITLE
Field 'mergeQueueEntry' doesn't exist on type 'PullRequest' GraphQL error: No such type MergeQueueEntry, so it can't be a fragment condition

### ISSUE THREAD

**Issue by DenisBY** [microsoft/vscode-pull-request-github#5808] opened 2024-03-05 17:16 UTC
I'm getting the error when I press "Create" in PR create "wizard" since v0.82.0:
```
Field 'mergeQueueEntry' doesn't exist on type 'PullRequest' GraphQL error: No such type MergeQueueEntry, so it can't be a fragment condition
```
v0.80.1 of plugin is working fine

- Extension version: v0.82.0
- VSCode Version: 1.87.0
- OS: Ubuntu 22.04
- Repository Clone Configuration (single repository/fork of an upstream repository): single
- Github Product (Github.com/Github Enterprise version x.x.x): GHE 3.7.4

Steps to Reproduce:

1. push a new branch with some changes
2. try to create a new PR

**Comment by Geczy** [comment] 2024-03-06 14:08
same issue here

```
2024-03-06 08:07:08.537 [error] GitHubRepository> Fetching all pull requests failed: Error: GraphQL error: Field 'mergeQueueEntry' doesn't exist on type 'PullRequest'
GraphQL error: No such type MergeQueueEntry, so it can't be a fragment condition
2024-03-06 08:07:08.538 [error] GitHubRepository> Error querying GraphQL API: GraphQL error: Field 'mergeQueueEntry' doesn't exist on type 'PullRequest'
GraphQL error: No such type MergeQueueEntry, so it can't be a fragment condition
2024-03-06 08:07:08.539 [error] GitHubRepository> Error querying GraphQL API: GraphQL error: Field 'mergeQueueEntry' doesn't exist on type 'PullRequest'
GraphQL error: No such type MergeQueueEntry, so it can't be a fragment condition
2024-03-06 08:07:08.539 [error] GitHubRepository> Fetching all pull requests failed: Error: GraphQL error: Field 'mergeQueueEntry' doesn't exist on type 'PullRequest'
GraphQL error: No such type MergeQueueEntry, so it can't be a fragment condition
2024-03-06 08:07:09.830 [info] FolderRepositoryManager+0> Found GitHub pr repo for pr #1030: yes
```

**Comment by vanduc2514** [comment] 2024-03-12 07:42
Same issue with vscode 1.87.1

**Comment by pedroelir** [comment] 2024-03-12 19:30
I had the same issue Extension version: `v0.82.0` 
I workaround it by rolling back to previous version `v0.80.1`
![image](https://github.com/microsoft/vscode-pull-request-github/assets/94746327/d5406e24-4aad-4bc4-b2af-fa5eeebdeeb2)

**Comment by alexr00** [comment] 2024-04-02 09:25
Folks who see this: I think your enterprise instance is returning an error that the extension isn't handling properly. I've added logging in the latest pre-release version of the extension. If you could install the [pre-release version](https://github.com/microsoft/vscode-pull-request-github/wiki/Pre-release-Build) of the extension then share the output of "GitHub Pull Request" once you see the issue again then I'll know what error I need to look for.

**Comment by DenisBY** [comment] 2024-04-02 14:12
v0.83.2024030509 (pre-release)

```
2024-04-02 16:08:49.655 [error] GitHubRepository> Fetching pull request templates failed: TypeError: Cannot read properties of null (reading 'repository')
2024-04-02 16:08:49.683 [error] GitHubRepository> Fetching pull request templates failed: TypeError: Cannot read properties of null (reading 'repository')
2024-04-02 16:08:49.776 [error] GitHubRepository> Error querying GraphQL API: GraphQL error: Field 'mergeQueue' doesn't exist on type 'Repository'
GraphQL error: Variable $branch is declared by MergeQueueForBranch but not used
2024-04-02 16:08:49.776 [error] GitHubRepository> Fetching branch has merge queue failed: Error: GraphQL error: Field 'mergeQueue' doesn't exist on type 'Repository'
GraphQL error: Variable $branch is declared by MergeQueueForBranch but not used
2024-04-02 16:08:49.817 [info] CreatePullRequestViewProvider> Initializing "create" view: {"defaultBaseRemote":{"owner":"tag","repositoryName":"tag.terraform"},"defaultBaseBranch":"master","defaultCompareRemote":{"owner":"tag","repositoryName":"tag.terraform"},"defaultCompareBranch":"TAG-1586","defaultTitle":"Get code directly from GHE","defaultDescription":"","defaultMergeMethod":"merge","baseHasMergeQueue":false,"remoteCount":2,"allowAutoMerge":false,"mergeMethodsAvailability":{"merge":true,"squash":true,"rebase":true},"autoMergeDefault":false,"createError":"","labels":[],"isDraftDefault":false,"isDarkTheme":true,"generateTitleAndDescriptionTitle":"Generate with Copilot","creating":false,"initializeWithGeneratedTitleAndDescription":false}
2024-04-02 16:09:06.684 [error] GitHubRepository> Unable to create PR: Error: GraphQL error: Field 'mergeQueueEntry' doesn't exist on type 'PullRequest'
GraphQL error: No such type MergeQueueEntry, so it can't be a fragment condition
2024-04-02 16:09:06.684 [error] FolderRepositoryManager+0> Creating pull requests failed: Error: GraphQL error: Field 'mergeQueueEntry' doesn't exist on type 'PullRequest'
GraphQL error: No such type MergeQueueEntry, so it can't be a fragment condition
```

**Comment by alexr00** [comment] 2024-04-02 14:54
@DenisBY thanks for the logs, but it looks like you're on a version of the pre-release extension that's nearly a month old. Can you update to the latest? You'll need to use[ VS Code insiders](https://code.visualstudio.com/insiders/) to get the latest version.

**Comment by DenisBY** [comment] 2024-04-02 15:08
> @DenisBY thanks for the logs, but it looks like you're on a version of the pre-release extension that's nearly a month old. Can you update to the latest? You'll need to use[ VS Code insiders](https://code.visualstudio.com/insiders/) to get the latest version.

v0.85.2024032704 (pre-release)
```
2024-04-02 17:06:18.820 [error] GitHubRepository> Fetching pull request templates failed: TypeError: Cannot read properties of null (reading 'repository')
2024-04-02 17:06:18.835 [error] GitHubRepository> Fetching pull request templates failed: TypeError: Cannot read properties of null (reading 'repository')
2024-04-02 17:06:18.940 [error] GitHubRepository> Error querying GraphQL API: GraphQL error: Field 'mergeQueue' doesn't exist on type 'Repository'
GraphQL error: Variable $branch is declared by MergeQueueForBranch but not used. undefinedField,variableNotUsed
2024-04-02 17:06:18.941 [error] GitHubRepository> Fetching branch has merge queue failed: Error: GraphQL error: Field 'mergeQueue' doesn't exist on type 'Repository'
GraphQL error: Variable $branch is declared by MergeQueueForBranch but not used
2024-04-02 17:06:18.955 [info] CreatePullRequestViewProvider> Initializing "create" view: {"defaultBaseRemote":{"owner":"tag","repositoryName":"tag.terraform"},"defaultBaseBranch":"master","defaultCompareRemote":{"owner":"tag","repositoryName":"tag.terraform"},"defaultCompareBranch":"TAG-1586","defaultTitle":"Get code directly from GHE","defaultDescription":"","defaultMergeMethod":"merge","baseHasMergeQueue":false,"remoteCount":2,"allowAutoMerge":false,"mergeMethodsAvailability":{"merge":true,"squash":true,"rebase":true},"autoMergeDefault":false,"createError":"","labels":[],"isDraftDefault":false,"isDarkTheme":true,"creating":false,"initializeWithGeneratedTitleAndDescription":false}
2024-04-02 17:06:36.292 [error] GitHubRepository> Unable to create PR: Error: GraphQL error: Field 'mergeQueueEntry' doesn't exist on type 'PullRequest'
GraphQL error: No such type MergeQueueEntry, so it can't be a fragment condition
2024-04-02 17:06:36.293 [error] FolderRepositoryManager+0> Creating pull requests failed: Error: GraphQL error: Field 'mergeQueueEntry' doesn't exist on type 'PullRequest'
GraphQL error: No such type MergeQueueEntry, so it can't be a fragment condition
```

**Comment by alexr00** [comment] 2024-04-03 12:40
Thanks @DenisBY for trying it out so quickly! We're getting ready to release soon, so I can't publish a new pre-release version with the fix, but I think I see what the problem is. If you're willing, here's an unpublished pre-release version of the extension to try out. You can rename to .vsix instead of .zip and install in VS Code with the command "Extensions: Install from VSIX...".

[GitHub.vscode-pull-request-github.0.85.2024040310.zip](https://github.com/microsoft/vscode-pull-request-github/files/14852200/GitHub.vscode-pull-request-github.0.85.2024040310.zip)

Or, if you wait until tomorrow the fix will be in the pre-release version of the extension tomorrow. As soon as we can confirm that this solves the issue I'll make a patch release with the fix.

**Comment by DenisBY** [comment] 2024-04-04 12:41
@alexr00 thanks, looking good with v0.85.2024040310. I don't see the error anymore.

**Comment by alexr00** [comment] 2024-04-04 14:55
Great, thanks for testing! I just published a pre-release build with the fix, which should be available shortly. I'll aim to have a stable build with the fix on Monday.

**Closed** 2024-04-08 10:06 UTC
Labels: bug, candidate
