### ISSUE TITLE
Provide keyboard shortcuts to iterate over changes in Pull Request

### ISSUE THREAD

**Issue by pbrezina** [microsoft/vscode-pull-request-github#1808] opened 2020-05-15 10:20 UTC
I think GH PR diff view very useful when reviewing a pull request but I'd like to do it on keyboard only.

Please, provide a way to iterate through changes in selected PR.

**Comment by RMacfarlane** [comment] 2020-11-11 16:49
Closing as a duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/483

**Closed by RMacfarlane** 2020-11-11 16:49 UTC
Labels: feature-request
