### ISSUE TITLE
Unable to see comments in commits file view

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode-pull-request-github#2688] opened 2021-04-28 15:51 UTC
Refs https://github.com/microsoft/vscode/issues/122245

I'm unsure if this is expected or not, but I at least expected to see the same comments from the Files section appear under the file in the Commits section as well

## Files
![image](https://user-images.githubusercontent.com/35271042/116433882-c5620800-a7fe-11eb-9559-9f4faa844d62.png)

## Commits
![image](https://user-images.githubusercontent.com/35271042/116433736-a5cadf80-a7fe-11eb-98b7-9bd795032a86.png)

GH PR Version: v2021.4.39423
Version: 1.56.0-insider (user setup)
Commit: 13f1afffab09548c10ddb3bc5d5db52587876ad8
Date: 2021-04-28T04:52:06.990Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by alexr00** [comment] 2021-06-24 15:08
Comments that were made when your PR was on the commit that you have selected should now show.

**Comment by misolori** [comment] 2021-06-30 15:10
I'm seeing a couple of issues, not sure if they're related to this. When trying to check out the PR from the overview page, I get a "branch not found" error. Then when I manually change to the branch and attempt to open the commit file, I get a "couldn't find commit"

<img width="1024" alt="CleanShot 2021-06-30 at 08 06 16@2x" src="https://user-images.githubusercontent.com/35271042/123985367-457d2900-d97a-11eb-8a83-cd659006da52.png">

GHPR: v2021.6.42304
Version: 1.58.0-insider (Universal)
Commit: 57930758db9e2c83f59b9ee1851400bd16192d32
Date: 2021-06-30T05:13:11.659Z
Electron: 12.0.12
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin arm64 20.5.0

<hr>

While on Windows I don't see these issues but then the original issue still repros.

**Comment by alexr00** [comment] 2021-07-01 09:29
Opened a new issue for the checkout from overview issue: https://github.com/microsoft/vscode-pull-request-github/issues/2812

@misolori I'm able to see comments in files opened from the commits tree. Note that each comment will _only_ show on one of the commits. Comments are mapped to commits, so each comment will only show in the commit for which that comment was added. (the commit hash isn't shown in the tree right now, I will add that in the hover for July since it seems useful). Can you double check that you had the commit that the comment was associated with open?

**Comment by misolori** [comment] 2021-07-01 16:05
I'm still seeing this, [here's another PR example](https://github.com/microsoft/vscode/pull/127757):

## Opening file
✅  This shows the comment
<img width="1168" alt="CleanShot 2021-07-01 at 09 03 17@2x" src="https://user-images.githubusercontent.com/35271042/124155336-3c0fc180-da4b-11eb-9664-d2fb5c4f3727.png">

## Opening the commit
❌ This does not show any commits even though there is 💬 icon on the file
<img width="1168" alt="CleanShot 2021-07-01 at 09 04 44@2x" src="https://user-images.githubusercontent.com/35271042/124155484-62cdf800-da4b-11eb-8d3c-7a3e0eb14121.png">

**Comment by misolori** [comment] 2021-07-01 16:07
I guess the question really is: should i be able to see comments from the **commits** node in addition to the **files** node? If not then we should hide the 💬 icon from that item in that node as it's confusing.

**Comment by rzhao271** [comment] 2021-07-02 18:26
I'll mark this issue as verification found again based on Miguel's question above.

**Comment by alexr00** [comment] 2021-07-05 10:33
I can repro with the PR that Miguel was testing with.

**Comment by alexr00** [comment] 2021-07-05 11:46
The issue is that the comments associated with the most recent commit will not show in that commit. Fix doesn't look low risk, so moving to July.

**Closed** 2021-07-08 14:31 UTC
Labels: bug, windows
