### ISSUE TITLE
Managing Multiple github accounts

### ISSUE THREAD

**Issue by nirou8** [microsoft/vscode-pull-request-github#3288] opened 2022-02-03 03:42 UTC
It would be great if we can connect and switch between GitHub accounts.

I'm already logged in with one personal account and everything works perfectly, but if I want to work on another repository from another user, it will fail and show a message "fatal: repository ..... not found.

**Comment by alexr00** [comment] 2022-02-03 15:32
duplicate of upstream issue https://github.com/microsoft/vscode/issues/127967

**Closed by alexr00** 2022-02-03 15:32 UTC
