### ISSUE TITLE
list of files in "changes in pull request" view disappear if in new vscode side panel

### ISSUE THREAD

**Issue by clenfest** [microsoft/vscode-pull-request-github#3318] opened 2022-02-11 17:30 UTC
Issue Type: <b>Bug</b>

Not sure of exactly how to reproduce, but if I moved the "changes in pull request" tab from the main side bar to the new side panel, I will be able to see the list of files for some period of time, but eventually they always seem to go away and not be listed. Refreshing does not seem to properly reload them, but restarting vscode usually will make it work again temporarily.

Extension version: 0.36.1
VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:00:56.651Z)
OS version: Darwin arm64 21.1.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 4, 4|
|Memory (System)|16.00GB (0.10GB free)|
|Process Argv|--crash-reporter-id 45e23dfb-f337-4325-b49b-aab4a83a5026|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30433059
pythonvs932:30410667
wslgetstartedc:30433508
vsrem710cf:30416617
pythonvsnew555:30436484
vsbas813:30436447

```

</details>

**Comment by clenfest** [comment] 2022-02-11 17:33
Here's a screenshot. Plenty of commits for the PR, but files list is empty.

![image](https://user-images.githubusercontent.com/12638044/153640096-7ace8fd3-6632-4bb5-8d73-4661f180003e.png)

**Comment by alexr00** [comment] 2022-02-14 12:37
@clenfest would you be willing to try out the [pre-release version](https://github.com/microsoft/vscode-pull-request-github/wiki/Pre-release-Build) of the extension and reply back with whether you end up seeing the same issue there? I made a fix last week that may address the problem you're seeing.

**Comment by xmatthias** [comment] 2022-02-14 18:07
I've been hitting this too and can confirm that (at least for my case) it's fixed with the pre-release version.

**Comment by clenfest** [comment] 2022-02-14 21:48
Yeah, it looks like it's take care of. Thanks again.

**Comment by alexr00** [comment] 2022-02-15 08:37
Thanks @xmatthias! I'll wait until I hear back from @clenfest before closing.

**Comment by mharris717** [comment] 2022-02-19 16:16
I've also been experiencing this. I just switched to pre-release version. Can't be sure it fixes it till I let VSCode run for a while. Will report back on Monday to confirm fixed. 

Thanks!

**Comment by alexr00** [comment] 2022-02-22 15:25
Closing since so far there are no reports of this issue occurring with the pre-release version.

**Comment by alexr00** [comment] 2022-02-22 16:53
@mharris717 do you have any clues about what you were doing when this occurred? (made a commit, changed branches, created a pr, pulled, etc.)

**Comment by mharris717** [comment] 2022-02-22 18:57
It happens constantly. Restarting VSCode fixes it. 

I'm pretty sure it requires some activity to trigger it, and not just time, since I didn't touch computer for 24h+ and when I returned it was still working. 

It seems to break pretty fast while I'm using VSCode. I can't say for sure that switching branches is a cause. I would guess, cause I'm switching branches all the time, but I don't have a good "control group"

**Comment by mharris717** [comment] 2022-02-22 18:59
Once it breaks, it never unbreaks without a restart. 

It may be getting "stuck" on a previous branch. I've seen it showing the title for "a branch i've switched away from a while ago," along with no files.

**Comment by mharris717** [comment] 2022-02-22 19:01
The output for `GitHub Pull Request` is still going while the pane is broken. 

I switched to master and the pane went away, then switched back and pane reappeared, still in broken state 

```
[Info] Review> current branch eligibility-dialog-cypress-022222 is associated with pull request #35200
[Info] Review> Resolving pull request
[Info] Review> Fetching pull request data
[Info] Review> register comments provider
[Info] Review> display pull request status bar indicator and refresh pull request tree view.
[Info] Review> using focus mode = true.
[Info] Review> state validation silent = true.
[Info] Review> PR show should show = false.
[Info] Review> Validate state in progress
[Info] Review> Validating state...
[Info] Found GitHub remote
[Info] Trying to use globalState for mentionable users.
[Info] Using globalState mentionable users for 1.
[Info] Review> no matching pull request metadata found for current branch master
[Info] Review> no matching pull request metadata found on GitHub for current branch master
[Info] Review> Queuing additional validate state
[Info] Review> Validating state...
[Info] Found GitHub remote
[Info] Review> current branch eligibility-dialog-cypress-022222 is associated with pull request #35200
[Info] Review> Resolving pull request
[Info] Review> Fetching pull request data
[Info] Review> register comments provider
[Info] Review> display pull request status bar indicator and refresh pull request tree view.
[Info] Review> using focus mode = true.
[Info] Review> state validation silent = true.
[Info] Review> PR show should show = false.
```

**Comment by mharris717** [comment] 2022-02-22 19:04
installed extensions with GitHub in name 
![image](https://user-images.githubusercontent.com/64296/155201019-c8119bfd-93cc-424d-8e0c-2aba23df3cf1.png)

**Comment by alexr00** [comment] 2022-02-28 14:34
@mharris717 I've tried lots of switching branches and pushing commits but I haven't been able to trigger the issue. Next time you see it, can you open the developer tools (command "Developer: Toggle Developer Tools" and share the contents of the console?

**Comment by mharris717** [comment] 2022-02-28 16:25
Just restarted VSCode and saw this. The bug isn't occurring yet, but seems like a clue. 

```[GitHub.vscode-pull-request-github]: `remoteHub/pullRequest` is not a valid menu identifier```

![image](https://user-images.githubusercontent.com/64296/156019715-324b44f5-1f24-44fb-8e37-4e37899847bb.png)

**Comment by mharris717** [comment] 2022-02-28 16:30
Bingo, just made it happen. 

I made changes to the branch in a different unrelated working copy, pushed them, then pulled them down in VSCode into the WC open in VSCode (from VSCode terminal). Caused bug to happen in 1-2 seconds, which tracks with the error message. 

![image](https://user-images.githubusercontent.com/64296/156020177-d0e3de4a-bf36-4308-be6d-b01a6dceb532.png)

```
log.ts:301  INFO IExtensionHostStarter.start() took 178 ms.
log.ts:313   ERR [Extension Host] (node:42059) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Electron --trace-deprecation ...` to show where the warning was created)
console.ts:137 [Extension Host] (node:42059) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.(Use `Electron --trace-deprecation ...` to show where the warning was created)
I @ console.ts:137
_logExtensionHostMessage @ localProcessExtensionHost.ts:581
(anonymous) @ localProcessExtensionHost.ts:335
fire @ event.ts:628
K @ ipc.ts:644
onResponse @ ipc.ts:723
onBuffer @ ipc.ts:709
(anonymous) @ ipc.ts:521
fire @ event.ts:628
G @ event.ts:344
emit @ events.js:315
onMessage @ electron/js2c/renderer_init.js:105
abstractExtensionService.ts:928 [GitHub.vscode-pull-request-github]: `remoteHub/pullRequest` is not a valid menu identifier
_logMessageInConsole @ abstractExtensionService.ts:928
_handleExtensionPointMessage @ abstractExtensionService.ts:879
X @ abstractExtensionService.ts:853
_msg @ extensionsRegistry.ts:39
warn @ extensionsRegistry.ts:52
(anonymous) @ menusExtensionPoint.ts:748
_ @ collections.ts:42
(anonymous) @ menusExtensionPoint.ts:728
_handle @ extensionsRegistry.ts:144
acceptUsers @ extensionsRegistry.ts:135
_handleExtensionPoint @ abstractExtensionService.ts:913
_doHandleExtensionPoints @ abstractExtensionService.ts:859
_startLocalExtensionHost @ extensionService.ts:467
async function (async)
_startLocalExtensionHost @ extensionService.ts:438
_scanAndHandleExtensions @ extensionService.ts:432
_initialize @ abstractExtensionService.ts:526
async function (async)
_initialize @ abstractExtensionService.ts:524
(anonymous) @ extensionService.ts:110
requestIdleCallback (async)
e.runWhenIdle @ async.ts:1148
(anonymous) @ extensionService.ts:109
Promise.then (async)
rc @ extensionService.ts:107
_createInstance @ instantiationService.ts:110
_createServiceInstance @ instantiationService.ts:230
_createServiceInstanceWithOwner @ instantiationService.ts:219
_createAndCacheServiceInstance @ instantiationService.ts:208
_safeCreateAndCacheServiceInstance @ instantiationService.ts:151
_getOrCreateServiceInstance @ instantiationService.ts:135
_createInstance @ instantiationService.ts:88
createInstance @ instantiationService.ts:76
acquireInstantiationService @ configurationService.ts:461
(anonymous) @ workbench.ts:214
invokeFunction @ instantiationService.ts:61
initServices @ workbench.ts:208
startup @ workbench.ts:139
open @ desktop.main.ts:115
async function (async)
open @ desktop.main.ts:106
K @ desktop.main.ts:378
m.load.configureDeveloperSettings @ workbench.js:32
(anonymous) @ bootstrap-window.js:180
i._invokeFactory @ loader.js:1185
i.complete @ loader.js:1195
i._onModuleComplete @ loader.js:1821
i._onModuleComplete @ loader.js:1833
i._resolve @ loader.js:1781
i.defineModule @ loader.js:1424
v @ loader.js:1871
define @ loader.js:1947
(anonymous) @ extensionService.ts:594
(anonymous) @ fake:1
TMScopeRegistry.ts:45 Overwriting grammar scope name to file mapping for scope source.sql.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/sql/syntaxes/sql.tmLanguage.json.
New grammar file: file:///Users/michael.harris/.vscode/extensions/mtxr.sqltools-0.23.0/language/sql.tmLanguage.json
register @ TMScopeRegistry.ts:45
A @ TMGrammarFactory.ts:72
_getOrCreateGrammarFactory @ abstractTextMateService.ts:227
async function (async)
_getOrCreateGrammarFactory @ abstractTextMateService.ts:216
createTokenizationSupport @ abstractTextMateService.ts:251
_create @ tokenizationRegistry.ts:145
resolve @ tokenizationRegistry.ts:139
getOrCreate @ tokenizationRegistry.ts:71
(anonymous) @ abstractTextMateService.ts:152
_handle @ extensionsRegistry.ts:144
acceptUsers @ extensionsRegistry.ts:135
_handleExtensionPoint @ abstractExtensionService.ts:913
_doHandleExtensionPoints @ abstractExtensionService.ts:859
_startLocalExtensionHost @ extensionService.ts:467
async function (async)
_startLocalExtensionHost @ extensionService.ts:438
_scanAndHandleExtensions @ extensionService.ts:432
_initialize @ abstractExtensionService.ts:526
async function (async)
_initialize @ abstractExtensionService.ts:524
(anonymous) @ extensionService.ts:110
requestIdleCallback (async)
e.runWhenIdle @ async.ts:1148
(anonymous) @ extensionService.ts:109
Promise.then (async)
rc @ extensionService.ts:107
_createInstance @ instantiationService.ts:110
_createServiceInstance @ instantiationService.ts:230
_createServiceInstanceWithOwner @ instantiationService.ts:219
_createAndCacheServiceInstance @ instantiationService.ts:208
_safeCreateAndCacheServiceInstance @ instantiationService.ts:151
_getOrCreateServiceInstance @ instantiationService.ts:135
_createInstance @ instantiationService.ts:88
createInstance @ instantiationService.ts:76
acquireInstantiationService @ configurationService.ts:461
(anonymous) @ workbench.ts:214
invokeFunction @ instantiationService.ts:61
initServices @ workbench.ts:208
startup @ workbench.ts:139
open @ desktop.main.ts:115
async function (async)
open @ desktop.main.ts:106
K @ desktop.main.ts:378
m.load.configureDeveloperSettings @ workbench.js:32
(anonymous) @ bootstrap-window.js:180
i._invokeFactory @ loader.js:1185
i.complete @ loader.js:1195
i._onModuleComplete @ loader.js:1821
i._onModuleComplete @ loader.js:1833
i._resolve @ loader.js:1781
i.defineModule @ loader.js:1424
v @ loader.js:1871
define @ loader.js:1947
(anonymous) @ extensionService.ts:594
(anonymous) @ fake:1
console.ts:137 [Extension Host] vscode
console.ts:137 [Extension Host] rejected promise not handled within 1 second: Error: TreeError [prStatus:github] Data tree node not found: [object Object]
I @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:472
_invokeHandler @ rpcProtocol.ts:457
_receiveRequest @ rpcProtocol.ts:373
_receiveOneMessage @ rpcProtocol.ts:295
(anonymous) @ rpcProtocol.ts:160
fire @ event.ts:628
fire @ ipc.net.ts:638
_receiveMessage @ ipc.net.ts:958
(anonymous) @ ipc.net.ts:831
fire @ event.ts:628
acceptChunk @ ipc.net.ts:382
(anonymous) @ ipc.net.ts:338
x @ ipc.net.ts:60
emit @ events.js:315
addChunk @ internal/streams/readable.js:309
readableAddChunk @ internal/streams/readable.js:284
Readable.push @ internal/streams/readable.js:223
onStreamRead @ internal/stream_base_commons.js:188
console.ts:137 [Extension Host] stack trace: Error: TreeError [prStatus:github] Data tree node not found: [object Object]    at se.getDataNode (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:201:19917)    at se.getNode (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:201:17566)    at fe (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:655:34927)    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:67:4675    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:67:4808    at Array.forEach (<anonymous>)    at r.bufferEvents (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:67:4797)    at v.setCollapsible (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:82:10582)    at v.spliceSimple (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:82:9606)    at v.splice (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:82:7530)    at A._setChildren (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:82:17603)    at A.setChildren (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:82:17005)    at I.setChildren (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:201:6680)    at se.render (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:201:23336)    at se.refreshAndRenderNode (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:201:20057)    at processTicksAndRejections (internal/process/task_queues.js:93:5)    at async se._updateChildren (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:201:17119)    at async se.updateChildren (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:201:16785)    at async Promise.all (index 0)    at async pe.doRefresh (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2587:15187)
I @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:472
_invokeHandler @ rpcProtocol.ts:457
_receiveRequest @ rpcProtocol.ts:373
_receiveOneMessage @ rpcProtocol.ts:295
(anonymous) @ rpcProtocol.ts:160
fire @ event.ts:628
fire @ ipc.net.ts:638
_receiveMessage @ ipc.net.ts:958
(anonymous) @ ipc.net.ts:831
fire @ event.ts:628
acceptChunk @ ipc.net.ts:382
(anonymous) @ ipc.net.ts:338
x @ ipc.net.ts:60
emit @ events.js:315
addChunk @ internal/streams/readable.js:309
readableAddChunk @ internal/streams/readable.js:284
Readable.push @ internal/streams/readable.js:223
onStreamRead @ internal/stream_base_commons.js:188
log.ts:313   ERR TreeError [prStatus:github] Data tree node not found: [object Object]: Error: TreeError [prStatus:github] Data tree node not found: [object Object]
    at se.getDataNode (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:201:19917)
    at se.getNode (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:201:17566)
    at fe (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:655:34927)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:67:4675
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:67:4808
    at Array.forEach (<anonymous>)
    at r.bufferEvents (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:67:4797)
    at v.setCollapsible (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:82:10582)
    at v.spliceSimple (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:82:9606)
    at v.splice (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:82:7530)
    at A._setChildren (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:82:17603)
    at A.setChildren (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:82:17005)
    at I.setChildren (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:201:6680)
    at se.render (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:201:23336)
    at se.refreshAndRenderNode (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:201:20057)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async se._updateChildren (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:201:17119)
    at async se.updateChildren (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:201:16785)
    at async Promise.all (index 0)
    at async pe.doRefresh (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2587:15187)

```

**Comment by mharris717** [comment] 2022-02-28 16:35
If you have trouble reproing from here lmk, happy to attempt to repro my repro / narrow down the cause 🤣

**Comment by alexr00** [comment] 2022-03-01 12:31
@mharris717 this helps, thank you. I haven't been able to repro the issue yet, so I think this is a timing issue. Do you use the "mark file as viewed" feature when reviewing pull requests?

**Comment by mharris717** [comment] 2022-03-01 14:46
Nope. These are generally my own PRs, I often just like the view to see my pushed changes so far.

**Comment by mharris717** [comment] 2022-03-01 14:47
I can try to do another repro while recording my screen, will do that today if I have time.

**Comment by mharris717** [comment] 2022-03-01 14:48
And just to be clear on how I have things setup 
![image](https://user-images.githubusercontent.com/64296/156190631-76c83332-8b27-43e2-8e5e-bfaa61697c81.png)

**Comment by alexr00** [comment] 2022-04-26 13:45
@mharris717 I've been using the extension for my regular work without seeing this issue for at least one month. If you're still seeing the problem then I'll add some additional logs and then we can keep looking.

**Comment by alexr00** [comment] 2022-05-04 15:02
Closing as it seems this is no longer reproducible

**Closed by alexr00** 2022-05-04 15:02 UTC
Labels: bug
