### ISSUE TITLE
Files that have only been renamed don't open in editor

### ISSUE THREAD

**Issue by Graham42** [Microsoft/vscode-pull-request-github#447] opened 2018-09-12 14:11 UTC
Issue Type: <b>Bug</b>

1. Open a PR that only renames a file, doesn't change any of the file content.
2. View that PR in VS Code using this extension
3. Click on the file that has only been renamed
4. It will open in the browser instead of in the editor

Extension version: 0.1.3
VS Code version: Code 1.27.1 (5944e81f3c46a3938a82c701f96d7a59b074cfdc, 2018-09-06T09:21:47.222Z)
OS version: Linux x64 4.4.0-135-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|31.09GB (15.92GB free)|
|Process Argv|/usr/share/code/code .|
|Screen Reader|no|
|VM|44%|

</details>

**Comment by RMacfarlane** [comment] 2018-09-12 16:29
Closing this as a duplicate of https://github.com/Microsoft/vscode-pull-request-github/issues/442, since the root cause is the same

**Closed by RMacfarlane** 2018-09-12 16:29 UTC
Labels: ux
