### ISSUE TITLE
No feedback in UI when organization is not authorized

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode-pull-request-github#2527] opened 2021-02-25 05:49 UTC
Issue Type: <b>Bug</b>

1. In the VS Code repo on a new machine
1. Sign in but forget to authorize the `microsoft` organization
1. Go to pr/issues view 
1. It is empty. 
1. Try pressing refresh and nothing happens

In the logs, I see

```
[Info] GithubRepository> Unable to fetch PR: Error: GraphQL error: Resource protected by organization SAML enforcement. You must grant your OAuth token access to this organization.
[Info] GithubRepository> Unable to fetch issues: Error: GraphQL error: Resource protected by organization SAML enforcement. You must grant your OAuth token access to this organization.
```

It would be great if this error was shown to users in the UI too

Extension version: 2021.2.34443
VS Code version: Code - Insiders 1.54.0-insider (c47da720f351455681978a48edc4d9a0d095ea0e, 2021-02-24T11:23:03.943Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.04GB (1.30GB free)|
|Process Argv|--crash-reporter-id 98ab83f8-a588-4ded-9863-d25098038154 --crash-reporter-id 98ab83f8-a588-4ded-9863-d25098038154 --crash-reporter-id 98ab83f8-a588-4ded-9863-d25098038154|
|Screen Reader|no|
|VM|100%|
</details>

**Comment by alexr00** [comment] 2021-11-19 15:56
duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/2385

**Closed by alexr00** 2021-11-19 15:56 UTC
