### ISSUE TITLE
Reviewer listed twice after delete and add

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode-pull-request-github#988] opened 2019-02-25 18:24 UTC
- Extension version: Nightly 1.56.0
- VSCode Version: 1.32 Insiders
- OS: Windows

Found while testing https://github.com/Microsoft/vscode/issues/69254

Steps to Reproduce:

1. In vscode-docs open an existing PR.
2. Delete a reviewer and then add them back

Initially the reviewer is shown twice. Refreshing the description corrects the issue. GitHub does not show the duplicate.

![image](https://user-images.githubusercontent.com/12818376/53359328-78650d00-38e7-11e9-9e31-3ef7b7c545b5.png)

Repro is intermittent.

**Comment by gregvanl** [comment] 2019-02-25 18:31
Can also see this will Labels if you remove and then add back a labels.

![image](https://user-images.githubusercontent.com/12818376/53359681-79e30500-38e8-11e9-8b6a-94b02bb189df.png)

**Comment by RMacfarlane** [comment] 2019-10-15 21:55
Closing this since I'm no longer able to reproduce it

**Closed by RMacfarlane** 2019-10-15 21:55 UTC
Labels: bug, description page

**Comment by rajesh-pandian** [comment] 2019-11-20 17:15
We are getting PR's listed twice under the Review Request tab.
Is this a bug in Github?
![image](https://user-images.githubusercontent.com/24638162/69261355-6622b180-0b8f-11ea-95f3-2ddd4f556885.png)

**Comment by RMacfarlane** [comment] 2019-11-20 17:17
@rajesh-pandian Do you mean on GitHub as in your screenshot, or in the GitHub Pull Requests tree in VSCode?

**Comment by rajesh-pandian** [comment] 2019-11-20 17:20
in GitHub as in the screenshot.

**Comment by RMacfarlane** [comment] 2019-11-20 17:31
Then this would be an issue with GitHub. You can see if anyone else has reported it at https://github.community/ or try contacting their support
