### ISSUE TITLE
Pull Request view still shows PR after I checkout out a different branch in terminal

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-pull-request-github#4381] opened 2023-01-04 16:42 UTC
1. Checkout some PR so that it shows in the GH PR view
2. Open terminal. In the terminal switch back to the main `main` branch
3. GH PR view still shows the PR 🐛 

Are we listening on git events that change branches? Should we automatically get out of PR review mode here? Or am I missing some git events on my machine again?

![Screenshot 2023-01-04 at 17 42 22](https://user-images.githubusercontent.com/1926584/210605369-2d01cf79-10c5-4062-89cc-bc982d875296.png)

**Comment by alexr00** [comment] 2023-01-05 10:31
> Are we listening on git events that change branches? Should we automatically get out of PR review mode here? Or am I missing some git events on my machine again?

We are listening to these events, and we should automatically get out of PR review mode here. I do suspect you're missing git events again. Next time you see this can you go to the SCM view and refresh?

**Comment by alexr00** [comment] 2023-01-05 14:12
>  A different PR got shown in my GITHUB PULL REQUEST view. Going to the SCM view and hitting refresh did not change anything.

I have started seeing this too. I'm following up with @mjbvz to see if I'm doing something wrong with disposing of a webview view and reregistering it.

**Comment by alan345** [comment] 2023-01-13 22:32
Hello, 
Same issue here: 
I see Some (not all of them) PRs even though they are all merged.
<img width="1487" alt="image" src="https://user-images.githubusercontent.com/15246526/212431296-801a5dd7-59fb-4ce2-926c-07f3e8d0c7f6.png">

How can I hide them because there are no pending actions

**Comment by alexr00** [comment] 2023-01-17 10:46
@alan345 do you still have those branches checked out? If so, this is the intended behavior. If you don't want to show merged PRs you can set: 
```
"githubPullRequests.useReviewMode": {
  "merged": false
}
```

**Comment by austinbutler** [comment] 2023-03-15 20:42
Seeing this right now. Switched branch to `master` from a separate terminal, then opened VS Code and it's showing a PR I have in a branch _from_ `master` set to auto-merge _to_ `master`. 

The bottom-left branch indicator shows `master`, yet the PR view in VS Code shows:
![image](https://user-images.githubusercontent.com/354741/225436863-6e8983b6-3e6f-4285-9e99-6543e3097a8e.png)

And the same view shows `austinbutler wants to merge changes into <myrepo>:master
from
<myrepo>:<mybranch>`. Clicking refresh doesn't do anything.

**Comment by alexr00** [comment] 2023-03-16 10:21
@austinbutler it sounds like you're talking about the PR description/overview which shows in the editor. That is not related to the current branch and instead shows the PR description/overview of the PR that you opened it from.

**Comment by robhung** [comment] 2023-04-07 04:13
Getting the same issue when I checkout `master` on my repo - the plugin thinks I'm still checked out on an old branch, showing me diff and comments related to that PR.

Works fine if I checkout to a separate branch, but my `master` is now always tainted with the old branch which will never go away.

Have tried toggling enable/disable on plugin, as well as reinstalling it - no change.

**Comment by alexr00** [comment] 2023-04-13 13:55
@robhung this sounds like https://github.com/microsoft/vscode-pull-request-github/issues/4642. I have some questions about your setup:
- Do you have a clone of a repo with an upstream remote another remote that's a fork that you own of the upstream?
- If so, is the remote of your `master` branch the upstream repo, or your fork?

Until I do figure it out you can "unpollute" your `master` branch by opening the `.git/config` file, finding the section that starts with `[branch "master"]`, and deleting the `github-pr-owner-number` line from there.

**Comment by alexr00** [comment] 2023-06-20 09:26
[This](https://github.com/microsoft/vscode-pull-request-github/issues/4381#issuecomment-1372264688) should be fixed now.

**Closed by alexr00** 2023-06-20 09:26 UTC
Labels: info-needed

**Comment by robhung** [comment] 2023-11-01 22:53
> @robhung this sounds like #4642. I have some questions about your setup:
> 
> * Do you have a clone of a repo with an upstream remote another remote that's a fork that you own of the upstream?
> * If so, is the remote of your `master` branch the upstream repo, or your fork?
I have the same repo checked out in two computers, but no clones of the repo on the same computer. I do have a clone of the VS code workspace for the same repo, does that affect the plugin?

> Until I do figure it out you can "unpollute" your `master` branch by opening the `.git/config` file, finding the section that starts with `[branch "master"]`, and deleting the `github-pr-owner-number` line from there.
This worked perfectly, thank you!
