### ISSUE TITLE
Per-Commit Comments

### ISSUE THREAD

**Issue by ldelossa** [microsoft/vscode-pull-request-github#3957] opened 2022-09-19 03:10 UTC
Per commit reviewing is pretty good in `vscode-pull-request-github`. However, would it be possible to allow commenting on files per-commit. The GitHub API should handle these cases OK and set the comments to "outdated" when they reference changed or missing lines in children commits.

**Comment by alexr00** [comment] 2022-09-21 12:29
Agree that this would be good to have. Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/2793

**Closed by alexr00** 2022-09-21 12:29 UTC
