### ISSUE TITLE
Context menu on the PR should have option to Exit Review Mode

### ISSUE THREAD

**Issue by ramya-rao-a** [microsoft/vscode-pull-request-github#595] opened 2018-10-20 18:05 UTC
Issue Type: <b>Feature Request</b>

Context menu on the PR has the option to Checkout PR.
Once the PR is checked out, it should have an option to Exit Review Mode as well

Extension version: 0.2.1
VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:12.403Z)
OS version: Windows_NT ia32 10.0.17134

**Comment by RMacfarlane** [comment] 2019-10-09 23:31
Closing as a duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/199

**Closed by RMacfarlane** 2019-10-09 23:31 UTC
Labels: enhancement
