### ISSUE TITLE
PR title is not populated from commit

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-pull-request-github#5865] opened 2024-03-22 18:58 UTC
Type: <b>Bug</b>

I used to be able to make a commit, then "Create Pull Request", and the PR title would be whatever my last commit message was. Now this happens sometimes but usually the PR title is empty.

```
2024-03-22 13:28:40.781 [info] Review+2> Resolved PR #199720, state is 1
2024-03-22 13:28:41.930 [info] Review+2> This PR is merged
2024-03-22 13:55:58.950 [info] Review+2> Validate state in progress
2024-03-22 13:55:58.950 [info] Review+2> Validating state...
2024-03-22 13:55:58.982 [info] PullRequestGitHelper> associate roblou/immense-snake with base branch microsoft/vscode#main
2024-03-22 13:55:59.033 [info] Found GitHub remote for folder /Users/roblou/code/vscode
2024-03-22 13:55:59.042 [info] Using in-memory cached assignable users.
2024-03-22 13:55:59.580 [info] Review+2> No matching pull request metadata found locally for current branch roblou/immense-snake
2024-03-22 13:55:59.632 [info] Review+2> No matching pull request metadata found on GitHub for current branch roblou/immense-snake
2024-03-22 13:56:08.600 [info] Review+2> Validate state in progress
2024-03-22 13:56:08.600 [info] Review+2> Validating state...
2024-03-22 13:56:08.735 [info] Found GitHub remote for folder /Users/roblou/code/vscode
2024-03-22 13:56:08.742 [info] Using in-memory cached assignable users.
2024-03-22 13:56:09.039 [info] Review+2> No matching pull request metadata found locally for current branch roblou/immense-snake
2024-03-22 13:56:09.107 [info] Review+2> No matching pull request metadata found on GitHub for current branch roblou/immense-snake
2024-03-22 13:56:25.891 [info] CreatePullRequestViewProvider> Initializing "create" view: {"defaultBaseRemote":{"owner":"microsoft","repositoryName":"vscode"},"defaultBaseBranch":"main","defaultCompareRemote":{"owner":"microsoft","repositoryName":"vscode"},"defaultCompareBranch":"roblou/immense-snake","defaultTitle":"","defaultDescription":"<!-- Thank you for submitting a Pull Request. Please:\n* Read our Pull Request guidelines:\n  https://github.com/microsoft/vscode/wiki/How-to-Contribute#pull-requests\n* Associate an issue with the Pull Request.\n* Ensure that the code is up-to-date with the `main` branch.\n* Include a description of the proposed changes and how to test them.\n-->\n","defaultMergeMethod":"squash","baseHasMergeQueue":false,"remoteCount":1,"allowAutoMerge":true,"mergeMethodsAvailability":{"merge":true,"squash":true,"rebase":true},"autoMergeDefault":true,"createError":"","labels":[],"isDraftDefault":false,"isDarkTheme":true,"generateTitleAndDescriptionTitle":"Generate with Copilot","creating":false,"initializeWithGeneratedTitleAndDescription":false}
```

Extension version: 0.85.2024032111
VS Code version: Code - Insiders 1.88.0-insider (409da0445d397e37a790ce5d2499688955c3fcfa, 2024-03-22T05:51:39.055Z)
OS version: Darwin x64 23.4.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|6, 5, 4|
|Memory (System)|32.00GB (0.04GB free)|
|Process Argv|--enable-proposed-api roblourens.chat-agent-dalle --enable-proposed-api ms-vscode.dscopilot-agent --crash-reporter-id a2c1d522-e9f0-4e3f-b78a-9253f1c2d2d3|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256197
vscod805cf:30301675
vsaa593:30376534
py29gd2263:30784851
vscaac:30438845
c4g48928:30535728
2i9eh265:30646982
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30926734
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
h48ei257:30992801
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
d6fi2104:30968146
cppperfnew:30980852
d34g3935:30961436
fegfb526:30952798
bg6jg535:30979844
ccp1r6:30958151
pythonait:30973460
7ghi1836:30988844

```

</details>

**Comment by alexr00** [comment] 2024-03-26 13:04
Has your system been slower recently? Since October there's been a 5 second timeout to get the latest commit message. You might be hitting that. I've added logs so we can see if that's actually what's happening.

**Comment by ulugbekna** [comment] 2024-04-03 12:32
Could you have this setting accidentally added to your settings? 🤔 

```
  "githubPullRequests.pullRequestDescription": "none",
```

**Comment by alexr00** [comment] 2024-04-04 10:32
Closing since I can't repro. If you see it again please share logs (info log level is fine) so we can see if the problem is that the timeout is being hit. I've also added telemetry so I can see how often this happens.

**Comment by roblourens** [comment] 2024-04-13 20:02
https://github.com/microsoft/vscode-pull-request-github/issues/5923 would explain why it's slow for me though

**Comment by alexr00** [comment] 2024-04-15 10:27
`2024-04-12 12:27:22.521 [info] CreatePullRequestViewProvider> Timeout getting last commit message`

You're definitely hitting the timeout. https://github.com/microsoft/vscode-pull-request-github/issues/5923 is from trying to find a PR template, which I can fix by using GitHub API instead of searching the filesystem.

**Comment by alexr00** [comment] 2024-04-19 09:16
I checked the data, and there isn't any spike in the number of users hitting the timeout. It seems to stay between 0 and 20 users per day. Let me know if you see this again with https://github.com/microsoft/vscode-pull-request-github/issues/5923 fixed!

**Comment by alexr00** [comment] 2024-12-16 11:11
Closing since the many ripgrep issue's slowness may have caused the slowness in getting the commit message.

**Closed by alexr00** 2024-12-16 11:11 UTC
Labels: bug
