### ISSUE TITLE
Update pending state after submitting review

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#794] opened 2019-01-07 19:42 UTC
ext version: 1.7.1

Repro:

1. Add comment(s) to review
2. Submit review

![image](https://user-images.githubusercontent.com/2193314/50789463-3584a280-1271-11e9-98d3-2480a1521edd.png)

**Comment by RMacfarlane** [comment] 2019-10-16 01:28
Closing as I'm not able to reproduce this with the latest version of the extension

**Closed by RMacfarlane** 2019-10-16 01:28 UTC
Labels: bug
