### ISSUE TITLE
Double plus looks like a visual glitch

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-pull-request-github#856] opened 2019-01-29 13:42 UTC
Refs: https://github.com/Microsoft/vscode/issues/67294

Hover over the + while looking at the change in PR extension.
Double plus looks like a visual glitch

![screenshot 2019-01-29 at 14 41 54](https://user-images.githubusercontent.com/1926584/51912242-1b536580-23d4-11e9-86ed-985e4427a10c.png)

**Comment by RMacfarlane** [comment] 2020-11-10 18:48
Closing as a duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/286

**Closed by RMacfarlane** 2020-11-10 18:48 UTC
Labels: comments, ux
