### ISSUE TITLE
Cross Repo view like "Pull Requests" view on github.com

### ISSUE THREAD

**Issue by tchkreddy** [microsoft/vscode-pull-request-github#2013] opened 2020-07-20 04:58 UTC
Currently, I can see PRs only from one repo.Most companies use tracks across multiple repos, so it would be better to simulate the list like the one on "Pull Requests" tab of github.com

**Comment by RMacfarlane** [comment] 2020-07-21 16:26
This looks like a duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/1583, let's track it there

**Closed by RMacfarlane** 2020-07-21 16:26 UTC
