### ISSUE TITLE
Git Hub User Per Workspace

### ISSUE THREAD

**Issue by scrossan-crown** [microsoft/vscode-pull-request-github#415] opened 2018-09-11 15:36 UTC
I work on my personal and work projects on the same machine and would like to be able to use a different user specified by a setting per workspace in the same way that extensions can be disabled per workspace.

**Comment by alexr00** [comment] 2021-11-17 13:58
@TylerLeonhardt is this possible using just the auth UX? I think the answer is no, but I wanted to check.

**Comment by TylerLeonhardt** [comment] 2021-11-17 16:59
GitHub doesn't support multiple accounts at the moment:

https://github.com/microsoft/vscode/issues/127967

**Comment by alexr00** [comment] 2021-11-18 08:37
Duplicate of the upstream https://github.com/microsoft/vscode/issues/127967 then.

**Closed by alexr00** 2021-11-18 08:37 UTC
Labels: feature-request, github
