### ISSUE TITLE
Tunneling socket issue, status code 502

### ISSUE THREAD

**Issue by szalonna** [microsoft/vscode-pull-request-github#1567] opened 2020-03-12 09:25 UTC
# Environment
- Extension version: 0.14.0
- VSCode Version: 1.43.0
- OS: Windows 10 Pro

# Steps to Reproduce

1. Corporate network with proxy and a Github Enterprise repository, repo authentication uses SSH key
2. Installed extension
3. No PR is visible

# Output
```
[Info] GitHubServer> No response from host https://github.[   ].com/[   ]/[   ]-repo: tunneling socket could not be established, statusCode=502
[Info] No remote with name 'origin' found. Please update your 'githubPullRequests.remotes' setting.
[Info] No remote with name 'upstream' found. Please update your 'githubPullRequests.remotes' setting.
```

# Git remote
```
λ git remote -v
origin  git@github.[   ].com:[   ]/[   ]-repo.git (fetch)
origin  git@github.[   ].com:[   ]/[   ]-repo.git (push)
```

# Environment variables
`http_proxy` and `https_proxy` is set to the same proxy. 

# VSCode config
- Http: Proxy: set manually to the proxy
- Http: Proxy Strict SSL: disabled
- Http: Proxt support for extensions: on

**Comment by alexr00** [comment] 2020-11-11 15:54
duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/701

**Closed by alexr00** 2020-11-11 15:54 UTC
