### ISSUE TITLE
Expected for checking out pull request command to be generalized

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode-pull-request-github#3155] opened 2021-12-01 16:51 UTC
Testing #3144

<img width="642" alt="CleanShot 2021-12-01 at 08 48 41@2x" src="https://user-images.githubusercontent.com/35271042/144277151-02f997a4-3347-4c05-9f70-b0a76e44efda.png">

While the original use case for checking out a PR via # is achieved in this new command, i would've expected a more generalized solution. Like, instead of "Checkout Pull Request by Number" why not "Checkout Pull Request" and have the quick pick show the list of PRs? Adding the number or url would just immediately check that PR out.

<img width="299" alt="CleanShot 2021-12-01 at 08 49 59@2x" src="https://user-images.githubusercontent.com/35271042/144277212-0d19a7fc-311c-486a-8fbe-094937d6395c.png">

**Comment by alexr00** [comment] 2021-12-02 08:46
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/3151

**Closed by alexr00** 2021-12-02 08:47 UTC
