### ISSUE TITLE
Support updating branch

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#615] opened 2018-10-24 23:09 UTC
My merge flow goes like this:

1. Approve
2. Assign milestone (https://github.com/Microsoft/vscode-pull-request-github/issues/614)
3. Open issue and assign milestone
3. **Maybe update branch if I'm concerned about recent changes on master**
4. Merge

![image](https://user-images.githubusercontent.com/2193314/47466665-27ad9e00-d7a7-11e8-8bc2-8536521b9696.png)

**Comment by RMacfarlane** [comment] 2019-10-09 18:08
Closing as a duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/200

**Closed by RMacfarlane** 2019-10-09 18:08 UTC
Labels: enhancement
