### ISSUE TITLE
File level comment is not collapsed by default despite the `collapseAll` in settings

### ISSUE THREAD

**Issue by DemianParkhomenko** [microsoft/vscode-pull-request-github#5678] opened 2024-01-24 15:23 UTC
- Extension version: v0.78.1
- VSCode Version: 
Version: 1.85.2
Commit: 8b3775030ed1a69b13e4f4c628c612102e30a681
Date: 2024-01-18T06:40:11.430Z
Electron: 25.9.7
ElectronBuildId: 26354273
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 23.2.0
- OS: macOS Sonoma Version 14.2.1

Steps to Reproduce:

1. Set `collapseAll` in settings. 
2. Open file with file level comment and comment is expanded. 

I am expecting that all comments should collapsed.

https://github.com/microsoft/vscode-pull-request-github/assets/95881717/afa5fad1-586f-4a8e-9006-462c06575e40

**Comment by alexr00** [comment] 2024-02-05 11:07
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/5512, which is fixed in 0.80.

**Closed by alexr00** 2024-02-05 11:07 UTC
