### ISSUE TITLE
Extension issue: is not valid menu identifier

### ISSUE THREAD

**Issue by Taneros** [microsoft/vscode-pull-request-github#3494] opened 2022-04-26 19:22 UTC
- Issue Type: `Bug`
- Extension Name: `vscode-pull-request-github`
- Extension Version: `0.40.0`
- OS Version: `Windows_NT x64 10.0.19044`
- VS Code version: `1.66.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

![image](https://user-images.githubusercontent.com/9476807/165376385-9d7d0804-a12a-40ea-addd-6c4bd6b15417.png)

**Comment by alexr00** [comment] 2022-05-03 11:37
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/3417, and sadly by design.

**Closed by alexr00** 2022-05-03 11:37 UTC
