### ISSUE TITLE
Submodules not always appear in list

### ISSUE THREAD

**Issue by oleg-liatte** [microsoft/vscode-pull-request-github#5148] opened 2023-08-04 09:51 UTC
- Extension version: v0.70.0
- VSCode Version:
```
Version: 1.81.0 (system setup)
Commit: 6445d93c81ebe42c4cbd7a60712e0b17d9463e97
Date: 2023-08-02T12:37:13.485Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045
```

### Steps to Reproduce:
1. Open repository with multiple submodules in it. In my case there are about 10 submodules including recursive ones (sub-submodules)
2. Open `GitHub` at sidebar

### Result:
Only root repository's PRs are displayed. Sometimes few submodules (in addition to the main repo) also appear in list, but I never saw all of them

### Expected:
Main repo and all submodules with their PRs are always accessible at `GitHub` panel.

### Workaround:
1. Disable `GitHub Pull Requests and Issues` module
2. Execute `Developer: Reload Window` command or just restart vscode
3. Wait until all submodules are loaded and appeared in `Source Control` panel
4. Enable `GitHub Pull Requests and Issues` module again
5. All submodules (and their PRs) are displayed in `GitHub` panel

**Comment by oleg-liatte** [comment] 2023-08-04 09:52
I suspect there is a race between `Source Control` and `GitHub`: the latter does not wait/sync to the former

**Comment by alexr00** [comment] 2023-08-07 14:16
We are lacking support for submodules. Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/4688

**Closed by alexr00** 2023-08-07 14:16 UTC
