### ISSUE TITLE
Group reviewer support

### ISSUE THREAD

**Issue by AngerM** [Microsoft/vscode-pull-request-github#1140] opened 2019-05-01 18:49 UTC
My org has a bunch of reviewer groups, unfortunately the vscode github extension doesn't show these as reviewers to choose from, and even if I add them from the github web ui, they don't show up in the vscode extension as people tagged in the review.
![image](https://user-images.githubusercontent.com/1715525/57035542-2c945400-6c07-11e9-87b4-bd66a4fcb185.png)
![Screen Shot 2019-05-01 at 11 49 13 AM](https://user-images.githubusercontent.com/1715525/57035553-31f19e80-6c07-11e9-945e-bfe7e58a9728.png)

**Comment by RMacfarlane** [comment] 2019-05-01 18:51
Hey @AngerM, this looks like a duplicate of https://github.com/Microsoft/vscode-pull-request-github/issues/1126. Let's track it there.

**Closed by RMacfarlane** 2019-05-01 18:51 UTC
