### ISSUE TITLE
Unable to comment on added files in a PR when file is opened from the commits tree view

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-pull-request-github#3836] opened 2022-08-10 06:20 UTC
- Extension version: v0.49.2022080912
- VSCode Version: 1.71-insider
- OS: Windows 11

Steps to Reproduce:

1. Open a PR with an added file
2. ✅ from Files tree node, can open an added file and see comment ranges
3. :bug: from Commits tree node, cannot see comment ranges in added file
![image](https://user-images.githubusercontent.com/30305945/183828385-aea6f49d-0c48-46ae-959f-aa0ed8bfccbc.png)

**Comment by alexr00** [comment] 2022-08-10 12:10
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/2793

**Closed by alexr00** 2022-08-10 12:10 UTC
