### ISSUE TITLE
Comments panel is way too aggressive

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode-pull-request-github#165] opened 2018-08-10 07:47 UTC
I thoroughly dislike the comments panel opening at any given opportunity. It even opens up when there aren't any comments to read.

For example, I just checked out this PR:

![image](https://user-images.githubusercontent.com/22350/43945444-5f9a0c6e-9c82-11e8-8e02-ec158412d2d7.png)

First thing after checking out, the comments panel opens up empty.

**Comment by RMacfarlane** [comment] 2018-08-10 14:54
Duplicate of https://github.com/Microsoft/vscode-pull-request-github/issues/70

**Closed by RMacfarlane** 2018-08-10 14:54 UTC
