### ISSUE TITLE
Changeable Git URL

### ISSUE THREAD

**Issue by zimaitis** [microsoft/vscode-pull-request-github#2315] opened 2020-12-04 14:46 UTC
Change git URL. If you have a company github like https://github.my-company.com/ you cannot authenticate or connect

**Comment by RMacfarlane** [comment] 2020-12-07 16:22
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/1793

**Closed by RMacfarlane** 2020-12-07 16:22 UTC
