### ISSUE TITLE
PR tree node collapses when checking out PR

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode-pull-request-github#362] opened 2018-09-04 12:58 UTC
Issue Type: <b>Bug</b>

- Expand a PR node under Assigned To Me.
- Click through file diffs.
- Right-click PR node and check out.
-> The PR node collapses.

Extension version: 0.0.22
VS Code version: Code - Insiders 1.27.0-insider (7b9afc4196bda60b0facdf62cfc02815509b23d6, 2018-09-03T09:07:33.052Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.17GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by RMacfarlane** [comment] 2018-09-04 14:48
Closing as a duplicate of https://github.com/Microsoft/vscode-pull-request-github/issues/238

**Closed by RMacfarlane** 2018-09-04 14:48 UTC
