### ISSUE TITLE
Allow All Open query to be configured

### ISSUE THREAD

**Issue by eric-g-97477** [microsoft/vscode-pull-request-github#6270] opened 2024-10-08 15:41 UTC
I can configure the query for Created By Me, etc. I would like to be able to configure the query for "All Open" as well.

**Comment by alexr00** [comment] 2024-12-17 11:32
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/1777

**Closed by alexr00** 2024-12-17 11:32 UTC
Labels: feature-request
