### ISSUE TITLE
Difference between GitHub PR review Web UI and this extension with changes since last review

### ISSUE THREAD

**Issue by seantleonard** [microsoft/vscode-pull-request-github#5455] opened 2023-11-09 20:49 UTC
Alluded to in #4510 (as a feature request, but this discrepancy seems like a **bug**) and #4618

Whenever I select "changes since last review" view in VSCode within this extension, the resulting PR file tree shows **all** files included in "merge latest main" commits. These 'merge main' commits can include dozens of files depending on the volume of activity in the project. and distract from the actual code changes I am trying to review. **This behavior differs from GitHub Web UI.** 

Alternatively, introducing a toggle which changes the behavior of whether those extraneous commits show in the PR review UI when using the vscode extension.

1. GitHub Review UI: **Excludes** merge commits from "changes since last review"
2. GitHub VSCode PR extension: **Includes** merge commits in "Changes since last review"

I feel this is a discrepancy that has made it near impossible in certain circumstances to use this extension for reviewing code. If there is something I could be doing differently, I would appreciate any guidance you may have since using this extension has enabled me to be way more productive in reviewing code. 

Is the GraphQL api used between the extension and GitHub web UI different? It seems like the api response returned to the webui automatically excludes such 'merge main' commits, meaning the there's no special way to format a request to pull "changes since last review" to accomplish this and the behavior should come for free?

**Comment by alexr00** [comment] 2023-12-15 10:12
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/4510

**Closed by alexr00** 2023-12-15 10:12 UTC
Labels: bug
