### ISSUE TITLE
Using multiple GitHub accounts

### ISSUE THREAD

**Issue by pfaltynek-als** [microsoft/vscode-pull-request-github#1904] opened 2020-06-15 08:34 UTC
I would like to use more GitHub accounts (for example one for private projects and other for jobs) But I cannot to find any way to register two Github accounts.

**Comment by nsoria1** [comment] 2020-08-16 14:17
Hi there! Thank you creating this extension. Just checking up if this feature request is in backlog or won't be in scope.

**Comment by alexr00** [comment] 2021-11-18 14:55
Duplicate of upstream issue: https://github.com/microsoft/vscode/issues/127967

**Closed by alexr00** 2021-11-18 14:55 UTC
Labels: feature-request
