### ISSUE TITLE
User should be able to specify a branch to checkout from

### ISSUE THREAD

**Issue by adedayojs** [microsoft/vscode-pull-request-github#2752] opened 2021-05-27 10:34 UTC
I believe when a user is about to start work on an issue and a branch is created, the user should be able to select an existing branch where the new branch is to be created from. Currently, by default, the new branch is created from master branch.

**Comment by alexr00** [comment] 2021-06-03 13:43
There is an existing setting for this! `"githubIssues.useBranchForIssues": "prompt"`.

**Comment by adedayojs** [comment] 2021-06-04 13:26
> There is an existing setting for this! `"githubIssues.useBranchForIssues": "prompt"`.

@alexr00 I mean that.

While checking out to a branch, i should be able to specify the base branch i am checking out from, not the name of the branch. 

For example if a new branch is about to be created for me by the extension, i should be able to specify and say "Hey create a new branch using master branch as the base branch" or "Hey create a new branch from develop branch"

**Comment by MartinBernstorff** [comment] 2023-12-18 08:42
Would love to be able to set this is a default as well!

**Comment by alexr00** [comment] 2023-12-18 11:00
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/1707

**Closed by alexr00** 2023-12-18 11:00 UTC
Labels: feature-request
