### ISSUE TITLE
Create fork

### ISSUE THREAD

**Issue by brianjmurrell** [microsoft/vscode-pull-request-github#3391] opened 2022-03-10 12:59 UTC
Issue Type: <b>Feature Request</b>

It would be nice to automatically create a fork of a repo you don't have write permissions to when working in such a repo.

Perhaps this is triggered when trying to push a branch you have created locally since you will not be able to push it to the remote you don't have write permission in.

Extension version: 0.38.0
VS Code version: Code 1.65.1 (8908a9ca0f221f36507231afb39d2d8d1e182702, 2022-03-08T02:09:03.269Z)
OS version: Linux x64 5.15.14-200.fc35.x86_64
Restricted Mode: No

**Comment by alexr00** [comment] 2022-03-21 13:02
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/2998

**Closed by alexr00** 2022-03-21 13:02 UTC
