### ISSUE TITLE
Select default base branch when checking out issue

### ISSUE THREAD

**Issue by MartinBernstorff** [microsoft/vscode-pull-request-github#5504] opened 2023-11-24 08:18 UTC
When checking out an issue into a new branch, I would love for a setting saying that checkout should happen from my `main` branch every time.

Current behaviour is to branch from the currently checked out branch. This means I carry the commits from the branch I working on into a new branch.

**Comment by alexr00** [comment] 2023-12-15 15:39
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/2752

**Closed by alexr00** 2023-12-15 15:39 UTC
Labels: feature-request
