### ISSUE TITLE
Cannot open current issue in web view

### ISSUE THREAD

**Issue by jooyoungseo** [microsoft/vscode-pull-request-github#5535] opened 2023-12-05 14:25 UTC
Type: <b>Feature Request</b>

For pull request, I can focus in the active pull request via `github:activePullRequest.focus` command. However, there is no similar command for issues. Please consider supporting `github:activeIssue.focus` command to view the current issue in web view.

![Recording 2023-12-05 at 08 22 43](https://github.com/microsoft/vscode-pull-request-github/assets/19754711/a0784e2e-19b8-486b-9b85-cb157307ebce)

Extension version: 0.77.2023120509
VS Code version: Code - Insiders 1.85.0-insider (c46c2f120b96f1d538333b263e42d1f133a200f0, 2023-12-05T09:50:32.134Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by Shepard777** [comment] 2023-12-06 00:32
Ka tu?

**Comment by alexr00** [comment] 2023-12-12 16:01
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/3433

**Closed by alexr00** 2023-12-12 16:02 UTC
