### ISSUE TITLE
Cannot open a closed PR

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-pull-request-github#6005] opened 2024-05-16 12:35 UTC
This may be a design limitation or cannot be supported, but it would be great if I could open a closed PR and still interact with it. I can do that on Github.com and still add comments and do code review.

Today when you open a closed PR by pressing `.` on github VSCode opens but not the PR.

**Comment by alexr00** [comment] 2024-05-21 11:07
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/4613. You can restore the branch to work around this.

**Closed by alexr00** 2024-05-21 11:07 UTC

**Comment by bpasero** [comment] 2024-05-21 11:40
In this case I am not sure if the branch was deleted and I am also not sure if I can restore a branch that I did not create 🤔

**Comment by alexr00** [comment] 2024-05-21 13:21
Hmm, if the branch is not deleted then maybe you have GHPR configured to not show the PR for closed PRs. Do you have `"githubPullRequests.useReviewMode": "auto"`? That should get you the behavior you want.

**Comment by bpasero** [comment] 2024-05-21 13:47
This is mainly pressing "." on a github.dev

**Comment by alexr00** [comment] 2024-05-21 14:59
The default value of `"githubPullRequests.useReviewMode"` is `auto`, but if you have setting sync turned on then you may have lost it.

**Comment by bpasero** [comment] 2024-05-21 15:02
Interesting, I had this configured, removed it now:

```
"githubPullRequests.useReviewMode": {
    "merged": false,
    "closed": false
}
```

**Comment by bpasero** [comment] 2024-05-21 15:03
Wow that was really it, thanks!

**Comment by alexr00** [comment] 2024-05-23 08:00
`auto` came later to resolve exactly this issue. Glad it worked!
