### ISSUE TITLE
Binning Issues by Milestones in custom queries

### ISSUE THREAD

**Issue by benedikt-mayer** [microsoft/vscode-pull-request-github#2216] opened 2020-10-20 15:23 UTC
In the `default` search query, issues are divided into a tree, based on milestones.

It would be great to enable users to build these tree structures themselves when writing custom queries.
A minimal version of this feature would be to allow the milestone-based structure via a flag like
```json
{
    "label": "Created Issues",
    "query": "author:${user} state:open repo:${owner}/${repository} sort:created-desc",
    "treeStructure": "on"
}
```
Even better would be to allow this tree structure to be based on github issue queries:
```json
{
    "label": "Created Issues",
    "query": "author:${user} state:open repo:${owner}/${repository} sort:created-desc",
    "treeStructure": "on",
    "splitBy": "milestone"
}
```
`splitBy` here also be something like `repo`.

**Comment by therealchjones** [comment] 2021-03-04 20:04
This appears to be a (more specific) duplicate of #1881

**Closed** 2021-11-18 16:55 UTC
Labels: duplicate, feature-request
