### ISSUE TITLE
Posting comments on a PR does not trigger GitHub workflow

### ISSUE THREAD

**Issue by cegekaJG** [microsoft/vscode-pull-request-github#5929] opened 2024-04-15 10:09 UTC
One of the workflow file in the repository linked below has the following property:
```yml
on:
  issue_comment:
    types:
      created
```

Despite this, GitHub workflows with the trigger `issue_comment` will not start when adding a comment to a PR from the extension's editor view. This error does not occur when commenting on the web client.

- Extension version: `v0.86.1`
- VSCode Version: `1.88.1`
- OS: Windows_NT x64 10.0.20348
- Repository Clone Configuration (single repository/fork of an upstream repository): https://github.com/cegekaJG/test-branch-update
- Github Product (Github.com/Github Enterprise version x.x.x): Github.com

Steps to Reproduce:

1. Open a repository with a workflow with the trigger `issue_comment: type: created`
2. Create a new PR and open the editor view of the PR
3. Submit a new comment

**Comment by alexr00** [comment] 2024-12-16 11:07
Duplicate of #5559

**Closed by alexr00** 2024-12-16 11:07 UTC
Labels: bug
