### ISSUE TITLE
Can't push to github actions workflow

### ISSUE THREAD

**Issue by Surendrajat** [microsoft/vscode-pull-request-github#1814] opened 2020-05-16 18:34 UTC
Issue Type: <b>Bug</b>

Whenever I update the actions workflow .yml file and push it fails with below error:
 ```
! [remote rejected] master -> master (refusing to allow an OAuth App to create or update workflow `.github/workflows/app.yml` without `workflow` scope)
```
Extension version: 0.16.0
VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:22.494Z)
OS version: Linux x64 5.3.0-51-generic

**Comment by MarkBennett** [comment] 2020-05-18 17:37
I'm having this issue as well, and just curious if there's a know workaround?

**Comment by RMacfarlane** [comment] 2020-05-18 17:41
Duplicate of https://github.com/microsoft/vscode/issues/97396, unfortunately there isn't a workaround right now but this should be fixed within this iteration

**Closed by RMacfarlane** 2020-05-18 17:41 UTC

**Comment by MarkBennett** [comment] 2020-05-18 17:44
> Duplicate of [microsoft/vscode#97396](https://github.com/microsoft/vscode/issues/97396), unfortunately there isn't a workaround right now but this should be fixed within this iteration

Thanks @RMacfarlane I'll follow that issue!

**Comment by Anselmoo** [comment] 2024-05-05 19:31
It might be a little bit of the topic, but

```shell
gh auth login --web -h github.com
```

helped to switch from `ssh` to `https` as recommended and pushed changes of the workflow files to the repo.
