### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Mamdouh-Saady** [microsoft/vscode-pull-request-github#3228] opened 2022-01-04 07:03 UTC
- Issue Type: `Performance`
- Extension Name: `vscode-pull-request-github`
- Extension Version: `0.32.0`
- OS Version: `Windows_NT x64 10.0.22000`
- VS Code version: `1.62.3`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\mamdo\AppData\Local\Temp\GitHub.vscode-pull-request-github-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by alexr00** [comment] 2022-01-07 12:28
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/841

**Closed by alexr00** 2022-01-07 12:28 UTC
