### ISSUE TITLE
github pr extension is unable to sign in, while other extensions are fine

### ISSUE THREAD

**Issue by syffs** [microsoft/vscode-pull-request-github#5785] opened 2024-02-27 10:03 UTC
- Extension version: 0.80.1
- VSCode Version: 1.86.2
- OS: W11 Pro
- Repository Clone Configuration (single repository/fork of an upstream repository): single repository
- Github Product (Github.com/Github Enterprise version x.x.x): Github.com

Steps to Reproduce:

1. Installed Github Pull Requests extension
2. Signed in/out multiple times from github
3. Github Copilot / Copilot chat extensions work well
4. Github Pull Requests extension keep showing the same pane with "You have not yet signed in with GitHub", and clicking on Sign in does not do anything:
<img width="283" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/4192037/faf85773-bfbc-47db-9a3f-88be6f1334b7">

**Comment by bavarianbidi** [comment] 2024-02-27 11:23
I have a similar issue where my enterprise-managed account (where the Copilot-license is handled) conflict with the PullRequest extension.

My current findings so far:
* since [v0.76.0](https://github.com/microsoft/vscode-pull-request-github/releases/tag/v0.76.0) the PR plugin has support for Copilot generated PR/Issue titles
* This requires copilot-scope access
* any previous granted copilot access (e.g. from another account) will get revoked - and with that copilot doesn't work anymore

My current solution:
I've downgraded PR plugin to version `v0.74.1` and with that, the Plugin only needs permissions to PullRequests.
And my enterprise-managed account (with the Copilot license) is still able to stay logged in.

**Comment by Am0rfu5** [comment] 2024-03-09 17:37
Version: 1.87.1
Commit: 1e790d77f81672c49be070e04474901747115651
Date: 2024-03-06T00:21:07.287Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Linux x64 6.5.0-14-generic

Same isse wth Github PR v0.82.0

Reproduced issue exactly as stated above by @syffs

**Comment by Am0rfu5** [comment] 2024-03-09 17:57
Spending 2 seconds reading the documentation fixed this for me.  In my case I named the remote 'github' instead of 'origin' or 'upstream'.   Just added that and it works fine.

Would add that having the Sign In fail makes sense BUT it isn't obvious what the issue is.  Could add a note under that "Sign In" dialog to validate that the remote name matches, just for my fellow midwits who don't read the docs.

**Comment by TylerLeonhardt** [comment] 2024-03-11 15:31
Multiple GitHub account in VS Code is tracked here: https://github.com/microsoft/vscode/issues/127967

**Comment by alexr00** [comment] 2024-12-16 11:33
This should be fixed now. Please do comment if you still see issues!

**Closed by alexr00** 2024-12-16 11:33 UTC
Labels: info-needed
