### ISSUE TITLE
Show some progress indicator when entering conflict resolution mode

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#5950] opened 2024-04-23 18:38 UTC
Testing #5939

Repro:

1. Open a PR description for conflicts
2. Click resolve conflicts, 🐛 no feedback for ~3 seconds apart from the button dimming

![image](https://github.com/microsoft/vscode-pull-request-github/assets/2193314/1dec08b8-c683-404b-93e0-29cba65ecd7e)

**Comment by Tyriar** [comment] 2024-04-23 18:45
I tried to resolve on #195255 and was waiting for over a minute. Eventually I got this:

![image](https://github.com/microsoft/vscode-pull-request-github/assets/2193314/3ae88db5-c18d-4315-a29c-5b7da901509d)

🤷

**Comment by Tyriar** [comment] 2024-04-23 18:49
![Recording 2024-04-23 at 11 49 07](https://github.com/microsoft/vscode-pull-request-github/assets/2193314/8228e7ee-ac37-417c-bf00-3651d6e52fe6)

**Comment by alexr00** [comment] 2024-04-24 08:28
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/5944

**Closed by alexr00** 2024-04-24 08:28 UTC
