### ISSUE TITLE
Commits show full name, reviews show handle

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode-pull-request-github#73] opened 2018-06-27 02:26 UTC
It should be consistently handle

![image](https://user-images.githubusercontent.com/2193314/41949542-aee885d6-7976-11e8-9426-c96b0cea4a3c.png)

**Comment by RMacfarlane** [comment] 2018-08-30 19:00
Duplicate of https://github.com/Microsoft/vscode-pull-request-github/issues/294

**Closed by RMacfarlane** 2018-08-30 19:00 UTC
Labels: enhancement, github, overview
