### ISSUE TITLE
Clicking PR description in "Changes In PR" view will not focus an already opened PR description tab

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode-pull-request-github#1094] opened 2019-03-29 19:58 UTC
Repro:

1. Check out a PR
2. Click the PR description (root node) in the "Changes in Pull Request" view
3. Click on a diff in Files
4. Click the PR description again, the tab will not be focused

**Comment by rebornix** [comment] 2019-03-29 21:00
Duplicate of https://github.com/Microsoft/vscode/issues/71463 .

**Closed** 2019-03-29 21:00 UTC
Labels: duplicate, upstream/vscode
