### ISSUE TITLE
"Open all files" button

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode-pull-request-github#1248] opened 2019-06-26 18:46 UTC
Issue Type: <b>Feature Request</b>

It'd be nice to have a quick way to open all changed files in a PR in their own tabs. Idk, just a thought. 

Extension version: 0.8.0
VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:29:22.216Z)
OS version: Darwin x64 18.6.0

**Comment by JeffreyCA** [comment] 2019-11-09 06:15
I can work on this 🙂

**Comment by alexr00** [comment] 2021-11-17 16:04
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/3047, because that one has more discussion.

**Closed by alexr00** 2021-11-17 16:04 UTC
Labels: feature-request
