### ISSUE TITLE
Double clicking a checkbox will result in delayed reaction

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode-pull-request-github#6194] opened 2024-08-30 11:22 UTC
1. As you review a PR, quickly click a checkbox twice

🐛 The checkbox state will toggle twice: once as you click, and another time after a few millis

https://github.com/user-attachments/assets/93c12c9e-8b08-4483-bcd2-c21d0da651f6

**Comment by alexr00** [comment] 2024-08-30 13:24
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/3972 🙂

**Closed by alexr00** 2024-08-30 13:24 UTC
Labels: bug
