### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'number')

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-pull-request-github#4893] opened 2023-06-07 04:38 UTC
Seeing this in insiders opening the `vscode` folder.

```
Extension Host] stack trace: TypeError: Cannot read properties of undefined (reading 'number')
    at Ut.createOrUpdatePullRequestModel (/Users/bpasero/.vscode-insiders/extensions/github.vscode-pull-request-github-0.65.2023060609/dist/extension.js:1705:4679)
    at Ut.getPullRequestForBranch (/Users/bpasero/.vscode-insiders/extensions/github.vscode-pull-request-github-0.65.2023060609/dist/extension.js:1703:39251)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Zi.getMatchingPullRequestMetadataFromGitHub (/Users/bpasero/.vscode-insiders/extensions/github.vscode-pull-request-github-0.65.2023060609/dist/extension.js:1781:7211)
    at Vi.checkGitHubForPrBranch (/Users/bpasero/.vscode-insiders/extensions/github.vscode-pull-request-github-0.65.2023060609/dist/extension.js:1784:6892)
    at Vi.validateState (/Users/bpasero/.vscode-insiders/extensions/github.vscode-pull-request-github-0.65.2023060609/dist/extension.js:1784:8322)
    at Vi.validateStatueAndSetContext (/Users/bpasero/.vscode-insiders/extensions/github.vscode-pull-request-github-0.65.2023060609/dist/extension.js:1784:5755) (at console.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:99:161026))
```

**Comment by chrmarti** [comment] 2023-06-09 06:58
I also see this in 0.66.0. The PR viewlet remain empty in loading state.

**Comment by chrmarti** [comment] 2023-06-09 07:03
This was working very recently in pre-releases, might be a recent regression.

Seeing this with the devcontainers/cli repo, but not with microsoft/vscode. Is there a workaround?

**Comment by alexr00** [comment] 2023-06-09 07:59
It should be fixed in pre-release on Monday. It is happening because the PR branch detection has gotten narrower and narrower. Are you seeing any functional problems? I expected this to just be an error in the console.

**Comment by Danp2** [comment] 2023-06-09 13:26
I'm seeing functional problems similar to #4890. I have to completely close the the working folder and then reopen it to make the current PR go away or switch to a different one.

**Comment by alexr00** [comment] 2023-06-09 15:34
I am seeing the functional problems now. Will fix in a recovery release early next week.

**Comment by Danp2** [comment] 2023-06-12 16:39
Just tried today's build and it's working much better. Thanks!

**Comment by alexr00** [comment] 2023-06-13 09:46
@Danp2 thank you for verifying! I will make a stable recovery release today.

**Closed by alexr00** 2023-06-13 09:46 UTC
Labels: bug, candidate
