### ISSUE TITLE
Not seeing automerge checkbox when I should be.

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-pull-request-github#3666] opened 2022-06-28 22:47 UTC
Testing #3657

On MacOS. 

Using: https://github.com/greazer/covid-19-data.
1. I created a new branch called "automerge2"
2. I trivially modified the first cell SampleNbsAndScripts/myanalysis_plotly.ipynb 
4. I checked in the change and published the branch.
5. Create a new pull request in VS Code per the instructions:

I don't see the auto-merge checkbox...
<img width="375" alt="image" src="https://user-images.githubusercontent.com/11685408/176316869-8ff5af26-5346-44e9-9aba-709da4b8a2db.png">

I verified:
1. That the repo below has automerge set. 
<img width="1557" alt="image" src="https://user-images.githubusercontent.com/11685408/176316607-b40a7373-06fe-47e9-904d-0cefcd7c16b2.png">

2. That I definitely do see the automerge checkbox in the new pull request webview for a different repo.
<img width="370" alt="image" src="https://user-images.githubusercontent.com/11685408/176317016-b19f6290-a6d5-4481-bcec-d7bdb004c9eb.png">

**Comment by alexr00** [comment] 2022-06-29 08:22
@greazer could this be a duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/3660?

**Closed** 2022-12-09 12:50 UTC
Labels: info-needed
