### ISSUE TITLE
Adopt prompt tsx: Rsponse too long

### ISSUE THREAD

**Issue by asifroyal** [microsoft/vscode-pull-request-github#6476] opened 2024-11-14 09:58 UTC
Type: <b>Bug</b>

Response too long issue while summarizing PR using copilot

Extension version: 0.100.1
VS Code version: Code 1.95.2 (e8653663e8840adaf45af01eab5c627a5af81807, 2024-11-07T11:07:22.054Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by alexr00** [comment] 2024-12-13 16:00
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/6367

**Closed by alexr00** 2024-12-13 16:00 UTC
Labels: bug, debt
