### ISSUE TITLE
Let us comment on and resolve review comments left by other in Description view

### ISSUE THREAD

**Issue by assanesuzy** [microsoft/vscode-pull-request-github#3361] opened 2022-02-28 17:50 UTC
It seems that looking at the list of files, any comments that are outdated do not show up as a comment in the files. This creates a problem because if there is a line shift, it makes any comments in those lines as outdated and they don't show up even though they are not either marked as resolved or still needed. In the description it would be nice if we can have the ability to resolve or comment on any review comments left by others. Shows the full list of comments which is a good alternative to using the github site.

**Comment by alexr00** [comment] 2022-03-02 14:41
@assanesuzy you should be able to see these comments in the comments view (command "View: Focus on Comments View"). If you click on them there, it will open a file at the commit with the comment and you can reply there. 

Does that work for you?

Side note: the comments view is not easy to find right now. We are going to make it easier to find.

**Comment by assanesuzy** [comment] 2022-03-02 15:10
That view is actually where my problem lies. The reason why I was mentioning the "Description" view is because the comments are not always up to date in the view you mentioned. There have been many instances where there were recent review comments added and they do not show up in the files in this same view. They are only visible in the "Description" view. I've tried refreshing and closing and opening, but the most recent review comments are never visible

**Comment by alexr00** [comment] 2022-03-02 15:25
@assanesuzy I think I understand now. The "review summary" comments only show in the Description:

![image](https://user-images.githubusercontent.com/38270282/156391506-04482b08-e84c-4943-ab91-4b12bdba9783.png)

However, the non-summary comments that are part of that review should be shown in the Comments view, so you should still be able to get to the non-summary comment from there. Does that work for you? If not, that's a bug and I'll look into it.

We are missing an easy way to go from the comment in the description view to the individual comments in files. We should add a button for this.

**Comment by assanesuzy** [comment] 2022-03-02 15:45
Interesting. What I'm missing is that section where it says "Add new review comment". When the I create a  PR and someone else leaves review summary with other non-summary comments, I am looking for the ability to leave a non-summary comment in response to whatever their comments are. I guess I'll wait for that feature to be released and I'll see if that fixes my issue. Thank you for your help.

**Comment by olafurw** [comment] 2023-03-29 14:25
I think this is the same thing I found missing.

![image](https://user-images.githubusercontent.com/103783/228569198-d414d18e-c8b8-4852-bc8d-71a723f3c656.png)

If you've left a comment through a review, there's no way to reply to that comment in the Description view. Which you can inside of the GitHub Pull Request page.

Also if you click on the file name, it does not show that comment inside of the file, it's hidden in the margins, and you have to find which one of the comments it is and expand it.

![image](https://user-images.githubusercontent.com/103783/228569907-604e487b-f98f-4ae0-8c94-dda8db9c8950.png)

**Comment by alexr00** [comment] 2023-03-29 15:34
@olafurw comments from you and resolved comments are collapsed into the margin by default. You can toggle expanding all comments by running the command Comments: Expand All comments.

**Comment by alexr00** [comment] 2024-12-17 11:50
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/601

**Closed by alexr00** 2024-12-17 11:50 UTC
Labels: feature-request
