### ISSUE TITLE
Support adding team reviewers

### ISSUE THREAD

**Issue by diminutivesloop** [microsoft/vscode-pull-request-github#3070] opened 2021-10-29 17:33 UTC
Issue Type: <b>Feature Request</b>

In addition to adding individual reviewers to PRs, this extension should support  adding teams reviewers for parity with the GitHub web ui.

Extension version: 0.31.1
VS Code version: Code 1.61.2 (Universal) (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T15:49:28.381Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

**Comment by jordangarrison** [comment] 2022-08-31 19:56
Yes +1 for this!

This also could allow it to reflect the reviewers shown in the WebUI inside the extension's pane. Currently teams don't show up in the reviewers list for the PR.

**Comment by lsnina** [comment] 2022-11-30 12:24
+1

This is a nice feature to add. 
When need to add a team must open browser 😞

**Comment by alexr00** [comment] 2022-12-13 07:35
duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/1126

**Closed by alexr00** 2022-12-13 07:35 UTC
Labels: feature-request
