### ISSUE TITLE
Remove tick in viewlet after a new branch is checked out

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#789] opened 2019-01-07 19:08 UTC
ext version: 1.7.1

Repro:

1. Checkout a PR, wait for it to finish
2. Checkout another PR

After the actual branch is checked out I think the tick on the first PR should go away.

![image](https://user-images.githubusercontent.com/2193314/50787788-4383f480-126c-11e9-899e-f1f0f5bb9161.png)
![image](https://user-images.githubusercontent.com/2193314/50787794-45e64e80-126c-11e9-84e1-b36938d865d0.png)

The tick/state prevents checking out the other branch if I changed my mind until the entire review mode process has finished.

**Comment by RMacfarlane** [comment] 2020-11-03 23:43
Closing as I can't reproduce this in the current version of the extension

**Closed by RMacfarlane** 2020-11-03 23:43 UTC
