### ISSUE TITLE
Collapse comments on resolve

### ISSUE THREAD

**Issue by MartinBernstorff** [microsoft/vscode-pull-request-github#4333] opened 2022-12-15 10:15 UTC
Love the new "resolve conversation" button! 

![image](https://user-images.githubusercontent.com/8526086/207833249-073cc277-a307-4ab7-9fdd-71816f3c5921.png)

Even better would be if I could set a setting for automatically collapsing the conversations when I press resolve :-)

**Comment by brettcannon** [comment] 2023-08-29 16:29
I think this and https://github.com/microsoft/vscode-pull-request-github/issues/5031 are duplicates of each other.

**Comment by alexr00** [comment] 2023-08-29 17:01
@brettcannon you are correct. Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/5031.

**Closed by alexr00** 2023-08-29 17:01 UTC
Labels: feature-request
