### ISSUE TITLE
Register system-wide URI handler to open PRs in Code

### ISSUE THREAD

**Issue by heaths** [microsoft/vscode-pull-request-github#1590] opened 2020-03-28 14:39 UTC
GitHub's experience for PRs with a lot of files or with large files is painful, often grinding browsers to a halt even with 16GB of RAM. What would be great is if GitHub had a way to open PRs directly in Code, whether they made the change to the site themselves or added via browser extension.

To enable this, you could call window.registerUriHandler and add an onUri activation that opened the PR directly in Code.

I imagine the trickiest part would be to identify the local repo associated with that PR, if needed. You could keep a cache of local repos and if none are found or the cache is stale for a particular entry (e.g. repo was moved or deleted) you could prompt the user to open a folder or workspace.

**Comment by alexr00** [comment] 2020-11-11 15:56
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/597

**Closed by alexr00** 2020-11-11 15:56 UTC
Labels: feature-request
