### ISSUE TITLE
Issues in PR description are not showing up as link

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode-pull-request-github#201] opened 2018-08-15 09:19 UTC
![image](https://user-images.githubusercontent.com/900690/44141330-20532596-a07d-11e8-93ec-7e1eec456d2b.png)

**Comment by rebornix** [comment] 2018-08-15 18:12
Thanks, it's a duplicate of https://github.com/Microsoft/vscode-pull-request-github/issues/66, let's track it there.

**Closed by rebornix** 2018-08-15 18:12 UTC
Labels: bug, github
