### ISSUE TITLE
GitHub not loading

### ISSUE THREAD

**Issue by NathanBrianRoberts** [microsoft/vscode-pull-request-github#2724] opened 2021-05-09 15:13 UTC
- Extension version: 0.26.0
- VSCode Version: 1.56.0
- OS: 10 Dev (Build 21376.1)

Steps to Reproduce:

1. Install GitHub
2.Wait for the thing to load

The extension will not load, to finish setting up the extension and connecting with my GitHub respirometry's . It just sits there saying it is loading.

**Comment by RMacfarlane** [comment] 2021-05-12 16:45
Closing as a duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/2572

**Closed by RMacfarlane** 2021-05-12 16:45 UTC
