### ISSUE TITLE
Allow to toggle between file Diff View, and regular view

### ISSUE THREAD

**Issue by DavidSchuldenfrei** [Microsoft/vscode-pull-request-github#466] opened 2018-09-13 12:47 UTC
It is sometimes easier to work on the complete file, instead of the diff view. Allowing to toggle from one to the other would be very helpful.

**Comment by RMacfarlane** [comment] 2018-09-13 16:57
Duplicate of https://github.com/Microsoft/vscode-pull-request-github/issues/268, let's track this there

**Closed by RMacfarlane** 2018-09-13 16:57 UTC
