### ISSUE TITLE
Comments panel opens for no reason when checking out a pull request

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode-pull-request-github#748] opened 2018-12-11 19:47 UTC
- Check out https://github.com/Microsoft/vscode/pull/64267 via the extension
- Go to type something in the terminal
- A second later, the comments panel opens and steals my focus. It's empty.

It happened a couple times but now I can't repro it again...

**Comment by RMacfarlane** [comment] 2018-12-13 00:20
Duplicate of https://github.com/Microsoft/vscode-pull-request-github/issues/70

Currently the panel only steals focus the first time a workspace provider is registered, but it's still annoying. let me know what you think of adding a setting to make it less annoying: https://github.com/Microsoft/vscode-pull-request-github/issues/70#issuecomment-446794124

**Closed by RMacfarlane** 2018-12-13 00:20 UTC
Labels: upstream/vscode
