### ISSUE TITLE
Query fails when trying to get "is:closed is:unmerged" 

### ISSUE THREAD

**Issue by mindcloud69** [microsoft/vscode-pull-request-github#5801] opened 2024-03-04 08:09 UTC
Type: <b>Bug</b>

I noticed that you have tried to squash this bug several times. I have tried with the release and prerelease versions.

My query is:
```
                            {
                                "label": "Closed & Unmerged",
                                "query": "is:closed is:unmerged"
                            },
                            {
                                "label": "Closed",
                                "query": "is:closed"
                            }
```
It Occurs with both. 

This is the error that pops up:
Element with id Closed & Unmergedhttps://github.com/netbox-community/devicetype-library/pull/1924 is already registered 

This is the error in the console:
```
workbench.desktop.main.js:sourcemap:769 Error: Element with id Closed & Unmergedhttps://github.com/netbox-community/devicetype-library/pull/1924 is already registered
    at n.db (f:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:141:69226)
    at f:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:141:68020
    at async Promise.all (index 10)
    at n.Y (f:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:141:67887)
    at n.getChildren (f:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:141:64179)
```

Extension version: 0.79.2024011609
VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by alexr00** [comment] 2024-04-09 15:02
@mindcloud69 I can't reproduce this issue. Can you please try again? Is this in a multi repo workspace, or do you only have one GitHub repo open?

**Comment by mindcloud69** [comment] 2024-04-20 11:26
Sorry I missed your request for info. I only have one repo open.

https://github.com/netbox-community/devicetype-library/

Anything else I can do. Is there a way to enable better logging for you?

**Comment by muradddd** [comment] 2024-04-23 20:23
I also have the same issue @alexr00.

**Comment by alexr00** [comment] 2024-12-16 11:27
Should be fixed with https://github.com/microsoft/vscode-pull-request-github/issues/6218

**Closed by alexr00** 2024-12-16 11:27 UTC
Labels: info-needed
