### ISSUE TITLE
Suggested change in review comment

### ISSUE THREAD

**Issue by davidpadbury** [microsoft/vscode-pull-request-github#3611] opened 2022-06-10 13:58 UTC
I'd like to be able to provide a suggested change in review comments similar to how we can do in the web interface ([number 6 in this guide](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/commenting-on-a-pull-request)).

I've attempted using the same syntax that appears in the comment dialog in the web interface within the VSCode comment box however this doesn't show up as a suggested change on the eventual review:
````
```suggestion
my suggested change
```
````

**Comment by alexr00** [comment] 2022-06-13 12:32
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/603, which is about supporting the "suggest a change" GitHub feature.

**Closed by alexr00** 2022-06-13 12:32 UTC
