### ISSUE TITLE
Cmd+Enter to submit review in focus mode

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode-pull-request-github#2449] opened 2021-02-02 18:24 UTC
In the focus mode review view, it'd be nice if cmd+enter sumbitted the review/comment, as it does on github.com.

**Comment by alexr00** [comment] 2021-11-19 14:35
Similar to https://github.com/microsoft/vscode-pull-request-github/issues/2241

**Comment by jennyxing** [comment] 2022-05-27 02:32
I believe hitting "cmd+enter" or "ctrl+enter" used to submit the review/comment, but it stopped working for me a few months ago.

**Comment by alexr00** [comment] 2022-12-12 12:27
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/2241

**Closed by alexr00** 2022-12-12 12:27 UTC
Labels: feature-request
