### ISSUE TITLE
Feature Request : Open Description for Issue

### ISSUE THREAD

**Issue by barraIhsan** [microsoft/vscode-pull-request-github#2708] opened 2021-05-04 12:44 UTC
So, when you **click** on the issue, its gonna open up the description page in vscode, just like pr
And you can comment on it, close the issue, just like pr

**Comment by RMacfarlane** [comment] 2021-05-04 15:55
Hey @barraIhsan, this looks like a duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/2229 so I'm going to go ahead and close it. Thanks!

**Closed by RMacfarlane** 2021-05-04 15:55 UTC
