### ISSUE TITLE
PR description should auto fill when the PR is a single commit

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#2540] opened 2021-02-26 14:02 UTC
Ext:

![image](https://user-images.githubusercontent.com/2193314/109309462-2ae24a00-77f8-11eb-8b1e-d63ffbfa234d.png)

.com:

![image](https://user-images.githubusercontent.com/2193314/109309517-3c2b5680-77f8-11eb-9b47-abf546ce0823.png)

**Comment by joshuaobrien** [comment] 2021-07-13 07:04
Hey @RMacfarlane, I'll take this on! Could you please assign it to me?

**Comment by alexr00** [comment] 2021-07-13 12:48
Hi @joshuaobrien no need to assign to you now that I know you want to work on it! (And actually, the way we track issues in progress is usually to assign them to one of the managers of the project, which is me now 🙂) 

Do you need/want any pointers for where to get started?

**Comment by joshuaobrien** [comment] 2021-07-14 02:04
Thanks @alexr00!

I should be okay for now, I'll take some time to go through the project and determine what needs to be done. If I need any further info, I'll reach out here :)

**Comment by joshuaobrien** [comment] 2021-07-17 02:03
Hey @alexr00! I just tried to reproduce this, and I think it might already be fixed? Looks like the behaviour is the same now :)

Commit:
![image](https://user-images.githubusercontent.com/7654793/126022051-567e5591-7aa4-42fb-ae8e-4df467a90166.png)

Extension:
![image](https://user-images.githubusercontent.com/7654793/126022029-ddb07b80-0072-4601-b287-aca628385169.png)

Site:
![image](https://user-images.githubusercontent.com/7654793/126022037-15215cdc-813c-4c2d-9ecc-219d06a7bbd2.png)

**Comment by alexr00** [comment] 2021-07-19 09:07
@joshuaobrien I'm still seeing this issue. The issue only occurs in a repo where there is a PR template set up on GitHub. When there's a template, we currently just dump the template into description, and we don't include the commit message at all.

**Comment by joshuaobrien** [comment] 2021-07-19 09:27
Ahhh gotcha @alexr00, I misunderstood. I didn't realise it was only when a template was set up

**Closed** 2021-08-11 14:49 UTC
Labels: bug, good first issue
