### ISSUE TITLE
The last line of a multiline comment appears as an empty range from column 0 to 0

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode-pull-request-github#3497] opened 2022-04-27 13:44 UTC
Testing microsoft/vscode#148048

Follow the steps of microsoft/vscode-pull-request-github#3496

![image](https://user-images.githubusercontent.com/22350/165532497-d2800195-3de9-4767-a209-2379d93d869e.png)

**Comment by alexr00** [comment] 2022-04-28 15:42
duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/3496

**Closed by alexr00** 2022-04-28 15:42 UTC
Labels: bug
