### ISSUE TITLE
Unable to get token

### ISSUE THREAD

**Issue by bjorn3** [microsoft/vscode-pull-request-github#1239] opened 2019-06-16 12:15 UTC
Issue Type: <b>Bug</b>

1. Click on sign in to github.com.
2. Click on continue in the new browser tab.
3. "Oh no! An error occurred!"

![afbeelding](https://user-images.githubusercontent.com/17426603/59563970-20dae080-9041-11e9-8d26-f52a094b933c.png)

Extension version: 0.8.0
VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:16:40.241Z)
OS version: Darwin x64 18.6.0

**Comment by RMacfarlane** [comment] 2020-11-09 18:40
Closing as a duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/1221

**Closed by RMacfarlane** 2020-11-09 18:40 UTC
Labels: authentication, github
