### ISSUE TITLE
Rate limited in Github Enterprise

### ISSUE THREAD

**Issue by nsheaps** [microsoft/vscode-pull-request-github#4132] opened 2022-10-28 23:33 UTC
- Extension version: v0.52.0
- VSCode Version: 1.72.2 (Universal)
- OS: Mac OS Ventura

Steps to Reproduce:
0. Work against Github Enterprise Server with rate limits set to 15000 API requests per user per hour
1. Work in 2+ repos that have a lot of open pull requests and comments/actors
2. Have VScode Github Pull Requests open in 2 windows for those two repos
3. Work as normal, get ratelimited in other github-enabled web-apps, note no error from plugin

Is there a way that we could maybe do one of the following:
* add a rate limiting option to the API calls made from this
* option to not fetch info about PRs that you don't click on
* Use the graphql API to fetch all the needed info at once

**Comment by alexr00** [comment] 2022-10-31 21:59
@nsheaps thanks for trying out the GitHub Enterprise support! This is mostly likely caused by https://github.com/microsoft/vscode-pull-request-github/issues/3847

That bug is fixed in the [pre-release build of this extension](https://github.com/microsoft/vscode-pull-request-github/wiki/Pre-release-Build). The fix will be in the next stable release too (should occur later this week).

**Closed by alexr00** 2022-10-31 21:59 UTC

**Comment by sheldonhull** [comment] 2022-12-08 22:04
I ran into issues with rate limiting and from what I can see much of the calls when tracing with proxy are api calls from this extension, and calls such as `

`application/vnd.github.shadow-cat-preview+json,application/vnd.github.merge-info-preview+json`

I'll be capturing more traffic today to see if I can verify the primary api call totals.

**Comment by alexr00** [comment] 2022-12-09 07:53
@sheldonhull can you set `"githubPullRequests.logLevel": "debug"` then share the output of GitHub Pull Request next time you see the issue? Note that there might be information about your repository in those logs that you want to remove before sharing.

**Comment by alexr00** [comment] 2022-12-09 07:53
Also, please make sure that you're on the latest version of the extension!
