### ISSUE TITLE
Issues without a milestone don't appear in suggestions

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-pull-request-github#1522] opened 2020-02-25 20:54 UTC
We can `ignoreMilestones`, but it seems like issues without a milestone are never shown in completion. Many smaller projects or maintenance-mode projects without planned releases don't use milestones.  Maybe we should show them and have some magic `<None>` option in ignoreMilestones to refer to them.

**Comment by alexr00** [comment] 2020-02-26 10:16
Yes, will add. Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/1502

**Closed** 2020-02-26 10:16 UTC
Labels: duplicate
