### ISSUE TITLE
Cannot add multiple file comments

### ISSUE THREAD

**Issue by RobLuzmo** [microsoft/vscode-pull-request-github#6223] opened 2024-09-11 13:56 UTC
Type: <b>Bug</b>

1. Open a file in a PR that doesn't have any file comments yet.
2. Click `Add File Comment` button
3. Add a comment
4. Click the `Add File Comment` button again

Expected behaviour: another comment box is shown to add a comment.
Actual behaviour: the current comment is hidden.

Extension version: 0.96.0
VS Code version: Code 1.93.0 (4849ca9bdf9666755eb463db297b69e5385090e3, 2024-09-04T13:02:38.431Z)
OS version: Linux x64 6.8.0-41-generic
Modes:

**Comment by alexr00** [comment] 2024-09-26 10:16
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/5786

**Closed by alexr00** 2024-09-26 10:16 UTC
