### ISSUE TITLE
When reviewing pull request changes the diff view reloads every few minutes and moves my cursor to a different location

### ISSUE THREAD

**Issue by Mainstay-Noah-Huppert** [microsoft/vscode-pull-request-github#4159] opened 2022-11-04 18:23 UTC
- Extension version: v0.52.0
- VSCode Version: 1.72.2, Using remote access extension onto Linux
- OS: OSX 13.0 (22A380) (Intel)

Steps to Reproduce:

1. Install the GitHub extension and sign in
2. Click the GitHub logo in the left bar
3. Have someone request a pull request review 
4. Expand the "Waiting For My Review" filter
5. Click on a pull request to expand the diff file tree
6. Click on a diff file and start reviewing the diff
7. Wait a few minutes as you review, ensure the PR author does not push any commits or update their PR
8. The entire diff window will flash and reload. This is probably the extension checking for a new version of the diff, this will cause you to not be able to read the diff for a second (because it is loading) and your cursor will be moved to a place in the file which you already viewed a few minutes ago

**Comment by Mainstay-Noah-Huppert** [comment] 2022-11-04 18:44
It also seems that if this refresh happens right after I mark a file as viewed, the file will be marked as un-viewed.

**Comment by alexr00** [comment] 2022-11-11 10:00
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/4031, which is fixed in version 0.54.0.

**Closed by alexr00** 2022-11-11 10:00 UTC
Labels: bug

**Comment by Mainstay-Noah-Huppert** [comment] 2022-11-14 15:46
Awesome thanks!
