### ISSUE TITLE
Cannot ping people using @ sign in comment text field

### ISSUE THREAD

**Issue by jooyoungseo** [microsoft/vscode-pull-request-github#5525] opened 2023-11-30 00:56 UTC
Type: <b>Bug</b>

When leaving a comment in a PR, @ sign does not populate the autopletion so I cannot easily ping my team members.

Extension version: 0.77.2023112911
VS Code version: Code - Insiders 1.85.0-insider (8762127fc97b8aaae5f3a0dd6a6d853d9a1b7574, 2023-11-29T17:38:23.440Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz (8 x 2611)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.71GB (5.51GB free)|
|Process Argv|--crash-reporter-id b05b88e5-8894-4031-ae34-fa034ebddea9|
|Screen Reader|yes|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
py29gd2263:30784851
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
a9j8j154:30646983
showlangstatbar:30737417
pythonfmttext:30716741
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
welcomedialog:30812478
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
pythonmpswarning:30901777
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30902439
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
aa_t_chat:30882232

```

</details>

**Comment by alexr00** [comment] 2023-12-05 11:58
Can you share a screenshot of where you're trying to do this?

**Comment by jooyoungseo** [comment] 2023-12-05 14:02
@alexr00 -- Please watch the following gif:

![Recording 2023-12-05 at 08 01 19](https://github.com/microsoft/vscode-pull-request-github/assets/19754711/946d6f71-7fcf-4855-a9b8-9294bac78afb)

**Comment by alexr00** [comment] 2023-12-05 14:43
Thanks! Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/2401, which is about enabling some kind of suggest widget in webviews.

**Closed by alexr00** 2023-12-05 14:43 UTC
Labels: info-needed
