### ISSUE TITLE
Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-pull-request-github#1263] opened 2019-07-10 00:16 UTC
Issue Type: <b>Bug</b>

- Created a PR in a private repo through the extension.
- Try to add a reviewer 
-> error notification: Cannot read property 'filter' of undefined

Extension version: 1.860.1
VS Code version: Code - Insiders 1.37.0-insider (9296aaa2201b638e2b1dc71a9b9fe38c5ab2e904, 2019-07-09T05:24:16.868Z)
OS version: Darwin x64 18.6.0
Remote OS version: Linux x64 4.18.0-1018-azure
Remote OS version: Linux x64 4.18.0-1018-azure
Remote OS version: Linux x64 4.18.0-1018-azure
Remote OS version: Linux x64 4.18.0-1018-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv|-psn_0_1261876|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: az-devbox|
|OS|Linux x64 4.18.0-1018-azure|
|CPUs|Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz (4 x 2294)|
|Memory (System)|15.64GB (1.57GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: az-devbox|
|OS|Linux x64 4.18.0-1018-azure|
|CPUs|Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz (4 x 2294)|
|Memory (System)|15.64GB (1.57GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: az-devbox|
|OS|Linux x64 4.18.0-1018-azure|
|CPUs|Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz (4 x 2294)|
|Memory (System)|15.64GB (1.57GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: az-devbox|
|OS|Linux x64 4.18.0-1018-azure|
|CPUs|Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz (4 x 2294)|
|Memory (System)|15.64GB (1.57GB free)|
|VM|0%|
</details>

**Comment by dmr86** [comment] 2019-07-10 12:07
Exact same thing on current latest version (1.36.1) on macOS

**Comment by RMacfarlane** [comment] 2019-07-12 17:11
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/1181

**Closed by RMacfarlane** 2019-07-12 17:11 UTC
