### ISSUE TITLE
Add refresh button to "Create" view (Newly published branch doesn't show up in merge changes from)

### ISSUE THREAD

**Issue by kriswuollett** [microsoft/vscode-pull-request-github#3699] opened 2022-07-07 17:23 UTC
Issue Type: <b>Bug</b>

Summary:

Seems like the GitHub plugin isn't notified that a new branch was published. It only shows up if I reload the window. There is no manual refresh button on the GitHub pull request screen either.

Steps to Reproduce:

* Create a new repo
* Publish an initial commit
* Create new branch off of main
* Add another commit
* Push/publish new branch on remote
* Go to GitHub Pull Request screen

Expected:

The new branch shows up in "MERGE CHANGES FROM".

Actual:

Only the "main" branch shows up in "MERGE CHANGES FROM".

Workaround:

Run "Developer: Reload Window"

Extension version: 0.46.0
VS Code version: Code 1.68.1 (Universal) (30d9c6cd9483b2cc586687151bcbcd635f373630, 2022-06-14T12:52:13.188Z)
OS version: Darwin x64 21.5.0
Restricted Mode: No
Remote OS version: Linux x64 5.13.0-1033-gcp

<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30519255
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdf:30486550

```

</details>

**Comment by kriswuollett** [comment] 2022-07-07 17:25
![CleanShot 2022-07-07 at 12 23 32@2x](https://user-images.githubusercontent.com/1834192/177833576-853bedb1-0d02-4237-a5b3-14a2e93cc00e.png)

**Comment by kriswuollett** [comment] 2022-07-07 17:27
I used the dropdown menu from the "SOURCE CONTROL" view to invoke "Push" which asked me if I want to publish on remote. Is there no mechanism that the GitHub plugin uses to know that new branches are known locally / on remote?

**Comment by alexr00** [comment] 2022-12-09 13:03
duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/3588

**Closed** 2022-12-09 13:04 UTC
Labels: feature-request
