### ISSUE TITLE
Refine GitHub Query Hierarchy with Subtree nodes (for ex. Milestones, Labels, Repositories)

### ISSUE THREAD

**Issue by maddes8cht** [microsoft/vscode-pull-request-github#5511] opened 2023-11-26 12:54 UTC
In the GitHub Issues.querys section, I've noticed that the "default" query displays all open issues of the current repository assigned to me, organized by milestones as tree nodes. While attempting to recreate this structure with custom queries, I encountered challenges, specifically in having subtrees under the tree node corresponding to the "label" assigned to the query.

For instance, I want to access closed issues using:

```
"githubIssues.queries": [
    {
        "label": "My Issues",
        "query": "default"
    },
    {
        "label": "Closed Issues",
        "query": "-state:open author:${user} repo:${owner}/${repository}"
    }
]
```
However, this setup doesn't provide subnodes with milestones.

Additionally, I would like to review my other open issues across different repositories:

```
{
    "label": "Other Open Issues",
    "query": "state:open author:${user} sort:updated-desc -repo:${owner}/${repository}"
}
```
It would be ideal to have these issues ordered in subtrees by their repository names.

Is it currently possible to configure such a structure in VSCode? If not, I propose it as a valuable feature to enhance the usability and flexibility of the GitHub Pull Requests and Issues extension.

Your guidance on achieving this structure or consideration for implementing it as a feature would be greatly appreciated.

**Comment by alexr00** [comment] 2023-11-29 13:13
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/1881

**Closed by alexr00** 2023-11-29 13:13 UTC
