### ISSUE TITLE
Autofill @usernames in comments

### ISSUE THREAD

**Issue by brianjmurrell** [microsoft/vscode-pull-request-github#2284] opened 2020-11-11 22:43 UTC
When adding a comment to a PR, typing an `@` followed by some letters should populate a list of relevant users like the GH UI does.

**Comment by RMacfarlane** [comment] 2020-11-12 01:23
I think this is a duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/1206, unless you're seeing that there are no completions within comments in a file

**Comment by brianjmurrell** [comment] 2020-11-12 15:22
Yeah, I tend to agree.

**Comment by RMacfarlane** [comment] 2020-11-12 16:46
Thanks, I will go ahead and close this in favor of #1206

**Closed by RMacfarlane** 2020-11-12 16:46 UTC
