### ISSUE TITLE
Support code review per commit

### ISSUE THREAD

**Issue by shai-ostshega** [microsoft/vscode-pull-request-github#6532] opened 2024-12-12 08:34 UTC
Many times PR contains multiple commits. 
The code review of the PR in github web supports to review per commit, while in the VS code extension code review is only supported at the PR level.

**Comment by alexr00** [comment] 2024-12-13 14:14
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/4315

**Closed by alexr00** 2024-12-13 14:14 UTC
