### ISSUE TITLE
Cannot checkout when untracked files are present

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode-pull-request-github#613] opened 2018-10-24 22:54 UTC
Repro:

1. `touch a`
2. Try checkout a PR with the extension

If there are only untracked files the extension should attempt to checkout and report the failure if it fails checking out.

**Comment by RMacfarlane** [comment] 2018-11-07 17:54
Duplicate of https://github.com/Microsoft/vscode-pull-request-github/issues/553

**Closed by RMacfarlane** 2018-11-07 17:54 UTC
