### ISSUE TITLE
Unable to Resolve and Unresolve comments in PRs all of a sudden (Unresolving conversation failed: Error: GraphQL error: Could not resolve to a node with the global id)

### ISSUE THREAD

**Issue by wtomw** [microsoft/vscode-pull-request-github#2910] opened 2021-08-15 16:49 UTC
- Extension version: 
- VSCode Version: v0.29.2

- OS: Windows

Steps to Reproduce:

1. Create a PR, add a comment (in portal)
2. Try to open PR in VSCODE and resolve it
3. Get:
Unresolving conversation failed: Error: GraphQL error: Could not resolve to a node with the global id of 'github-review-23.20'
For PR: https://github.com/Azure/AzureDefender-K8S-InClusterDefense/pull/23

**Comment by alexr00** [comment] 2021-08-16 13:13
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/2857. If you don't want to wait for the next release, you can disable the stable build of the extension and install the [nightly build](https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github-insiders).

**Closed by alexr00** 2021-08-16 13:13 UTC
