### ISSUE TITLE
Images missing from extension editor readme preview

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode-pull-request-github#2568] opened 2021-03-11 18:59 UTC
Images in preview are linked to `master`, but the branch is now `main`. The latest vsce version fixes this :) 
![image](https://user-images.githubusercontent.com/8586769/110839875-e8d5f100-8258-11eb-89e0-3a9892a155a9.png)

**Comment by thirschbuechler** [comment] 2021-06-12 18:15
my guess is that vscode doesn't show relative image links, so this
`/.readme/demo.gif`
should be that
`https://github.com/microsoft/vscode-pull-request-github/blob/main/.readme/demo.gif`

and so on,
as can be seen for example in 
`https://github.com/mhutchie/vscode-git-graph/blob/develop/README.md`
with working images in the extension browser

**Comment by alexr00** [comment] 2021-06-14 09:01
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/2769

**Closed by alexr00** 2021-06-14 09:01 UTC
