### ISSUE TITLE
Cannot change the keybinding for `workbench.action.hideComment`

### ISSUE THREAD

**Issue by forivall** [microsoft/vscode-pull-request-github#6377] opened 2024-10-23 02:51 UTC
This is related to #1455, but it's not strictly a duplicate.

- Extension version: 0.98.0
- VSCode Version: 1.94.2
- OS: Mac OS X 10_15_7 Chrome/130.0.0.0
- Repository Clone Configuration (single repository/fork of an upstream repository): using `github.dev` on a pull request
- Github Product (Github.com/Github Enterprise version x.x.x): github.com / github.dev

Steps to Reproduce:

1. Add the following to your `keybindings.json` to disable the `escape` keybinding for `workbench.action.hideComment`

  ```jsonc
  {
    "key": "escape",
    "command": "-workbench.action.hideComment",
    "when": "commentEditorFocused"
  }
  ```

2. Open a pull request, open a comment
3. Hit escape
4. Observe that the comment is hidden.

This is especially frustrating as I use https://github.com/71/dance for helix keybindings (similar to vim), and when i try to hit escape to switch to normal mode inside of a comment editor, the comment editor simply closes.

**Comment by alexr00** [comment] 2024-10-24 08:17
Duplicate of https://github.com/microsoft/vscode/issues/231674

**Closed by alexr00** 2024-10-24 08:17 UTC
