### ISSUE TITLE
[Feature Request] When Squash Merging, should collate commits into list of description like Web does

### ISSUE THREAD

**Issue by JustinGrote** [microsoft/vscode-pull-request-github#1790] opened 2020-05-11 18:48 UTC
Per the title, when you have a lot of commit messages and go to squash merge, the web interface takes these and makes them a markdown list in the description part of your commit. The extension currently just brings over the PR title and doesn't collapse the commit names into the description like so:

![image](https://user-images.githubusercontent.com/15258962/81599345-508f8700-937d-11ea-9f18-89ed62fe902c.png)

**Comment by RMacfarlane** [comment] 2020-05-11 23:54
This looks like a duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/1679, let's track it there

**Closed by RMacfarlane** 2020-05-11 23:54 UTC

**Comment by JustinGrote** [comment] 2020-05-12 00:29
Agreed, did a search but didn't come across this one. Thanks!
