### ISSUE TITLE
Mimic GitHub PR sidebar click areas

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode-pull-request-github#4210] opened 2022-11-17 20:34 UTC
On GitHub these entire areas are clickable. This is one of those issues that I hit pretty much daily but never really got around to file it, it's just so etched in my muscle memory.

![image](https://user-images.githubusercontent.com/22350/202553879-c4bacdca-9928-4fa8-b5b1-a2c7fc1fe87b.png)

**Comment by alexr00** [comment] 2022-11-18 13:42
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/4196

**Closed by alexr00** 2022-11-18 13:42 UTC
