### ISSUE TITLE
The comment box is only a single line tall

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode-pull-request-github#44] opened 2018-06-26 22:15 UTC
![image](https://user-images.githubusercontent.com/2193314/41942295-d0a21836-7953-11e8-95d6-8232ae6ad311.png)

**Comment by RMacfarlane** [comment] 2018-07-03 00:36
I think this is a duplicate of https://github.com/Microsoft/vscode-pull-request-github/issues/14

**Closed by RMacfarlane** 2018-07-03 00:36 UTC
Labels: bug, comments
