### ISSUE TITLE
Remove "description" and instead show it when title item is clicked

### ISSUE THREAD

**Issue by pke** [microsoft/vscode-pull-request-github#406] opened 2018-09-11 08:56 UTC
Somehow the "description" item under each PR is confusing to me.
I'd have expected clicking the PR entry under each grouping to reveal the description.
When its possible to click the PR entry itself to reveal the description, the separate entry "description" can be removed then.

**Comment by Astrantia** [comment] 2019-01-04 19:30
@rebornix Why was the current design chosen? It's very confusing indeed

**Comment by rebornix** [comment] 2019-01-04 21:01
IIRC, when we implemented the first version, we can't differentiate clicking a node or expanding a node, so we add the description under the Pull Request node. Since it's supported now, we can experiment with what's being proposed above.

**Comment by RMacfarlane** [comment] 2020-09-04 18:11
Closing as a duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/112

**Closed by RMacfarlane** 2020-09-04 18:11 UTC
Labels: feature-request
