### ISSUE TITLE
Plugin do not scan recursevely when multi repositories inside folder inside workspace

### ISSUE THREAD

**Issue by jonathanvila** [microsoft/vscode-pull-request-github#1620] opened 2020-04-14 10:33 UTC
- Extension version: 0.15.0
- VSCode Version: 1.44
- OS: Fedora 31

Steps to Reproduce:

1. Have a folder with several repositories
2. Add this top folder only to the workspace
3. Not even changing the repository in source pane makes the pull requests to appear

**Comment by jonathanvila** [comment] 2020-04-14 10:47
Creating a new workspace with 10 repositories folders added to it ( instead of 1 ) makes the plugin to show some PRs ( 14 PRs ), but not all. Changing the project on Source pane, or Git pane doesn't make any difference .

**Comment by RMacfarlane** [comment] 2020-10-13 22:00
Closing as a duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/436. This should be fixed in version 0.20.0 of the extension. Thanks!

**Closed by RMacfarlane** 2020-10-13 22:00 UTC
