### ISSUE TITLE
New comment button is the same as the existing comment button

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode-pull-request-github#45] opened 2018-06-26 22:17 UTC
A `+` inside the speech bubble could fix this

![image](https://user-images.githubusercontent.com/2193314/41942327-f39cf7c0-7953-11e8-876d-e27b1c0a18ff.png)

**Comment by kieferrm** [comment] 2018-06-27 10:02
Duplicate of #13.

**Closed** 2018-06-27 10:02 UTC
Labels: bug, duplicate
