### ISSUE TITLE
"go to review" *deletes* current comment draft

### ISSUE THREAD

**Issue by mtaran** [microsoft/vscode-pull-request-github#3146] opened 2021-11-30 06:06 UTC
- Extension version: v0.33.2021112917
- VSCode Version: 1.63.0-insider
- OS: Mac OS

Steps to Reproduce:

1. Open a PR with some comments and start a review for writing a response
2. Start typing a comment in response to an existing one
3. Click the "go to review" button to see other (potentially related) comments
4. Go back to the previous tab to continue writing the comment response from before

Expected:

Your comment draft is still there.

Actual:

The comment draft is gone with no way to bring it back!

**Comment by alexr00** [comment] 2021-12-01 15:35
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/2707

**Closed** 2021-12-01 15:36 UTC
