### ISSUE TITLE
Show warning when both nightly and stable versions are enabled

### ISSUE THREAD

**Issue by abheist** [microsoft/vscode-pull-request-github#1782] opened 2020-05-09 20:55 UTC
When installing the nightly and stable version together, every icon is rendered twice in the sidebar.

- Extension version: v2020.5.10981 & v0.16.0
- VSCode Version:
```
Version: 1.46.0-insider
Commit: d487078dc7fc1c276657cadb61b4f63833a8df55
Date: 2020-05-07T16:30:12.593Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0
```
- OS: macOS

Steps to Reproduce:
1. Install both extensions together, nightly and stable.
I'm not sure, will it be count as a bug or not. I downloaded the nightly version for testing it. But IMO it should not happen.

Gif for reference:
![Screen Recording 2020-05-10 at 2 13 45 AM](https://user-images.githubusercontent.com/5029660/81484684-44b0a180-9265-11ea-84f8-b70639e59e33.gif)

**Comment by RMacfarlane** [comment] 2020-05-29 14:41
This is expected behavior, they both contribute the same commands and icons. They are not meant to be enabled side by side, we should show a warning notification when they are.

**Comment by abheist** [comment] 2020-05-30 04:43
Yeah, that will be great too. 🙌

**Comment by rzhao271** [comment] 2021-02-24 19:24
Going to say "verification found" because I didn't get the notification showing.
I tried testing on Codespaces, but I also didn't get the notifs showing on Windows locally.
https://github.com/microsoft/vscode-internalbacklog/issues/1918

**Comment by alexr00** [comment] 2021-11-18 14:26
We will soon be moving to VS Code's insiders extension support (within the next month I expect), which will eliminate this issue..

**Closed by alexr00** 2021-11-18 14:26 UTC
Labels: feature-request, verification-found
