### ISSUE TITLE
Don't pollute devtools when there's no GitHub remote

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode-pull-request-github#1662] opened 2020-04-21 11:13 UTC
My devtools fills up simply by opening a repository which doesn't have a github remote:

![image](https://user-images.githubusercontent.com/22350/79859754-c8e3d780-83d1-11ea-99d2-a8e339f7b615.png)

**Comment by IllusionMH** [comment] 2020-04-21 11:14
Looks like duplicate of #1614

**Closed** 2020-04-21 11:54 UTC
