### ISSUE TITLE
PR creation progress notification shown, but didn't notice it...

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-pull-request-github#3773] opened 2022-07-26 21:02 UTC
Testing #3761

In checking the progress bar aspect, I did see the progress notification box appear in the lower right corner of vscode, but I wasn't looking there. I kinda expected a progress bar to show in the Create view.

**Comment by alexr00** [comment] 2022-07-27 08:18
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/3743

**Closed by alexr00** 2022-07-27 08:18 UTC

**Comment by alexr00** [comment] 2022-07-28 09:20
I also added the spinner to the "Create" view yesterday, so even if you don't notice the notification you will see something that indicates that it's not stuck near where you clicked.
