### ISSUE TITLE
Resolve conversation command

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode-pull-request-github#666] opened 2018-11-06 01:19 UTC
- Extension version: 0.2.3
- VSCode Version: 1.29
- OS: macOS

Now GitHub pull request commenting system has *Resolve conversation* command, similarly to Codeflow. Right now we have to go back .com to perform this operation.

**Comment by RMacfarlane** [comment] 2018-11-28 23:46
Duplicate of https://github.com/Microsoft/vscode-pull-request-github/issues/339

**Closed by RMacfarlane** 2018-11-28 23:46 UTC
Labels: enhancement
