### ISSUE TITLE
New PR View: Bad button layout

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode-pull-request-github#5038] opened 2023-07-11 13:35 UTC
<img width="342" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/22350/0e941019-ebe8-4d1b-8429-0672d025145c">

**Comment by alexr00** [comment] 2023-07-11 14:48
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/5030

**Closed by alexr00** 2023-07-11 14:48 UTC
