### ISSUE TITLE
Confusing error when trying to create a PR

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#3323] opened 2022-02-16 14:32 UTC
Maybe this is a problem with GHPRI, I did the following:

1. Opened github.dev on https://github.com/microsoft/vscode-docs
2. Made a change
3. Created a new branch via the status bar
4. Committed the change
5. Tried to create a PR, clicking create gave me:
  ![image](https://user-images.githubusercontent.com/2193314/154285949-2736274c-943a-4c0e-aed4-106c126f2829.png)
6. That was confusing as the branch is already pushed, but I clicked publish branch and got this error
  ![image](https://user-images.githubusercontent.com/2193314/154286076-d9971147-565f-4b30-9b7d-ecb220f46444.png)

**Comment by joyceerhl** [comment] 2022-02-16 14:44
👍Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/3309

**Closed by joyceerhl** 2022-02-16 14:44 UTC
