### ISSUE TITLE
Remote Branch Reference in local repository not pruned after PR

### ISSUE THREAD

**Issue by JustinGrote** [microsoft/vscode-pull-request-github#2598] opened 2021-03-20 00:04 UTC
The PR process gives you the option to delete local and remote branches after merging. 

This is great however you still have a lingering remote branch in your local git. There should be an option to also specifically prune the remote branch reference in the local repo as well for a complete cleanup. This should be targeted specifically to the PR'd branch, equivalent of `git pull origin JustinGrote/MyMergedPR -p`

**Comment by RMacfarlane** [comment] 2021-03-23 19:13
Hey @JustinGrote, I think this is a duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/2504 - we've recently fixed the remote branch reference not getting removed when "remote" is checked for delete, now the remote should get deleted from GitHub and it should be pruned locally. This is available in the [nightly](https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github-insiders) version of the extension and will be shipped with the next stable version in about a week. Going to go ahead and close this, let me know if I've missed anything. Thanks!

**Closed by RMacfarlane** 2021-03-23 19:13 UTC
