### ISSUE TITLE
Activation failed

### ISSUE THREAD

**Issue by bm-stschneider** [microsoft/vscode-pull-request-github#2169] opened 2020-09-28 09:57 UTC
Issue Type: <b>Bug</b>

Maybe due to an update of the insiders version.

<img width="944" alt="image" src="https://user-images.githubusercontent.com/30625381/94418467-bd1aef00-0181-11eb-85c9-587dd758d09d.png">

Extension version: 0.20.0
VS Code version: Code - Insiders 1.50.0-insider (772aa0723f7f6b04b710bc3a92b7a904b60ef439, 2020-09-28T05:41:42.988Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|16.00GB (1.13GB free)|
|Process Argv|--crash-reporter-id 3b7acc73-7f05-4994-b539-24b72f428fcd|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by zoltanbedi** [comment] 2020-09-28 12:59
Duplicate of #2168

**Comment by RMacfarlane** [comment] 2020-10-05 19:02
Thanks, closing as a duplicate! This should now be fixed with version 0.20.1 of the extension.

**Closed by RMacfarlane** 2020-10-05 19:02 UTC
