### ISSUE TITLE
No response from host https://ssh.github.com/... Client network socket disconnected before secure TLS connection was established

### ISSUE THREAD

**Issue by aryzing** [microsoft/vscode-pull-request-github#1929] opened 2020-06-23 08:33 UTC
- Extension version: v0.17.0
- VSCode Version: 
```
1.46.1
cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
x64
```
- OS: Ubuntu 18.04 LTS
- Node.js: 14.4.0

Steps to Reproduce:

As soon as vs code is opened, the extension starts to run, and is unable to connect to github. The full log of the issue from the OUTPUT tab is (emphasis mine):

```
[Info] Looking for git repository
[Info] Git repository found, initializing review manager and pr tree view.
[Info] Review> Validate state in progress
[Info] Review> Validating state...

### (emphasis mine)
[Info] GitHubServer> No response from host https://ssh.github.com/<org>/<repo>: Client network socket disconnected before secure TLS connection was established
###

[Info] No remote with name 'origin' found. Please update your 'githubPullRequests.remotes' setting.
[Info] No remote with name 'upstream' found. Please update your 'githubPullRequests.remotes' setting.
[Info] No GitHub remotes found
[Info] Review> no matching pull request metadata found for current branch master
```

**Comment by RMacfarlane** [comment] 2020-06-23 15:22
Are you using a proxy? Can you check the value of your `HTTP_PROXY` and `HTTPS_PROXY` environment variables?

**Comment by aryzing** [comment] 2020-06-24 13:21
@RMacfarlane not using a proxy, just at home, using my wifi. This worked just fine a couple of weeks ago, so either something has changed in the plugin or vs-code, or my ISP is playing tricks on me.

As a side note, I do have the following set up in my .gitconfig to help me in cases where particular workpace wifi have ssh disabled:

```
[url "ssh://git@github.com/"]
	insteadOf = https://github.com/
```

Although, to reiterate, this worked fine a couple weeks ago.

**Comment by rgujral-ari** [comment] 2020-07-26 14:36
Ran into same problem, what I have observed is using HTTPS instead of SSH and re-installing the extension solved the issue.
Now I am able to see the PR's

**Comment by alexr00** [comment] 2020-11-11 16:48
I think this is a duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/1656

**Closed** 2020-11-11 16:48 UTC
