### ISSUE TITLE
Setting to automatically pull after merge

### ISSUE THREAD

**Issue by tyler36** [microsoft/vscode-pull-request-github#3017] opened 2021-10-01 04:54 UTC
# My problem
I create and complete an issue. Then I submit PR using a 'merge & rebase' stategy. Then I get the option to "delete branch...", and select both the local & remote branches. This closes out the window and moves me back to the `main` branch.

However, my `origin/main` branch is now ahead of `main`. Here is my problem. Sometimes I forget to `pull` and create and assign a new issue via the extension. This occures on the local `main` so I'm working on an outdated branch.

# Feature Request
What I would like is after I click the "delete branch", and select the branches, the extension should:
- switch me to the main branch (currently does)
- pulls the latest copy down (what I want)

I'm not sure everyone would like this feature so it would be best have a setting which allows enabling / disabling.
I'm not sure of everyones workflow so maybe it may be desirable to tie to the 'merge & rebase' method as well. Or have the setting configurable per merge strategy.

**Comment by varna** [comment] 2022-02-08 14:40
Same here. Am I using it in the wrong way?

p.s. My project is in a private organisation repo, while issue branches are created on my personal account fork for some reason.

**Comment by alexr00** [comment] 2022-12-12 14:35
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/2263

**Closed by alexr00** 2022-12-12 14:35 UTC
Labels: feature-request
