### ISSUE TITLE
Groups not available in reviewer list

### ISSUE THREAD

**Issue by SimonWilliams-STL** [microsoft/vscode-pull-request-github#1393] opened 2019-10-18 08:15 UTC
- Extension version: 0.12.0
- VSCode Version: 1.39.2
- OS: Windows 10 (1903)

Steps to Reproduce:

1. Create a pull request 
2. Click on the plus next to reviewers to add a reviewer

The pick list that is presented contains all the people that would be presented on the website, but not the groups.

**Comment by RMacfarlane** [comment] 2019-10-18 18:02
@SimonWilliams-STL This looks like a duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/1126, let's track it there

**Closed by RMacfarlane** 2019-10-18 18:02 UTC
