### ISSUE TITLE
Issues pane: Sort issues in milestone by issue priority

### ISSUE THREAD

**Issue by aaronadamsCA** [microsoft/vscode-pull-request-github#2029] opened 2020-07-29 10:28 UTC
I'd like the issue pane to sort my milestone issues by priority, so that they appear in the same order as on GitHub.

GitHub:

<img src="https://user-images.githubusercontent.com/1505561/88788885-3ef89700-d196-11ea-81eb-caa8843d30e5.png" width="400">

Extension:

<img src="https://user-images.githubusercontent.com/1505561/88788916-4ae45900-d196-11ea-9358-28f551ae67a9.png" width="300">

Happy to take a crack at it myself, might just need some direction.

**Comment by chrisdias** [comment] 2020-07-30 00:52
You can define your own queries as well as modify the "My Issues" query in `settings.json`, using the same query syntax as on github.com (see https://docs.github.com/en/github/searching-for-information-on-github/understanding-the-search-syntax).  You can do this for both Pull Requests and Issues.

``` json
    "githubIssues.queries": [
        {
            "label": "My Issues",
            "query": "is:issue is:open repo:${owner}/${repository} sort:comments-desc "
        },
        {
            "label": "Created Issues",
            "query": "author:${user} state:open repo:${owner}/${repository} sort:updated-desc"
        },
        {
            "label": "Closed Issues",
            "query": "author:${user} state:closed repo:${owner}/${repository} sort:updated-desc"
        }
   ]
```

Does this help?

**Comment by aaronadamsCA** [comment] 2020-07-30 14:25
I don't think so, because (unless I'm mistaken) the settings syntax isn't expressive enough to recreate the default behaviour of grouping tickets by milestone. I also don't think GitHub query syntax offers sorting by milestone priority.

I was assuming that milestone grouping was probably implementing in the extension itself, and that ordering by milestone priority (assuming the data is even available via the GitHub API) would need to go in the same place.

**Comment by alexr00** [comment] 2020-08-10 10:38
I think you are looking for a way to group issues. If we provide a way to group them, then you can use GitHub's search syntax to sort however you want.

**Comment by alexr00** [comment] 2020-08-10 10:39
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/1881

**Closed by alexr00** 2020-08-10 10:39 UTC

**Comment by aaronadamsCA** [comment] 2020-08-11 15:28
Sounds good! I do still think the default query should sort by milestone priority, if possible, but if I can eventually do it myself that's good too.
