### ISSUE TITLE
Allow for Jump to Definition 

### ISSUE THREAD

**Issue by therapon** [microsoft/vscode-pull-request-github#1832] opened 2020-05-26 22:22 UTC
It would help a lot if the extension would show the diff for the PR in question but also allow for some of the IDE's feature like "Jump to Definition". 

While being able to perform PRs in my IDE is very convenient, the ability to have a view of the PR in my IDE **and** navigate the code will be even better.

**Comment by Rusty-1** [comment] 2020-05-27 04:23
I agree as this would also help immensely for code review sessions. This is something that the web client lacks.

**Comment by RMacfarlane** [comment] 2020-05-29 14:34
This looks like a duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/486.

There's already some ability to do this, but it requires clicking the "Checkout" button on a pull request's overview. This brings up a new "Changes in Pull Request" view under the old tree, the diffs opened under that should support code navigation as normal.

**Closed by RMacfarlane** 2020-05-29 14:34 UTC
