### ISSUE TITLE
Not auto-suggesting to open PR after push

### ISSUE THREAD

**Issue by diminutivesloop** [microsoft/vscode-pull-request-github#3372] opened 2022-03-04 14:06 UTC
Issue Type: <b>Bug</b>

1. Create a new git branch and commit changes
2. Push that branch via the "Git: Push" command

No notification appears offering to create a PR from the pushed branch. This behavior existed until recently.

Extension version: 0.36.2
VS Code version: Code 1.65.0 (Universal) (b5205cc8eb4fbaa726835538cd82372cc0222d43, 2022-03-02T11:11:20.886Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|32.00GB (6.46GB free)|
|Process Argv|--crash-reporter-id ed50f89e-497f-43cd-86f3-a73119f730ed|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
testflight:30433670
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30433507
vsclayoutctrc:30437038
vsrem710:30416614
dsvsc009:30440023
pythonvsnew555cf:30442237
vsbas813:30436447
vscscmwlcmt:30438805
helix:30440343
vscaac:30438847
vsnot107cf:30443615

```

</details>

**Comment by alexr00** [comment] 2022-12-09 15:05
If you're still seeing this then please ping this issue! Closing as I can't reproduce the issue.

**Closed by alexr00** 2022-12-09 15:05 UTC
