### ISSUE TITLE
Suggest Edit should not ask for staging changes

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode-pull-request-github#734] opened 2018-12-05 11:27 UTC
Testing https://github.com/Microsoft/vscode/issues/64262

Making suggest changes one step process is easy than to asking me to stage and suggest. I think staging can be hidden, if I explicitly ask for suggesting them, just like you unstage and undo them after suggesting is done

**Comment by RMacfarlane** [comment] 2018-12-05 21:45
This sounds like a duplicate of https://github.com/Microsoft/vscode-pull-request-github/issues/719

**Closed by RMacfarlane** 2018-12-05 21:45 UTC
