### ISSUE TITLE
@<code complete> is not working in the PR description editor

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode-pull-request-github#328] opened 2018-08-29 13:50 UTC
Testing Microsoft/vscode#57301

This is a very useful thing in the web.

**Comment by RMacfarlane** [comment] 2018-08-29 16:10
Closing as a duplicate of https://github.com/Microsoft/vscode-pull-request-github/issues/223

**Closed by RMacfarlane** 2018-08-29 16:10 UTC
