### ISSUE TITLE
The plugin says "'remoteHub/pullRequest' is not a valid menu identifier."

### ISSUE THREAD

**Issue by lkxed** [microsoft/vscode-pull-request-github#3417] opened 2022-03-20 10:13 UTC
- Extension version: v0.38.1
- VSCode Version: 1.65.2
- OS: macOS 12.2.1

Steps to Reproduce:

1. Open VSCode -> Select Extension Panel -> Select this Plugin -> Select RuntimeState (may be this name because I am not using an English version)
2. See this "'remoteHub/pullRequest' is not a valid menu identifier." (translated)

I've tried to restart VSCode, it keeps appearing. Not a real bug I think, because it doesn't affect anything so far. Seems like a harmless stubborn hint.

**Comment by lkxed** [comment] 2022-03-21 17:11
@alexr00 this screen shot should do it. (the display is in Simplified Chinese)
<img width="893" alt="Snipaste_2022-03-22_01-07-42" src="https://user-images.githubusercontent.com/39257389/159326889-8e783930-f703-4ddc-afcc-6c58785d6bed.png">

**Comment by alexr00** [comment] 2022-03-22 09:34
Thanks! This is expected as an outcome of https://github.com/microsoft/vscode/issues/140463.

@sandy081, would you consider not showing infos in the extension page like this?

**Comment by alexr00** [comment] 2022-03-22 13:33
Sounds like this is intended behavior then. It is indeed a harmless stubborn hint. Closing as-designed.

**Closed by alexr00** 2022-03-22 13:33 UTC
Labels: needs more info
