### ISSUE TITLE
GraphQL error: Invalid email address

### ISSUE THREAD

**Issue by appleoddity** [microsoft/vscode-pull-request-github#5842] opened 2024-03-18 15:23 UTC
- Extension version: v0.82.0
- VSCode Version: 1.87.0
- OS: Windows 11
- Repository Clone Configuration (single repository/fork of an upstream repository): Single repository
- Github Product (Github.com/Github Enterprise version x.x.x): Github.com

It looks like this issue added a email address selection when creating a merge commit: https://github.com/microsoft/vscode-pull-request-github/issues/5326

I have been unable to submit a merge commit through vscode for probably a month now. I can everything but submit the merge commit. I have to go to the Github UI to do that.

When I click to, `Create Merge Commit`, I get `Unable to merge pull request. GraphQL error: Invalid email address`

Yet, in the details of the merge commit I see `Commit will be associated with <my valid email>`.

I'm not sure what else I can look for here. I'm not sure if I need to reset a setting somewhere, or what. Everything about the pull request extension seems to work fine, so I know it is recognizing my email and user account properly.

What else can I do to provide more detail or troubleshoot the issue?

**Comment by alexr00** [comment] 2024-03-26 11:35
I'm adding some additional logging with https://github.com/microsoft/vscode-pull-request-github/pull/5870. If you could try the pre-release version of the extension tomorrow and set the log level to debug (command Developer: Set Log Level -> GitHub Pull Request -> Debug), then you'll get the new logging. 

Once you have the new logging, can you try to reproduce the issue then check the GitHub Pull Request output for a log like that says "Merging PR"? That line will also include the email address. Can you confirm whether that email address is correct?

**Comment by statropy** [comment] 2024-04-03 20:02
I had this same issue, so I captured a log with the pre-release version. I did not see anything in the log that says "Merging PR". Below is from selecting the correct email address, then pressing Squash and Merge. The -1 cost and undefined are interesting. It may be stopping on error before your new debug line.

```2024-04-03 15:45:44.442 [debug] GitHubRepository> Fetch authenticated user emails - enter
2024-04-03 15:45:44.442 [debug] RateLimit> Extension rate limit remaining: 140, /user/emails
2024-04-03 15:45:44.756 [debug] GitHubRepository> Fetch authenticated user emails - done
2024-04-03 15:45:44.757 [debug] RateLimit> REST Rate limit remaining: 4994, cost: -1, /user/emails
2024-04-03 15:45:50.798 [debug] PullRequestOverviewPanel> initialized with PR
2024-04-03 15:45:54.906 [debug] RateLimit> Extension rate limit remaining: 140, undefined```

**Comment by ericohlin** [comment] 2024-04-04 01:37
I'm getting this same error  `Unable to merge pull request. GraphQL error: Invalid email address`

`
2024-04-03 18:35:13.970 [debug] RateLimit> Extension rate limit remaining: 140, undefined
`

GitHub Pull Requests v0.82.1

Version: 1.87.2 (system setup)
Commit: 863d2581ecda6849923a2118d93a088b0745d9d6
Date: 2024-03-08T15:20:17.278Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.20348

**Comment by alexr00** [comment] 2024-04-04 09:44
Thanks for the logs, but they are missing the new log line. The latest pre-release version of the extension requires that you use VS Code insiders (at least it will for a few more hours, there should be a new stable version of VS Code and the extension today).

**Comment by statropy** [comment] 2024-04-04 14:37
I did switch to the insiders plugin. I think the error happens earlier on.

**Comment by fearnycompknowhow** [comment] 2024-04-04 20:36
Just to add more to this discussion, I **am** able to merge the PR if I use the `Create Merge Commit` button from the `GitHub Pull Request` sub-menu, but (like the others have said) it doesn't work if I try to do the same thing from the Pull Request description screen
<img width="1762" alt="Screenshot 2024-04-04 at 3 34 07 PM" src="https://github.com/microsoft/vscode-pull-request-github/assets/73258164/a0c87a5d-321b-4087-a1e4-92b118f59c5d">

**Comment by ericohlin** [comment] 2024-04-04 20:59
Hey @alexr00, 

I updated my VSCode and I'm on the latest pre-release of GitHub Pull Requests. 

GitHub Pull Requests: v0.87.2024040414 (pre-release)

Version: 1.88.0 (system setup)
Commit: 5c3e652f63e798a5ac2f31ffd0d863669328dc4c
Date: 2024-04-03T13:26:18.741Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.20348

The issue still exists. 

`2024-04-04 13:57:16.560 [debug] FolderRepositoryManager+0> Merging PR: 33 method: merge for user: "myusername@mycompany.com" - enter
2024-04-04 13:57:16.561 [debug] RateLimit> Extension rate limit remaining: 140, undefined
`

Thanks!

**Comment by alexr00** [comment] 2024-04-05 08:02
@ericohlin thanks for sharing those log! Is the email address listed in the logs the one that you expected the merge to be associated with? No extra spaces or other incorrect characters?

**Comment by ericohlin** [comment] 2024-04-05 16:53
> @ericohlin thanks for sharing those log! Is the email address listed in the logs the one that you expected the merge to be associated with? No extra spaces or other incorrect characters?

Hey @alexr00, yes, that's correct. I sanitized the log before sharing. To double-check, I copied the value from the log into Beyond Compare and then manually typed my email address, and they appear to be a 100% match. Everything looks exactly as it should.

**Comment by alexr00** [comment] 2024-04-08 09:16
Ok, I'm not sure what's going on here then. Does your email address have any special characters? If you go to github.com to merge the PR are you allowed to select this email address there?

**Comment by ericohlin** [comment] 2024-04-08 17:28
> Ok, I'm not sure what's going on here then. Does your email address have any special characters? If you go to github.com to merge the PR are you allowed to select this email address there?

Good morning. There are no special characters in my email address. If I go to github.com and merge the PR, when I click on Merge Pull Request, it says just above the Commit Merge button _This commit will be authored by myusername@mycompany.com_ and the email address is identical to the one in the logs. 

This may be helpful, or maybe it's not, but this PR also has a commit from another team member. There were two total commits, one from me and one from my teammate.

**Comment by alexr00** [comment] 2024-04-09 10:47
> If I go to github.com and merge the PR, when I click on Merge Pull Request, it says just above the Commit Merge button This commit will be authored by [myusername@mycompany.com](mailto:myusername@mycompany.com) and the email address is identical to the one in the logs.

This is exactly what I needed to know, though I don't see why this can happen. 

> This may be helpful, or maybe it's not, but this PR also has a commit from another team member. There are two total commits, one from me and one from my teammate.

Maybe. Let's see if we can find the exact combination that can cause this:
- Did you create the PR, or did your colleague?
- Did you make the first commit? 
- Did you make the most recent commit?
- Do you and your colleague have the same level of permissions in the repo? What level of permissions do you both have?
- Is this an org-owned repo, or a personal repo?

**Comment by appleoddity** [comment] 2024-04-09 19:08
I can confirm that the email address is correct. I have monitored the GraphQL query with Fiddler, and even recreated the request with the GitHub GraphQL Explorer. It is always the same result, "Invalid email address."

If I remove the `authorEmail` variable from the graphQL request all together, the merge pull request succeeds.

I'm starting to wonder if this is a Github issue. Can anybody successfully perform a merge pull request with GraphQL while supplying an `authorEmail`?

**Comment by ericohlin** [comment] 2024-04-09 22:23
> > If I go to github.com and merge the PR, when I click on Merge Pull Request, it says just above the Commit Merge button This commit will be authored by [myusername@mycompany.com](mailto:myusername@mycompany.com) and the email address is identical to the one in the logs.
> 
> This is exactly what I needed to know, though I don't see why this can happen.
> 
> > This may be helpful, or maybe it's not, but this PR also has a commit from another team member. There are two total commits, one from me and one from my teammate.
> 
> Maybe. Let's see if we can find the exact combination that can cause this:
> 
> * Did you create the PR, or did your colleague?
> * Did you make the first commit?
> * Did you make the most recent commit?
> * Do you and your colleague have the same level of permissions in the repo? What level of permissions do you both have?
> * Is this an org-owned repo, or a personal repo?

Did you create the PR, or did your colleague?
-- I created
Did you make the first commit?
-- I made first commit
Did you make the most recent commit?
-- Colleague made most recent commit
Do you and your colleague have the same level of permissions in the repo? What level of permissions do you both have?
-- Same. Maintain
Is this an org-owned repo, or a personal repo?
-- Org-owned

**Comment by alexr00** [comment] 2024-04-10 15:59
Tried with a private, org owned, repo. I still can't repro the issue.

**Comment by grays29** [comment] 2024-04-10 16:12
We are experiencing the same issue by all users. Org owned Repo's 

Our email is the format Firstname_surname@domain

Works Fine from the web

**Comment by appleoddity** [comment] 2024-04-15 20:14
> Tried with a private, org owned, repo. I still can't repro the issue.

Can you grab the API query with Fiddler. Maybe we can compare how it is different.

As mentioned, I grabbed the query being sent to Github and it had what looked like a valid formed request, with the proper email address, yet it still fails when submitting directly. I wonder how your request looks different. Perhaps it is something on the Github side that has to do with a certain repo setting, or what not.

**Comment by ericohlin** [comment] 2024-04-23 16:22
Hey @alexr00, I was able to reproduce this error again with a brand new PR; this time, I was the only contributor. 

Private, org-owned, repo, solo contributor. 

What do you need from me? 😄  

Thanks!

**Comment by alexr00** [comment] 2024-04-29 13:19
I guess having other contributors to the PR was a red herring. 

One more question: when you go to github.com for your repo, is there a little label in the top right that says "GitHub Enterprise", like this?

![image](https://github.com/microsoft/vscode-pull-request-github/assets/38270282/c0988c51-01d0-47fd-afbc-9d63d8f6843a)

**Comment by ChrisHines** [comment] 2024-04-30 21:44
I have encountered this problem. My details are similar to those described in https://github.com/microsoft/vscode-pull-request-github/issues/5842#issuecomment-2047957521. github.com _does_ have the "GitHub Enterprise" label you asked about in the above comment.

**Comment by ericohlin** [comment] 2024-04-30 23:07
> I guess having other contributors to the PR was a red herring.
> 
> One more question: when you go to github.com for your repo, is there a little label in the top right that says "GitHub Enterprise", like this?
> 
> ![image](https://private-user-images.githubusercontent.com/38270282/326450486-c0988c51-01d0-47fd-afbc-9d63d8f6843a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ1MTg3MzcsIm5iZiI6MTcxNDUxODQzNywicGF0aCI6Ii8zODI3MDI4Mi8zMjY0NTA0ODYtYzA5ODhjNTEtMDFkMC00N2ZkLWFmYmMtOWQ2M2Q4ZjY4NDNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDMwVDIzMDcxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3MzY3Yjg0ZjQ4ZDMzYzdlMTM0OGQwODc5ZjRhYjIyNTFjYzQxYmFjMzliMGUzMzI3OTY2NzUwYWFlOTI4OTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eWJAZXG4v13m4U61M_80sN7AD5EJ3SdKBc18UAykujk)

Yes there is.

**Comment by alexr00** [comment] 2024-05-02 07:38
> Yes there is.

> github.com does have the "GitHub Enterprise" label you asked about in the above comment.

This is great news. I'll disable this feature for Enterprise. I'm guessing Enterprise just never supports setting an email because you'll only have one email associated with your enterprise account.

**Comment by alexr00** [comment] 2024-05-07 07:49
The fix has been available in the pre-release version of the extension for a couple days. Could some of the folks in this thread install the pre-release version and let me know if it solves the issue?

**Closed** 2024-05-07 14:02 UTC
Labels: bug, candidate

**Comment by ericohlin** [comment] 2024-05-07 14:29
@alexr00  this resolved the issue for me. I'm on version v0.89.2024050704 (pre-release). 

Thank you! 🙇🏻 🙇🏻

**Comment by alexr00** [comment] 2024-05-07 14:35
Thanks for verifying and for your patience while I found a fix!

**Comment by appleoddity** [comment] 2024-05-14 14:29
Confirmed working in latest release. Thank you very much.
