### ISSUE TITLE
Open an issue in a tab

### ISSUE THREAD

**Issue by krlmlr** [microsoft/vscode-pull-request-github#2747] opened 2021-05-24 05:25 UTC
A pull request can be opened in a local tab. It would be great if the same was supported for issues.

Apologies if this is a duplicate, I did a search but haven't found anything related.

**Comment by alexr00** [comment] 2021-11-22 14:09
duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/2229

**Closed by alexr00** 2021-11-22 14:09 UTC
Labels: feature-request, issues
