### ISSUE TITLE
Graceful handling of Create PR when there are changes but no commits

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-pull-request-github#717] opened 2018-12-04 21:35 UTC
Issue Type: <b>Feature Request</b>

Testing https://github.com/Microsoft/vscode/issues/64262.

1) create a new branch
2) change a file but don't commit
3) Run `Create PR` from the command palette
-> Warning
```
Creating pull requests for 'kieferrm/show-busy-indicator' failed: Validation Failed: No commits between remote-hackathon and kieferrm/show-busy-indicator
```

Just as with committing without staged changes we should ask people whether the current changes should be included in the PR. Similarly, we should push for the user if there are local commits.

Extension version: 0.337.0
VS Code version: Code - Insiders 1.30.0-insider (fa87e67ebfd6b8014ba697ddbc6c2d6c0e2cb970, 2018-12-04T09:26:33.257Z)
OS version: Darwin x64 18.0.0

**Comment by RMacfarlane** [comment] 2020-11-09 17:36
Closing as a duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/2100, this should already be fixed

**Closed by RMacfarlane** 2020-11-09 17:36 UTC
Labels: feature-request
