### ISSUE TITLE
Enhance New Issue Creation Interface

### ISSUE THREAD

**Issue by maddes8cht** [microsoft/vscode-pull-request-github#5509] opened 2023-11-25 20:51 UTC
When creating a new Pull Request, we benefit from a user-friendly interface with distinct text boxes in the left sidebar. However, the experience differs when creating a new Issue, as it currently provides only a basic Text editor.

I propose implementing an improved interface for creating new Issues, mirroring the Pull Request layout. This enhanced interface should include:

- Title box
- Assignees box
- Labels box
- Milestones box
-  a sizable text box for the Issue description
Assignees, labels and Milestones boxes should allow users to choose from existing options and provide the flexibility to create new ones.

This enhancement would elevate the status of 'issues' in the 'Pull Requests and Issues' extension, transitioning it from a third-class member to a second-class one. Your consideration and implementation of this feature would greatly enhance the usability of the platform.

**Comment by alexr00** [comment] 2023-12-15 14:45
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/4023

**Closed by alexr00** 2023-12-15 14:45 UTC
Labels: feature-request
