### ISSUE TITLE
Errors when offline

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-pull-request-github#4163] opened 2022-11-07 18:52 UTC
- Disable wifi, open a vscode window with git repo
- Get this error popup a couple times `Fetching pull requests failed: request to https://api.github.com/repos/microsoft/vscode/pulls?per_page=20&page=1 failed, reason: getaddrinfo ENOTFOUND api.github.com`

Log

```

[Debug 1667846016.196s] Activation> Initializing state.
[Debug 1667846016.196s] Activation> Creating credential store.
[Debug 1667846016.215s] RateLimit> API call count: 8 (Viewer)
[Debug 1667846016.222s] Activation> Registering built in git provider.
[Debug 1667846016.222s] Activation> Registering live share git provider.
[Debug 1667846016.222s] Activation> Creating tree view.
[Debug 1667846016.222s] Looking for git repository
[Debug 1667846016.222s] Found 0 repositories during activation
[Debug 1667846016.222s] Git repository found, initializing review manager and pr tree view.
[Debug 1667846016.232s] Registering git provider
[Debug 1667846016.236s] Review> Validate state in progress
[Debug 1667846016.236s] Review> Validating state...
[Debug 1667846016.241s] RateLimit> API call count: 9 (/notifications)
[Debug 1667846016.287s] GitPostCommitCommands> Trying to register post commit commands.
[Debug 1667846016.297s] GitHubServer> No response from host https://no_pus/h: request to https://no_pus/api/v3/rate_limit failed, reason: getaddrinfo ENOTFOUND no_pus
[Debug 1667846016.297s] GitHubServer> Host https://no_pus/h is associated with GitHub: 0
[Debug 1667846016.297s] FolderRepositoryManager> Not all remotes found. The following remotes are missing: upstream
[Debug 1667846016.297s] FolderRepositoryManager> Displaying configured remotes: origin, upstream
[Debug 1667846016.301s] Found GitHub remote
[Debug 1667846016.301s] GitHubRepository> Fetch metadata - enter
[Debug 1667846016.301s] RateLimit> API call count: 10 (/repos/{owner}/{repo})
[Debug 1667846016.312s] Unable to resolve remote: HttpError: request to https://api.github.com/repos/microsoft/vscode failed, reason: getaddrinfo ENOTFOUND api.github.com
[Debug 1667846016.312s] GitHubRepository> Fetch metadata - enter
[Debug 1667846016.312s] RateLimit> API call count: 11 (/repos/{owner}/{repo})
[Debug 1667846016.324s] Missing upstream check failed: HttpError: request to https://api.github.com/repos/microsoft/vscode failed, reason: getaddrinfo ENOTFOUND api.github.com
[Debug 1667846016.324s] GitHubRepository> Fetch assignable users - enter
[Debug 1667846016.324s] GitHubRepository> Fetch all issues - enter
[Debug 1667846016.324s] GitPostCommitCommands> Trying to register post commit commands.
[Debug 1667846016.324s] GitPostCommitCommands> GitHub remote(s) found, registering post commit commands.
[Debug 1667846016.325s] GitHubRepository> Fetch all issues - enter
[Debug 1667846016.325s] RateLimit> API call count: 12 (GetAssignableUsers)
[Debug 1667846016.326s] GitHubRepository> Fetch metadata - enter
[Debug 1667846016.326s] GitHubRepository> Fetch metadata - enter
[Debug 1667846016.326s] RateLimit> API call count: 13 (/repos/{owner}/{repo})
[Debug 1667846016.326s] RateLimit> API call count: 14 (/repos/{owner}/{repo})
[Debug 1667846016.337s] GitHubRepository> Fetch all pull requests - enter
[Debug 1667846016.375s] RateLimit> API call count: 15 (/repos/{owner}/{repo}/pulls)
[Debug 1667846016.399s] GitHubRepository> Unable to fetch assignable users: Error: Network error: request to https://api.github.com/graphql failed, reason: getaddrinfo ENOTFOUND api.github.com
[Debug 1667846016.399s] GitHubRepository> Fetching all pull requests failed: HttpError: request to https://api.github.com/repos/microsoft/vscode/pulls?per_page=20&page=1 failed, reason: getaddrinfo ENOTFOUND api.github.com
[Debug 1667846016.537s] Repo state for file:///Users/roblou/code/vscode changed.
[Debug 1667846016.537s] Repo file:///Users/roblou/code/vscode has already been setup.
[Debug 1667846016.538s] GitHubRepository> Fetch all issues - enter
[Debug 1667846016.538s] GitHubRepository> Fetch metadata - enter
[Debug 1667846016.538s] RateLimit> API call count: 16 (/repos/{owner}/{repo})
[Debug 1667846017.309s] GitHubRepository> Fetch all issues - enter
[Debug 1667846017.309s] GitHubRepository> Fetch metadata - enter
[Debug 1667846017.309s] RateLimit> API call count: 17 (/repos/{owner}/{repo})
[Debug 1667846017.311s] Review> current branch main is associated with pull request #151549
[Debug 1667846017.311s] Review> Resolving pull request
[Debug 1667846017.311s] GitHubRepository> Fetch pull request 151549 - enter
[Debug 1667846017.311s] RateLimit> API call count: 18 (PullRequest)
[Debug 1667846017.338s] GithubRepository> Unable to fetch PR: Error: Network error: request to https://api.github.com/graphql failed, reason: getaddrinfo ENOTFOUND api.github.com
[Debug 1667846017.342s] Review> This PR is no longer valid
[Debug 1667846017.343s] GitHubRepository> Fetch all pull requests - enter
[Debug 1667846017.343s] RateLimit> API call count: 19 (/repos/{owner}/{repo}/pulls)
[Debug 1667846017.353s] GitHubRepository> Fetching all pull requests failed: HttpError: request to https://api.github.com/repos/microsoft/vscode/pulls?per_page=20&page=1 failed, reason: getaddrinfo ENOTFOUND api.github.com
```

**Comment by alexr00** [comment] 2024-12-17 11:48
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/706

**Closed by alexr00** 2024-12-17 11:48 UTC
Labels: bug
