### ISSUE TITLE
Don't open the diff automatically when I load a (local?) window with a PR

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#2593] opened 2021-03-19 13:44 UTC
Repro:

1. Check out a branch with a PR
2. Open some file, eg. settings.json
3. Reload the window

When reloaded, after a few seconds a diff from the PR will show up. This breaks my workflow because I often send PRs to myself while I'm stabilizing a large change (CI running, viewing diff in GH, comment indicators help show which parts the PR changed across all commits).

I'm guessing this was added for Codespaces, so maybe this should only happen there.

**Comment by RMacfarlane** [comment] 2021-03-19 14:58
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/2295

**Closed by RMacfarlane** 2021-03-19 14:58 UTC
