### ISSUE TITLE
Cannot read property 'toLocaleLowerCase' of undefined

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-pull-request-github#474] opened 2018-09-13 20:14 UTC
- Extension version: 0.1.4
- VSCode Version: 1.28 Insiders
- OS: macOS

Get exception `Cannot read property 'toLocaleLowerCase' of undefined` from https://github.com/Microsoft/vscode-pull-request-github/blob/4d60958a35112c6af5175cbe1f0d26a8e1764f68/src/authentication/vsConfiguration.ts#L55-L57

**Comment by shana** [comment] 2018-09-18 11:04
Ugh, sigh

**Comment by shana** [comment] 2018-09-18 11:08
@rebornix is there a stacktrace for this exception? All the calls to this method check whether the value is defined before calling it, so I'm not sure how the exception could happen in the current codepaths. The method is public so of course new code could be calling it without checking and I'll make sure it doesn't blow up, just curious if I missed anything on the existing code.

**Comment by RMacfarlane** [comment] 2019-10-09 18:04
Closing this issue since I haven't been able to reproduce it in the latest version of the extension and believe it has been fixed since this was filed

**Closed by RMacfarlane** 2019-10-09 18:04 UTC
Labels: bug
