### ISSUE TITLE
Changing application while "exit review mode" list is open leaves button in inconsistent state

### ISSUE THREAD

**Issue by paustint** [Microsoft/vscode-pull-request-github#488] opened 2018-09-16 15:36 UTC
- Extension version: 0.1.5
- VSCode Version: 1.27.2
- OS: OSX (latest)

Steps to Reproduce:

1. Check out a PR
2. click on the Exit review mode to show the list of branches to choose from
3. Change applications (alt/command+tab)
4. Bring focus back to VSCode
    1. Notice that the list of branches has been hidden
    1. Notice that button is still in a disabled state
5. To restore to a usable state, re-click on "details" in the github pull request sidebar (or possibly change tab focus and come back to existing tab)

**Comment by rebornix** [comment] 2018-09-17 17:47
Duplicate of https://github.com/Microsoft/vscode-pull-request-github/issues/358, thanks for reporting the issue!

**Closed** 2018-09-17 17:47 UTC
Labels: duplicate
