### ISSUE TITLE
VSCode - GitHub authentication - Failed to open uri

### ISSUE THREAD

**Issue by Pieber** [microsoft/vscode-pull-request-github#3472] opened 2022-04-19 10:22 UTC
Hi!

The authentication through GitHub does not work (the authentication with Microsoft works).

- VSCode Version:
```
Version: 1.66.2
Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
Date: 2022-04-11T07:49:24.808Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Linux x64 5.10.0-13-amd64 snap
```
- OS: Debian 11 Bullseye Xfce

Steps to Reproduce:

0. Install VSCode with snap.
1. Launch VSCode.
2. Click on _Accounts - Sign in to Sync Settings_.
3. Click on _Sign in with GitHub_.
4. Authentication on GitHub.
5. Click on _Open open-xdg_ in the Open open-xdg window.
6. An error window appears: _Failed to open URI. The specified location is not supported._

Below is a screenshot of the error:

![Screenshot_2022-04-19_11-59-09](https://user-images.githubusercontent.com/32089033/163983455-89078588-3ceb-4613-8c4f-4abb5fc10c68.png)

**Comment by alexr00** [comment] 2022-04-22 11:06
@TylerLeonhardt I know you've made some GitHub auth changes recently. Does this look like anything you've seen before?

**Comment by TylerLeonhardt** [comment] 2022-04-23 01:04
Ah yes.. the problem with the tar is that it doesn't setup our `vscode://` handler. This is a duplicate of https://github.com/microsoft/vscode/issues/146408#issuecomment-1095273737 (that comment also has context)

To combat this on auth side, we have fallback logic when you have trouble logging in... it will suggest using a different way to log in that doesn't use `vscode://`. That's in VS Code Insiders and will be in the next stable version.

**Closed** 2022-04-23 01:04 UTC
Labels: duplicate

**Comment by StakFallT** [comment] 2022-08-18 13:11
So here's what I did. I created the association myself, it took a little doing since I wasn't familiar with how xdg-open gets its list of associations of mimetypes so I spent a little time working through the documentation. I'm on Manjaro so your results may vary! In any case, I put it all together in the following BASH script:
`#!/bin/sh
# For more information see:
# 	https://wiki.archlinux.org/title/User:Larivact/xdg-open#Set_the_default_browser
# 	https://wiki.archlinux.org/title/Default_applications#MIME_types_and_desktop_entries

# For creating .desktop files see:
# 	https://wiki.archlinux.org/title/Desktop_entries
# 	https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#recognized-keys
xdg-mime default code-oss-url-handler.desktop x-scheme-handler/vscode

MIME_contents="x-scheme-handler/vscode=code-oss.desktop;";

DESKTOP_filecontents="[Desktop Entry]
Type=Application
Name=code-oss
GenericName=Developer Utility
Icon=com.visualstudio.code
TryExec=/home/stakfallt/Downloads/VSCode-linux-x64/bin/code
Exec=/home/stakfallt/Downloads/VSCode-linux-x64/bin/code --uri=%U
Terminal=false
MimeType=x-scheme-handler/vscode;
Categories=Development;
NoDisplay=true
Hidden=true
# StartupWMClass=spotify"

echo ${DESKTOP_filecontents} >~/.Desktop/code-oss.desktop
echo ${MIME_contents} >>~/.config/mimeapps.list`

**Comment by AAdewunmi** [comment] 2023-05-30 15:46
I know this issue is closed but I thought I'd still contribute something. 
Had the same problem -> GitHub authentication - Failed to open uri. 
Using MacOS and VSCODE (version: Version: 1.78.2)
All I did was generate a new personal access token for VSCODE 
and push went straight to git repo from local repo.

😎

**Comment by nikonikolov** [comment] 2023-11-24 00:03
I am still encountering this error. For the most recent VS Code, the `.desktop` file needs to be slightly different
```
[Desktop Entry]
Name=Visual Studio Code - URL Handler
Comment=Code Editing. Redefined.
GenericName=Text Editor
Exec=/usr/bin/code --open-url %U
Icon=/usr/share/icons/hicolor/1024x1024/apps/code.png
Type=Application
NoDisplay=true
StartupNotify=true
Categories=Utility;TextEditor;Development;IDE;
MimeType=x-scheme-handler/vscode;
Keywords=vscode;
```

The important part is the `Exec` entry (speficially `--open-url` argument; note you might need to change the path to your VS Code) as well as the `MimeType` entry. Make sure you use a separate `.desktop` file for this and not the default one installed by VS code. You need to install the file so it is recognized by the system:

```
desktop-file-install --dir=$HOME/.local/share/applications ~/code-url-handler.desktop
update-desktop-database ~/.local/share/applications
xdg-mime query default x-scheme-handler/vscode  # Check it worked. This should print code-url-handler.desktop
```

**Comment by quinn** [comment] 2024-01-23 13:44
Is there a work-around for this? IS there a way to auth github without the `vscode://` link?

**Comment by BanjoFox** [comment] 2025-01-17 22:47
Crumbs for future viewers having this issue.  This is the solution that worked for me:

- Create a file called `code-url-handler.desktop` with the following contents:
```
[Desktop Entry]
Name=code-oss - URL Handler
Comment=Code Editing. Redefined.
GenericName=Text Editor
Exec=/opt/vscode-bin/code --open-url %U
Icon=com.visualstudio.code
Type=Application
NoDisplay=true
StartupNotify=true
Categories=Utility;TextEditor;Development;IDE;
MimeType=x-scheme-handler/vscode;
Keywords=vscode;
```
Source URL:  [https://github.com/microsoft/vscode/blob/main/resources/linux/code-url-handler.desktop](https://github.com/microsoft/vscode/blob/main/resources/linux/code-url-handler.desktop)
 
- Move the file to `/usr/share/applications` (system-wide)
- Update the mime database with: `xdg-mime default code-uri-handler.desktop x-scheme-handler/vscode`

NOTE:
You can also create the `code-uri-handler.desktop` for specific users by putting in their `~/.local/share/applications/` directory but then you have to make sure that `update-mime-database` is looking in those directories.
