### ISSUE TITLE
Fetch destination branch before deleting

### ISSUE THREAD

**Issue by coffeedoughnuts** [microsoft/vscode-pull-request-github#3464] opened 2022-04-13 11:03 UTC
Hi!

A common workflow for me (and others I presume) is to use this extension to merge a pull request, then delete the local and remote branches. This then leaves me in my destination branch (`main`) but I then need to `git pull` again to get the commit that I just merged from my PR.

It would be cool if, in the popup that asks if I want to delete my local and my remote branch (I appears after I click 'delete branch' after merging) there was a third pre-checked checkbox which would run `git fetch origin main main` (or whatever is applicable) _before_ the delete. This way when I land in my destination branch I have the commit that I just merged.

**Comment by alexr00** [comment] 2022-04-21 15:34
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/3017

**Closed by alexr00** 2022-04-21 15:34 UTC
