### ISSUE TITLE
unable to configure remote

### ISSUE THREAD

**Issue by mathesond2** [microsoft/vscode-pull-request-github#2061] opened 2020-08-14 17:56 UTC
Hi, I hate to add an issue here, but I updated to mac OS Catalina 10.15.6, blew away and recloned my original repo, and am now unable to see my PRs within the 'Github' viewlet.

I see the 'configure remotes' option, but I've tried:
* adding just my main remote url (`git@github.com:mathesond2/myRepoName.git`)
* adding both my origin and upstream remote urls
* adding neither (opting for default settings)

Regardless, I cant seem to get my pull requests to come through. I'm signed in to Github via VS Code and have authorized the extension, but am at a loss as to how I can get my setup working again, any ideas?

<img width="961" alt="Screen Shot 2020-08-14 at 1 48 37 PM" src="https://user-images.githubusercontent.com/5042175/90278503-8721e580-de35-11ea-9fe1-0161f5b9694a.png">

**Comment by RMacfarlane** [comment] 2020-08-14 18:00
Hi @mathesond2, can you include the logs shown in the Output panel when "GitHub Pull Requests" is chosen in the dropdown? What's the result of running `git remote -v` in the folder you have open? And is this using the most recent version of vscode and the extension?

**Comment by RMacfarlane** [comment] 2020-08-14 18:24
Nevermind, I'm able to reproduce this! Investigating currently...

**Comment by RMacfarlane** [comment] 2020-08-14 18:44
Actually, I had a mis-configured remote in the folder I was using to test with, I had been making edits to my ssh config. So, I'm no longer able to reproduce this.

**Comment by mathesond2** [comment] 2020-08-14 19:40
Thx for the quick response, @RMacfarlane! Is there any additional info I should provide?

**Comment by RMacfarlane** [comment] 2020-08-14 19:44
Yes, it would be great if you could provide:

- Logs from the Output panel
- Result of `git remote -v`
- Current VScode and extension versions

**Comment by mathesond2** [comment] 2020-08-14 21:30
sure thing
* no logs shown from output panel
* result:
```
origin	git@github.com:mathesond2/davidmatheson.me.git (fetch)
origin	git@github.com:mathesond2/davidmatheson.me.git (push)
```
* versions:
   * vscode: v 1.48.0, Commit: db40434f562994116e5b21c24015a2e40b2504e6
   * extension: v 0.19.0

**Comment by RMacfarlane** [comment] 2020-08-17 21:44
Hmm, it's strange to me that there's nothing in the output panel. It should have something like the following:
![Screen Shot 2020-08-17 at 2 44 13 PM](https://user-images.githubusercontent.com/3672607/90447436-29d99e80-e098-11ea-94d3-5f5b511c8812.png)

**Comment by RMacfarlane** [comment] 2020-08-19 15:49
@mathesond2 I notice from your first screenshot that there's also a workspace setting for remotes, can you check what that is? Would you mind also double checking the output panel?

**Comment by mathesond2** [comment] 2020-08-27 15:11
Sure thing, @RMacfarlane, and my apologies for the late response...I was incorrect on the output panel being empty as I had not selected the "Github Pull Request" tab...I've tried both ssh and https methods to no avail 🤷‍♂️

<img width="1185" alt="Screen Shot 2020-08-27 at 11 09 04 AM" src="https://user-images.githubusercontent.com/5042175/91460369-bb45cf00-e855-11ea-87af-a168070aa2ae.png">

**Comment by RMacfarlane** [comment] 2020-09-04 15:56
@mathesond2 Ah, the expected value of this setting is the name of the remote, not the url. Can you change it to `origin` and see what's in the output panel then?

**Comment by theetrain** [comment] 2020-09-13 19:38
(this is a cross-post and potential duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/1618#issuecomment-678395099)

I am also experiencing this issue. I am logged into the extension, yet I see the **No remotes match the current setting** message. 

Output of `git remote -v`
```
origin  git@github.com:TechnologyMasters/techmasters.chat.git (fetch)
origin  git@github.com:TechnologyMasters/techmasters.chat.git (push)
```

Output from the GitHub pull requests extension
```
[Info] Looking for git repository
[Info] Git repository found, initializing review manager and pr tree view.
[Info] Review> Validate state in progress
[Info] Review> Validating state...
[Info] GitHubServer> No response from host https://ssh.github.com/technologymasters/techmasters.chat: write 
EPROTO XXXXXXXXX:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:../../third_party/boringssl/src/ssl/tls_record.cc:242:

[Info] No remote with name 'upstream' found. Please update your 'githubPullRequests.remotes' setting.
[Info] No remote with name 'origin' found. Please update your 'githubPullRequests.remotes' setting.
[Info] No GitHub remotes found
[Info] Review> no matching pull request metadata found for current branch fix/signup-link
```

Here's a screenshot:

![image](https://user-images.githubusercontent.com/12798751/93026697-00982980-f5d6-11ea-8b57-50e19fdd9da6.png)

And my versions:

| System/Tool | Version |
| --- | --- |
| MacOS | 10.15.6 |
| VSCode | 1.49.0 | 
| GitHub Pull Requests Extension | 0.20.0 |
| SSL | OpenSSH_8.1p1, LibreSSL 2.7.3 |
| Git | 2.28.0 |

**Comment by mathesond2** [comment] 2020-10-15 02:43
Hi @RMacfarlane, THANK YOU so much for your help! 🙌 adding the origin's name rather than its url was the missing link

**Closed** 2020-10-15 02:44 UTC
Labels: needs more info

**Comment by ashish-kb** [comment] 2021-09-17 18:18
hi @RMacfarlane,  any plans on allowing full names? my GitHub url is slightly different from it is like ->  xxx.GitHub.com.

**Comment by eazevedo016** [comment] 2021-12-02 15:36
> Olá @RMacfarlane , MUITO OBRIGADO pela ajuda!🙌 adicionar o nome da origem ao invés de seu url era o elo que faltava

Não entendi. Você poderia explicar passo a passo como fez para funcionar a visualização dos seus PR's? Estou com o mesmo problema.
