### ISSUE TITLE
Unable to create a GitHub permalink for the selection. Check that your local branch is tracking a remote branch.

### ISSUE THREAD

**Issue by phstc** [microsoft/vscode-pull-request-github#1779] opened 2020-05-09 01:08 UTC
- Extension version: 0.16.0
- VSCode Version:  1.45.0
- OS: macOS 10.15.4

Steps to Reproduce:

1. CMD+Shift+P enter "Copy GitHub Permalink"
2. Then you should get 

> Unable to create a GitHub permalink for the selection. Check that your local branch is tracking a remote branch.

![image](https://user-images.githubusercontent.com/105652/81459905-05ecef80-9170-11ea-9f9b-e7f6cabbcbf3.png)

The integration with pull requests and issues is working fine. But I can no longer copy the permalink.

**Comment by alexr00** [comment] 2020-06-10 08:37
Can you share the outputof `git remote -v`? Do you have the setting `githubPullRequests.remotes` configured?

**Comment by phstc** [comment] 2020-06-14 15:51
Hi @alexr00 

> Can you share the output of git remote -v?

```
origin  git@github.com:org/repo.git (fetch)
origin  git@github.com:org/repo.git (push)
```

> githubPullRequests.remotes configured?

I don't, the only reference for `githubPullRequests` I found was this 👇 

```
    "githubPullRequests.queries": [
    
        {
            "label": "Waiting For My Review",
            "query": "is:open review-requested:${user}"
        },
        {
            "label": "Assigned To Me",
            "query": "is:open assignee:${user}"
        },
        {
            "label": "Created By Me",
            "query": "is:open author:${user}"
        }
    ]
```

I couldn't reproduce the error today. It was happening consistently since I posted the issue.

**Comment by alexr00** [comment] 2020-06-15 08:05
Please ping this issue if you see it again and I will reopen.

**Comment by phstc** [comment] 2020-06-15 17:18
@alexr00 it is happening again 👇 

![image](https://user-images.githubusercontent.com/105652/84686736-838fe200-af0a-11ea-9265-1de86abfee56.png)

![image](https://user-images.githubusercontent.com/105652/84686864-b934cb00-af0a-11ea-8a2c-9e19094876d1.png)


```sh
git remote -v
origin  git@github.com:org/private-repo.git (fetch)
origin  git@github.com:org/private-repo.git (push)
```

**Comment by alexr00** [comment] 2020-06-16 08:33
@phstc I added some better error messages to track this down in version 0.17.0, which was released in the last day. Can you update the extension and see if there's a different error message?

**Comment by lerebear** [comment] 2020-07-09 18:52
I'm seeing this problem also, and the error message I'm receiving reads as follows:

> Unable to create a GitHub permalink for the selection. Can't get the owner and repository from the git remote url.

Unfortunately I'm working in a private repository, so I'd rather not share the true output of `git remote -v`, but the remote appears to be set correctly and it's of the form `https://github.com/<org>/<repo> (fetch)`.

I looked for the error message in this repository and from there found this line: 

https://github.com/microsoft/vscode-pull-request-github/blob/8fd98be135221723cdca78fae52440a38fb44560/src/issues/util.ts#L360

Comparing that with the form of my git remote, it appears that this might be caused by the `\.git$` suffix at the end of that regular expression (my remote does not end in ".git"). I'm not sure why my remote doesn't end in that suffix, but might it be viable to make it optional? Looks like the function will produce the right result without it.

**Comment by RMacfarlane** [comment] 2020-07-09 18:55
Thanks @lerebear, this sounds like a duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/1878. You're right that the problem is the `.git` suffix, there's currently a PR out to fix this issue.

**Comment by daniellepintz** [comment] 2021-10-01 03:50
Hi, I am experiencing this same issue :/ 

<img width="559" alt="Screen Shot 2021-09-30 at 8 48 00 PM" src="https://user-images.githubusercontent.com/38207072/135562285-2340fa19-bafb-4229-88f0-db35879a4d35.png">

the output of `git remote -v` is:
```
origin	git@github.com:daniellepintz/pytorch-lightning.git (fetch)
origin	git@github.com:daniellepintz/pytorch-lightning.git (push)
upstream	https://github.com/PyTorchLightning/pytorch-lightning.git (fetch)
upstream	https://github.com/PyTorchLightning/pytorch-lightning.git (push)
```

I do have `githubPullRequests.remotes` set correctly:
<img width="901" alt="Screen Shot 2021-09-30 at 8 49 41 PM" src="https://user-images.githubusercontent.com/38207072/135562383-e1a26673-187c-465f-9a47-bf621d48fa19.png">

and I am on a local branch that has a remote counterpart (in origin)

Any chance someone could help me with this?

**Comment by alexr00** [comment] 2021-11-18 14:25
This almost always occurs when you try to make a permalink for lines or files that don't exist on the remote. The error message has been updated to reflect this.

**Closed by alexr00** 2021-11-18 14:25 UTC
