### ISSUE TITLE
proxy server ignored

### ISSUE THREAD

**Issue by 2403772980ygy** [microsoft/vscode-pull-request-github#1467] opened 2019-12-14 06:06 UTC
- Extension version: idk
- VSCode Version: 1.41.0-insider
- OS: windows build 19041.1

HTTPS_PROXY environment variable ignored: Invalid URL: 127.0.0.1:1080 at startup

Steps to Reproduce:

1. set https_proxy environment to this value
2. install the extension......

**Comment by RMacfarlane** [comment] 2019-12-16 18:32
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/701

**Closed by RMacfarlane** 2019-12-16 18:32 UTC
