### ISSUE TITLE
authentication for a github enterprise account

### ISSUE THREAD

**Issue by jmoguill** [microsoft/vscode-pull-request-github#4660] opened 2023-03-22 16:22 UTC
Hi,
the company I work for has a github enterprise account, e.g. github.company_name.com

I'm trying to use visual studio code plugin for github pull requests but it keeps going to github.com for authentication so I can't sign in and access the pull requests in my company's github repos.  

Please advise.
Thanks,
Jeff

**Comment by alexr00** [comment] 2023-03-31 12:03
@jmoguill we try to detect if you're using GitHub Enterprise, but it doesn't cover every scenario as Enterprise servers can be configured differently. Do you have the setting `github-enterprise.uri` set?

**Comment by jmoguill** [comment] 2023-03-31 14:48
Yes it was set and the authentication worked intermittently.  It seemed for
some cases it went to GitHub.com instead of the enterprise uri.  Maybe you
can test on your side?

**Comment by alexr00** [comment] 2023-04-14 08:11
@jmoguill do you have any ideas for what might have been different about the times when it worked and the times when it didn't? Next time you see it not work, can you share the output of GitHub Pull Request?

**Comment by mothas** [comment] 2023-04-19 21:19
I can confirm that I also saw this same issue. I'm on a ghe instance. The GH PR extension worked for a few repos, but not others. All repos have `github-enterprise.uri` set though.

But I think I have a solution that worked for me. A good old restart. For the repos I had difficulty with GH signin, I restarted VScode and fixed the issue 🤦🏽

**Comment by mothas** [comment] 2023-04-19 21:30
So it looks like setting `github-enterprise.uri` alone is not enough. VSCode doesn't look like it is using that info, even though VSCode is setting `github-enterprise.uri` . And, more importantly, it looks like VSCode uses `github-enterprise.uri` ONLY after a restart. Hope this is helpful in resolving this issue.

**Closed** 2023-12-12 16:08 UTC
Labels: info-needed
